-- Additive migration: batch 2, 100 new dishes (pool only, no schedule rows)
INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('Xiaolongbao','xiaolongbao','China','east-asia','appetizer','hot','pork','["flour","pork","ginger","scallion","soy sauce","sesame oil"]'),
('Congee','congee','China','east-asia','breakfast','hot','poultry','["rice","chicken","ginger","scallion","soy sauce"]'),
('Char Siu','char-siu','China','east-asia','entree','hot','pork','["pork","honey","soy sauce","five spice","garlic","hoisin sauce"]'),
('Dan Dan Noodles','dan-dan-noodles','China','east-asia','entree','hot','pork','["noodles","pork","chili bean paste","sichuan peppercorn","scallion","garlic","peanuts"]'),
('Okonomiyaki','okonomiyaki','Japan','east-asia','entree','hot','pork','["flour","cabbage","egg","pork","scallion","mayonnaise","soy sauce"]'),
('Tonkatsu','tonkatsu','Japan','east-asia','entree','hot','pork','["pork","breadcrumbs","egg","flour","cabbage"]'),
('Takoyaki','takoyaki','Japan','east-asia','appetizer','hot','seafood','["flour","octopus","egg","scallion","mayonnaise","soy sauce"]'),
('Tteokbokki','tteokbokki','South Korea','east-asia','entree','hot','vegetarian','["rice","gochujang","scallion","garlic","fish sauce"]'),
('Japchae','japchae','South Korea','east-asia','entree','hot','beef','["noodles","beef","spinach","carrot","mushroom","soy sauce","sesame"]'),
('Kimchi Jjigae','kimchi-jjigae','South Korea','east-asia','entree','hot','pork','["cabbage","pork","tofu","scallion","garlic","gochujang"]'),
('Egg Tart','egg-tart','Hong Kong','east-asia','dessert','hot','vegetarian','["flour","egg","sugar","cream","butter"]'),
('Momo','momo','Nepal','south-asia','appetizer','hot','poultry','["flour","chicken","onion","garlic","ginger","cilantro"]'),
('Palak Paneer','palak-paneer','India','south-asia','entree','hot','vegetarian','["spinach","cheese","cream","garlic","ginger","garam masala"]'),
('Dal Makhani','dal-makhani','India','south-asia','entree','hot','vegetarian','["lentils","butter","cream","tomato","garlic","ginger"]'),
('Tandoori Chicken','tandoori-chicken','India','south-asia','entree','hot','poultry','["chicken","yogurt","garam masala","ginger","garlic","lemon"]'),
('Rogan Josh','rogan-josh','India','south-asia','entree','hot','lamb','["lamb","yogurt","garlic","ginger","garam masala","onion"]'),
('Pav Bhaji','pav-bhaji','India','south-asia','entree','hot','vegetarian','["potato","tomato","bell pepper","butter","onion","garlic"]'),
('Idli','idli','India','south-asia','breakfast','hot','vegetarian','["rice","lentils","mustard seeds","curry leaf"]'),
('Chana Masala','chana-masala','India','south-asia','entree','hot','vegetarian','["chickpeas","tomato","onion","garlic","ginger","garam masala"]'),
('Khao Soi','khao-soi','Thailand','southeast-asia','entree','hot','poultry','["noodles","chicken","coconut milk","curry powder","lime","scallion"]'),
('Tom Yum Goong','tom-yum-goong','Thailand','southeast-asia','appetizer','hot','seafood','["shrimp","lemongrass","lime leaves","chili","fish sauce","lime"]'),
('Green Papaya Salad','green-papaya-salad','Thailand','southeast-asia','appetizer','cold','seafood','["papaya","chili","lime","fish sauce","peanuts","tomato"]'),
('Massaman Curry','massaman-curry','Thailand','southeast-asia','entree','hot','beef','["beef","coconut milk","potato","peanuts","cinnamon","cardamom"]'),
('Satay','satay','Indonesia','southeast-asia','appetizer','hot','poultry','["chicken","peanuts","soy sauce","turmeric","coconut milk"]'),
('Gado-Gado','gado-gado','Indonesia','southeast-asia','appetizer','cold','vegetarian','["potato","bean sprouts","cabbage","egg","peanuts","tofu"]'),
('Adobo Sa Gata','adobo-sa-gata','Philippines','southeast-asia','entree','hot','pork','["pork","coconut milk","vinegar","soy sauce","garlic","chili"]'),
('Lumpia','lumpia','Philippines','southeast-asia','appetizer','hot','pork','["flour","pork","carrot","cabbage","garlic","onion"]'),
('Beef Wellington','beef-wellington','United Kingdom','europe','entree','hot','beef','["beef","mushroom","phyllo","mustard","egg"]'),
('Sticky Toffee Pudding','sticky-toffee-pudding','United Kingdom','europe','dessert','hot','vegetarian','["flour","dates","butter","sugar","cream"]'),
('Beef Bourguignon','beef-bourguignon','France','europe','entree','hot','beef','["beef","red wine","bacon","mushroom","onion","carrot","garlic"]'),
('Quiche Lorraine','quiche-lorraine','France','europe','breakfast','hot','pork','["flour","egg","cream","bacon","gruyere"]'),
('Bouillabaisse','bouillabaisse','France','europe','entree','hot','seafood','["white fish","mussels","tomato","saffron","garlic","fennel"]'),
('Pretzel','pretzel','Germany','europe','appetizer','hot','vegetarian','["flour","yeast","butter","salt"]'),
('Sauerbraten','sauerbraten','Germany','europe','entree','hot','beef','["beef","red wine","vinegar","onion","bay leaf","gingersnap"]'),
('Spanakopita','spanakopita','Greece','europe','appetizer','hot','vegetarian','["phyllo","spinach","cheese","egg","dill","olive oil"]'),
('Souvlaki','souvlaki','Greece','europe','entree','hot','pork','["pork","lemon","garlic","oregano","pita","tomato"]'),
('Tzatziki','tzatziki','Greece','europe','appetizer','cold','vegetarian','["yogurt","cucumber","garlic","dill","olive oil"]'),
('Piri Piri Chicken','piri-piri-chicken','Portugal','europe','entree','hot','poultry','["chicken","chili","garlic","lemon","paprika","olive oil"]'),
('Pastel de Nata','pastel-de-nata','Portugal','europe','dessert','hot','vegetarian','["flour","egg","cream","sugar","cinnamon"]'),
('Ossobuco','ossobuco','Italy','europe','entree','hot','beef','["veal","white wine","tomato","carrot","celery","onion"]'),
('Arancini','arancini','Italy','europe','appetizer','hot','beef','["rice","beef","mozzarella","tomato","breadcrumbs","egg"]'),
('Panna Cotta','panna-cotta','Italy','europe','dessert','cold','vegetarian','["cream","sugar","vanilla","gelatin"]'),
('Jambalaya','jambalaya','United States','north-america','entree','hot','seafood','["rice","shrimp","sausage","tomato","bell pepper","celery","onion"]'),
('Buffalo Wings','buffalo-wings','United States','north-america','appetizer','hot','poultry','["chicken","hot sauce","butter","celery"]'),
('Key Lime Pie','key-lime-pie','United States','north-america','dessert','cold','vegetarian','["lime","egg","sugar","cream","flour"]'),
('Clam Bake','clam-bake','United States','north-america','entree','hot','seafood','["clams","corn","potato","lobster","butter"]'),
('Chili Con Carne','chili-con-carne','United States','north-america','entree','hot','beef','["beef","chili","tomato","onion","garlic","cumin"]'),
('Cobb Salad','cobb-salad','United States','north-america','appetizer','cold','poultry','["chicken","bacon","egg","lettuce","tomato","cheese","avocado"]'),
('Reuben Sandwich','reuben-sandwich','United States','north-america','entree','hot','beef','["bread","beef","cheese","sauerkraut","mustard"]'),
('Butter Tart','butter-tart','Canada','north-america','dessert','cold','vegetarian','["flour","butter","sugar","egg","raisins"]'),
('Tourtiere','tourtiere','Canada','north-america','entree','hot','pork','["pork","potato","onion","garlic","cinnamon","flour"]'),
('Nanaimo Bar','nanaimo-bar','Canada','north-america','dessert','cold','vegetarian','["chocolate","butter","sugar","coconut","vanilla"]'),
('Elote','elote','Mexico','latin-america','appetizer','hot','vegetarian','["corn","mayonnaise","cheese","chili","lime"]'),
('Chiles Rellenos','chiles-rellenos','Mexico','latin-america','entree','hot','beef','["chili","cheese","beef","egg","flour","tomato"]'),
('Pozole','pozole','Mexico','latin-america','entree','hot','pork','["pork","hominy","chili","cabbage","radish","lime"]'),
('Tamales','tamales','Mexico','latin-america','entree','hot','pork','["corn","pork","chili","corn husk","lard"]'),
('Enchiladas','enchiladas','Mexico','latin-america','entree','hot','poultry','["tortilla","chicken","chili","cheese","onion","tomato"]'),
('Aguachile','aguachile','Mexico','latin-america','appetizer','cold','seafood','["shrimp","lime","chili","cucumber","onion","cilantro"]'),
('Arroz con Pollo','arroz-con-pollo','Colombia','latin-america','entree','hot','poultry','["rice","chicken","bell pepper","onion","garlic","peas"]'),
('Bandeja Paisa','bandeja-paisa','Colombia','latin-america','entree','hot','pork','["beans","rice","pork","egg","avocado","plantain","beef"]'),
('Asado','asado','Argentina','latin-america','entree','hot','beef','["beef","salt","chimichurri"]'),
('Milanesa','milanesa','Argentina','latin-america','entree','hot','beef','["beef","breadcrumbs","egg","flour","lemon"]'),
('Choripan','choripan','Argentina','latin-america','entree','hot','pork','["sausage","bread","chimichurri","onion"]'),
('Anticuchos','anticuchos','Peru','latin-america','appetizer','hot','beef','["beef heart","chili","garlic","cumin","vinegar"]'),
('Lomo Saltado','lomo-saltado','Peru','latin-america','entree','hot','beef','["beef","tomato","onion","soy sauce","rice"]'),
('Causa Limena','causa-limena','Peru','latin-america','appetizer','cold','seafood','["potato","lime","chili","chicken","avocado","mayonnaise"]'),
('Fried Plantains','fried-plantains','Cuba','latin-america','appetizer','hot','vegetarian','["plantain","olive oil","salt","garlic"]'),
('Ropa Vieja','ropa-vieja','Cuba','latin-america','entree','hot','beef','["beef","tomato","bell pepper","onion","garlic","olives"]'),
('Mofongo','mofongo','Puerto Rico','latin-america','entree','hot','pork','["plantain","garlic","pork","olive oil"]'),
('Injera with Doro Wat','injera-with-doro-wat','Ethiopia','africa','entree','hot','poultry','["teff","chicken","egg","onion","chili","garlic","ginger"]'),
('Egusi Soup','egusi-soup','Nigeria','africa','entree','hot','beef','["beef","spinach","chili","onion","garlic"]'),
('Suya','suya','Nigeria','africa','appetizer','hot','beef','["beef","peanuts","chili","ginger","onion"]'),
('Piri Piri Prawns','piri-piri-prawns','Mozambique','africa','entree','hot','seafood','["shrimp","chili","garlic","lemon","olive oil"]'),
('Bunny Chow','bunny-chow','South Africa','africa','entree','hot','beef','["bread","beef","curry powder","onion","garlic","potato"]'),
('Biltong','biltong','South Africa','africa','appetizer','cold','beef','["beef","vinegar","coriander","black pepper","salt"]'),
('Koshari','koshari','Egypt','africa','entree','hot','vegetarian','["rice","lentils","macaroni","tomato","chickpeas","garlic"]'),
('Tagine of Lamb and Prunes','tagine-of-lamb-and-prunes','Morocco','africa','entree','hot','lamb','["lamb","prunes","onion","cinnamon","ginger","almonds"]'),
('Fattoush','fattoush','Lebanon','middle-east','appetizer','cold','vegetarian','["bread","cucumber","tomato","lettuce","lemon","sumac"]'),
('Tabbouleh','tabbouleh','Lebanon','middle-east','appetizer','cold','vegetarian','["parsley","bulgur","tomato","lemon","mint","olive oil"]'),
('Kibbeh','kibbeh','Lebanon','middle-east','appetizer','hot','lamb','["bulgur","lamb","onion","pine nuts","cinnamon"]'),
('Manakish','manakish','Lebanon','middle-east','breakfast','hot','vegetarian','["flour","thyme","olive oil","cheese"]'),
('Shawarma','shawarma','Lebanon','middle-east','entree','hot','lamb','["lamb","garlic","yogurt","pita","tomato","pickles"]'),
('Muhammara','muhammara','Syria','middle-east','appetizer','cold','vegetarian','["bell pepper","walnuts","pomegranate","garlic","chili"]'),
('Khoresh Fesenjan','khoresh-fesenjan','Iran','middle-east','entree','hot','poultry','["chicken","walnuts","pomegranate","onion"]'),
('Baklava Cheesecake Knafeh','baklava-cheesecake-knafeh','Palestine','middle-east','dessert','hot','vegetarian','["cheese","semolina","sugar","pistachio","honey"]'),
('Lahmacun','lahmacun','Türkiye','middle-east','entree','hot','lamb','["flour","lamb","tomato","onion","parsley"]'),
('Manti','manti','Türkiye','middle-east','entree','hot','lamb','["flour","lamb","onion","yogurt","garlic"]'),
('Kofta','kofta','Türkiye','middle-east','entree','hot','lamb','["lamb","onion","parsley","cumin","garlic"]'),
('Khachapuri','khachapuri','Georgia','middle-east','breakfast','hot','vegetarian','["flour","cheese","egg","butter"]'),
('Poke Bowl','poke-bowl','United States','north-america','entree','cold','seafood','["tuna","rice","soy sauce","sesame","scallion","avocado"]'),
('Meat Pie','meat-pie','Australia','oceania','entree','hot','beef','["flour","beef","gravy","onion"]'),
('Lamington','lamington','Australia','oceania','dessert','cold','vegetarian','["sponge cake","chocolate","coconut"]'),
('Hangi','hangi','New Zealand','oceania','entree','hot','poultry','["chicken","potato","sweet potato","cabbage"]'),
('Fish Curry','fish-curry','Fiji','oceania','entree','hot','seafood','["white fish","coconut milk","chili","onion","turmeric","lime"]'),
('Borsch Ukrainian Style','borsch-ukrainian-style','Ukraine','europe','entree','hot','pork','["beetroot","cabbage","pork","potato","carrot","dill"]'),
('Chicken Paprikash','chicken-paprikash','Hungary','europe','entree','hot','poultry','["chicken","paprika","sour cream","onion","bell pepper"]'),
('Trdelnik','trdelnik','Czech Republic','europe','dessert','hot','vegetarian','["flour","sugar","cinnamon","butter"]'),
('Pierniki','pierniki','Poland','europe','dessert','cold','vegetarian','["flour","honey","cinnamon","ginger","cloves"]'),
('Haggis','haggis','Scotland','europe','entree','hot','lamb','["lamb","oats","onion","black pepper","suet"]'),
('Colcannon','colcannon','Ireland','europe','entree','hot','pork','["potato","cabbage","butter","milk","bacon"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='xiaolongbao'),1,'A steamed pouch from East Asia that hides a surprise inside.'),
((SELECT id FROM dishes WHERE slug='xiaolongbao'),2,'Shanghai cooks in the 19th century figured out how to trap gelatinized broth inside a dumpling wrapper.'),
((SELECT id FROM dishes WHERE slug='xiaolongbao'),3,'Diners are warned to bite a small hole first or risk a scalding broth explosion.'),
((SELECT id FROM dishes WHERE slug='xiaolongbao'),4,'A thin dough purse pleated shut around minced pork and a jellied broth that melts when steamed.'),
((SELECT id FROM dishes WHERE slug='xiaolongbao'),5,'The soup-filled steamed dumpling of Shanghai.'),
((SELECT id FROM dishes WHERE slug='congee'),1,'A breakfast bowl found across East Asia, endlessly customizable.'),
((SELECT id FROM dishes WHERE slug='congee'),2,'Rice porridge has fed China for over two thousand years, especially the sick and the very young.'),
((SELECT id FROM dishes WHERE slug='congee'),3,'It''s the go-to comfort food street vendors sell before dawn all over Hong Kong.'),
((SELECT id FROM dishes WHERE slug='congee'),4,'Rice is simmered for hours in broth until it breaks down into a silky porridge, topped with shredded meat.'),
((SELECT id FROM dishes WHERE slug='congee'),5,'The slow-simmered rice porridge of China.'),
((SELECT id FROM dishes WHERE slug='char-siu'),1,'A glossy roasted meat that hangs in Chinatown windows worldwide.'),
((SELECT id FROM dishes WHERE slug='char-siu'),2,'Cantonese cooks have skewer-roasted marinated pork over open fire since imperial times.'),
((SELECT id FROM dishes WHERE slug='char-siu'),3,'Its red-lacquered strips are a Hong Kong lunch-counter icon, served over rice.'),
((SELECT id FROM dishes WHERE slug='char-siu'),4,'Pork shoulder is marinated in honey and five spice, then roasted until the edges caramelize.'),
((SELECT id FROM dishes WHERE slug='char-siu'),5,'Cantonese honey-glazed roast pork.'),
((SELECT id FROM dishes WHERE slug='dan-dan-noodles'),1,'A numbing noodle dish named for the pole it was once carried on.'),
((SELECT id FROM dishes WHERE slug='dan-dan-noodles'),2,'Sichuan street vendors once balanced two baskets of it on a shoulder pole, hawking bowl by bowl.'),
((SELECT id FROM dishes WHERE slug='dan-dan-noodles'),3,'Its tongue-tingling heat comes from a spice that isn''t a pepper at all.'),
((SELECT id FROM dishes WHERE slug='dan-dan-noodles'),4,'Wheat noodles are tossed in chili oil, minced pork and a numbing peppercorn sauce.'),
((SELECT id FROM dishes WHERE slug='dan-dan-noodles'),5,'Sichuan''s numbing, spicy carried-pole noodles.'),
((SELECT id FROM dishes WHERE slug='okonomiyaki'),1,'A griddled dish whose name means ''grilled as you like it''.'),
((SELECT id FROM dishes WHERE slug='okonomiyaki'),2,'Osaka street stalls popularized this batter pancake after WWII food shortages eased.'),
((SELECT id FROM dishes WHERE slug='okonomiyaki'),3,'Diners often cook it themselves at the table on a built-in iron griddle.'),
((SELECT id FROM dishes WHERE slug='okonomiyaki'),4,'A cabbage-and-batter pancake griddled with pork, then striped with sauce and mayonnaise.'),
((SELECT id FROM dishes WHERE slug='okonomiyaki'),5,'Japan''s savory ''as you like it'' cabbage pancake.'),
((SELECT id FROM dishes WHERE slug='tonkatsu'),1,'A crunchy cutlet that reinvented a European technique in Japan.'),
((SELECT id FROM dishes WHERE slug='tonkatsu'),2,'Tokyo cooks in the 1900s deep-fried a breaded pork cutlet, adapting a French dish for Japanese kitchens.'),
((SELECT id FROM dishes WHERE slug='tonkatsu'),3,'It''s the backbone of a rice-bowl dish so beloved it has its own vending-machine ordering ritual.'),
((SELECT id FROM dishes WHERE slug='tonkatsu'),4,'A thick pork cutlet is breaded in panko and deep-fried until shatteringly crisp.'),
((SELECT id FROM dishes WHERE slug='tonkatsu'),5,'Japan''s deep-fried breaded pork cutlet.'),
((SELECT id FROM dishes WHERE slug='takoyaki'),1,'A ball-shaped street snack cooked in a special molded pan.'),
((SELECT id FROM dishes WHERE slug='takoyaki'),2,'Osaka vendors started filling batter balls with diced seafood in the 1930s.'),
((SELECT id FROM dishes WHERE slug='takoyaki'),3,'Its molten center has burned the mouths of impatient festival-goers for generations.'),
((SELECT id FROM dishes WHERE slug='takoyaki'),4,'Batter is poured into a molded pan around diced octopus and flipped into golf-ball-sized spheres.'),
((SELECT id FROM dishes WHERE slug='takoyaki'),5,'Osaka''s octopus-filled batter balls.'),
((SELECT id FROM dishes WHERE slug='tteokbokki'),1,'A chewy street food that stains everything it touches bright red.'),
((SELECT id FROM dishes WHERE slug='tteokbokki'),2,'Palace cooks once served a soy-sauce version to Korean royalty before chili paste took over.'),
((SELECT id FROM dishes WHERE slug='tteokbokki'),3,'It''s the after-school snack that lines every Seoul street-cart alley.'),
((SELECT id FROM dishes WHERE slug='tteokbokki'),4,'Cylindrical rice cakes simmer in a fiery gochujang sauce until glossy and chewy.'),
((SELECT id FROM dishes WHERE slug='tteokbokki'),5,'Korea''s chewy rice cakes in fiery red sauce.'),
((SELECT id FROM dishes WHERE slug='japchae'),1,'A glossy noodle dish that started as a dish with no noodles at all.'),
((SELECT id FROM dishes WHERE slug='japchae'),2,'A 17th-century Korean official first served it as a vegetable-only dish to please a king.'),
((SELECT id FROM dishes WHERE slug='japchae'),3,'It''s the stir-fried centerpiece of nearly every Korean holiday table today.'),
((SELECT id FROM dishes WHERE slug='japchae'),4,'Glass noodles are stir-fried with beef and vegetables in a sweet soy-sesame sauce.'),
((SELECT id FROM dishes WHERE slug='japchae'),5,'Korea''s stir-fried glass noodles.'),
((SELECT id FROM dishes WHERE slug='kimchi-jjigae'),1,'A bubbling stew built entirely around a fermented staple.'),
((SELECT id FROM dishes WHERE slug='kimchi-jjigae'),2,'Korean households use aged, sour kimchi to simmer this stew when the batch gets too funky to eat raw.'),
((SELECT id FROM dishes WHERE slug='kimchi-jjigae'),3,'It''s considered the ultimate hangover cure across Korea.'),
((SELECT id FROM dishes WHERE slug='kimchi-jjigae'),4,'Fermented cabbage simmers with pork and tofu into a tangy, fiery red stew.'),
((SELECT id FROM dishes WHERE slug='kimchi-jjigae'),5,'Korea''s fermented-cabbage stew.'),
((SELECT id FROM dishes WHERE slug='egg-tart'),1,'A flaky pastry with roots in two colonial kitchens.'),
((SELECT id FROM dishes WHERE slug='egg-tart'),2,'Portuguese custard tarts and British egg tarts merged in this city''s bakeries in the 20th century.'),
((SELECT id FROM dishes WHERE slug='egg-tart'),3,'It''s said to be a former governor''s favorite teatime treat.'),
((SELECT id FROM dishes WHERE slug='egg-tart'),4,'A wobbly egg custard is baked inside a flaky or crumbly pastry shell.'),
((SELECT id FROM dishes WHERE slug='egg-tart'),5,'Hong Kong''s flaky egg custard tart.'),
((SELECT id FROM dishes WHERE slug='momo'),1,'A steamed dumpling that crossed the Himalayas to become a national obsession.'),
((SELECT id FROM dishes WHERE slug='momo'),2,'Tibetan traders carried this dumpling over mountain passes into Nepal centuries ago.'),
((SELECT id FROM dishes WHERE slug='momo'),3,'Kathmandu street corners now serve it with a fiery tomato-sesame dip as a national pastime.'),
((SELECT id FROM dishes WHERE slug='momo'),4,'Minced meat and onion are folded into pleated dough pouches and steamed.'),
((SELECT id FROM dishes WHERE slug='momo'),5,'Nepal''s pleated steamed dumpling.'),
((SELECT id FROM dishes WHERE slug='palak-paneer'),1,'A vivid green curry built around a fresh cheese.'),
((SELECT id FROM dishes WHERE slug='palak-paneer'),2,'North Indian home cooks have simmered greens with fresh cheese for centuries as a vegetarian staple.'),
((SELECT id FROM dishes WHERE slug='palak-paneer'),3,'Its bright color makes it the dish most photographed on Indian restaurant menus.'),
((SELECT id FROM dishes WHERE slug='palak-paneer'),4,'Pureed spinach simmers into a creamy gravy studded with cubes of fresh cheese.'),
((SELECT id FROM dishes WHERE slug='palak-paneer'),5,'India''s creamy spinach and cheese curry.'),
((SELECT id FROM dishes WHERE slug='dal-makhani'),1,'A slow-simmered lentil dish famous for its buttery finish.'),
((SELECT id FROM dishes WHERE slug='dal-makhani'),2,'Punjabi tandoor cooks in Delhi began slow-cooking black lentils overnight in the mid-20th century.'),
((SELECT id FROM dishes WHERE slug='dal-makhani'),3,'Its recipe is guarded jealously by the restaurant credited with inventing it.'),
((SELECT id FROM dishes WHERE slug='dal-makhani'),4,'Black lentils simmer for hours with butter, cream and tomato into a velvety stew.'),
((SELECT id FROM dishes WHERE slug='dal-makhani'),5,'Punjab''s buttery slow-cooked black lentils.'),
((SELECT id FROM dishes WHERE slug='tandoori-chicken'),1,'A fiery-red grilled dish named for the clay oven that cooks it.'),
((SELECT id FROM dishes WHERE slug='tandoori-chicken'),2,'A Punjabi restaurateur popularized this clay-oven chicken in Delhi after the 1947 Partition.'),
((SELECT id FROM dishes WHERE slug='tandoori-chicken'),3,'Its smoky char and red hue have made it a curry-house menu fixture worldwide.'),
((SELECT id FROM dishes WHERE slug='tandoori-chicken'),4,'Chicken is marinated in spiced yogurt and roasted in a blistering clay oven.'),
((SELECT id FROM dishes WHERE slug='tandoori-chicken'),5,'India''s clay-oven roasted red chicken.'),
((SELECT id FROM dishes WHERE slug='rogan-josh'),1,'A deep-red curry that traveled south with Persian conquerors.'),
((SELECT id FROM dishes WHERE slug='rogan-josh'),2,'Kashmiri cooks adapted a Persian braised-meat technique into this fiery curry centuries ago.'),
((SELECT id FROM dishes WHERE slug='rogan-josh'),3,'Its brick-red color traditionally came from a Kashmiri chili grown for color, not heat.'),
((SELECT id FROM dishes WHERE slug='rogan-josh'),4,'Lamb braises slowly in a yogurt and spice gravy until deeply tender.'),
((SELECT id FROM dishes WHERE slug='rogan-josh'),5,'Kashmir''s aromatic red-braised lamb curry.'),
((SELECT id FROM dishes WHERE slug='pav-bhaji'),1,'A mashed vegetable dish invented to feed textile mill workers.'),
((SELECT id FROM dishes WHERE slug='pav-bhaji'),2,'Bombay street vendors created this quick lunch for overnight mill shift workers in the 1850s.'),
((SELECT id FROM dishes WHERE slug='pav-bhaji'),3,'It''s now a beach-boardwalk staple, sizzled on a giant flat griddle.'),
((SELECT id FROM dishes WHERE slug='pav-bhaji'),4,'Mixed vegetables are mashed and cooked with butter and spices, served with toasted buns.'),
((SELECT id FROM dishes WHERE slug='pav-bhaji'),5,'Mumbai''s buttery mashed-vegetable and bun dish.'),
((SELECT id FROM dishes WHERE slug='idli'),1,'A pillowy steamed cake that starts as a fermented batter.'),
((SELECT id FROM dishes WHERE slug='idli'),2,'South Indian cooks have fermented rice and lentil batter overnight for this dish for over a thousand years.'),
((SELECT id FROM dishes WHERE slug='idli'),3,'It''s the lightest item on any South Indian breakfast tray, often paired with a coconut chutney.'),
((SELECT id FROM dishes WHERE slug='idli'),4,'Fermented rice and lentil batter is steamed in molds into soft, spongy cakes.'),
((SELECT id FROM dishes WHERE slug='idli'),5,'South India''s steamed fermented rice cake.'),
((SELECT id FROM dishes WHERE slug='chana-masala'),1,'A tangy chickpea curry that anchors countless vegetarian thalis.'),
((SELECT id FROM dishes WHERE slug='chana-masala'),2,'Punjabi street stalls built this dish around dried chickpeas, a cheap and filling pantry staple.'),
((SELECT id FROM dishes WHERE slug='chana-masala'),3,'It''s often paired with a fried bread as a quick roadside breakfast across North India.'),
((SELECT id FROM dishes WHERE slug='chana-masala'),4,'Chickpeas simmer in a tangy tomato and onion gravy spiced with garam masala.'),
((SELECT id FROM dishes WHERE slug='chana-masala'),5,'North India''s tangy stewed chickpea curry.'),
((SELECT id FROM dishes WHERE slug='khao-soi'),1,'A noodle soup topped with its own crunchy alter ego.'),
((SELECT id FROM dishes WHERE slug='khao-soi'),2,'Muslim traders brought a curry-noodle style into northern Thailand generations ago.'),
((SELECT id FROM dishes WHERE slug='khao-soi'),3,'Chiang Mai locals debate fiercely whose bowl of it is the city''s best.'),
((SELECT id FROM dishes WHERE slug='khao-soi'),4,'Egg noodles swim in a coconut curry broth, topped with a handful of deep-fried noodles.'),
((SELECT id FROM dishes WHERE slug='khao-soi'),5,'Northern Thailand''s coconut curry noodle soup.'),
((SELECT id FROM dishes WHERE slug='tom-yum-goong'),1,'A soup famous for balancing four flavors at once.'),
((SELECT id FROM dishes WHERE slug='tom-yum-goong'),2,'Central Thai river communities built this soup around fresh-caught shrimp and wild herbs.'),
((SELECT id FROM dishes WHERE slug='tom-yum-goong'),3,'Its fiery, sour aroma is often cited as the smell that defines Thai cuisine abroad.'),
((SELECT id FROM dishes WHERE slug='tom-yum-goong'),4,'Shrimp simmer in a hot-and-sour broth of lemongrass, lime leaves and chili.'),
((SELECT id FROM dishes WHERE slug='tom-yum-goong'),5,'Thailand''s hot and sour shrimp soup.'),
((SELECT id FROM dishes WHERE slug='green-papaya-salad'),1,'A pounded salad that starts unripe on purpose.'),
((SELECT id FROM dishes WHERE slug='green-papaya-salad'),2,'Laotian and Isaan farmers first pounded unripe fruit with mortar and pestle for a filling field lunch.'),
((SELECT id FROM dishes WHERE slug='green-papaya-salad'),3,'Its preparation ritual, loud pestle-pounding included, is part of the street-stall theater.'),
((SELECT id FROM dishes WHERE slug='green-papaya-salad'),4,'Shredded unripe papaya is pounded with chili, lime, fish sauce and dried shrimp.'),
((SELECT id FROM dishes WHERE slug='green-papaya-salad'),5,'Thailand''s pounded green papaya salad.'),
((SELECT id FROM dishes WHERE slug='massaman-curry'),1,'A curry whose name hints at its Muslim, foreign roots.'),
((SELECT id FROM dishes WHERE slug='massaman-curry'),2,'Persian and Indian Muslim traders brought warming spices into southern Thai kitchens centuries ago.'),
((SELECT id FROM dishes WHERE slug='massaman-curry'),3,'CNN once ranked it the world''s most delicious food in a global readers'' poll.'),
((SELECT id FROM dishes WHERE slug='massaman-curry'),4,'Beef and potato simmer in a rich coconut curry warmed with cinnamon and cardamom.'),
((SELECT id FROM dishes WHERE slug='massaman-curry'),5,'Thailand''s Persian-spiced coconut beef curry.'),
((SELECT id FROM dishes WHERE slug='satay'),1,'Skewered street food dipped in a rich nut sauce.'),
((SELECT id FROM dishes WHERE slug='satay'),2,'Javanese street vendors adapted Middle Eastern kebab-style grilling into this dish in the 19th century.'),
((SELECT id FROM dishes WHERE slug='satay'),3,'It''s now a hawker-stall staple across half a dozen Southeast Asian countries.'),
((SELECT id FROM dishes WHERE slug='satay'),4,'Marinated meat skewers are grilled over charcoal and served with a thick peanut sauce.'),
((SELECT id FROM dishes WHERE slug='satay'),5,'Southeast Asia''s grilled skewers with peanut sauce.'),
((SELECT id FROM dishes WHERE slug='gado-gado'),1,'A composed salad whose name means ''mix mix''.'),
((SELECT id FROM dishes WHERE slug='gado-gado'),2,'Javanese cooks built this dish as a way to use whatever vegetables were on hand, dressed in peanut sauce.'),
((SELECT id FROM dishes WHERE slug='gado-gado'),3,'Its jumble of textures makes it Indonesia''s answer to a chef''s salad.'),
((SELECT id FROM dishes WHERE slug='gado-gado'),4,'Blanched vegetables, tofu and boiled egg are drenched in a creamy peanut dressing.'),
((SELECT id FROM dishes WHERE slug='gado-gado'),5,'Indonesia''s mixed vegetable salad in peanut sauce.'),
((SELECT id FROM dishes WHERE slug='adobo-sa-gata'),1,'A regional twist on a national dish, enriched with a tropical staple.'),
((SELECT id FROM dishes WHERE slug='adobo-sa-gata'),2,'Bicol region cooks folded coconut milk into the archipelago''s classic vinegar-soy braise.'),
((SELECT id FROM dishes WHERE slug='adobo-sa-gata'),3,'It''s proof that a single national dish can taste completely different island to island.'),
((SELECT id FROM dishes WHERE slug='adobo-sa-gata'),4,'Pork braises in vinegar, soy sauce and garlic, finished with coconut milk for richness.'),
((SELECT id FROM dishes WHERE slug='adobo-sa-gata'),5,'The Bicol region''s coconut-enriched pork adobo.'),
((SELECT id FROM dishes WHERE slug='lumpia'),1,'A crisp fried roll with Chinese immigrant roots.'),
((SELECT id FROM dishes WHERE slug='lumpia'),2,'Chinese Filipino immigrants adapted spring rolls into this crunchy party staple generations ago.'),
((SELECT id FROM dishes WHERE slug='lumpia'),3,'No Filipino birthday table is considered complete without a platter of these.'),
((SELECT id FROM dishes WHERE slug='lumpia'),4,'Minced pork and vegetables are rolled in thin wrappers and deep-fried until crackling.'),
((SELECT id FROM dishes WHERE slug='lumpia'),5,'The Philippines'' crisp fried spring roll.'),
((SELECT id FROM dishes WHERE slug='beef-wellington'),1,'A showstopping roast wrapped in golden pastry.'),
((SELECT id FROM dishes WHERE slug='beef-wellington'),2,'Victorian-era chefs are said to have named this dish for a famous Duke, though the story is disputed.'),
((SELECT id FROM dishes WHERE slug='beef-wellington'),3,'Reality-TV cooking shows treat it as the ultimate test of a home cook''s nerve.'),
((SELECT id FROM dishes WHERE slug='beef-wellington'),4,'A beef fillet is coated in mushroom paste and wrapped in puff pastry, then roasted.'),
((SELECT id FROM dishes WHERE slug='beef-wellington'),5,'Britain''s pastry-wrapped beef fillet roast.'),
((SELECT id FROM dishes WHERE slug='sticky-toffee-pudding'),1,'A dense cake drowned in a sweet sauce.'),
((SELECT id FROM dishes WHERE slug='sticky-toffee-pudding'),2,'A Lake District hotel chef popularized this date-based cake in the mid-20th century.'),
((SELECT id FROM dishes WHERE slug='sticky-toffee-pudding'),3,'It regularly tops British polls for the nation''s favorite dessert.'),
((SELECT id FROM dishes WHERE slug='sticky-toffee-pudding'),4,'A moist date sponge cake is soaked in a warm buttery toffee sauce.'),
((SELECT id FROM dishes WHERE slug='sticky-toffee-pudding'),5,'Britain''s date sponge cake in toffee sauce.'),
((SELECT id FROM dishes WHERE slug='beef-bourguignon'),1,'A slow-braised stew named for a wine region.'),
((SELECT id FROM dishes WHERE slug='beef-bourguignon'),2,'Burgundian peasants braised tough cuts of beef in local red wine to tenderize them over long cooking.'),
((SELECT id FROM dishes WHERE slug='beef-bourguignon'),3,'A famous American TV chef''s 1960s broadcast of this dish made French cooking approachable at home.'),
((SELECT id FROM dishes WHERE slug='beef-bourguignon'),4,'Beef chunks braise for hours in red wine with bacon, mushroom and pearl onions.'),
((SELECT id FROM dishes WHERE slug='beef-bourguignon'),5,'Burgundy''s red-wine braised beef stew.'),
((SELECT id FROM dishes WHERE slug='quiche-lorraine'),1,'A savory custard tart named for a northeastern region.'),
((SELECT id FROM dishes WHERE slug='quiche-lorraine'),2,'Lorraine''s German-influenced kitchens developed this bacon-and-custard tart centuries ago.'),
((SELECT id FROM dishes WHERE slug='quiche-lorraine'),3,'It became a 1980s American brunch cliché, spawning the phrase ''real men don''t eat quiche''.'),
((SELECT id FROM dishes WHERE slug='quiche-lorraine'),4,'A buttery pastry shell is filled with an egg custard studded with bacon and cheese.'),
((SELECT id FROM dishes WHERE slug='quiche-lorraine'),5,'Lorraine''s bacon and egg custard tart.'),
((SELECT id FROM dishes WHERE slug='bouillabaisse'),1,'A fisherman''s stew from a sun-drenched Mediterranean port.'),
((SELECT id FROM dishes WHERE slug='bouillabaisse'),2,'Marseille fishermen once simmered their unsold catch into this stew at the end of the day.'),
((SELECT id FROM dishes WHERE slug='bouillabaisse'),3,'Its authentic version is protected by a charter listing exactly which fish may be used.'),
((SELECT id FROM dishes WHERE slug='bouillabaisse'),4,'An assortment of fish and shellfish simmers with tomato, saffron and fennel into a fragrant broth.'),
((SELECT id FROM dishes WHERE slug='bouillabaisse'),5,'Marseille''s saffron-scented fisherman''s stew.'),
((SELECT id FROM dishes WHERE slug='pretzel'),1,'A twisted bread whose knot shape has a folklore explanation.'),
((SELECT id FROM dishes WHERE slug='pretzel'),2,'Medieval monks are said to have twisted dough into arms-crossed-in-prayer shapes for Lent.'),
((SELECT id FROM dishes WHERE slug='pretzel'),3,'It''s the unofficial mascot of every beer garden and Oktoberfest tent in Bavaria.'),
((SELECT id FROM dishes WHERE slug='pretzel'),4,'Dough is dipped in a lye bath before baking, giving it a deep brown, chewy crust.'),
((SELECT id FROM dishes WHERE slug='pretzel'),5,'Germany''s lye-dipped twisted bread.'),
((SELECT id FROM dishes WHERE slug='sauerbraten'),1,'A pot roast marinated for days before it ever touches heat.'),
((SELECT id FROM dishes WHERE slug='sauerbraten'),2,'German households have marinated tough beef roasts in vinegar and wine for over a week since medieval times.'),
((SELECT id FROM dishes WHERE slug='sauerbraten'),3,'Its gravy is famously thickened with crumbled gingerbread cookies.'),
((SELECT id FROM dishes WHERE slug='sauerbraten'),4,'Beef marinates for days in vinegar and wine, then braises into a tangy, tender roast.'),
((SELECT id FROM dishes WHERE slug='sauerbraten'),5,'Germany''s days-marinated sour pot roast.'),
((SELECT id FROM dishes WHERE slug='spanakopita'),1,'A flaky pie whose filling turns a whole country''s fields green.'),
((SELECT id FROM dishes WHERE slug='spanakopita'),2,'Byzantine-era Greek cooks layered wild greens between paper-thin dough sheets centuries ago.'),
((SELECT id FROM dishes WHERE slug='spanakopita'),3,'Its crackling golden layers make it a staple of every Greek bakery window.'),
((SELECT id FROM dishes WHERE slug='spanakopita'),4,'Spinach and feta are layered between buttered phyllo sheets and baked until crisp.'),
((SELECT id FROM dishes WHERE slug='spanakopita'),5,'Greece''s flaky spinach and cheese pie.'),
((SELECT id FROM dishes WHERE slug='souvlaki'),1,'Skewered street food that shares its name with a sword.'),
((SELECT id FROM dishes WHERE slug='souvlaki'),2,'Ancient Greek texts already describe grilling skewered meat over coals millennia ago.'),
((SELECT id FROM dishes WHERE slug='souvlaki'),3,'It''s the fast food of Athens, eaten walking down the street wrapped in pita.'),
((SELECT id FROM dishes WHERE slug='souvlaki'),4,'Cubed marinated meat is grilled on skewers and wrapped in warm pita with tomato and onion.'),
((SELECT id FROM dishes WHERE slug='souvlaki'),5,'Greece''s grilled meat skewer wrap.'),
((SELECT id FROM dishes WHERE slug='tzatziki'),1,'A cooling dip that shows up beside nearly every Greek grill.'),
((SELECT id FROM dishes WHERE slug='tzatziki'),2,'Ottoman-era yogurt-and-cucumber dips spread across the eastern Mediterranean and settled into Greek cuisine.'),
((SELECT id FROM dishes WHERE slug='tzatziki'),3,'It''s the go-to cooldown for a mouthful of fiery grilled meat.'),
((SELECT id FROM dishes WHERE slug='tzatziki'),4,'Strained yogurt is mixed with grated cucumber, garlic and dill into a cool, tangy dip.'),
((SELECT id FROM dishes WHERE slug='tzatziki'),5,'Greece''s cucumber and yogurt dip.'),
((SELECT id FROM dishes WHERE slug='piri-piri-chicken'),1,'A fiery grilled chicken born from a colonial spice route.'),
((SELECT id FROM dishes WHERE slug='piri-piri-chicken'),2,'Portuguese sailors carried a small African chili back from Mozambique and Angola centuries ago.'),
((SELECT id FROM dishes WHERE slug='piri-piri-chicken'),3,'A global fast-food chain now built an entire empire around this one dish.'),
((SELECT id FROM dishes WHERE slug='piri-piri-chicken'),4,'Chicken is butterflied, marinated in chili and garlic, and grilled until charred.'),
((SELECT id FROM dishes WHERE slug='piri-piri-chicken'),5,'Portugal''s chili-marinated grilled chicken.'),
((SELECT id FROM dishes WHERE slug='pastel-de-nata'),1,'A custard tart born behind a monastery''s walls.'),
((SELECT id FROM dishes WHERE slug='pastel-de-nata'),2,'18th-century monks near Lisbon baked these using egg yolks left over from starching monastery linens.'),
((SELECT id FROM dishes WHERE slug='pastel-de-nata'),3,'Its recipe secret is still guarded by one bakery that supplies the rest of the country.'),
((SELECT id FROM dishes WHERE slug='pastel-de-nata'),4,'A flaky pastry shell is filled with egg custard and baked until the top blisters and blackens.'),
((SELECT id FROM dishes WHERE slug='pastel-de-nata'),5,'Lisbon''s blistered custard tart.'),
((SELECT id FROM dishes WHERE slug='ossobuco'),1,'A braised dish named for the marrow-filled bone at its center.'),
((SELECT id FROM dishes WHERE slug='ossobuco'),2,'Milanese cooks in the 19th century slow-braised veal shanks, prizing the marrow inside as a delicacy.'),
((SELECT id FROM dishes WHERE slug='ossobuco'),3,'A special narrow spoon exists just for scooping out its bone marrow.'),
((SELECT id FROM dishes WHERE slug='ossobuco'),4,'Veal shanks braise slowly in white wine and vegetables until the meat falls from the bone.'),
((SELECT id FROM dishes WHERE slug='ossobuco'),5,'Milan''s braised veal shank with marrow.'),
((SELECT id FROM dishes WHERE slug='arancini'),1,'A fried ball whose name means ''little orange'' in Italian.'),
((SELECT id FROM dishes WHERE slug='arancini'),2,'Sicilian cooks under Arab rule began forming saffron rice into fried balls over a thousand years ago.'),
((SELECT id FROM dishes WHERE slug='arancini'),3,'Its golden, round shape is what earned it the citrus-fruit nickname.'),
((SELECT id FROM dishes WHERE slug='arancini'),4,'Leftover risotto is formed around a meat and cheese filling, breaded and deep-fried.'),
((SELECT id FROM dishes WHERE slug='arancini'),5,'Sicily''s fried stuffed rice ball.'),
((SELECT id FROM dishes WHERE slug='panna-cotta'),1,'A wobbly dessert whose name literally means ''cooked cream''.'),
((SELECT id FROM dishes WHERE slug='panna-cotta'),2,'Piedmont households in northern Italy have set sweetened cream desserts like this for over a century.'),
((SELECT id FROM dishes WHERE slug='panna-cotta'),3,'Its trembling, barely-set texture is the mark of a well-made version.'),
((SELECT id FROM dishes WHERE slug='panna-cotta'),4,'Sweetened cream is set with gelatin and unmolded into a silky, wobbling dome.'),
((SELECT id FROM dishes WHERE slug='panna-cotta'),5,'Piedmont''s silky cooked-cream dessert.'),
((SELECT id FROM dishes WHERE slug='jambalaya'),1,'A one-pot rice dish born from three culinary traditions colliding.'),
((SELECT id FROM dishes WHERE slug='jambalaya'),2,'Spanish, French and West African cooking traditions merged in 18th-century Louisiana to create it.'),
((SELECT id FROM dishes WHERE slug='jambalaya'),3,'Its name is rumored to blend French and African words for ham and rice.'),
((SELECT id FROM dishes WHERE slug='jambalaya'),4,'Rice cooks down with sausage, shrimp and the Cajun ''holy trinity'' of vegetables.'),
((SELECT id FROM dishes WHERE slug='jambalaya'),5,'Louisiana''s one-pot rice, sausage and shrimp dish.'),
((SELECT id FROM dishes WHERE slug='buffalo-wings'),1,'A bar snack invented almost by accident in an upstate New York kitchen.'),
((SELECT id FROM dishes WHERE slug='buffalo-wings'),2,'A Buffalo, New York bar owner in 1964 fried leftover chicken wings and doused them in hot sauce for hungry patrons.'),
((SELECT id FROM dishes WHERE slug='buffalo-wings'),3,'It single-handedly turned a throwaway cut of chicken into a Super Bowl staple.'),
((SELECT id FROM dishes WHERE slug='buffalo-wings'),4,'Chicken wings are deep-fried plain, then tossed in a butter and hot sauce mixture.'),
((SELECT id FROM dishes WHERE slug='buffalo-wings'),5,'Buffalo, New York''s hot sauce-tossed chicken wings.'),
((SELECT id FROM dishes WHERE slug='key-lime-pie'),1,'A tangy pie named for a small citrus grown on a chain of islands.'),
((SELECT id FROM dishes WHERE slug='key-lime-pie'),2,'Florida Keys sponge fishermen made this no-bake pie using canned milk long before refrigeration reached the islands.'),
((SELECT id FROM dishes WHERE slug='key-lime-pie'),3,'It''s the official state pie of Florida by legislative decree.'),
((SELECT id FROM dishes WHERE slug='key-lime-pie'),4,'Tart lime juice is whisked with condensed milk and egg into a tangy, set custard pie.'),
((SELECT id FROM dishes WHERE slug='key-lime-pie'),5,'The Florida Keys'' tangy lime custard pie.'),
((SELECT id FROM dishes WHERE slug='clam-bake'),1,'A coastal feast cooked the way it was for centuries, in a pit.'),
((SELECT id FROM dishes WHERE slug='clam-bake'),2,'Indigenous peoples of coastal New England steamed shellfish over hot stones long before European settlers arrived.'),
((SELECT id FROM dishes WHERE slug='clam-bake'),3,'Modern versions still ritually layer seaweed, shellfish and corn for a communal beach feast.'),
((SELECT id FROM dishes WHERE slug='clam-bake'),4,'Clams, lobster, corn and potatoes steam together over hot rocks and seaweed.'),
((SELECT id FROM dishes WHERE slug='clam-bake'),5,'New England''s pit-steamed shellfish and corn feast.'),
((SELECT id FROM dishes WHERE slug='chili-con-carne'),1,'A stew whose ''authentic'' recipe is a source of endless regional feuding.'),
((SELECT id FROM dishes WHERE slug='chili-con-carne'),2,'19th-century cattle-trail cooks in Texas simmered dried beef and chili peppers into a portable, filling stew.'),
((SELECT id FROM dishes WHERE slug='chili-con-carne'),3,'One Texas city hosts a world championship cook-off devoted entirely to it.'),
((SELECT id FROM dishes WHERE slug='chili-con-carne'),4,'Beef simmers with chili, cumin and tomato into a thick, deeply spiced stew.'),
((SELECT id FROM dishes WHERE slug='chili-con-carne'),5,'Texas''s chili pepper and beef stew.'),
((SELECT id FROM dishes WHERE slug='cobb-salad'),1,'A composed salad said to be born from a late-night kitchen raid.'),
((SELECT id FROM dishes WHERE slug='cobb-salad'),2,'A Hollywood restaurateur allegedly threw this together from icebox leftovers in the 1930s.'),
((SELECT id FROM dishes WHERE slug='cobb-salad'),3,'Its neat rows of ingredients became a template copied by diners nationwide.'),
((SELECT id FROM dishes WHERE slug='cobb-salad'),4,'Chopped lettuce is topped with neat rows of chicken, bacon, egg, tomato and cheese.'),
((SELECT id FROM dishes WHERE slug='cobb-salad'),5,'Hollywood''s neatly-arranged chopped salad.'),
((SELECT id FROM dishes WHERE slug='reuben-sandwich'),1,'A grilled deli sandwich named after a person, though nobody agrees who.'),
((SELECT id FROM dishes WHERE slug='reuben-sandwich'),2,'Competing legends credit either an Omaha grocer or a New York deli owner in the early 20th century.'),
((SELECT id FROM dishes WHERE slug='reuben-sandwich'),3,'It''s a diner-menu fixture built entirely around cured beef and tangy cabbage.'),
((SELECT id FROM dishes WHERE slug='reuben-sandwich'),4,'Cured beef, melted cheese and sauerkraut are grilled between slices of rye bread.'),
((SELECT id FROM dishes WHERE slug='reuben-sandwich'),5,'The deli classic of cured beef and sauerkraut on rye.'),
((SELECT id FROM dishes WHERE slug='butter-tart'),1,'A gooey pastry that sparks fierce regional loyalty over one ingredient.'),
((SELECT id FROM dishes WHERE slug='butter-tart'),2,'Early 20th-century Ontario settlers baked this simple sugar-and-egg filled pastry from pantry staples.'),
((SELECT id FROM dishes WHERE slug='butter-tart'),3,'Canadians still argue passionately over whether raisins belong inside it.'),
((SELECT id FROM dishes WHERE slug='butter-tart'),4,'A flaky pastry shell is filled with a gooey butter, sugar and egg mixture and baked.'),
((SELECT id FROM dishes WHERE slug='butter-tart'),5,'Ontario''s gooey sugar-filled pastry tart.'),
((SELECT id FROM dishes WHERE slug='tourtiere'),1,'A spiced meat pie tied to a specific holiday meal.'),
((SELECT id FROM dishes WHERE slug='tourtiere'),2,'French Canadian settlers in Quebec have baked this spiced pie for Christmas Eve feasts since colonial times.'),
((SELECT id FROM dishes WHERE slug='tourtiere'),3,'Families guard their exact spice blend as closely as any secret family recipe.'),
((SELECT id FROM dishes WHERE slug='tourtiere'),4,'Ground pork is spiced with cinnamon and clove, sealed in pastry, and baked.'),
((SELECT id FROM dishes WHERE slug='tourtiere'),5,'Quebec''s spiced Christmas meat pie.'),
((SELECT id FROM dishes WHERE slug='nanaimo-bar'),1,'A no-bake dessert layered like a striped flag.'),
((SELECT id FROM dishes WHERE slug='nanaimo-bar'),2,'A community cookbook in a small British Columbia city popularized this three-layer bar in the 1950s.'),
((SELECT id FROM dishes WHERE slug='nanaimo-bar'),3,'The city that shares its name now hosts an annual festival celebrating it.'),
((SELECT id FROM dishes WHERE slug='nanaimo-bar'),4,'A coconut-crumb base, custard filling and chocolate topping stack into a rich, no-bake bar.'),
((SELECT id FROM dishes WHERE slug='nanaimo-bar'),5,'British Columbia''s three-layer no-bake bar.'),
((SELECT id FROM dishes WHERE slug='elote'),1,'A charred street snack served on a stick.'),
((SELECT id FROM dishes WHERE slug='elote'),2,'Mexican street vendors have grilled corn over open coals since pre-Columbian times.'),
((SELECT id FROM dishes WHERE slug='elote'),3,'Its messy, drippy toppings make it one of the most photographed street foods on social media.'),
((SELECT id FROM dishes WHERE slug='elote'),4,'Grilled corn is slathered in mayonnaise, cheese, chili powder and lime juice.'),
((SELECT id FROM dishes WHERE slug='elote'),5,'Mexico''s charred corn on a stick.'),
((SELECT id FROM dishes WHERE slug='chiles-rellenos'),1,'A stuffed pepper dish that''s battered before frying.'),
((SELECT id FROM dishes WHERE slug='chiles-rellenos'),2,'Puebla convent kitchens are credited with stuffing and battering chilies alongside other regional classics.'),
((SELECT id FROM dishes WHERE slug='chiles-rellenos'),3,'Its light, airy batter is whipped from egg whites just before frying.'),
((SELECT id FROM dishes WHERE slug='chiles-rellenos'),4,'Roasted chilies are stuffed with cheese or meat, dipped in egg batter and fried.'),
((SELECT id FROM dishes WHERE slug='chiles-rellenos'),5,'Puebla''s battered stuffed chili.'),
((SELECT id FROM dishes WHERE slug='pozole'),1,'A hominy stew once reserved for sacred ceremonies.'),
((SELECT id FROM dishes WHERE slug='pozole'),2,'Aztec ritual feasts featured an ancestor of this hominy stew centuries before the conquest.'),
((SELECT id FROM dishes WHERE slug='pozole'),3,'It''s the traditional dish served on Mexican Independence Day across the country.'),
((SELECT id FROM dishes WHERE slug='pozole'),4,'Dried hominy corn simmers with pork and chili into a hearty stew topped with cabbage and radish.'),
((SELECT id FROM dishes WHERE slug='pozole'),5,'Mexico''s hominy and pork stew.'),
((SELECT id FROM dishes WHERE slug='tamales'),1,'A masa dish steamed inside its own wrapper.'),
((SELECT id FROM dishes WHERE slug='tamales'),2,'Mesoamerican civilizations wrapped masa in corn husks for portable meals for warriors and travelers.'),
((SELECT id FROM dishes WHERE slug='tamales'),3,'Families gather for marathon group cooking sessions to make hundreds at once for the holidays.'),
((SELECT id FROM dishes WHERE slug='tamales'),4,'Corn masa is spread on a husk, filled with meat and chili, folded and steamed.'),
((SELECT id FROM dishes WHERE slug='tamales'),5,'Mexico''s husk-wrapped steamed corn masa.'),
((SELECT id FROM dishes WHERE slug='enchiladas'),1,'A rolled tortilla dish drenched in sauce before serving.'),
((SELECT id FROM dishes WHERE slug='enchiladas'),2,'Aztec-era cooks were already rolling tortillas around small fish in chili sauce well before the conquest.'),
((SELECT id FROM dishes WHERE slug='enchiladas'),3,'Its name literally means ''seasoned with chili'' in Spanish.'),
((SELECT id FROM dishes WHERE slug='enchiladas'),4,'Tortillas are filled with chicken, rolled and smothered in a chili sauce and cheese.'),
((SELECT id FROM dishes WHERE slug='enchiladas'),5,'Mexico''s chili-sauced rolled tortillas.'),
((SELECT id FROM dishes WHERE slug='aguachile'),1,'A raw seafood dish whose name means ''chili water''.'),
((SELECT id FROM dishes WHERE slug='aguachile'),2,'Sinaloa fishing communities developed this fiery lime-cured shrimp dish along the Pacific coast.'),
((SELECT id FROM dishes WHERE slug='aguachile'),3,'Its blistering green chili sauce makes it a spicier cousin to ceviche.'),
((SELECT id FROM dishes WHERE slug='aguachile'),4,'Raw shrimp cure quickly in lime juice blended with fiery green chili and cucumber.'),
((SELECT id FROM dishes WHERE slug='aguachile'),5,'Sinaloa''s fiery lime-cured shrimp dish.'),
((SELECT id FROM dishes WHERE slug='arroz-con-pollo'),1,'A one-pot chicken and rice dish claimed by an entire continent.'),
((SELECT id FROM dishes WHERE slug='arroz-con-pollo'),2,'Spanish colonial cooking merged with local ingredients across Latin America to produce countless versions of this dish.'),
((SELECT id FROM dishes WHERE slug='arroz-con-pollo'),3,'Nearly every Latin American country has its own beloved variation and insists its version is the original.'),
((SELECT id FROM dishes WHERE slug='arroz-con-pollo'),4,'Chicken and rice cook together in a seasoned tomato and pepper broth until tender.'),
((SELECT id FROM dishes WHERE slug='arroz-con-pollo'),5,'Latin America''s chicken and rice one-pot dish.'),
((SELECT id FROM dishes WHERE slug='bandeja-paisa'),1,'A massive combination platter said to fuel a whole day''s farm work.'),
((SELECT id FROM dishes WHERE slug='bandeja-paisa'),2,'Coffee-region farmworkers in Colombia''s Antioquia needed a calorie-dense plate to power through long harvest days.'),
((SELECT id FROM dishes WHERE slug='bandeja-paisa'),3,'Restaurants proudly serve it heaped on a platter large enough for two people.'),
((SELECT id FROM dishes WHERE slug='bandeja-paisa'),4,'Beans, rice, ground beef, pork, egg, avocado and plantain all share one enormous plate.'),
((SELECT id FROM dishes WHERE slug='bandeja-paisa'),5,'Colombia''s massive farmer''s combination platter.'),
((SELECT id FROM dishes WHERE slug='asado'),1,'A grilling ritual that doubles as a weekend social event.'),
((SELECT id FROM dishes WHERE slug='asado'),2,'Gaucho cattle herders on the pampas grilled beef over open fire as their daily meal for centuries.'),
((SELECT id FROM dishes WHERE slug='asado'),3,'Sunday gatherings built entirely around this slow grill are a near-sacred family tradition.'),
((SELECT id FROM dishes WHERE slug='asado'),4,'Various cuts of beef grill slowly over wood coals, seasoned simply with salt.'),
((SELECT id FROM dishes WHERE slug='asado'),5,'Argentina''s slow-grilled beef cookout.'),
((SELECT id FROM dishes WHERE slug='milanesa'),1,'A breaded cutlet that Italian immigrants brought across the Atlantic.'),
((SELECT id FROM dishes WHERE slug='milanesa'),2,'Italian immigrants to Argentina in the 19th century adapted Milanese veal cutlets using local beef.'),
((SELECT id FROM dishes WHERE slug='milanesa'),3,'It''s now so common that Argentine households eat it more often than steak.'),
((SELECT id FROM dishes WHERE slug='milanesa'),4,'A thin beef cutlet is breaded and fried until golden and crisp.'),
((SELECT id FROM dishes WHERE slug='milanesa'),5,'Argentina''s breaded fried beef cutlet.'),
((SELECT id FROM dishes WHERE slug='choripan'),1,'A grilled sandwich sold outside every stadium and street fair.'),
((SELECT id FROM dishes WHERE slug='choripan'),2,'Argentine grill culture turned a simple grilled sausage into a portable sandwich for soccer crowds.'),
((SELECT id FROM dishes WHERE slug='choripan'),3,'Its name simply mashes together the words for sausage and bread.'),
((SELECT id FROM dishes WHERE slug='choripan'),4,'A grilled sausage is split and stuffed into crusty bread with tangy chimichurri sauce.'),
((SELECT id FROM dishes WHERE slug='choripan'),5,'Argentina''s grilled sausage sandwich.'),
((SELECT id FROM dishes WHERE slug='anticuchos'),1,'A skewered street food with pre-colonial roots that predate the cattle it now uses.'),
((SELECT id FROM dishes WHERE slug='anticuchos'),2,'Andean communities skewered llama meat over coals long before Spanish colonizers introduced cattle.'),
((SELECT id FROM dishes WHERE slug='anticuchos'),3,'It''s now the most iconic late-night street snack sold outside Lima''s stadiums.'),
((SELECT id FROM dishes WHERE slug='anticuchos'),4,'Marinated beef heart is skewered and grilled over charcoal, basted in a spiced chili sauce.'),
((SELECT id FROM dishes WHERE slug='anticuchos'),5,'Peru''s skewered grilled beef heart.'),
((SELECT id FROM dishes WHERE slug='lomo-saltado'),1,'A stir-fry that reveals a Chinese immigrant chapter of a South American country''s history.'),
((SELECT id FROM dishes WHERE slug='lomo-saltado'),2,'Chinese immigrants to 19th-century Peru brought wok stir-frying, which fused with local beef and potatoes.'),
((SELECT id FROM dishes WHERE slug='lomo-saltado'),3,'It''s the clearest single dish proof of Peru''s deep Chinese-Peruvian culinary fusion, called chifa.'),
((SELECT id FROM dishes WHERE slug='lomo-saltado'),4,'Strips of beef are stir-fried with tomato and onion in soy sauce, served with fries and rice.'),
((SELECT id FROM dishes WHERE slug='lomo-saltado'),5,'Peru''s Chinese-fusion beef stir-fry.'),
((SELECT id FROM dishes WHERE slug='causa-limena'),1,'A layered mashed potato dish colored by a native chili.'),
((SELECT id FROM dishes WHERE slug='causa-limena'),2,'Coastal Peruvian cooks pressed seasoned mashed potato around fillings as a cold layered dish for generations.'),
((SELECT id FROM dishes WHERE slug='causa-limena'),3,'Its bright yellow color comes from a native Peruvian chili pepper mashed into the potato.'),
((SELECT id FROM dishes WHERE slug='causa-limena'),4,'Chili-seasoned mashed potato is layered around a chicken or seafood filling and chilled.'),
((SELECT id FROM dishes WHERE slug='causa-limena'),5,'Peru''s layered yellow potato dish.'),
((SELECT id FROM dishes WHERE slug='fried-plantains'),1,'A twice-fried side dish that turns a starchy fruit into crispy discs.'),
((SELECT id FROM dishes WHERE slug='fried-plantains'),2,'Caribbean cooks brought the plantain from West Africa and made frying it a daily kitchen ritual.'),
((SELECT id FROM dishes WHERE slug='fried-plantains'),3,'It''s smashed flat between fryings, a technique locals call giving it a ''stomp''.'),
((SELECT id FROM dishes WHERE slug='fried-plantains'),4,'Green plantains are sliced, fried, smashed flat, and fried again until crisp.'),
((SELECT id FROM dishes WHERE slug='fried-plantains'),5,'Cuba''s twice-fried crispy plantain.'),
((SELECT id FROM dishes WHERE slug='ropa-vieja'),1,'A shredded beef stew whose name means ''old clothes''.'),
((SELECT id FROM dishes WHERE slug='ropa-vieja'),2,'Sephardic Jewish cooks in the Canary Islands brought a shredded-meat stew tradition that took root in Cuba.'),
((SELECT id FROM dishes WHERE slug='ropa-vieja'),3,'Its name jokes that the shredded, stringy beef resembles a pile of ragged clothing.'),
((SELECT id FROM dishes WHERE slug='ropa-vieja'),4,'Beef is slow-cooked until it shreds, then simmered with tomato, pepper and olives.'),
((SELECT id FROM dishes WHERE slug='ropa-vieja'),5,'Cuba''s shredded beef stew.'),
((SELECT id FROM dishes WHERE slug='mofongo'),1,'A mashed dish pounded in a wooden mortar shaped like a bowl.'),
((SELECT id FROM dishes WHERE slug='mofongo'),2,'West African mashed-starch traditions merged with fried plantain in colonial-era Puerto Rico.'),
((SELECT id FROM dishes WHERE slug='mofongo'),3,'Its dome shape and mortar-and-pestle prep make it a plate that''s often served as its own bowl.'),
((SELECT id FROM dishes WHERE slug='mofongo'),4,'Fried plantain is mashed with garlic and pork cracklings into a dense, savory mound.'),
((SELECT id FROM dishes WHERE slug='mofongo'),5,'Puerto Rico''s mashed fried plantain mound.'),
((SELECT id FROM dishes WHERE slug='injera-with-doro-wat'),1,'A spongy flatbread that also serves as the plate and the utensil.'),
((SELECT id FROM dishes WHERE slug='injera-with-doro-wat'),2,'Ethiopian highland farmers cultivated a tiny ancient grain to ferment into this sour flatbread for centuries.'),
((SELECT id FROM dishes WHERE slug='injera-with-doro-wat'),3,'Diners tear off pieces of the bread itself to scoop up the spicy stew on top.'),
((SELECT id FROM dishes WHERE slug='injera-with-doro-wat'),4,'A tangy fermented flatbread is topped with a fiery chicken and hard-boiled egg stew.'),
((SELECT id FROM dishes WHERE slug='injera-with-doro-wat'),5,'Ethiopia''s sour flatbread topped with spiced chicken stew.'),
((SELECT id FROM dishes WHERE slug='egusi-soup'),1,'A thick soup thickened by a ground melon seed.'),
((SELECT id FROM dishes WHERE slug='egusi-soup'),2,'West African farming communities have ground melon seeds into thickening paste for soups for generations.'),
((SELECT id FROM dishes WHERE slug='egusi-soup'),3,'It''s traditionally eaten by hand, scooped up with a pounded starchy side.'),
((SELECT id FROM dishes WHERE slug='egusi-soup'),4,'Ground melon seeds thicken a spiced soup of leafy greens and beef.'),
((SELECT id FROM dishes WHERE slug='egusi-soup'),5,'West Africa''s melon-seed thickened soup.'),
((SELECT id FROM dishes WHERE slug='suya'),1,'A spiced skewer sold from roadside grills after dark.'),
((SELECT id FROM dishes WHERE slug='suya'),2,'Hausa cattle traders in northern Nigeria developed this peanut-spiced skewer as a portable trail food.'),
((SELECT id FROM dishes WHERE slug='suya'),3,'Its ground peanut and chili spice blend is now bottled and sold as its own seasoning.'),
((SELECT id FROM dishes WHERE slug='suya'),4,'Thin beef strips are coated in a ground peanut and chili spice mix and grilled.'),
((SELECT id FROM dishes WHERE slug='suya'),5,'Nigeria''s peanut-spiced grilled beef skewer.'),
((SELECT id FROM dishes WHERE slug='piri-piri-prawns'),1,'A fiery grilled seafood dish from a former Portuguese colony.'),
((SELECT id FROM dishes WHERE slug='piri-piri-prawns'),2,'Portuguese settlers combined a Mozambican chili with Mediterranean grilling technique for coastal seafood.'),
((SELECT id FROM dishes WHERE slug='piri-piri-prawns'),3,'It''s now a signature dish claimed proudly by both African and Portuguese kitchens.'),
((SELECT id FROM dishes WHERE slug='piri-piri-prawns'),4,'Shrimp are marinated in a fiery chili and garlic sauce and grilled quickly over high heat.'),
((SELECT id FROM dishes WHERE slug='piri-piri-prawns'),5,'Mozambique''s chili-grilled shrimp.'),
((SELECT id FROM dishes WHERE slug='bunny-chow'),1,'A curry served inside a hollowed loaf of bread instead of a bowl.'),
((SELECT id FROM dishes WHERE slug='bunny-chow'),2,'Indian indentured laborers in Durban improvised this portable curry-in-bread meal in the early 20th century.'),
((SELECT id FROM dishes WHERE slug='bunny-chow'),3,'It remains Durban''s most iconic street food, despite the name having nothing to do with rabbits.'),
((SELECT id FROM dishes WHERE slug='bunny-chow'),4,'A hollowed-out bread loaf is filled with a thick, spiced curry and eaten by hand.'),
((SELECT id FROM dishes WHERE slug='bunny-chow'),5,'Durban''s curry served inside hollowed bread.'),
((SELECT id FROM dishes WHERE slug='biltong'),1,'A dried, spiced meat snack that predates refrigeration by centuries.'),
((SELECT id FROM dishes WHERE slug='biltong'),2,'Dutch settlers and indigenous South Africans both dried spiced meat strips to preserve food before refrigeration existed.'),
((SELECT id FROM dishes WHERE slug='biltong'),3,'It''s the snack South Africans reach for at every road trip and rugby match.'),
((SELECT id FROM dishes WHERE slug='biltong'),4,'Beef strips are cured in vinegar and spices, then air-dried until firm and chewy.'),
((SELECT id FROM dishes WHERE slug='biltong'),5,'South Africa''s air-dried spiced meat snack.'),
((SELECT id FROM dishes WHERE slug='koshari'),1,'A carb-heavy street dish layering three starches in one bowl.'),
((SELECT id FROM dishes WHERE slug='koshari'),2,'19th-century Cairo street vendors combined Indian, Italian and Middle Eastern staples into a single cheap meal.'),
((SELECT id FROM dishes WHERE slug='koshari'),3,'It''s widely called Egypt''s national dish, sold from carts on nearly every city corner.'),
((SELECT id FROM dishes WHERE slug='koshari'),4,'Rice, lentils and macaroni layer together, topped with spiced tomato sauce and crispy onions.'),
((SELECT id FROM dishes WHERE slug='koshari'),5,'Egypt''s layered rice, lentil and pasta dish.'),
((SELECT id FROM dishes WHERE slug='tagine-of-lamb-and-prunes'),1,'A slow braise named for the cone-shaped pot it''s cooked in.'),
((SELECT id FROM dishes WHERE slug='tagine-of-lamb-and-prunes'),2,'Berber cooks developed a conical clay pot centuries ago that traps steam for slow desert-oven cooking.'),
((SELECT id FROM dishes WHERE slug='tagine-of-lamb-and-prunes'),3,'Its sweet-and-savory combination of fruit and meat is a hallmark of Moroccan royal cuisine.'),
((SELECT id FROM dishes WHERE slug='tagine-of-lamb-and-prunes'),4,'Lamb braises slowly with prunes, cinnamon and almonds in a cone-shaped clay pot.'),
((SELECT id FROM dishes WHERE slug='tagine-of-lamb-and-prunes'),5,'Morocco''s sweet lamb and prune stew.'),
((SELECT id FROM dishes WHERE slug='fattoush'),1,'A salad that fries its bread instead of throwing it away.'),
((SELECT id FROM dishes WHERE slug='fattoush'),2,'Levantine households turned stale flatbread into crunchy croutons rather than waste it.'),
((SELECT id FROM dishes WHERE slug='fattoush'),3,'Its tangy sumac dressing gives it a distinct lemony color and flavor found nowhere else.'),
((SELECT id FROM dishes WHERE slug='fattoush'),4,'Chopped vegetables toss with crispy fried flatbread pieces and a tart sumac dressing.'),
((SELECT id FROM dishes WHERE slug='fattoush'),5,'Lebanon''s bread and vegetable salad.'),
((SELECT id FROM dishes WHERE slug='tabbouleh'),1,'A salad that''s mostly herb, with just a little grain.'),
((SELECT id FROM dishes WHERE slug='tabbouleh'),2,'Levantine mountain villages built this parsley-heavy salad around bulgur wheat centuries ago.'),
((SELECT id FROM dishes WHERE slug='tabbouleh'),3,'Its parsley-to-grain ratio famously confuses first-timers expecting a grain salad.'),
((SELECT id FROM dishes WHERE slug='tabbouleh'),4,'Finely chopped parsley is tossed with a small amount of bulgur, tomato, mint and lemon.'),
((SELECT id FROM dishes WHERE slug='tabbouleh'),5,'Lebanon''s parsley-forward grain salad.'),
((SELECT id FROM dishes WHERE slug='kibbeh'),1,'A torpedo-shaped fried dumpling stuffed with spiced meat.'),
((SELECT id FROM dishes WHERE slug='kibbeh'),2,'Levantine cooks have pounded bulgur and lamb into a fine paste for this dish for centuries.'),
((SELECT id FROM dishes WHERE slug='kibbeh'),3,'Shaping its hollow torpedo shell by hand is considered a rite of passage in Lebanese kitchens.'),
((SELECT id FROM dishes WHERE slug='kibbeh'),4,'A bulgur and lamb shell is stuffed with spiced ground meat and pine nuts, then fried.'),
((SELECT id FROM dishes WHERE slug='kibbeh'),5,'Lebanon''s fried torpedo-shaped meat dumpling.'),
((SELECT id FROM dishes WHERE slug='manakish'),1,'A flatbread often called the Lebanese pizza.'),
((SELECT id FROM dishes WHERE slug='manakish'),2,'Levantine bakeries have topped flatbread with a wild thyme blend for breakfast for generations.'),
((SELECT id FROM dishes WHERE slug='manakish'),3,'It''s the most common grab-and-go breakfast bought fresh from corner bakeries across Beirut.'),
((SELECT id FROM dishes WHERE slug='manakish'),4,'Dough is topped with a thyme and olive oil paste or cheese, then baked in a hot oven.'),
((SELECT id FROM dishes WHERE slug='manakish'),5,'Lebanon''s thyme-topped breakfast flatbread.'),
((SELECT id FROM dishes WHERE slug='shawarma'),1,'A vertical spit-roasted meat that spread across an entire region.'),
((SELECT id FROM dishes WHERE slug='shawarma'),2,'Ottoman-era cooks stacked marinated meat on a vertical spit, an ancestor of döner kebab and gyro alike.'),
((SELECT id FROM dishes WHERE slug='shawarma'),3,'Its slow-turning spit is now a common sight lit up in shop windows worldwide.'),
((SELECT id FROM dishes WHERE slug='shawarma'),4,'Layers of marinated meat roast slowly on a vertical spit, shaved off and wrapped in pita.'),
((SELECT id FROM dishes WHERE slug='shawarma'),5,'The Levant''s spit-roasted wrapped meat.'),
((SELECT id FROM dishes WHERE slug='muhammara'),1,'A dip whose tang comes from a molasses, not a citrus.'),
((SELECT id FROM dishes WHERE slug='muhammara'),2,'Aleppo households have blended roasted peppers and walnuts into this dip for centuries.'),
((SELECT id FROM dishes WHERE slug='muhammara'),3,'Its distinct sour note comes from pomegranate molasses rather than the usual lemon.'),
((SELECT id FROM dishes WHERE slug='muhammara'),4,'Roasted red peppers blend with walnuts, garlic and pomegranate molasses into a spicy-sweet dip.'),
((SELECT id FROM dishes WHERE slug='muhammara'),5,'Aleppo''s roasted pepper and walnut dip.'),
((SELECT id FROM dishes WHERE slug='khoresh-fesenjan'),1,'A stew whose deep color comes from ground nuts, not spice.'),
((SELECT id FROM dishes WHERE slug='khoresh-fesenjan'),2,'Persian royal courts served this rich walnut and pomegranate stew at banquets for centuries.'),
((SELECT id FROM dishes WHERE slug='khoresh-fesenjan'),3,'Its slow-cooked walnut paste turns the sauce a deep, glossy brown that surprises first-time diners.'),
((SELECT id FROM dishes WHERE slug='khoresh-fesenjan'),4,'Chicken simmers for hours in a ground walnut and tangy pomegranate molasses sauce.'),
((SELECT id FROM dishes WHERE slug='khoresh-fesenjan'),5,'Persia''s walnut and pomegranate chicken stew.'),
((SELECT id FROM dishes WHERE slug='baklava-cheesecake-knafeh'),1,'A cheese-stuffed dessert layered under shredded pastry threads.'),
((SELECT id FROM dishes WHERE slug='baklava-cheesecake-knafeh'),2,'Nablus pastry makers have layered stretchy cheese under crisped semolina threads for generations.'),
((SELECT id FROM dishes WHERE slug='baklava-cheesecake-knafeh'),3,'Its vivid orange top layer comes from a food coloring bakers add for visual drama.'),
((SELECT id FROM dishes WHERE slug='baklava-cheesecake-knafeh'),4,'A gooey cheese layer is topped with crisped shredded pastry, soaked in syrup and crushed pistachio.'),
((SELECT id FROM dishes WHERE slug='baklava-cheesecake-knafeh'),5,'Nablus''s cheese-filled shredded pastry dessert.'),
((SELECT id FROM dishes WHERE slug='lahmacun'),1,'A thin-crust flatbread often called Turkish pizza.'),
((SELECT id FROM dishes WHERE slug='lahmacun'),2,'Southeastern Anatolian bakers have spread minced meat over thin dough for generations before wood-fired baking.'),
((SELECT id FROM dishes WHERE slug='lahmacun'),3,'It''s traditionally rolled up with fresh herbs and a squeeze of lemon and eaten on the go.'),
((SELECT id FROM dishes WHERE slug='lahmacun'),4,'A very thin dough is topped with spiced minced lamb and baked until crisp.'),
((SELECT id FROM dishes WHERE slug='lahmacun'),5,'Türkiye''s thin minced-meat flatbread.'),
((SELECT id FROM dishes WHERE slug='manti'),1,'A tiny dumpling topped with yogurt instead of a dipping sauce.'),
((SELECT id FROM dishes WHERE slug='manti'),2,'Central Asian nomads carried these tiny dumplings along trade routes into Anatolian kitchens centuries ago.'),
((SELECT id FROM dishes WHERE slug='manti'),3,'Making them impossibly small by hand is considered a mark of a skilled cook''s patience.'),
((SELECT id FROM dishes WHERE slug='manti'),4,'Tiny lamb-filled dumplings are boiled and served under garlicky yogurt and chili butter.'),
((SELECT id FROM dishes WHERE slug='manti'),5,'Türkiye''s yogurt-topped miniature dumplings.'),
((SELECT id FROM dishes WHERE slug='kofta'),1,'A grilled meatball found under a dozen different names across a whole region.'),
((SELECT id FROM dishes WHERE slug='kofta'),2,'Ottoman kitchens spread spiced ground-meat skewers across an empire stretching three continents.'),
((SELECT id FROM dishes WHERE slug='kofta'),3,'Nearly every country from Greece to India claims its own name and version of this dish.'),
((SELECT id FROM dishes WHERE slug='kofta'),4,'Spiced ground lamb is shaped around skewers and grilled until charred outside, juicy within.'),
((SELECT id FROM dishes WHERE slug='kofta'),5,'The Ottoman world''s spiced grilled meatball.'),
((SELECT id FROM dishes WHERE slug='khachapuri'),1,'A boat-shaped bread cradling a molten egg and cheese center.'),
((SELECT id FROM dishes WHERE slug='khachapuri'),2,'Georgian bakers shaped this cheese-filled bread into a boat to hold a cracked egg for centuries.'),
((SELECT id FROM dishes WHERE slug='khachapuri'),3,'Diners tear the crust and dip it into the runny egg and cheese pool at the center.'),
((SELECT id FROM dishes WHERE slug='khachapuri'),4,'A boat-shaped bread is filled with melted cheese, topped with a raw egg and butter, then baked.'),
((SELECT id FROM dishes WHERE slug='khachapuri'),5,'Georgia''s boat-shaped cheese and egg bread.'),
((SELECT id FROM dishes WHERE slug='poke-bowl'),1,'A raw fish bowl that started as a fisherman''s simple snack.'),
((SELECT id FROM dishes WHERE slug='poke-bowl'),2,'Native Hawaiian fishermen seasoned cut-up reef fish with sea salt and seaweed as a quick snack for generations.'),
((SELECT id FROM dishes WHERE slug='poke-bowl'),3,'Mainland poke shops have since piled it high with dozens of trendy toppings.'),
((SELECT id FROM dishes WHERE slug='poke-bowl'),4,'Cubed raw tuna is tossed in soy sauce and sesame oil, served over rice with toppings.'),
((SELECT id FROM dishes WHERE slug='poke-bowl'),5,'Hawaii''s seasoned raw fish rice bowl.'),
((SELECT id FROM dishes WHERE slug='meat-pie'),1,'A handheld pastry sold at every sporting match in a country.'),
((SELECT id FROM dishes WHERE slug='meat-pie'),2,'British settlers brought meat pie traditions that became a working-class staple across the continent.'),
((SELECT id FROM dishes WHERE slug='meat-pie'),3,'It''s eaten by the millions at cricket and football matches every single year.'),
((SELECT id FROM dishes WHERE slug='meat-pie'),4,'Diced beef and gravy are sealed inside a flaky pastry shell and baked.'),
((SELECT id FROM dishes WHERE slug='meat-pie'),5,'Australia''s gravy-filled handheld meat pie.'),
((SELECT id FROM dishes WHERE slug='lamington'),1,'A cake cube coated in chocolate and rolled in shredded coconut.'),
((SELECT id FROM dishes WHERE slug='lamington'),2,'A colonial-era governor''s household staff are credited with inventing this cake by accident in the early 1900s.'),
((SELECT id FROM dishes WHERE slug='lamington'),3,'It has its own national day of celebration in July.'),
((SELECT id FROM dishes WHERE slug='lamington'),4,'Squares of sponge cake are dipped in chocolate icing and rolled in desiccated coconut.'),
((SELECT id FROM dishes WHERE slug='lamington'),5,'Australia''s chocolate and coconut-coated sponge cube.'),
((SELECT id FROM dishes WHERE slug='hangi'),1,'A feast cooked entirely underground in heated earth.'),
((SELECT id FROM dishes WHERE slug='hangi'),2,'Maori communities have cooked communal feasts in earth pits lined with heated stones for centuries.'),
((SELECT id FROM dishes WHERE slug='hangi'),3,'Its smoky, earthy flavor comes from hours of steaming beneath the ground, not an oven.'),
((SELECT id FROM dishes WHERE slug='hangi'),4,'Meat and vegetables wrap in leaves and steam for hours in a pit of heated stones.'),
((SELECT id FROM dishes WHERE slug='hangi'),5,'New Zealand''s earth-pit steamed feast.'),
((SELECT id FROM dishes WHERE slug='fish-curry'),1,'A curry shaped by indentured laborers who crossed an entire ocean to get there.'),
((SELECT id FROM dishes WHERE slug='fish-curry'),2,'Indian indentured laborers brought curry-making traditions to Fiji''s sugar plantations in the 19th century.'),
((SELECT id FROM dishes WHERE slug='fish-curry'),3,'It now blends seamlessly with the fresh reef fish caught right off Fiji''s own shores.'),
((SELECT id FROM dishes WHERE slug='fish-curry'),4,'Fresh white fish simmers in a coconut milk curry with turmeric and chili.'),
((SELECT id FROM dishes WHERE slug='fish-curry'),5,'Fiji''s coconut fish curry.'),
((SELECT id FROM dishes WHERE slug='borsch-ukrainian-style'),1,'A crimson soup UNESCO recently recognized as cultural heritage.'),
((SELECT id FROM dishes WHERE slug='borsch-ukrainian-style'),2,'Ukrainian households have simmered this beet soup for generations, passing recipes down each family line.'),
((SELECT id FROM dishes WHERE slug='borsch-ukrainian-style'),3,'UNESCO added it to an urgent safeguarding list in 2022 amid the war, citing its cultural importance.'),
((SELECT id FROM dishes WHERE slug='borsch-ukrainian-style'),4,'Beets, cabbage and pork simmer together into a deep red, tangy soup topped with sour cream.'),
((SELECT id FROM dishes WHERE slug='borsch-ukrainian-style'),5,'Ukraine''s UNESCO-recognized crimson beet soup.'),
((SELECT id FROM dishes WHERE slug='chicken-paprikash'),1,'A creamy stew whose color comes from a spice grown across an entire nation''s fields.'),
((SELECT id FROM dishes WHERE slug='chicken-paprikash'),2,'Hungarian cooks built this dish around paprika after the spice took root nationwide in the 18th century.'),
((SELECT id FROM dishes WHERE slug='chicken-paprikash'),3,'Its rich red sauce is often served spooned over dumplings called nokedli.'),
((SELECT id FROM dishes WHERE slug='chicken-paprikash'),4,'Chicken simmers in a paprika-red sauce finished with a swirl of sour cream.'),
((SELECT id FROM dishes WHERE slug='chicken-paprikash'),5,'Hungary''s paprika-spiced chicken stew.'),
((SELECT id FROM dishes WHERE slug='trdelnik'),1,'A hollow pastry cylinder cooked by wrapping dough around a spinning rod.'),
((SELECT id FROM dishes WHERE slug='trdelnik'),2,'Central European villages have wound sweet dough around a wooden spit over open fire for centuries.'),
((SELECT id FROM dishes WHERE slug='trdelnik'),3,'Its hollow, cinnamon-dusted tube shape now makes it a favorite edible cup for ice cream.'),
((SELECT id FROM dishes WHERE slug='trdelnik'),4,'Sweet dough is wound around a rotating spit, grilled, and rolled in cinnamon sugar.'),
((SELECT id FROM dishes WHERE slug='trdelnik'),5,'Central Europe''s spit-grilled cinnamon pastry tube.'),
((SELECT id FROM dishes WHERE slug='pierniki'),1,'A spiced cookie from a city famous for baking it since the Middle Ages.'),
((SELECT id FROM dishes WHERE slug='pierniki'),2,'A Polish city''s bakers have made this honey-spice cookie since medieval trade routes brought exotic spices through town.'),
((SELECT id FROM dishes WHERE slug='pierniki'),3,'Its recipe was historically so prized it was protected as a closely guarded guild secret.'),
((SELECT id FROM dishes WHERE slug='pierniki'),4,'Honey dough is spiced with cinnamon, ginger and clove, then baked into firm cookies.'),
((SELECT id FROM dishes WHERE slug='pierniki'),5,'Poland''s medieval honey-spice cookie.'),
((SELECT id FROM dishes WHERE slug='haggis'),1,'A savory pudding celebrated with its own annual poem-reading dinner.'),
((SELECT id FROM dishes WHERE slug='haggis'),2,'Scottish farming households used every part of a slaughtered sheep, encasing offal and oats to avoid waste.'),
((SELECT id FROM dishes WHERE slug='haggis'),3,'Every January 25th, Scots gather for a formal dinner where a poet ceremonially addresses it before eating.'),
((SELECT id FROM dishes WHERE slug='haggis'),4,'Minced sheep offal is mixed with oats and suet, encased, and simmered for hours.'),
((SELECT id FROM dishes WHERE slug='haggis'),5,'Scotland''s ceremonially-addressed savory pudding.'),
((SELECT id FROM dishes WHERE slug='colcannon'),1,'A mashed dish traditionally hiding small charms inside for Halloween fortune-telling.'),
((SELECT id FROM dishes WHERE slug='colcannon'),2,'Irish farm households have mashed potato with cabbage as an autumn harvest staple for centuries.'),
((SELECT id FROM dishes WHERE slug='colcannon'),3,'Families once hid a coin or ring inside a bowl of it to predict a diner''s fortune.'),
((SELECT id FROM dishes WHERE slug='colcannon'),4,'Mashed potato is folded together with cooked cabbage, butter and crisped bacon.'),
((SELECT id FROM dishes WHERE slug='colcannon'),5,'Ireland''s mashed potato and cabbage dish.');
