-- Additive migration: batch 3, 15 more dishes (pool only, no schedule rows)
INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('Yorkshire Pudding','yorkshire-pudding','United Kingdom','europe','appetizer','hot','vegetarian','["flour","egg","milk","beef broth"]'),
('Scotch Egg','scotch-egg','United Kingdom','europe','appetizer','cold','pork','["egg","pork","breadcrumbs","flour","mustard"]'),
('Cornish Pasty','cornish-pasty','United Kingdom','europe','entree','hot','beef','["flour","beef","potato","onion","carrot"]'),
('Crepe Suzette','crepe-suzette','France','europe','dessert','hot','vegetarian','["flour","egg","milk","butter","orange","sugar"]'),
('Escargot','escargot','France','europe','appetizer','hot','seafood','["snails","butter","garlic","parsley"]'),
('Kartoffelpuffer','kartoffelpuffer','Germany','europe','breakfast','hot','vegetarian','["potato","egg","onion","flour"]'),
('Bacalhau à Brás','bacalhau-a-bras','Portugal','europe','entree','hot','seafood','["salt cod","potato","egg","onion","olives"]'),
('Smorrebrod','smorrebrod','Denmark','europe','appetizer','cold','seafood','["bread","salmon","egg","dill","cucumber"]'),
('Fish Cakes','fish-cakes','Norway','europe','entree','hot','seafood','["white fish","flour","milk","egg","onion"]'),
('Kanelbulle','kanelbulle','Sweden','europe','dessert','hot','vegetarian','["flour","cinnamon","butter","sugar","cardamom"]'),
('Osso Focaccia','osso-focaccia','Italy','europe','appetizer','hot','vegetarian','["flour","olive oil","yeast","rosemary","salt"]'),
('Focaccia di Recco','focaccia-di-recco','Italy','europe','entree','hot','vegetarian','["flour","cheese","olive oil"]'),
('Pastitsio','pastitsio','Greece','europe','entree','hot','beef','["pasta","beef","tomato","milk","flour","cinnamon","cheese"]'),
('Cullen Skink','cullen-skink','Scotland','europe','appetizer','hot','seafood','["smoked haddock","potato","onion","milk"]'),
('Boxty','boxty','Ireland','europe','breakfast','hot','vegetarian','["potato","flour","buttermilk","egg"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='yorkshire-pudding'),1,'A puffed batter side that shares a county''s name.'),
((SELECT id FROM dishes WHERE slug='yorkshire-pudding'),2,'18th-century cooks in northern England poured batter under roasting meat to catch the dripping fat.'),
((SELECT id FROM dishes WHERE slug='yorkshire-pudding'),3,'It''s the non-negotiable centerpiece of a proper Sunday roast.'),
((SELECT id FROM dishes WHERE slug='yorkshire-pudding'),4,'A simple egg batter is poured into scorching hot fat and baked until it puffs dramatically.'),
((SELECT id FROM dishes WHERE slug='yorkshire-pudding'),5,'Yorkshire''s puffed savory batter side.'),
((SELECT id FROM dishes WHERE slug='scotch-egg'),1,'A picnic snack that hides a whole egg inside meat.'),
((SELECT id FROM dishes WHERE slug='scotch-egg'),2,'A London department store claims to have invented this portable snack in the early 1700s for travelers.'),
((SELECT id FROM dishes WHERE slug='scotch-egg'),3,'It''s a pub-menu fixture, usually served with a smear of mustard.'),
((SELECT id FROM dishes WHERE slug='scotch-egg'),4,'A hard-boiled egg is wrapped in sausage meat, breaded and fried whole.'),
((SELECT id FROM dishes WHERE slug='scotch-egg'),5,'Britain''s sausage-wrapped boiled egg.'),
((SELECT id FROM dishes WHERE slug='cornish-pasty'),1,'A crimped hand pie once carried down into mine shafts.'),
((SELECT id FROM dishes WHERE slug='cornish-pasty'),2,'Cornish tin miners in the 19th century ate this pastry underground, holding the crimped edge as a handle.'),
((SELECT id FROM dishes WHERE slug='cornish-pasty'),3,'It now has European protected-origin status, like Champagne or Parmesan.'),
((SELECT id FROM dishes WHERE slug='cornish-pasty'),4,'Diced beef and root vegetables are sealed in a folded pastry and crimped along one edge.'),
((SELECT id FROM dishes WHERE slug='cornish-pasty'),5,'Cornwall''s crimped meat and vegetable hand pie.'),
((SELECT id FROM dishes WHERE slug='crepe-suzette'),1,'A flambeed dessert with a legendary, possibly apocryphal, origin story.'),
((SELECT id FROM dishes WHERE slug='crepe-suzette'),2,'A waiter allegedly caught fire by accident while preparing this for the Prince of Wales in 1895.'),
((SELECT id FROM dishes WHERE slug='crepe-suzette'),3,'Its tableside flambé remains one of fine dining''s most theatrical desserts.'),
((SELECT id FROM dishes WHERE slug='crepe-suzette'),4,'Thin pancakes are folded in an orange-caramel sauce and flambéed with liqueur.'),
((SELECT id FROM dishes WHERE slug='crepe-suzette'),5,'France''s flambéed orange-sauced pancake.'),
((SELECT id FROM dishes WHERE slug='escargot'),1,'A dish that turns a garden pest into a delicacy.'),
((SELECT id FROM dishes WHERE slug='escargot'),2,'Burgundian peasants gathered these from vineyards for food long before they became fine dining.'),
((SELECT id FROM dishes WHERE slug='escargot'),3,'Special multi-pronged tongs and forks exist just to eat this dish properly.'),
((SELECT id FROM dishes WHERE slug='escargot'),4,'Snails are baked in their shells with garlic-parsley butter until bubbling.'),
((SELECT id FROM dishes WHERE slug='escargot'),5,'Burgundy''s garlic-butter baked snails.'),
((SELECT id FROM dishes WHERE slug='kartoffelpuffer'),1,'A crisped potato dish found at winter markets across a country.'),
((SELECT id FROM dishes WHERE slug='kartoffelpuffer'),2,'German farmhouse kitchens fried grated potato scraps as a way to stretch a humble harvest.'),
((SELECT id FROM dishes WHERE slug='kartoffelpuffer'),3,'Christmas market stalls sell it hot with a dab of applesauce on cold December nights.'),
((SELECT id FROM dishes WHERE slug='kartoffelpuffer'),4,'Grated potato is bound with egg and flour, then fried into crisp golden cakes.'),
((SELECT id FROM dishes WHERE slug='kartoffelpuffer'),5,'Germany''s crisp fried potato pancake.'),
((SELECT id FROM dishes WHERE slug='bacalhau-a-bras'),1,'A dish built around a fish that''s dried, not fresh.'),
((SELECT id FROM dishes WHERE slug='bacalhau-a-bras'),2,'Portuguese sailors preserved cod in salt for long ocean voyages, and cooks built hundreds of recipes around it.'),
((SELECT id FROM dishes WHERE slug='bacalhau-a-bras'),3,'Locals joke there''s a different salt-cod recipe for every day of the year.'),
((SELECT id FROM dishes WHERE slug='bacalhau-a-bras'),4,'Shredded salt cod is scrambled with matchstick potatoes, egg and onion.'),
((SELECT id FROM dishes WHERE slug='bacalhau-a-bras'),5,'Portugal''s shredded salt cod and potato scramble.'),
((SELECT id FROM dishes WHERE slug='smorrebrod'),1,'An open-faced sandwich treated like edible art.'),
((SELECT id FROM dishes WHERE slug='smorrebrod'),2,'Danish farmhands topped dense rye bread with leftovers as a practical field lunch generations ago.'),
((SELECT id FROM dishes WHERE slug='smorrebrod'),3,'Fine restaurants in Copenhagen now compete over its elaborate, artful toppings.'),
((SELECT id FROM dishes WHERE slug='smorrebrod'),4,'A slice of dense rye bread is topped with fish, egg or meat and carefully garnished.'),
((SELECT id FROM dishes WHERE slug='smorrebrod'),5,'Denmark''s open-faced rye sandwich.'),
((SELECT id FROM dishes WHERE slug='fish-cakes'),1,'A humble patty that turns leftover catch into dinner.'),
((SELECT id FROM dishes WHERE slug='fish-cakes'),2,'Coastal Norwegian villages ground surplus fish into patties to stretch a catch through the week.'),
((SELECT id FROM dishes WHERE slug='fish-cakes'),3,'It remains a canned-goods pantry staple in nearly every Norwegian kitchen.'),
((SELECT id FROM dishes WHERE slug='fish-cakes'),4,'Ground white fish is bound with flour and milk, then pan-fried into pale, tender patties.'),
((SELECT id FROM dishes WHERE slug='fish-cakes'),5,'Norway''s ground fish patty.'),
((SELECT id FROM dishes WHERE slug='kanelbulle'),1,'A spiraled pastry celebrated with its own national holiday.'),
((SELECT id FROM dishes WHERE slug='kanelbulle'),2,'Swedish bakeries began twisting cinnamon-spiced dough into buns in the 1920s.'),
((SELECT id FROM dishes WHERE slug='kanelbulle'),3,'Sweden dedicates October 4th entirely to eating this pastry with coffee.'),
((SELECT id FROM dishes WHERE slug='kanelbulle'),4,'Yeasted dough is rolled with cinnamon and butter, coiled, and baked until golden.'),
((SELECT id FROM dishes WHERE slug='kanelbulle'),5,'Sweden''s cinnamon bun with its own holiday.'),
((SELECT id FROM dishes WHERE slug='osso-focaccia'),1,'A dimpled flatbread pressed with fingertips before baking.'),
((SELECT id FROM dishes WHERE slug='osso-focaccia'),2,'Ancient Roman bakers flattened dough directly on hearth stones, an ancestor of this Ligurian bread.'),
((SELECT id FROM dishes WHERE slug='osso-focaccia'),3,'Its trademark dimples are pressed in by hand to hold pools of olive oil.'),
((SELECT id FROM dishes WHERE slug='osso-focaccia'),4,'Dough is stretched, dimpled with fingers, drizzled with olive oil and baked until golden.'),
((SELECT id FROM dishes WHERE slug='osso-focaccia'),5,'Liguria''s dimpled olive oil flatbread.'),
((SELECT id FROM dishes WHERE slug='focaccia-di-recco'),1,'A cheese-filled flatbread stretched paper-thin by hand.'),
((SELECT id FROM dishes WHERE slug='focaccia-di-recco'),2,'A coastal Ligurian town has stretched this cheese-stuffed dough between two ultra-thin sheets for generations.'),
((SELECT id FROM dishes WHERE slug='focaccia-di-recco'),3,'It has earned a protected geographic status limiting who can legally call it by this name.'),
((SELECT id FROM dishes WHERE slug='focaccia-di-recco'),4,'Two paper-thin sheets of dough sandwich soft cheese and bake until blistered and crisp.'),
((SELECT id FROM dishes WHERE slug='focaccia-di-recco'),5,'Liguria''s paper-thin cheese-stuffed flatbread.'),
((SELECT id FROM dishes WHERE slug='pastitsio'),1,'A baked pasta dish Greeks call their answer to lasagna.'),
((SELECT id FROM dishes WHERE slug='pastitsio'),2,'20th-century Greek chef Nikolaos Tselementes layered a béchamel topping onto a spiced meat pasta bake.'),
((SELECT id FROM dishes WHERE slug='pastitsio'),3,'Its cinnamon-spiced meat sauce surprises diners expecting a purely Italian flavor.'),
((SELECT id FROM dishes WHERE slug='pastitsio'),4,'Tube pasta and spiced beef are layered under a thick béchamel and baked until golden.'),
((SELECT id FROM dishes WHERE slug='pastitsio'),5,'Greece''s cinnamon-spiced baked pasta.'),
((SELECT id FROM dishes WHERE slug='cullen-skink'),1,'A creamy soup named for a fishing town and an old word for broth.'),
((SELECT id FROM dishes WHERE slug='cullen-skink'),2,'Fishing families in a small Scottish coastal town simmered smoked fish into this chowder for generations.'),
((SELECT id FROM dishes WHERE slug='cullen-skink'),3,'Its odd name mixes a town''s name with an ancient Scots word for shin, meaning soup stock.'),
((SELECT id FROM dishes WHERE slug='cullen-skink'),4,'Smoked haddock simmers with potato and onion in milk into a creamy, smoky chowder.'),
((SELECT id FROM dishes WHERE slug='cullen-skink'),5,'Scotland''s smoked haddock and potato chowder.'),
((SELECT id FROM dishes WHERE slug='boxty'),1,'A pancake that rhymes with an old Irish saying about marrying well.'),
((SELECT id FROM dishes WHERE slug='boxty'),2,'An old Irish rhyme claims a woman who can''t make it well isn''t fit to be a wife.'),
((SELECT id FROM dishes WHERE slug='boxty'),3,'It survived Ireland''s 19th-century famine years as a resourceful way to stretch scarce potatoes.'),
((SELECT id FROM dishes WHERE slug='boxty'),4,'Grated raw and mashed potato combine with flour and buttermilk, then fry into a griddle cake.'),
((SELECT id FROM dishes WHERE slug='boxty'),5,'Ireland''s potato griddle pancake.');
