-- Additive migration: batch 4, 50 more dishes (pool only, no schedule rows) — USA + European focus
INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('Philly Cheesesteak','philly-cheesesteak','United States','north-america','entree','hot','beef','["beef","cheese","onion","bell pepper","hoagie roll"]'),
('Chicago Deep Dish Pizza','chicago-deep-dish-pizza','United States','north-america','entree','hot','pork','["flour","tomato","cheese","sausage","olive oil"]'),
('New York Bagel with Lox','new-york-bagel-with-lox','United States','north-america','breakfast','cold','seafood','["bagel","salmon","cream cheese","onion","caper"]'),
('Texas Beef Brisket','texas-beef-brisket','United States','north-america','entree','hot','beef','["beef","black pepper","salt","paprika","brown sugar"]'),
('Biscuits and Gravy','biscuits-and-gravy','United States','north-america','breakfast','hot','pork','["flour","butter","milk","pork sausage","black pepper"]'),
('Shrimp and Grits','shrimp-and-grits','United States','north-america','entree','hot','seafood','["shrimp","grits","cheese","bacon","butter"]'),
('Lobster Roll','lobster-roll','United States','north-america','entree','cold','seafood','["lobster","mayonnaise","butter","roll","lemon"]'),
('Manhattan Clam Chowder','manhattan-clam-chowder','United States','north-america','appetizer','hot','seafood','["clam","tomato","potato","onion","celery"]'),
('Crawfish Étouffée','crawfish-etouffee','United States','north-america','entree','hot','seafood','["crawfish","butter","flour","bell pepper","onion","celery"]'),
('Nashville Hot Chicken','nashville-hot-chicken','United States','north-america','entree','hot','poultry','["chicken","flour","cayenne pepper","buttermilk","brown sugar"]'),
('Kansas City BBQ Ribs','kansas-city-bbq-ribs','United States','north-america','entree','hot','pork','["pork ribs","brown sugar","paprika","tomato","molasses"]'),
('Cincinnati Chili','cincinnati-chili','United States','north-america','entree','hot','beef','["beef","cinnamon","tomato","spaghetti","cheese"]'),
('Chicago Hot Dog','chicago-hot-dog','United States','north-america','entree','hot','beef','["hot dog","mustard","onion","tomato","pickle","celery salt"]'),
('Po'' Boy','po-boy','United States','north-america','entree','hot','seafood','["shrimp","bread","lettuce","tomato","mayonnaise"]'),
('Beignets','beignets','United States','north-america','dessert','hot','vegetarian','["flour","egg","milk","sugar","powdered sugar"]'),
('Fried Green Tomatoes','fried-green-tomatoes','United States','north-america','appetizer','hot','vegetarian','["tomato","cornmeal","flour","buttermilk"]'),
('Pimento Cheese Sandwich','pimento-cheese-sandwich','United States','north-america','appetizer','cold','vegetarian','["cheese","pimento pepper","mayonnaise","bread"]'),
('Chicken and Waffles','chicken-and-waffles','United States','north-america','entree','hot','poultry','["chicken","flour","egg","milk","maple syrup"]'),
('Pecan Pie','pecan-pie','United States','north-america','dessert','cold','vegetarian','["pecan","flour","butter","egg","corn syrup","sugar"]'),
('Sweet Potato Pie','sweet-potato-pie','United States','north-america','dessert','cold','vegetarian','["sweet potato","flour","butter","egg","sugar","cinnamon"]'),
('Hush Puppies','hush-puppies','United States','north-america','appetizer','hot','vegetarian','["cornmeal","flour","onion","egg","milk"]'),
('Loco Moco','loco-moco','United States','north-america','entree','hot','beef','["beef","rice","egg","onion","beef broth"]'),
('Tex-Mex Fajitas','tex-mex-fajitas','United States','north-america','entree','hot','beef','["beef","bell pepper","onion","tortilla","lime"]'),
('Frito Pie','frito-pie','United States','north-america','entree','hot','beef','["corn chips","beef","cheese","onion","chili powder"]'),
('Maryland Crab Cakes','maryland-crab-cakes','United States','north-america','appetizer','hot','seafood','["crab","breadcrumbs","egg","mayonnaise","mustard"]'),
('Full English Breakfast','full-english-breakfast','United Kingdom','europe','breakfast','hot','pork','["egg","bacon","sausage","tomato","bread","baked beans"]'),
('Bangers and Mash','bangers-and-mash','United Kingdom','europe','entree','hot','pork','["sausage","potato","onion","butter","milk"]'),
('Welsh Rarebit','welsh-rarebit','United Kingdom','europe','appetizer','hot','vegetarian','["cheese","bread","mustard","beer","butter"]'),
('Eton Mess','eton-mess','United Kingdom','europe','dessert','cold','vegetarian','["strawberry","cream","meringue","sugar"]'),
('Victoria Sponge Cake','victoria-sponge-cake','United Kingdom','europe','dessert','cold','vegetarian','["flour","egg","butter","sugar","strawberry jam","cream"]'),
('Steak and Kidney Pie','steak-and-kidney-pie','United Kingdom','europe','entree','hot','beef','["beef","kidney","flour","onion","beef broth"]'),
('Toad in the Hole','toad-in-the-hole','United Kingdom','europe','entree','hot','pork','["sausage","flour","egg","milk","onion"]'),
('Bubble and Squeak','bubble-and-squeak','United Kingdom','europe','appetizer','hot','vegetarian','["potato","cabbage","onion","butter"]'),
('Flammkuchen','flammkuchen','Germany','europe','appetizer','hot','pork','["flour","cream","onion","bacon"]'),
('Rouladen','rouladen','Germany','europe','entree','hot','beef','["beef","bacon","onion","mustard","pickle"]'),
('Spaetzle','spaetzle','Germany','europe','entree','hot','vegetarian','["flour","egg","milk","butter","cheese"]'),
('Bratwurst','bratwurst','Germany','europe','entree','hot','pork','["pork","mustard","bread roll","sauerkraut"]'),
('Black Forest Cake','black-forest-cake','Germany','europe','dessert','cold','vegetarian','["flour","chocolate","cherry","cream","sugar"]'),
('Tortilla Española','tortilla-espanola','Spain','europe','appetizer','cold','vegetarian','["potato","egg","onion","olive oil"]'),
('Patatas Bravas','patatas-bravas','Spain','europe','appetizer','hot','vegetarian','["potato","tomato","paprika","olive oil","garlic"]'),
('Jamón Croquetas','jamon-croquetas','Spain','europe','appetizer','hot','pork','["ham","flour","milk","butter","breadcrumbs"]'),
('Cassoulet','cassoulet','France','europe','entree','hot','pork','["white bean","pork sausage","duck","garlic","onion"]'),
('Tarte Tatin','tarte-tatin','France','europe','dessert','hot','vegetarian','["apple","flour","butter","sugar"]'),
('Pain au Chocolat','pain-au-chocolat','France','europe','breakfast','hot','vegetarian','["flour","butter","chocolate","egg","yeast"]'),
('Niçoise Salad','nicoise-salad','France','europe','appetizer','cold','seafood','["tuna","egg","olive","tomato","green bean","potato"]'),
('Cacio e Pepe','cacio-e-pepe','Italy','europe','entree','hot','vegetarian','["pasta","cheese","black pepper","butter"]'),
('Bruschetta','bruschetta','Italy','europe','appetizer','cold','vegetarian','["bread","tomato","garlic","olive oil","basil"]'),
('Caprese Salad','caprese-salad','Italy','europe','appetizer','cold','vegetarian','["tomato","mozzarella","basil","olive oil"]'),
('Gnocchi','gnocchi','Italy','europe','entree','hot','vegetarian','["potato","flour","egg","cheese"]'),
('Pissaladière','pissaladiere','France','europe','appetizer','hot','seafood','["flour","onion","olive","anchovy","olive oil"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='philly-cheesesteak'),1,'A sandwich born in a mid-Atlantic American city famous for cracked bells and hoagies.'),
((SELECT id FROM dishes WHERE slug='philly-cheesesteak'),2,'Two Philadelphia hot dog vendors are credited with grilling beef and onions onto a roll in the 1930s.'),
((SELECT id FROM dishes WHERE slug='philly-cheesesteak'),3,'Ordering one at its most famous shops means shouting a fast combo of cheese type and onion preference.'),
((SELECT id FROM dishes WHERE slug='philly-cheesesteak'),4,'Thin-sliced beef and onions griddle together, then get piled onto a long roll with melted cheese.'),
((SELECT id FROM dishes WHERE slug='philly-cheesesteak'),5,'Philadelphia''s griddled beef and cheese sandwich on a long roll.'),
((SELECT id FROM dishes WHERE slug='chicago-deep-dish-pizza'),1,'A pizza from a Midwestern American city known for its skyline and blustery winters.'),
((SELECT id FROM dishes WHERE slug='chicago-deep-dish-pizza'),2,'A downtown restaurant near that city''s river is credited with baking pizza in a deep buttery pan in 1943.'),
((SELECT id FROM dishes WHERE slug='chicago-deep-dish-pizza'),3,'Its inches-thick crust makes tourists wait an hour just for one pie to bake.'),
((SELECT id FROM dishes WHERE slug='chicago-deep-dish-pizza'),4,'Buttery crust lines a deep pan, then gets layered with cheese first and chunky tomato sauce on top.'),
((SELECT id FROM dishes WHERE slug='chicago-deep-dish-pizza'),5,'Chicago''s deep-panned, cheese-first pizza.'),
((SELECT id FROM dishes WHERE slug='new-york-bagel-with-lox'),1,'A breakfast plate from a dense American city famous for delis and boiled-then-baked bread rings.'),
((SELECT id FROM dishes WHERE slug='new-york-bagel-with-lox'),2,'Jewish immigrant bakers brought this cured-salmon-and-bread pairing to that city''s delicatessens generations ago.'),
((SELECT id FROM dishes WHERE slug='new-york-bagel-with-lox'),3,'It''s the go-to order alongside black coffee at that city''s most old-school appetizing shops.'),
((SELECT id FROM dishes WHERE slug='new-york-bagel-with-lox'),4,'A boiled-then-baked bread ring is split and spread with cream cheese, then topped with cured salmon.'),
((SELECT id FROM dishes WHERE slug='new-york-bagel-with-lox'),5,'New York''s cream cheese and cured salmon bagel.'),
((SELECT id FROM dishes WHERE slug='texas-beef-brisket'),1,'A smoked meat from a large American state famous for cattle ranches and barbecue pits.'),
((SELECT id FROM dishes WHERE slug='texas-beef-brisket'),2,'German and Czech immigrant butchers in that state''s hill country began smoking this tough cut low and slow.'),
((SELECT id FROM dishes WHERE slug='texas-beef-brisket'),3,'Its bark-crusted slices are judged by pitmasters on how cleanly they pull apart with just a little tug.'),
((SELECT id FROM dishes WHERE slug='texas-beef-brisket'),4,'A tough beef cut rubbed with pepper and salt smokes for hours until fork-tender with a dark crust.'),
((SELECT id FROM dishes WHERE slug='texas-beef-brisket'),5,'Texas''s slow-smoked, pepper-crusted beef cut.'),
((SELECT id FROM dishes WHERE slug='biscuits-and-gravy'),1,'A breakfast plate from the American South, served on farms and diner counters alike.'),
((SELECT id FROM dishes WHERE slug='biscuits-and-gravy'),2,'Depression-era farm families stretched cheap pork drippings and flour into a filling morning gravy over bread.'),
((SELECT id FROM dishes WHERE slug='biscuits-and-gravy'),3,'It''s the hearty diner breakfast order that arrives smothered in white, peppery sauce.'),
((SELECT id FROM dishes WHERE slug='biscuits-and-gravy'),4,'Buttery baked bread rounds are split and ladled with a peppery sausage-flecked white gravy.'),
((SELECT id FROM dishes WHERE slug='biscuits-and-gravy'),5,'The American South''s sausage gravy over split biscuits.'),
((SELECT id FROM dishes WHERE slug='shrimp-and-grits'),1,'An entree from the American South''s coastal Lowcountry.'),
((SELECT id FROM dishes WHERE slug='shrimp-and-grits'),2,'Coastal fishing communities once ate this simple shrimp-and-cornmeal dish for breakfast before it became a supper favorite.'),
((SELECT id FROM dishes WHERE slug='shrimp-and-grits'),3,'Upscale Southern restaurants elevated this humble fisherman''s breakfast into a signature brunch dish.'),
((SELECT id FROM dishes WHERE slug='shrimp-and-grits'),4,'Ground corn simmers into creamy grits, topped with sautéed shrimp and often bacon.'),
((SELECT id FROM dishes WHERE slug='shrimp-and-grits'),5,'The Lowcountry''s creamy corn grits topped with shrimp.'),
((SELECT id FROM dishes WHERE slug='lobster-roll'),1,'A cold seafood sandwich from a chilly New England coastal state.'),
((SELECT id FROM dishes WHERE slug='lobster-roll'),2,'Roadside seafood shacks along that state''s coast began serving chunks of local catch in a buttered roll last century.'),
((SELECT id FROM dishes WHERE slug='lobster-roll'),3,'Summer tourists line up at coastal shacks for this simple sandwich packed with pricey shellfish.'),
((SELECT id FROM dishes WHERE slug='lobster-roll'),4,'Chilled lobster meat is tossed in mayonnaise or butter and piled into a split, toasted roll.'),
((SELECT id FROM dishes WHERE slug='lobster-roll'),5,'New England''s buttered-roll lobster sandwich.'),
((SELECT id FROM dishes WHERE slug='manhattan-clam-chowder'),1,'A soup from the same American coast as a creamier, white chowder rival.'),
((SELECT id FROM dishes WHERE slug='manhattan-clam-chowder'),2,'New York cooks broke from tradition by adding tomato instead of cream to their clam soup.'),
((SELECT id FROM dishes WHERE slug='manhattan-clam-chowder'),3,'Purists in one New England state have gone so far as to jokingly outlaw this red-broth version.'),
((SELECT id FROM dishes WHERE slug='manhattan-clam-chowder'),4,'Clams simmer with tomato, potato, and vegetables in a broth left cream-free.'),
((SELECT id FROM dishes WHERE slug='manhattan-clam-chowder'),5,'New York''s tomato-based clam chowder.'),
((SELECT id FROM dishes WHERE slug='crawfish-etouffee'),1,'A stew from the swampy bayous of the American Gulf Coast.'),
((SELECT id FROM dishes WHERE slug='crawfish-etouffee'),2,'French-descended Cajun cooks along the bayou built this dish around a dark roux and local mudbugs.'),
((SELECT id FROM dishes WHERE slug='crawfish-etouffee'),3,'Its name means "smothered," describing how the sauce blankets the shellfish.'),
((SELECT id FROM dishes WHERE slug='crawfish-etouffee'),4,'Crawfish tails smother in a dark roux with bell pepper, onion, and celery, served over rice.'),
((SELECT id FROM dishes WHERE slug='crawfish-etouffee'),5,'Cajun Louisiana''s roux-smothered crawfish stew.'),
((SELECT id FROM dishes WHERE slug='nashville-hot-chicken'),1,'A fried chicken dish from a Southern American music city.'),
((SELECT id FROM dishes WHERE slug='nashville-hot-chicken'),2,'Legend says a jilted lover''s revenge recipe, doused in fiery spice, became that city''s signature dish.'),
((SELECT id FROM dishes WHERE slug='nashville-hot-chicken'),3,'Fans rank their order by heat level, with the hottest tier warning diners in advance.'),
((SELECT id FROM dishes WHERE slug='nashville-hot-chicken'),4,'Fried chicken is coated in a cayenne-lard paste hot enough to leave a red crust.'),
((SELECT id FROM dishes WHERE slug='nashville-hot-chicken'),5,'Nashville''s fiery cayenne-crusted fried chicken.'),
((SELECT id FROM dishes WHERE slug='kansas-city-bbq-ribs'),1,'A barbecue style from a Midwestern American city split across a state line.'),
((SELECT id FROM dishes WHERE slug='kansas-city-bbq-ribs'),2,'That city''s smokehouses built their fame on a thick, sweet tomato-and-molasses sauce over slow-smoked meat.'),
((SELECT id FROM dishes WHERE slug='kansas-city-bbq-ribs'),3,'Its barbecue competitions and sauce are considered one of America''s defining regional styles.'),
((SELECT id FROM dishes WHERE slug='kansas-city-bbq-ribs'),4,'Pork ribs smoke for hours, then get glazed in a sweet, sticky tomato-based sauce.'),
((SELECT id FROM dishes WHERE slug='kansas-city-bbq-ribs'),5,'Kansas City''s sweet, tomato-glazed smoked ribs.'),
((SELECT id FROM dishes WHERE slug='cincinnati-chili'),1,'A chili style from an Ohio River city, spooned over noodles instead of eaten from a bowl alone.'),
((SELECT id FROM dishes WHERE slug='cincinnati-chili'),2,'Greek immigrant restaurateurs in that city spiced their chili with cinnamon and cocoa, more stew than chili.'),
((SELECT id FROM dishes WHERE slug='cincinnati-chili'),3,'Locals order it by "way," stacking cheese, onion, and beans in specific numbered layers.'),
((SELECT id FROM dishes WHERE slug='cincinnati-chili'),4,'Cinnamon- and cocoa-spiced beef sauce ladles over spaghetti, topped with a mountain of shredded cheese.'),
((SELECT id FROM dishes WHERE slug='cincinnati-chili'),5,'Cincinnati''s cinnamon-spiced beef sauce over spaghetti.'),
((SELECT id FROM dishes WHERE slug='chicago-hot-dog'),1,'A loaded hot dog from the same Midwestern city famous for its deep-dish pizza.'),
((SELECT id FROM dishes WHERE slug='chicago-hot-dog'),2,'That city''s vendors piled on a garden''s worth of toppings and swore off ketchup entirely.'),
((SELECT id FROM dishes WHERE slug='chicago-hot-dog'),3,'Asking for ketchup on one here can get a diner good-naturedly scolded by the vendor.'),
((SELECT id FROM dishes WHERE slug='chicago-hot-dog'),4,'A steamed all-beef hot dog is dragged through mustard, relish, onion, tomato, pickle, and peppers.'),
((SELECT id FROM dishes WHERE slug='chicago-hot-dog'),5,'Chicago''s all-beef hot dog dragged through the garden.'),
((SELECT id FROM dishes WHERE slug='po-boy'),1,'A sandwich from a jazz-birthplace city on the American Gulf Coast.'),
((SELECT id FROM dishes WHERE slug='po-boy'),2,'Streetcar strikers in that city were fed free sandwiches by sympathetic restaurant owners, giving the dish its name.'),
((SELECT id FROM dishes WHERE slug='po-boy'),3,'Locals debate whether the best filling is fried shrimp, oysters, or roast beef "dressed."'),
((SELECT id FROM dishes WHERE slug='po-boy'),4,'Crispy fried seafood or roast beef piles onto crusty French bread with lettuce, tomato, and mayonnaise.'),
((SELECT id FROM dishes WHERE slug='po-boy'),5,'New Orleans'' fried-seafood sandwich on crusty French bread.'),
((SELECT id FROM dishes WHERE slug='beignets'),1,'A fried dough treat from the same Gulf Coast city famous for its stuffed po'' sandwiches.'),
((SELECT id FROM dishes WHERE slug='beignets'),2,'French colonial settlers brought this fried dough to that city, where a century-old café still serves it round the clock.'),
((SELECT id FROM dishes WHERE slug='beignets'),3,'A dusting of powdered sugar on this pastry inevitably ends up all over diners'' shirts.'),
((SELECT id FROM dishes WHERE slug='beignets'),4,'Squares of yeasted dough fry until puffed, then get buried under powdered sugar.'),
((SELECT id FROM dishes WHERE slug='beignets'),5,'New Orleans'' powdered-sugar fried dough square.'),
((SELECT id FROM dishes WHERE slug='fried-green-tomatoes'),1,'A fried appetizer from the American South, made with unripe garden produce.'),
((SELECT id FROM dishes WHERE slug='fried-green-tomatoes'),2,'Southern home cooks found a use for tomatoes picked before they ripened, frying them up before frost hit.'),
((SELECT id FROM dishes WHERE slug='fried-green-tomatoes'),3,'A novel and film named for a whistle stop cafe made this dish famous nationwide.'),
((SELECT id FROM dishes WHERE slug='fried-green-tomatoes'),4,'Firm unripe tomato slices are dredged in cornmeal and buttermilk, then fried until crisp.'),
((SELECT id FROM dishes WHERE slug='fried-green-tomatoes'),5,'The American South''s cornmeal-fried unripe tomato slices.'),
((SELECT id FROM dishes WHERE slug='pimento-cheese-sandwich'),1,'A cold sandwich spread beloved across the American South.'),
((SELECT id FROM dishes WHERE slug='pimento-cheese-sandwich'),2,'Home cooks in that region folded canned sweet peppers into cheese, dubbing it their own "caviar."'),
((SELECT id FROM dishes WHERE slug='pimento-cheese-sandwich'),3,'It''s famously sold by the tubful at a major American golf tournament''s concession stands.'),
((SELECT id FROM dishes WHERE slug='pimento-cheese-sandwich'),4,'Shredded cheese is mixed with mayonnaise and diced sweet red peppers, then spread on soft white bread.'),
((SELECT id FROM dishes WHERE slug='pimento-cheese-sandwich'),5,'The South''s pepper-flecked cheese spread sandwich.'),
((SELECT id FROM dishes WHERE slug='chicken-and-waffles'),1,'A sweet-and-savory plate popular in American soul food diners.'),
((SELECT id FROM dishes WHERE slug='chicken-and-waffles'),2,'Harlem jazz clubs served this combination to musicians finishing late-night sets, wanting breakfast and supper at once.'),
((SELECT id FROM dishes WHERE slug='chicken-and-waffles'),3,'It''s the dish that made syrup-drizzled fried chicken a beloved brunch order nationwide.'),
((SELECT id FROM dishes WHERE slug='chicken-and-waffles'),4,'Crispy fried chicken pieces rest atop a warm waffle, finished with butter and maple syrup.'),
((SELECT id FROM dishes WHERE slug='chicken-and-waffles'),5,'Soul food''s fried chicken atop a syrup-soaked waffle.'),
((SELECT id FROM dishes WHERE slug='pecan-pie'),1,'A nutty pie from the American South, named for a native tree.'),
((SELECT id FROM dishes WHERE slug='pecan-pie'),2,'Southern cooks began setting whole nuts into a corn-syrup custard once that syrup became cheaply available.'),
((SELECT id FROM dishes WHERE slug='pecan-pie'),3,'It''s a fixture on nearly every American Thanksgiving dessert table alongside its pumpkin cousin.'),
((SELECT id FROM dishes WHERE slug='pecan-pie'),4,'A corn-syrup custard studded with pecan halves bakes inside a flaky crust until set.'),
((SELECT id FROM dishes WHERE slug='pecan-pie'),5,'The American South''s corn-syrup pecan custard pie.'),
((SELECT id FROM dishes WHERE slug='sweet-potato-pie'),1,'A spiced pie from the American South, made from an orange root vegetable.'),
((SELECT id FROM dishes WHERE slug='sweet-potato-pie'),2,'Enslaved African American cooks adapted a European custard pie tradition using a locally abundant tuber.'),
((SELECT id FROM dishes WHERE slug='sweet-potato-pie'),3,'It''s often mistaken for pumpkin pie at holiday tables, though Southern cooks insist it''s not the same.'),
((SELECT id FROM dishes WHERE slug='sweet-potato-pie'),4,'Mashed sweet potato is spiced with cinnamon and nutmeg, poured into a crust, and baked until set.'),
((SELECT id FROM dishes WHERE slug='sweet-potato-pie'),5,'The American South''s cinnamon-spiced sweet potato custard pie.'),
((SELECT id FROM dishes WHERE slug='hush-puppies'),1,'A fried side dish from the American South, often served alongside fried fish.'),
((SELECT id FROM dishes WHERE slug='hush-puppies'),2,'Legend says cooks fried up cornmeal scraps to quiet hungry dogs begging by the campfire, giving the dish its name.'),
((SELECT id FROM dishes WHERE slug='hush-puppies'),3,'Fish camps across the South consider a basket incomplete without a pile of these on the side.'),
((SELECT id FROM dishes WHERE slug='hush-puppies'),4,'Cornmeal batter is dropped by the spoonful into hot oil and fried into golden little balls.'),
((SELECT id FROM dishes WHERE slug='hush-puppies'),5,'The South''s golden fried cornmeal balls.'),
((SELECT id FROM dishes WHERE slug='loco-moco'),1,'A hearty plate-lunch dish from a Pacific American archipelago.'),
((SELECT id FROM dishes WHERE slug='loco-moco'),2,'A drive-in on that island chain''s Big Island invented this dish in the late 1940s for hungry teenagers on a budget.'),
((SELECT id FROM dishes WHERE slug='loco-moco'),3,'It''s considered the ultimate local comfort food across the islands, sold at lunch counters everywhere.'),
((SELECT id FROM dishes WHERE slug='loco-moco'),4,'A beef patty and fried egg sit on a bed of rice, all smothered in brown gravy.'),
((SELECT id FROM dishes WHERE slug='loco-moco'),5,'Hawaii''s rice, burger patty, and gravy plate lunch.'),
((SELECT id FROM dishes WHERE slug='tex-mex-fajitas'),1,'A sizzling entree from the border region of a large American state.'),
((SELECT id FROM dishes WHERE slug='tex-mex-fajitas'),2,'Ranch hands in that borderland once grilled a cheap, tough cut of beef and named the dish for it.'),
((SELECT id FROM dishes WHERE slug='tex-mex-fajitas'),3,'Servers famously carry these to the table on a cast-iron platter still audibly sizzling.'),
((SELECT id FROM dishes WHERE slug='tex-mex-fajitas'),4,'Grilled strips of beef and peppers wrap into warm tortillas with lime and onion.'),
((SELECT id FROM dishes WHERE slug='tex-mex-fajitas'),5,'The Tex-Mex border''s sizzling grilled beef and pepper wrap.'),
((SELECT id FROM dishes WHERE slug='frito-pie'),1,'A quick American snack-turned-meal built on a bag of corn chips.'),
((SELECT id FROM dishes WHERE slug='frito-pie'),2,'A Texas snack-food saleswoman is often credited with first spooning chili directly into a chip bag.'),
((SELECT id FROM dishes WHERE slug='frito-pie'),3,'New Mexico diners still serve it right in the chip bag, split open at the table.'),
((SELECT id FROM dishes WHERE slug='frito-pie'),4,'Corn chips are smothered in beef chili and topped with shredded cheese and onion.'),
((SELECT id FROM dishes WHERE slug='frito-pie'),5,'The Southwest''s chili-topped corn chip snack.'),
((SELECT id FROM dishes WHERE slug='maryland-crab-cakes'),1,'An appetizer from a mid-Atlantic American state famous for its bay and blue crabs.'),
((SELECT id FROM dishes WHERE slug='maryland-crab-cakes'),2,'Watermen along that state''s bay have pan-fried lump crabmeat patties for generations.'),
((SELECT id FROM dishes WHERE slug='maryland-crab-cakes'),3,'Purists there judge a cake by how little filler it uses, letting the crab meat shine.'),
((SELECT id FROM dishes WHERE slug='maryland-crab-cakes'),4,'Lump crabmeat is bound lightly with egg, mayonnaise, and breadcrumbs, then pan-fried until golden.'),
((SELECT id FROM dishes WHERE slug='maryland-crab-cakes'),5,'Maryland''s lightly-bound, pan-fried blue crab cake.'),
((SELECT id FROM dishes WHERE slug='full-english-breakfast'),1,'A hearty morning plate from a country famous for afternoon tea and rainy mornings.'),
((SELECT id FROM dishes WHERE slug='full-english-breakfast'),2,'Working-class households there built this filling plate to fuel a long day''s labor.'),
((SELECT id FROM dishes WHERE slug='full-english-breakfast'),3,'It''s the fry-up jokingly credited with curing hangovers across the country that invented it.'),
((SELECT id FROM dishes WHERE slug='full-english-breakfast'),4,'Eggs, bacon, sausage, grilled tomato, and toast share a plate with baked beans.'),
((SELECT id FROM dishes WHERE slug='full-english-breakfast'),5,'Britain''s fried eggs, bacon, and beans breakfast plate.'),
((SELECT id FROM dishes WHERE slug='bangers-and-mash'),1,'A comforting pub dish from the same country known for its fry-up breakfast.'),
((SELECT id FROM dishes WHERE slug='bangers-and-mash'),2,'Wartime rationing there once caused sausages to sputter and pop from added water, giving them their nickname.'),
((SELECT id FROM dishes WHERE slug='bangers-and-mash'),3,'It''s a staple on nearly every traditional pub menu in the country.'),
((SELECT id FROM dishes WHERE slug='bangers-and-mash'),4,'Grilled sausages sit atop a mound of buttery mashed potato, smothered in onion gravy.'),
((SELECT id FROM dishes WHERE slug='bangers-and-mash'),5,'Britain''s pub-classic sausage and mashed potato plate.'),
((SELECT id FROM dishes WHERE slug='welsh-rarebit'),1,'A savory toast dish from a country within the same island as England.'),
((SELECT id FROM dishes WHERE slug='welsh-rarebit'),2,'Despite its old name suggesting rabbit, this dish has never contained any meat at all.'),
((SELECT id FROM dishes WHERE slug='welsh-rarebit'),3,'Its cheeky historic name pokes fun at poorer households unable to afford real meat.'),
((SELECT id FROM dishes WHERE slug='welsh-rarebit'),4,'A beer-spiked cheese sauce with mustard is poured over toast and browned under a broiler.'),
((SELECT id FROM dishes WHERE slug='welsh-rarebit'),5,'Wales'' beer-and-cheese sauce over toast.'),
((SELECT id FROM dishes WHERE slug='eton-mess'),1,'A messy dessert named for a famous British boarding school.'),
((SELECT id FROM dishes WHERE slug='eton-mess'),2,'Legend says a dropped dessert at that school''s sports day was scooped up and served anyway, mess and all.'),
((SELECT id FROM dishes WHERE slug='eton-mess'),3,'It''s traditionally served at that school''s annual cricket match against a rival institution.'),
((SELECT id FROM dishes WHERE slug='eton-mess'),4,'Broken meringue, whipped cream, and crushed strawberries are folded together into a deliberately messy bowl.'),
((SELECT id FROM dishes WHERE slug='eton-mess'),5,'Britain''s broken meringue, cream, and strawberry dessert.'),
((SELECT id FROM dishes WHERE slug='victoria-sponge-cake'),1,'A layered teatime cake named for a long-reigning British monarch.'),
((SELECT id FROM dishes WHERE slug='victoria-sponge-cake'),2,'That queen is said to have enjoyed a slice of this jam-filled cake with her afternoon tea.'),
((SELECT id FROM dishes WHERE slug='victoria-sponge-cake'),3,'It remains the benchmark bake judged in British baking competitions for a light, even crumb.'),
((SELECT id FROM dishes WHERE slug='victoria-sponge-cake'),4,'Two airy butter cake layers sandwich strawberry jam and whipped cream, dusted with sugar on top.'),
((SELECT id FROM dishes WHERE slug='victoria-sponge-cake'),5,'Britain''s jam-and-cream-filled teatime layer cake.'),
((SELECT id FROM dishes WHERE slug='steak-and-kidney-pie'),1,'A savory pie from the same country famous for its Sunday roasts.'),
((SELECT id FROM dishes WHERE slug='steak-and-kidney-pie'),2,'Butchers there found a use for offal cuts by braising them with beef into a rich pie filling.'),
((SELECT id FROM dishes WHERE slug='steak-and-kidney-pie'),3,'It''s a fixture on traditional British pub menus alongside fish and chips.'),
((SELECT id FROM dishes WHERE slug='steak-and-kidney-pie'),4,'Chunks of beef and kidney braise in a dark gravy, then bake under a golden pastry lid.'),
((SELECT id FROM dishes WHERE slug='steak-and-kidney-pie'),5,'Britain''s beef and kidney pie under a pastry lid.'),
((SELECT id FROM dishes WHERE slug='toad-in-the-hole'),1,'An oddly-named oven dish from Britain, containing no amphibians at all.'),
((SELECT id FROM dishes WHERE slug='toad-in-the-hole'),2,'Frugal home cooks there began baking sausages directly into a pancake-like batter to stretch the meat.'),
((SELECT id FROM dishes WHERE slug='toad-in-the-hole'),3,'Its whimsical name pokes fun at how the sausages seem to peek out of the risen batter like little heads.'),
((SELECT id FROM dishes WHERE slug='toad-in-the-hole'),4,'Sausages are baked directly into a Yorkshire-pudding-style batter until puffed and golden.'),
((SELECT id FROM dishes WHERE slug='toad-in-the-hole'),5,'Britain''s sausages baked into puffed batter.'),
((SELECT id FROM dishes WHERE slug='bubble-and-squeak'),1,'A frying-pan dish named for the sounds it makes while cooking, from Britain.'),
((SELECT id FROM dishes WHERE slug='bubble-and-squeak'),2,'Frugal households there invented this dish to use up leftover vegetables from a Sunday roast.'),
((SELECT id FROM dishes WHERE slug='bubble-and-squeak'),3,'Its name literally describes the noises the pan makes as the vegetables fry.'),
((SELECT id FROM dishes WHERE slug='bubble-and-squeak'),4,'Leftover mashed potato and cabbage are mashed together and pan-fried until crisp and browned.'),
((SELECT id FROM dishes WHERE slug='bubble-and-squeak'),5,'Britain''s fried leftover potato and cabbage cake.'),
((SELECT id FROM dishes WHERE slug='flammkuchen'),1,'A thin flatbread from the border region between France and Germany.'),
((SELECT id FROM dishes WHERE slug='flammkuchen'),2,'Farmers there once used this thin dough to test their wood-fired oven''s temperature before baking bread.'),
((SELECT id FROM dishes WHERE slug='flammkuchen'),3,'Its name literally translates to "flame cake," referencing that fiery oven origin.'),
((SELECT id FROM dishes WHERE slug='flammkuchen'),4,'A paper-thin dough is topped with cream, onion, and bacon, then baked until blistered.'),
((SELECT id FROM dishes WHERE slug='flammkuchen'),5,'The Franco-German border''s cream, onion, and bacon flatbread.'),
((SELECT id FROM dishes WHERE slug='rouladen'),1,'A rolled beef entree from a Central European country famous for its sausages and beer.'),
((SELECT id FROM dishes WHERE slug='rouladen'),2,'Home cooks there stuffed thin beef slices with bacon and pickle, rolling them up for Sunday dinner.'),
((SELECT id FROM dishes WHERE slug='rouladen'),3,'Toothpicks or string traditionally hold each little roll together while it braises.'),
((SELECT id FROM dishes WHERE slug='rouladen'),4,'Thin beef slices are spread with mustard, bacon, onion, and pickle, then rolled and braised.'),
((SELECT id FROM dishes WHERE slug='rouladen'),5,'Germany''s mustard-and-bacon rolled braised beef.'),
((SELECT id FROM dishes WHERE slug='spaetzle'),1,'A soft egg noodle from southern Germany''s region.'),
((SELECT id FROM dishes WHERE slug='spaetzle'),2,'Home cooks there scrape a soft dough through a special press or board directly into boiling water.'),
((SELECT id FROM dishes WHERE slug='spaetzle'),3,'Its irregular little dumpling shape has earned it the nickname "little sparrows" in German.'),
((SELECT id FROM dishes WHERE slug='spaetzle'),4,'A thick egg-and-flour batter is pressed into boiling water, forming small soft noodles, then buttered.'),
((SELECT id FROM dishes WHERE slug='spaetzle'),5,'Southern Germany''s scraped egg-noodle dumpling.'),
((SELECT id FROM dishes WHERE slug='bratwurst'),1,'A grilled sausage synonymous with Germany''s beer gardens.'),
((SELECT id FROM dishes WHERE slug='bratwurst'),2,'Regional German butchers have guarded their own seasoned sausage recipes for centuries, some dating to medieval guild records.'),
((SELECT id FROM dishes WHERE slug='bratwurst'),3,'It''s the sausage most associated with Germany''s beer festivals and street food stalls.'),
((SELECT id FROM dishes WHERE slug='bratwurst'),4,'Seasoned ground pork is stuffed into casing, grilled, and served in a roll with mustard.'),
((SELECT id FROM dishes WHERE slug='bratwurst'),5,'Germany''s grilled pork sausage in a roll.'),
((SELECT id FROM dishes WHERE slug='black-forest-cake'),1,'A chocolate cake named for a mountainous, wooded German region.'),
((SELECT id FROM dishes WHERE slug='black-forest-cake'),2,'Bakers in that shadowy forest region layered chocolate cake with the cherry brandy distilled locally.'),
((SELECT id FROM dishes WHERE slug='black-forest-cake'),3,'Its name and cherry-brandy filling are protected enough that imitators abroad often can''t legally use the full title.'),
((SELECT id FROM dishes WHERE slug='black-forest-cake'),4,'Chocolate sponge layers are soaked in cherry brandy, filled with whipped cream and cherries, and shaved chocolate.'),
((SELECT id FROM dishes WHERE slug='black-forest-cake'),5,'Germany''s cherry-brandy chocolate and cream cake.'),
((SELECT id FROM dishes WHERE slug='tortilla-espanola'),1,'A thick egg dish from an Iberian country, despite sharing a name with a flatbread.'),
((SELECT id FROM dishes WHERE slug='tortilla-espanola'),2,'Farmers there stretched scarce eggs by folding in abundant potatoes during a 19th-century food shortage.'),
((SELECT id FROM dishes WHERE slug='tortilla-espanola'),3,'It''s served at room temperature in wedges as a beloved tapas bar staple.'),
((SELECT id FROM dishes WHERE slug='tortilla-espanola'),4,'Sliced potato and onion cook slowly in olive oil, then bind with beaten egg into a thick cake.'),
((SELECT id FROM dishes WHERE slug='tortilla-espanola'),5,'Spain''s potato and egg tapas cake.'),
((SELECT id FROM dishes WHERE slug='patatas-bravas'),1,'A fried potato tapa from the same Iberian country as the potato omelette above.'),
((SELECT id FROM dishes WHERE slug='patatas-bravas'),2,'Madrid tapas bars popularized dousing fried potato chunks in a fiery paprika sauce mid-20th century.'),
((SELECT id FROM dishes WHERE slug='patatas-bravas'),3,'Its name literally means "fierce potatoes," a nod to the spicy sauce.'),
((SELECT id FROM dishes WHERE slug='patatas-bravas'),4,'Fried potato cubes are drizzled with a smoky paprika-tomato sauce and often garlicky mayonnaise.'),
((SELECT id FROM dishes WHERE slug='patatas-bravas'),5,'Spain''s spicy paprika-sauced fried potato tapa.'),
((SELECT id FROM dishes WHERE slug='jamon-croquetas'),1,'A fried tapa from Spain built around its famous cured ham.'),
((SELECT id FROM dishes WHERE slug='jamon-croquetas'),2,'Home cooks there found a way to use up leftover cured ham scraps by binding them into a creamy fried shape.'),
((SELECT id FROM dishes WHERE slug='jamon-croquetas'),3,'Bartenders across that country''s tapas bars measure their kitchen''s skill by how creamy this fried bite stays inside.'),
((SELECT id FROM dishes WHERE slug='jamon-croquetas'),4,'A thick ham-studded béchamel is chilled, breaded, and deep-fried into a crisp, creamy bite.'),
((SELECT id FROM dishes WHERE slug='jamon-croquetas'),5,'Spain''s cured-ham-studded fried béchamel bite.'),
((SELECT id FROM dishes WHERE slug='cassoulet'),1,'A slow-baked bean stew from southwestern France.'),
((SELECT id FROM dishes WHERE slug='cassoulet'),2,'Farmhouse cooks in that region layered white beans with whatever preserved meats their pantry held.'),
((SELECT id FROM dishes WHERE slug='cassoulet'),3,'Towns in that region still argue over whose version, with duck or without, is the authentic one.'),
((SELECT id FROM dishes WHERE slug='cassoulet'),4,'White beans bake slowly with duck, sausage, and pork under a crust that gets broken and reformed as it cooks.'),
((SELECT id FROM dishes WHERE slug='cassoulet'),5,'Southwestern France''s slow-baked white bean and duck stew.'),
((SELECT id FROM dishes WHERE slug='tarte-tatin'),1,'An upside-down fruit tart from France, said to result from a kitchen mistake.'),
((SELECT id FROM dishes WHERE slug='tarte-tatin'),2,'Two sisters running a hotel there supposedly caramelized apples too long, then flipped the pastry over to save it.'),
((SELECT id FROM dishes WHERE slug='tarte-tatin'),3,'It''s flipped onto the serving plate tableside, revealing its caramelized fruit only at the last moment.'),
((SELECT id FROM dishes WHERE slug='tarte-tatin'),4,'Apples caramelize in butter and sugar under a pastry lid, then the whole tart flips upside down to serve.'),
((SELECT id FROM dishes WHERE slug='tarte-tatin'),5,'France''s caramelized upside-down apple tart.'),
((SELECT id FROM dishes WHERE slug='pain-au-chocolat'),1,'A breakfast pastry from France, filled with something sweet.'),
((SELECT id FROM dishes WHERE slug='pain-au-chocolat'),2,'Bakers there layered butter into yeasted dough, folding in chocolate batons before the morning bake.'),
((SELECT id FROM dishes WHERE slug='pain-au-chocolat'),3,'It''s the pastry French children traditionally grab from the bakery on their way to school.'),
((SELECT id FROM dishes WHERE slug='pain-au-chocolat'),4,'Buttery laminated dough wraps around two chocolate batons and bakes until flaky and golden.'),
((SELECT id FROM dishes WHERE slug='pain-au-chocolat'),5,'France''s flaky chocolate-filled breakfast pastry.'),
((SELECT id FROM dishes WHERE slug='nicoise-salad'),1,'A composed salad named for a sunny city on France''s Mediterranean coast.'),
((SELECT id FROM dishes WHERE slug='nicoise-salad'),2,'Fishing families in that coastal city built this salad around their local catch and garden vegetables.'),
((SELECT id FROM dishes WHERE slug='nicoise-salad'),3,'Purists there insist real versions never include cooked potato or green beans, though most restaurants add them anyway.'),
((SELECT id FROM dishes WHERE slug='nicoise-salad'),4,'Tuna, hard-boiled egg, olives, and tomato arrange over lettuce with green beans and potato.'),
((SELECT id FROM dishes WHERE slug='nicoise-salad'),5,'France''s Riviera composed tuna and egg salad.'),
((SELECT id FROM dishes WHERE slug='cacio-e-pepe'),1,'A simple pasta dish from central Italy, named for just two ingredients.'),
((SELECT id FROM dishes WHERE slug='cacio-e-pepe'),2,'Shepherds in that region carried aged cheese and peppercorns as portable rations, tossing them with pasta over a fire.'),
((SELECT id FROM dishes WHERE slug='cacio-e-pepe'),3,'Its deceptively short ingredient list makes it one of the hardest pasta sauces to get silky instead of clumpy.'),
((SELECT id FROM dishes WHERE slug='cacio-e-pepe'),4,'Pasta water helps melt sharp aged cheese and cracked black pepper into a creamy coating with no cream at all.'),
((SELECT id FROM dishes WHERE slug='cacio-e-pepe'),5,'Rome''s black pepper and aged cheese pasta.'),
((SELECT id FROM dishes WHERE slug='bruschetta'),1,'A simple toasted appetizer from Italy.'),
((SELECT id FROM dishes WHERE slug='bruschetta'),2,'Olive farmers there once tasted freshly pressed oil by rubbing it onto grilled bread with garlic.'),
((SELECT id FROM dishes WHERE slug='bruschetta'),3,'Its garlic-rubbed toast base has since become a canvas for countless toppings worldwide.'),
((SELECT id FROM dishes WHERE slug='bruschetta'),4,'Grilled bread is rubbed with garlic and olive oil, then piled with diced tomato and basil.'),
((SELECT id FROM dishes WHERE slug='bruschetta'),5,'Italy''s garlic-rubbed toast topped with tomato and basil.'),
((SELECT id FROM dishes WHERE slug='caprese-salad'),1,'A simple salad from a Mediterranean Italian island, colored like its national flag.'),
((SELECT id FROM dishes WHERE slug='caprese-salad'),2,'Cooks on that island arranged three ingredients to echo the colors of Italy''s flag.'),
((SELECT id FROM dishes WHERE slug='caprese-salad'),3,'Its patriotic red, white, and green arrangement is instantly recognizable on menus worldwide.'),
((SELECT id FROM dishes WHERE slug='caprese-salad'),4,'Sliced tomato, fresh mozzarella, and basil leaves layer together, drizzled with olive oil.'),
((SELECT id FROM dishes WHERE slug='caprese-salad'),5,'Italy''s tomato, mozzarella, and basil salad.'),
((SELECT id FROM dishes WHERE slug='gnocchi'),1,'A soft potato dumpling from Italy.'),
((SELECT id FROM dishes WHERE slug='gnocchi'),2,'Home cooks there began working boiled potato into dough after the tuber arrived from the Americas centuries ago.'),
((SELECT id FROM dishes WHERE slug='gnocchi'),3,'A fork is traditionally used to press ridges into each dumpling to help sauce cling.'),
((SELECT id FROM dishes WHERE slug='gnocchi'),4,'Boiled potato is mashed and worked into a soft dough with flour and egg, then shaped into small dumplings.'),
((SELECT id FROM dishes WHERE slug='gnocchi'),5,'Italy''s ridged potato dumpling.'),
((SELECT id FROM dishes WHERE slug='pissaladiere'),1,'An onion tart from the same sunny French coastal city as the composed salad above.'),
((SELECT id FROM dishes WHERE slug='pissaladiere'),2,'Sailors and dockworkers in that Mediterranean port city snacked on this slow-cooked onion tart between shifts.'),
((SELECT id FROM dishes WHERE slug='pissaladiere'),3,'Its name comes from a salted fish paste once spread beneath the onions, though anchovies now sit on top instead.'),
((SELECT id FROM dishes WHERE slug='pissaladiere'),4,'Sweet onions cook down slowly, then top a bread base with olives and anchovies.'),
((SELECT id FROM dishes WHERE slug='pissaladiere'),5,'France''s Riviera slow-cooked onion and anchovy tart.');
