-- Additive migration: batch 5, 50 common/well-known dishes (issue #26) — pool only, no schedule rows.
-- INSERTs only, keyed by slug; safe to run once on the live DB.

INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('Grilled Cheese','grilled-cheese','United States','north-america','appetizer','hot','vegetarian','["bread","cheddar","butter"]'),
('Club Sandwich','club-sandwich','United States','north-america','entree','cold','poultry','["bread","chicken","bacon","lettuce","tomato","mayonnaise"]'),
('BLT','blt','United States','north-america','appetizer','cold','pork','["bread","bacon","lettuce","tomato","mayonnaise"]'),
('Buttermilk Pancakes','buttermilk-pancakes','United States','north-america','breakfast','hot','vegetarian','["flour","egg","buttermilk","butter","maple syrup","baking powder"]'),
('French Toast','french-toast','France','europe','breakfast','hot','vegetarian','["bread","egg","milk","cinnamon","sugar","butter"]'),
('Eggs Benedict','eggs-benedict','United States','north-america','breakfast','hot','pork','["egg","english muffin","ham","butter","lemon"]'),
('Corn Dog','corn-dog','United States','north-america','appetizer','hot','pork','["hot dog","cornmeal","flour","egg","milk"]'),
('Sloppy Joe','sloppy-joe','United States','north-america','entree','hot','beef','["beef","tomato","onion","bell pepper","bread roll"]'),
('Chicken Pot Pie','chicken-pot-pie','United States','north-america','entree','hot','poultry','["chicken","flour","butter","carrot","peas","onion","milk"]'),
('Chicken Noodle Soup','chicken-noodle-soup','United States','north-america','appetizer','hot','poultry','["chicken","noodles","carrot","celery","onion","chicken broth"]'),
('New York Cheesecake','new-york-cheesecake','United States','north-america','dessert','cold','vegetarian','["cream cheese","sugar","egg","graham cracker","butter","vanilla"]'),
('Brownies','brownies','United States','north-america','dessert','cold','vegetarian','["chocolate","butter","sugar","egg","flour","cocoa"]'),
('Chocolate Chip Cookies','chocolate-chip-cookies','United States','north-america','dessert','cold','vegetarian','["flour","butter","sugar","chocolate chip","egg","vanilla"]'),
('Glazed Donut','glazed-donut','United States','north-america','dessert','cold','vegetarian','["flour","sugar","egg","milk","yeast","butter"]'),
('Caesar Salad','caesar-salad','Mexico','latin-america','appetizer','cold','vegetarian','["romaine lettuce","parmesan","crouton","garlic","anchovy","lemon","olive oil"]'),
('Chicken Parmesan','chicken-parmesan','United States','north-america','entree','hot','poultry','["chicken","breadcrumbs","tomato","mozzarella","parmesan","pasta"]'),
('Fettuccine Alfredo','fettuccine-alfredo','Italy','europe','entree','hot','vegetarian','["pasta","butter","parmesan","cream","black pepper"]'),
('Spaghetti and Meatballs','spaghetti-and-meatballs','United States','north-america','entree','hot','beef','["pasta","beef","tomato","garlic","onion","parmesan","basil"]'),
('Ravioli','ravioli','Italy','europe','entree','hot','vegetarian','["pasta","ricotta","spinach","egg","parmesan","tomato"]'),
('Minestrone','minestrone','Italy','europe','appetizer','hot','vegetarian','["tomato","white bean","carrot","celery","onion","pasta","zucchini"]'),
('Calzone','calzone','Italy','europe','entree','hot','pork','["flour","mozzarella","ricotta","ham","tomato","yeast"]'),
('Cannoli','cannoli','Italy','europe','dessert','cold','vegetarian','["ricotta","flour","sugar","chocolate chip","pistachio","powdered sugar"]'),
('Burrito','burrito','Mexico','latin-america','entree','hot','beef','["tortilla","beef","rice","black bean","cheese","salsa","sour cream"]'),
('Quesadilla','quesadilla','Mexico','latin-america','appetizer','hot','vegetarian','["tortilla","cheese","jalapeno","onion","cilantro"]'),
('Nachos','nachos','Mexico','latin-america','appetizer','hot','vegetarian','["corn chips","cheese","jalapeno","black bean","salsa","sour cream"]'),
('Fish Tacos','fish-tacos','Mexico','latin-america','entree','hot','seafood','["white fish","tortilla","cabbage","lime","cilantro","sour cream"]'),
('Huevos Rancheros','huevos-rancheros','Mexico','latin-america','breakfast','hot','vegetarian','["egg","tortilla","tomato","chili","black bean","cilantro"]'),
('Chilaquiles','chilaquiles','Mexico','latin-america','breakfast','hot','vegetarian','["tortilla","salsa","egg","cheese","onion","cilantro"]'),
('Flan','flan','Spain','europe','dessert','cold','vegetarian','["egg","milk","sugar","vanilla","cream"]'),
('Tres Leches Cake','tres-leches-cake','Mexico','latin-america','dessert','cold','vegetarian','["flour","egg","milk","condensed milk","evaporated milk","cream","sugar"]'),
('Fried Rice','fried-rice','China','east-asia','entree','hot','vegetarian','["rice","egg","scallion","carrot","peas","soy sauce","garlic"]'),
('Chow Mein','chow-mein','China','east-asia','entree','hot','poultry','["noodles","cabbage","carrot","onion","soy sauce","chicken","bean sprouts"]'),
('Sweet and Sour Pork','sweet-and-sour-pork','China','east-asia','entree','hot','pork','["pork","pineapple","bell pepper","onion","vinegar","sugar","cornstarch"]'),
('General Tso''s Chicken','general-tsos-chicken','United States','north-america','entree','hot','poultry','["chicken","soy sauce","sugar","chili","garlic","ginger","cornstarch"]'),
('Wonton Soup','wonton-soup','China','east-asia','appetizer','hot','pork','["pork","flour","shrimp","scallion","ginger","chicken broth","soy sauce"]'),
('Hot and Sour Soup','hot-and-sour-soup','China','east-asia','appetizer','hot','pork','["tofu","mushroom","egg","vinegar","white pepper","bamboo shoot","cornstarch"]'),
('Tempura','tempura','Japan','east-asia','appetizer','hot','seafood','["shrimp","flour","egg","sweet potato","zucchini","soy sauce"]'),
('Teriyaki Chicken','teriyaki-chicken','Japan','east-asia','entree','hot','poultry','["chicken","soy sauce","sugar","ginger","garlic","rice","sesame"]'),
('Udon','udon','Japan','east-asia','entree','hot','vegetarian','["noodles","dashi","soy sauce","scallion","egg"]'),
('Miso Soup','miso-soup','Japan','east-asia','appetizer','hot','vegetarian','["miso","tofu","seaweed","scallion","dashi"]'),
('Gyoza','gyoza','Japan','east-asia','appetizer','hot','pork','["pork","cabbage","flour","garlic","ginger","scallion","soy sauce"]'),
('Bulgogi','bulgogi','South Korea','east-asia','entree','hot','beef','["beef","soy sauce","sugar","sesame oil","garlic","scallion","pear"]'),
('Naan','naan','India','south-asia','appetizer','hot','vegetarian','["flour","yogurt","yeast","butter","garlic"]'),
('Chicken Korma','chicken-korma','India','south-asia','entree','hot','poultry','["chicken","yogurt","cream","onion","garlic","ginger","almond","garam masala"]'),
('Greek Salad','greek-salad','Greece','europe','appetizer','cold','vegetarian','["tomato","cucumber","feta","olives","onion","olive oil","oregano"]'),
('Gyro','gyro','Greece','europe','entree','hot','pork','["pork","pita","tomato","onion","yogurt","lettuce"]'),
('Thai Green Curry','thai-green-curry','Thailand','southeast-asia','entree','hot','poultry','["chicken","coconut milk","green chili","basil","fish sauce","eggplant","lime leaves"]'),
('Éclair','eclair','France','europe','dessert','cold','vegetarian','["flour","egg","butter","milk","chocolate","cream"]'),
('Croissant','croissant','France','europe','breakfast','hot','vegetarian','["flour","butter","yeast","milk","sugar","egg"]'),
('Belgian Waffles','belgian-waffles','Belgium','europe','breakfast','hot','vegetarian','["flour","egg","milk","butter","sugar","yeast","powdered sugar"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='grilled-cheese'),1,'A hot sandwich beloved at American diners and lunch counters coast to coast.'),
((SELECT id FROM dishes WHERE slug='grilled-cheese'),2,'It became a household staple during the Great Depression, when bread and cheese were cheap and filling.'),
((SELECT id FROM dishes WHERE slug='grilled-cheese'),3,'Diners famously pair it with a bowl of tomato soup for dunking.'),
((SELECT id FROM dishes WHERE slug='grilled-cheese'),4,'Buttered bread is griddled until golden while cheese melts gooey in the middle.'),
((SELECT id FROM dishes WHERE slug='grilled-cheese'),5,'Two slices of griddled buttered bread with melted cheese inside.'),
((SELECT id FROM dishes WHERE slug='club-sandwich'),1,'A triple-decker sandwich found on diner and country-club menus across North America.'),
((SELECT id FROM dishes WHERE slug='club-sandwich'),2,'It is said to have first appeared in American social clubs in the late 1800s.'),
((SELECT id FROM dishes WHERE slug='club-sandwich'),3,'It is the classic order held together with a frilly toothpick and served with fries.'),
((SELECT id FROM dishes WHERE slug='club-sandwich'),4,'Toasted bread is stacked with poultry, bacon, lettuce, tomato and mayonnaise in two tiers.'),
((SELECT id FROM dishes WHERE slug='club-sandwich'),5,'The toasted triple-decker of chicken or turkey, bacon, lettuce and tomato.'),
((SELECT id FROM dishes WHERE slug='blt'),1,'A cold sandwich known across America by a three-letter nickname.'),
((SELECT id FROM dishes WHERE slug='blt'),2,'It grew popular after World War II, when fresh produce became available year-round.'),
((SELECT id FROM dishes WHERE slug='blt'),3,'Its name is simply the initials of its three star ingredients.'),
((SELECT id FROM dishes WHERE slug='blt'),4,'Crisp bacon, lettuce and tomato are layered with mayonnaise on toasted bread.'),
((SELECT id FROM dishes WHERE slug='blt'),5,'The bacon, lettuce and tomato sandwich.'),
((SELECT id FROM dishes WHERE slug='buttermilk-pancakes'),1,'A stack of fluffy breakfast rounds flipped on griddles across America.'),
((SELECT id FROM dishes WHERE slug='buttermilk-pancakes'),2,'Flat cakes on hot stones date back millennia, but the fluffy leavened stack is a New World breakfast icon.'),
((SELECT id FROM dishes WHERE slug='buttermilk-pancakes'),3,'It is the Sunday-morning classic drowned in butter and syrup.'),
((SELECT id FROM dishes WHERE slug='buttermilk-pancakes'),4,'A batter of flour, egg and buttermilk is poured onto a griddle and flipped once bubbles form.'),
((SELECT id FROM dishes WHERE slug='buttermilk-pancakes'),5,'The fluffy griddle cakes stacked and topped with butter and maple syrup.'),
((SELECT id FROM dishes WHERE slug='french-toast'),1,'A breakfast dish whose English name points to a country in Western Europe.'),
((SELECT id FROM dishes WHERE slug='french-toast'),2,'Soaking stale bread in egg and milk dates to ancient Rome; the French call it "lost bread."'),
((SELECT id FROM dishes WHERE slug='french-toast'),3,'It is the brunch favorite for using up yesterday''s loaf.'),
((SELECT id FROM dishes WHERE slug='french-toast'),4,'Bread is dipped in beaten egg and milk, then fried and dusted with cinnamon and sugar.'),
((SELECT id FROM dishes WHERE slug='french-toast'),5,'Custard-soaked bread fried golden and served for breakfast.'),
((SELECT id FROM dishes WHERE slug='eggs-benedict'),1,'A brunch plate that became a New York City icon.'),
((SELECT id FROM dishes WHERE slug='eggs-benedict'),2,'Legend credits a hungover Wall Street broker at a Manhattan hotel in the 1890s.'),
((SELECT id FROM dishes WHERE slug='eggs-benedict'),3,'It is the poached-egg brunch dish smothered in a rich butter-and-yolk sauce.'),
((SELECT id FROM dishes WHERE slug='eggs-benedict'),4,'A poached egg and ham sit on a toasted muffin under hollandaise of egg yolk, butter and lemon.'),
((SELECT id FROM dishes WHERE slug='eggs-benedict'),5,'Poached eggs and ham on an English muffin under hollandaise sauce.'),
((SELECT id FROM dishes WHERE slug='corn-dog'),1,'A stick-food staple of American state fairs and boardwalks.'),
((SELECT id FROM dishes WHERE slug='corn-dog'),2,'It was popularized at fairs and amusement parks in the mid-20th-century United States.'),
((SELECT id FROM dishes WHERE slug='corn-dog'),3,'It is the quintessential fairground snack eaten off a wooden stick.'),
((SELECT id FROM dishes WHERE slug='corn-dog'),4,'A sausage is skewered, dunked in a cornmeal batter, and deep-fried until crisp.'),
((SELECT id FROM dishes WHERE slug='corn-dog'),5,'A batter-dipped, deep-fried hot dog on a stick.'),
((SELECT id FROM dishes WHERE slug='sloppy-joe'),1,'A messy sandwich served in American school cafeterias and diners.'),
((SELECT id FROM dishes WHERE slug='sloppy-joe'),2,'It is said to trace to a mid-1900s Midwestern cook who added tomato sauce to loose ground beef.'),
((SELECT id FROM dishes WHERE slug='sloppy-joe'),3,'Its name warns that you will need extra napkins.'),
((SELECT id FROM dishes WHERE slug='sloppy-joe'),4,'Ground beef is simmered with tomato, onion and pepper, then spooned onto a soft bun.'),
((SELECT id FROM dishes WHERE slug='sloppy-joe'),5,'Saucy ground beef piled on a hamburger bun.'),
((SELECT id FROM dishes WHERE slug='chicken-pot-pie'),1,'A comforting baked dish popular in American homes and diners.'),
((SELECT id FROM dishes WHERE slug='chicken-pot-pie'),2,'Savory meat pies came over with European settlers and became a New World cold-weather staple.'),
((SELECT id FROM dishes WHERE slug='chicken-pot-pie'),3,'It is the ultimate comfort food hidden under a golden pastry lid.'),
((SELECT id FROM dishes WHERE slug='chicken-pot-pie'),4,'Chicken, carrots and peas simmer in a creamy sauce beneath a flaky crust.'),
((SELECT id FROM dishes WHERE slug='chicken-pot-pie'),5,'Creamy chicken and vegetables baked under a pastry top.'),
((SELECT id FROM dishes WHERE slug='chicken-noodle-soup'),1,'A brothy bowl considered comfort in a cup across America.'),
((SELECT id FROM dishes WHERE slug='chicken-noodle-soup'),2,'Immigrant kitchens turned it into the classic American get-well remedy.'),
((SELECT id FROM dishes WHERE slug='chicken-noodle-soup'),3,'It is the soup grandmothers famously serve to cure a cold.'),
((SELECT id FROM dishes WHERE slug='chicken-noodle-soup'),4,'Chicken simmers with noodles, carrot and celery in a clear golden broth.'),
((SELECT id FROM dishes WHERE slug='chicken-noodle-soup'),5,'The get-well soup of chicken, noodles and vegetables in broth.'),
((SELECT id FROM dishes WHERE slug='new-york-cheesecake'),1,'A dense baked dessert that took its name from a big American city.'),
((SELECT id FROM dishes WHERE slug='new-york-cheesecake'),2,'Ancient Greeks made early versions, but cream cheese made this rich style famous in one U.S. metropolis.'),
((SELECT id FROM dishes WHERE slug='new-york-cheesecake'),3,'Delis in that city built their reputations on tall, plain slices of it.'),
((SELECT id FROM dishes WHERE slug='new-york-cheesecake'),4,'Cream cheese, sugar and eggs bake atop a buttery crushed-cracker crust.'),
((SELECT id FROM dishes WHERE slug='new-york-cheesecake'),5,'The dense cream-cheese dessert on a graham crust.'),
((SELECT id FROM dishes WHERE slug='brownies'),1,'A square baked treat born in the United States.'),
((SELECT id FROM dishes WHERE slug='brownies'),2,'One story credits a Chicago hotel chef asked to make a portable dessert for an 1893 world''s fair.'),
((SELECT id FROM dishes WHERE slug='brownies'),3,'Bakers still argue whether the best ones are fudgy or cakey.'),
((SELECT id FROM dishes WHERE slug='brownies'),4,'Melted chocolate, butter, sugar, egg and flour bake into a dense sheet, then get cut into squares.'),
((SELECT id FROM dishes WHERE slug='brownies'),5,'Dense chocolate squares cut from a baked sheet.'),
((SELECT id FROM dishes WHERE slug='chocolate-chip-cookies'),1,'A baked sweet invented by accident in the United States.'),
((SELECT id FROM dishes WHERE slug='chocolate-chip-cookies'),2,'A Massachusetts innkeeper chopped a chocolate bar into her dough in the 1930s and a classic was born.'),
((SELECT id FROM dishes WHERE slug='chocolate-chip-cookies'),3,'Its recipe famously appears on the back of the chocolate-chip bag.'),
((SELECT id FROM dishes WHERE slug='chocolate-chip-cookies'),4,'Butter, sugar, flour and egg are studded with chips and baked until golden.'),
((SELECT id FROM dishes WHERE slug='chocolate-chip-cookies'),5,'The round cookie dotted with melting chocolate chips.'),
((SELECT id FROM dishes WHERE slug='glazed-donut'),1,'A sweet ring popular at American coffee shops and bakeries.'),
((SELECT id FROM dishes WHERE slug='glazed-donut'),2,'Dutch settlers brought fried dough to New Amsterdam; the hole is an American refinement.'),
((SELECT id FROM dishes WHERE slug='glazed-donut'),3,'It is the breakfast pastry cops and coffee are joked about loving.'),
((SELECT id FROM dishes WHERE slug='glazed-donut'),4,'Yeasted dough is fried, then dipped in a thin sugar glaze that sets to a shine.'),
((SELECT id FROM dishes WHERE slug='glazed-donut'),5,'A fried ring of dough coated in sweet glaze.'),
((SELECT id FROM dishes WHERE slug='caesar-salad'),1,'A famous salad invented not in Italy but just across the U.S. border to the south.'),
((SELECT id FROM dishes WHERE slug='caesar-salad'),2,'An Italian restaurateur is said to have thrown it together from kitchen scraps in 1920s Tijuana.'),
((SELECT id FROM dishes WHERE slug='caesar-salad'),3,'Waiters at fancy restaurants still toss it tableside for show.'),
((SELECT id FROM dishes WHERE slug='caesar-salad'),4,'Romaine is coated in a dressing of garlic, anchovy, lemon and parmesan, then topped with croutons.'),
((SELECT id FROM dishes WHERE slug='caesar-salad'),5,'Romaine tossed in a garlicky parmesan dressing with croutons.'),
((SELECT id FROM dishes WHERE slug='chicken-parmesan'),1,'A hearty Italian-American dish that grew up in the United States.'),
((SELECT id FROM dishes WHERE slug='chicken-parmesan'),2,'Southern Italian immigrants adapted their eggplant original using breaded poultry in America.'),
((SELECT id FROM dishes WHERE slug='chicken-parmesan'),3,'It is the red-sauce restaurant classic often served over spaghetti.'),
((SELECT id FROM dishes WHERE slug='chicken-parmesan'),4,'A breaded chicken cutlet is topped with tomato sauce and melted mozzarella, then baked.'),
((SELECT id FROM dishes WHERE slug='chicken-parmesan'),5,'A breaded chicken cutlet baked under tomato sauce and mozzarella.'),
((SELECT id FROM dishes WHERE slug='fettuccine-alfredo'),1,'A rich pasta dish born in the capital of a boot-shaped country.'),
((SELECT id FROM dishes WHERE slug='fettuccine-alfredo'),2,'A Rome restaurateur created it for his pregnant wife in the early 1900s.'),
((SELECT id FROM dishes WHERE slug='fettuccine-alfredo'),3,'It became a Hollywood favorite after honeymooning movie stars raved about it.'),
((SELECT id FROM dishes WHERE slug='fettuccine-alfredo'),4,'Ribbon pasta is tossed with butter and parmesan until it forms a creamy sauce.'),
((SELECT id FROM dishes WHERE slug='fettuccine-alfredo'),5,'Ribbon pasta in a creamy butter-and-parmesan sauce.'),
((SELECT id FROM dishes WHERE slug='spaghetti-and-meatballs'),1,'A pasta plate that is an American icon despite its Italian roots.'),
((SELECT id FROM dishes WHERE slug='spaghetti-and-meatballs'),2,'Italian immigrants in America piled on cheap, plentiful meat in a way rare back home.'),
((SELECT id FROM dishes WHERE slug='spaghetti-and-meatballs'),3,'Two cartoon dogs famously share a strand of it in a Disney film.'),
((SELECT id FROM dishes WHERE slug='spaghetti-and-meatballs'),4,'Long pasta is topped with tomato sauce and rolled balls of seasoned ground beef.'),
((SELECT id FROM dishes WHERE slug='spaghetti-and-meatballs'),5,'Long pasta with tomato sauce and rolled beef meatballs.'),
((SELECT id FROM dishes WHERE slug='ravioli'),1,'A stuffed pasta from a country shaped like a boot.'),
((SELECT id FROM dishes WHERE slug='ravioli'),2,'Medieval Italian cooks were sealing filling inside pasta pockets by the 14th century.'),
((SELECT id FROM dishes WHERE slug='ravioli'),3,'A canned version made it a pantry staple in American kitchens.'),
((SELECT id FROM dishes WHERE slug='ravioli'),4,'Squares of pasta are sealed around a ricotta-and-spinach filling, boiled, then sauced.'),
((SELECT id FROM dishes WHERE slug='ravioli'),5,'Filled pasta pillows served in sauce.'),
((SELECT id FROM dishes WHERE slug='minestrone'),1,'A hearty vegetable soup from southern Europe.'),
((SELECT id FROM dishes WHERE slug='minestrone'),2,'Ancient Romans made thick pottages of whatever vegetables were on hand; this is its heir.'),
((SELECT id FROM dishes WHERE slug='minestrone'),3,'It is the "whatever is in the garden" soup with no fixed recipe.'),
((SELECT id FROM dishes WHERE slug='minestrone'),4,'Beans, tomatoes and seasonal vegetables simmer with small pasta in broth.'),
((SELECT id FROM dishes WHERE slug='minestrone'),5,'The Italian vegetable-and-bean soup with pasta.'),
((SELECT id FROM dishes WHERE slug='calzone'),1,'A folded, stuffed cousin of pizza from southern Italy.'),
((SELECT id FROM dishes WHERE slug='calzone'),2,'Naples street vendors created it as a pizza you could eat while walking.'),
((SELECT id FROM dishes WHERE slug='calzone'),3,'Its name means "trouser leg," for its folded-over shape.'),
((SELECT id FROM dishes WHERE slug='calzone'),4,'Pizza dough is folded over cheese and filling, sealed, and baked into a half-moon.'),
((SELECT id FROM dishes WHERE slug='calzone'),5,'A folded, stuffed pizza pocket.'),
((SELECT id FROM dishes WHERE slug='cannoli'),1,'A crunchy tube-shaped dessert from a Mediterranean island.'),
((SELECT id FROM dishes WHERE slug='cannoli'),2,'It began as a carnival treat on Sicily centuries ago.'),
((SELECT id FROM dishes WHERE slug='cannoli'),3,'A mobster''s famous movie line advises leaving a gun but taking these.'),
((SELECT id FROM dishes WHERE slug='cannoli'),4,'A fried pastry shell is piped full of sweetened ricotta and studded with chocolate.'),
((SELECT id FROM dishes WHERE slug='cannoli'),5,'A crisp shell filled with sweet ricotta cream.'),
((SELECT id FROM dishes WHERE slug='burrito'),1,'A rolled, handheld meal from a country south of the United States.'),
((SELECT id FROM dishes WHERE slug='burrito'),2,'Its name means "little donkey" in Spanish, from that country''s north.'),
((SELECT id FROM dishes WHERE slug='burrito'),3,'A California city gave rise to the oversized, foil-wrapped "mission" style.'),
((SELECT id FROM dishes WHERE slug='burrito'),4,'A large flour tortilla wraps rice, beans, meat and cheese into a tight bundle.'),
((SELECT id FROM dishes WHERE slug='burrito'),5,'A big flour tortilla wrapped around rice, beans and meat.'),
((SELECT id FROM dishes WHERE slug='quesadilla'),1,'A melted-cheese snack from a country south of the Rio Grande.'),
((SELECT id FROM dishes WHERE slug='quesadilla'),2,'Colonial cooks there filled tortillas with cheese soon after Europeans brought dairy.'),
((SELECT id FROM dishes WHERE slug='quesadilla'),3,'Its name comes from the Spanish word for cheese.'),
((SELECT id FROM dishes WHERE slug='quesadilla'),4,'A tortilla is folded over cheese and griddled until crisp and melty.'),
((SELECT id FROM dishes WHERE slug='quesadilla'),5,'A griddled tortilla folded around melted cheese.'),
((SELECT id FROM dishes WHERE slug='nachos'),1,'A shareable snack invented in a town on the U.S.–Mexico border.'),
((SELECT id FROM dishes WHERE slug='nachos'),2,'A maître d'' named Ignacio improvised them for hungry diners in 1940s northern Mexico.'),
((SELECT id FROM dishes WHERE slug='nachos'),3,'They are the loaded stadium snack piled high for the big game.'),
((SELECT id FROM dishes WHERE slug='nachos'),4,'Fried tortilla chips are smothered with melted cheese, jalapeños and toppings.'),
((SELECT id FROM dishes WHERE slug='nachos'),5,'Tortilla chips loaded with melted cheese and jalapeños.'),
((SELECT id FROM dishes WHERE slug='fish-tacos'),1,'A seafood handheld from the coasts of a country south of California.'),
((SELECT id FROM dishes WHERE slug='fish-tacos'),2,'They come from the Baja peninsula, where fishermen fried the day''s catch.'),
((SELECT id FROM dishes WHERE slug='fish-tacos'),3,'Surfers helped carry them north across the border in the late 20th century.'),
((SELECT id FROM dishes WHERE slug='fish-tacos'),4,'Battered or grilled white fish is tucked into a tortilla with cabbage and a lime crema.'),
((SELECT id FROM dishes WHERE slug='fish-tacos'),5,'Fish in a tortilla topped with cabbage and lime.'),
((SELECT id FROM dishes WHERE slug='huevos-rancheros'),1,'A hearty farmhouse breakfast from a country south of the border.'),
((SELECT id FROM dishes WHERE slug='huevos-rancheros'),2,'It was the mid-morning meal of ranch workers in that country.'),
((SELECT id FROM dishes WHERE slug='huevos-rancheros'),3,'Its name literally means "rancher''s eggs."'),
((SELECT id FROM dishes WHERE slug='huevos-rancheros'),4,'Fried eggs sit on tortillas under a warm tomato-chili salsa with beans.'),
((SELECT id FROM dishes WHERE slug='huevos-rancheros'),5,'Fried eggs on tortillas with salsa and beans.'),
((SELECT id FROM dishes WHERE slug='chilaquiles'),1,'A breakfast built to use up leftovers, from a country south of the U.S.'),
((SELECT id FROM dishes WHERE slug='chilaquiles'),2,'Its Nahuatl name reflects the ancient Aztec roots of the region''s cooking.'),
((SELECT id FROM dishes WHERE slug='chilaquiles'),3,'It is the classic morning-after dish for stale tortillas.'),
((SELECT id FROM dishes WHERE slug='chilaquiles'),4,'Fried tortilla pieces are simmered in salsa until softened, then topped with egg and cheese.'),
((SELECT id FROM dishes WHERE slug='chilaquiles'),5,'Tortilla chips simmered in salsa, topped with egg and cheese.'),
((SELECT id FROM dishes WHERE slug='flan'),1,'A wobbly caramel-topped custard popular across the Spanish-speaking world.'),
((SELECT id FROM dishes WHERE slug='flan'),2,'The Romans first baked custards; Spain gave this sweet caramel version its name.'),
((SELECT id FROM dishes WHERE slug='flan'),3,'It is the shimmering dessert unmolded to reveal a pool of caramel on top.'),
((SELECT id FROM dishes WHERE slug='flan'),4,'Eggs, milk and sugar bake in a caramel-lined mold, then flip out custard-side up.'),
((SELECT id FROM dishes WHERE slug='flan'),5,'Caramel-topped baked custard.'),
((SELECT id FROM dishes WHERE slug='tres-leches-cake'),1,'A soaked sponge cake beloved across Latin America.'),
((SELECT id FROM dishes WHERE slug='tres-leches-cake'),2,'It rose to fame in mid-20th-century Mexico, promoted on condensed-milk can labels.'),
((SELECT id FROM dishes WHERE slug='tres-leches-cake'),3,'Its name counts the three dairy liquids it is drenched in.'),
((SELECT id FROM dishes WHERE slug='tres-leches-cake'),4,'Sponge cake is soaked in evaporated, condensed and regular milk, then topped with cream.'),
((SELECT id FROM dishes WHERE slug='tres-leches-cake'),5,'Sponge cake soaked in three kinds of milk.'),
((SELECT id FROM dishes WHERE slug='fried-rice'),1,'A stir-fried staple from the world''s most populous East Asian country.'),
((SELECT id FROM dishes WHERE slug='fried-rice'),2,'Cooks there invented it centuries ago as a tasty way to use day-old rice.'),
((SELECT id FROM dishes WHERE slug='fried-rice'),3,'It is the takeout side that is better made with yesterday''s leftover rice.'),
((SELECT id FROM dishes WHERE slug='fried-rice'),4,'Cold rice is stir-fried in a hot wok with egg, scallion and vegetables.'),
((SELECT id FROM dishes WHERE slug='fried-rice'),5,'Wok-tossed rice with egg and vegetables.'),
((SELECT id FROM dishes WHERE slug='chow-mein'),1,'A stir-fried noodle dish from a large East Asian country.'),
((SELECT id FROM dishes WHERE slug='chow-mein'),2,'Its name simply means "stir-fried noodles" in a southern Chinese dialect.'),
((SELECT id FROM dishes WHERE slug='chow-mein'),3,'It became a defining dish of Chinese-American takeout counters.'),
((SELECT id FROM dishes WHERE slug='chow-mein'),4,'Noodles are tossed in a hot wok with cabbage, carrot and soy sauce.'),
((SELECT id FROM dishes WHERE slug='chow-mein'),5,'Stir-fried noodles with vegetables.'),
((SELECT id FROM dishes WHERE slug='sweet-and-sour-pork'),1,'A tangy stir-fry from a large East Asian country.'),
((SELECT id FROM dishes WHERE slug='sweet-and-sour-pork'),2,'It comes from the Cantonese south, where cooks balanced sugar and vinegar.'),
((SELECT id FROM dishes WHERE slug='sweet-and-sour-pork'),3,'Its bright orange, pineapple-dotted version is a takeout-menu staple worldwide.'),
((SELECT id FROM dishes WHERE slug='sweet-and-sour-pork'),4,'Battered pork is fried, then tossed with pineapple and peppers in a sweet-tart sauce.'),
((SELECT id FROM dishes WHERE slug='sweet-and-sour-pork'),5,'Fried pork in a sweet-and-sour sauce with pineapple.'),
((SELECT id FROM dishes WHERE slug='general-tsos-chicken'),1,'A sweet, crispy chicken dish born in American Chinese restaurants.'),
((SELECT id FROM dishes WHERE slug='general-tsos-chicken'),2,'A Taiwanese chef created it, but New York restaurants made the deep-fried version famous.'),
((SELECT id FROM dishes WHERE slug='general-tsos-chicken'),3,'It is named after a 19th-century Chinese military general who never tasted it.'),
((SELECT id FROM dishes WHERE slug='general-tsos-chicken'),4,'Battered chicken is fried, then coated in a sweet, garlicky, mildly spicy sauce.'),
((SELECT id FROM dishes WHERE slug='general-tsos-chicken'),5,'Crispy fried chicken in a sweet, tangy sauce, named for a general.'),
((SELECT id FROM dishes WHERE slug='wonton-soup'),1,'A brothy bowl of filled dumplings from a large East Asian country.'),
((SELECT id FROM dishes WHERE slug='wonton-soup'),2,'Northern China''s folded dumplings traveled south and slimmed into delicate parcels.'),
((SELECT id FROM dishes WHERE slug='wonton-soup'),3,'It is the starter that opens countless Chinese restaurant meals.'),
((SELECT id FROM dishes WHERE slug='wonton-soup'),4,'Thin wrappers around pork and shrimp float in a clear seasoned broth.'),
((SELECT id FROM dishes WHERE slug='wonton-soup'),5,'Pork-and-shrimp dumplings in clear broth.'),
((SELECT id FROM dishes WHERE slug='hot-and-sour-soup'),1,'A peppery, tangy soup from a large East Asian country.'),
((SELECT id FROM dishes WHERE slug='hot-and-sour-soup'),2,'It hails from central China, balancing heat and sourness as regional cooks prized.'),
((SELECT id FROM dishes WHERE slug='hot-and-sour-soup'),3,'It is the takeout soup that is both spicy and mouth-puckering.'),
((SELECT id FROM dishes WHERE slug='hot-and-sour-soup'),4,'Tofu, mushrooms and egg ribbons simmer in a broth sharpened with vinegar and pepper.'),
((SELECT id FROM dishes WHERE slug='hot-and-sour-soup'),5,'A vinegary, peppery broth with tofu, mushroom and egg.'),
((SELECT id FROM dishes WHERE slug='tempura'),1,'A light fried dish from an East Asian island nation.'),
((SELECT id FROM dishes WHERE slug='tempura'),2,'Portuguese missionaries introduced batter-frying there in the 1500s.'),
((SELECT id FROM dishes WHERE slug='tempura'),3,'Specialist restaurants in that country fry each piece to order at the counter.'),
((SELECT id FROM dishes WHERE slug='tempura'),4,'Shrimp and vegetables are dipped in a thin, cold batter and flash-fried until lacy.'),
((SELECT id FROM dishes WHERE slug='tempura'),5,'Shrimp and vegetables in a light, crispy fried batter.'),
((SELECT id FROM dishes WHERE slug='teriyaki-chicken'),1,'A glossy grilled dish from an East Asian island nation.'),
((SELECT id FROM dishes WHERE slug='teriyaki-chicken'),2,'Its glazing technique was refined in that country and spread worldwide via its restaurants.'),
((SELECT id FROM dishes WHERE slug='teriyaki-chicken'),3,'Its name refers to the shine of the sweet-soy glaze.'),
((SELECT id FROM dishes WHERE slug='teriyaki-chicken'),4,'Chicken is grilled and brushed with a sweet, glossy soy-and-sugar sauce.'),
((SELECT id FROM dishes WHERE slug='teriyaki-chicken'),5,'Chicken glazed in sweet soy sauce.'),
((SELECT id FROM dishes WHERE slug='udon'),1,'A thick noodle from an East Asian island nation.'),
((SELECT id FROM dishes WHERE slug='udon'),2,'Legend says a Buddhist monk brought the noodle-making method there from China.'),
((SELECT id FROM dishes WHERE slug='udon'),3,'Its especially chewy, fat strands set it apart from thinner Asian noodles.'),
((SELECT id FROM dishes WHERE slug='udon'),4,'Thick wheat noodles are served in a dashi-and-soy broth topped with scallion.'),
((SELECT id FROM dishes WHERE slug='udon'),5,'Thick wheat noodles in a light soy broth.'),
((SELECT id FROM dishes WHERE slug='miso-soup'),1,'A savory starter served at nearly every meal in an East Asian island nation.'),
((SELECT id FROM dishes WHERE slug='miso-soup'),2,'Fermented soybean paste has been a dietary cornerstone there for over a thousand years.'),
((SELECT id FROM dishes WHERE slug='miso-soup'),3,'It is the small bowl that arrives before sushi almost everywhere.'),
((SELECT id FROM dishes WHERE slug='miso-soup'),4,'Fermented soybean paste is whisked into dashi with cubes of tofu and seaweed.'),
((SELECT id FROM dishes WHERE slug='miso-soup'),5,'A broth of fermented soybean paste with tofu and seaweed.'),
((SELECT id FROM dishes WHERE slug='gyoza'),1,'A pan-fried dumpling popular in an East Asian island nation.'),
((SELECT id FROM dishes WHERE slug='gyoza'),2,'Soldiers returning from mainland China brought the recipe home after World War II.'),
((SELECT id FROM dishes WHERE slug='gyoza'),3,'Its signature is a crispy browned bottom under a steamed top.'),
((SELECT id FROM dishes WHERE slug='gyoza'),4,'Thin wrappers are stuffed with pork and cabbage, then fried and steamed in one pan.'),
((SELECT id FROM dishes WHERE slug='gyoza'),5,'Pan-fried pork-and-cabbage dumplings.'),
((SELECT id FROM dishes WHERE slug='bulgogi'),1,'A grilled beef dish from a peninsula in East Asia.'),
((SELECT id FROM dishes WHERE slug='bulgogi'),2,'Its roots reach back over a thousand years to the skewered grilled meat of the region.'),
((SELECT id FROM dishes WHERE slug='bulgogi'),3,'Its name literally means "fire meat."'),
((SELECT id FROM dishes WHERE slug='bulgogi'),4,'Thin beef is marinated in soy, sugar, sesame and pear, then grilled quickly.'),
((SELECT id FROM dishes WHERE slug='bulgogi'),5,'Marinated, grilled thin-sliced beef.'),
((SELECT id FROM dishes WHERE slug='naan'),1,'A soft flatbread from a large South Asian country.'),
((SELECT id FROM dishes WHERE slug='naan'),2,'It was baked in the clay ovens of Persian and Mughal courts across the region.'),
((SELECT id FROM dishes WHERE slug='naan'),3,'It is the pillowy bread torn to scoop up curries.'),
((SELECT id FROM dishes WHERE slug='naan'),4,'A leavened dough of flour and yogurt is slapped onto the wall of a blazing clay oven.'),
((SELECT id FROM dishes WHERE slug='naan'),5,'The soft, blistered flatbread baked in a clay oven.'),
((SELECT id FROM dishes WHERE slug='chicken-korma'),1,'A mild, creamy curry from a large South Asian country.'),
((SELECT id FROM dishes WHERE slug='chicken-korma'),2,'It graced the royal Mughal courts, braised gently to please emperors.'),
((SELECT id FROM dishes WHERE slug='chicken-korma'),3,'It is the go-to order for those wanting a curry without the heat.'),
((SELECT id FROM dishes WHERE slug='chicken-korma'),4,'Chicken is braised in a sauce of yogurt, cream and ground almonds.'),
((SELECT id FROM dishes WHERE slug='chicken-korma'),5,'A mild, creamy nut-thickened chicken curry.'),
((SELECT id FROM dishes WHERE slug='greek-salad'),1,'A fresh salad from a sunny country in southeastern Europe.'),
((SELECT id FROM dishes WHERE slug='greek-salad'),2,'Its rustic version has fed the farmers and villagers of that country for generations.'),
((SELECT id FROM dishes WHERE slug='greek-salad'),3,'In its homeland it is simply called "village salad."'),
((SELECT id FROM dishes WHERE slug='greek-salad'),4,'Tomato, cucumber and onion are tossed with olives and a slab of brined white cheese.'),
((SELECT id FROM dishes WHERE slug='greek-salad'),5,'Tomato, cucumber, olives and feta in olive oil.'),
((SELECT id FROM dishes WHERE slug='gyro'),1,'A stacked-meat wrap from a country in southeastern Europe.'),
((SELECT id FROM dishes WHERE slug='gyro'),2,'Vertical-spit roasting arrived there via cooks from the eastern Mediterranean.'),
((SELECT id FROM dishes WHERE slug='gyro'),3,'Its name comes from the Greek word for "turn," like the rotating spit.'),
((SELECT id FROM dishes WHERE slug='gyro'),4,'Meat shaved from a vertical rotisserie is wrapped in pita with tomato, onion and yogurt sauce.'),
((SELECT id FROM dishes WHERE slug='gyro'),5,'Spit-roasted meat in pita with a yogurt-cucumber sauce.'),
((SELECT id FROM dishes WHERE slug='thai-green-curry'),1,'A fragrant, spicy curry from a country in Southeast Asia.'),
((SELECT id FROM dishes WHERE slug='thai-green-curry'),2,'Its curry pastes reflect that kingdom''s blend of native herbs and imported chilies.'),
((SELECT id FROM dishes WHERE slug='thai-green-curry'),3,'It is famous for being one of the spicier curries on the menu.'),
((SELECT id FROM dishes WHERE slug='thai-green-curry'),4,'Chicken simmers in coconut milk with a paste of green chilies, basil and lime leaves.'),
((SELECT id FROM dishes WHERE slug='thai-green-curry'),5,'A coconut curry colored green by chilies and herbs.'),
((SELECT id FROM dishes WHERE slug='eclair'),1,'A long, cream-filled pastry from a country in Western Europe.'),
((SELECT id FROM dishes WHERE slug='eclair'),2,'A celebrated 19th-century chef in that country is credited with perfecting it.'),
((SELECT id FROM dishes WHERE slug='eclair'),3,'Its name means "lightning," supposedly for how fast it is eaten.'),
((SELECT id FROM dishes WHERE slug='eclair'),4,'Choux pastry is baked into a hollow log, filled with cream, and topped with chocolate.'),
((SELECT id FROM dishes WHERE slug='eclair'),5,'A cream-filled choux pastry glazed with chocolate.'),
((SELECT id FROM dishes WHERE slug='croissant'),1,'A flaky breakfast pastry associated with a country in Western Europe.'),
((SELECT id FROM dishes WHERE slug='croissant'),2,'It descends from an Austrian crescent roll, refined into its buttery form in Paris.'),
((SELECT id FROM dishes WHERE slug='croissant'),3,'Its crescent shape gives it its name.'),
((SELECT id FROM dishes WHERE slug='croissant'),4,'Butter is folded into dough again and again, then shaped and baked into flaky layers.'),
((SELECT id FROM dishes WHERE slug='croissant'),5,'The buttery, flaky, crescent-shaped breakfast pastry.'),
((SELECT id FROM dishes WHERE slug='belgian-waffles'),1,'A deep-pocketed breakfast cake named for a small Western European country.'),
((SELECT id FROM dishes WHERE slug='belgian-waffles'),2,'It was introduced to Americans at the 1964 New York World''s Fair.'),
((SELECT id FROM dishes WHERE slug='belgian-waffles'),3,'Its extra-deep squares are built to hold pools of syrup and cream.'),
((SELECT id FROM dishes WHERE slug='belgian-waffles'),4,'A yeasted batter is cooked in a griddle iron into thick squares, then dusted with sugar.'),
((SELECT id FROM dishes WHERE slug='belgian-waffles'),5,'Thick, deep-pocketed waffles dusted with powdered sugar.');
