-- Additive migration: 60 dishes filling the analytics gaps
-- (breakfast, africa, south-asia, cold, seafood) — pool only, no schedule rows.
-- INSERTs only, dish keyed by slug; safe to run once on the live DB.

INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('Couscous','couscous','Morocco','africa','entree','hot','vegetarian','["semolina","carrot","zucchini","chickpeas","onion","turmeric","cinnamon","raisins"]'),
('Fufu','fufu','Ghana','africa','entree','hot','vegetarian','["cassava","plantain","salt"]'),
('Milk Tart','milk-tart','South Africa','africa','dessert','cold','vegetarian','["milk","flour","egg","sugar","cinnamon","butter"]'),
('Moroccan Mint Tea','moroccan-mint-tea','Morocco','africa','drink','hot','vegetarian','["tea","mint","sugar"]'),
('Aloo Paratha','aloo-paratha','India','south-asia','breakfast','hot','vegetarian','["flour","potato","onion","cilantro","cumin","butter","green chili"]'),
('Pani Puri','pani-puri','India','south-asia','appetizer','cold','vegetarian','["flour","semolina","potato","chickpeas","tamarind","mint","cumin"]'),
('Vindaloo','vindaloo','India','south-asia','entree','hot','pork','["pork","vinegar","garlic","chili","cumin","cinnamon","cloves","rice"]'),
('Gulab Jamun','gulab-jamun','India','south-asia','dessert','hot','vegetarian','["milk","flour","sugar","cardamom","rose water","butter"]'),
('Kulfi','kulfi','India','south-asia','dessert','cold','vegetarian','["milk","sugar","cardamom","pistachio","saffron"]'),
('Mango Lassi','mango-lassi','India','south-asia','drink','cold','vegetarian','["mango","yogurt","milk","sugar","cardamom"]'),
('Masala Chai','masala-chai','India','south-asia','drink','hot','vegetarian','["tea","milk","sugar","ginger","cardamom","cinnamon","cloves"]'),
('Aloo Gobi','aloo-gobi','India','south-asia','entree','hot','vegetarian','["potato","cauliflower","turmeric","cumin","ginger","garlic","tomato","cilantro"]'),
('Onion Bhaji','onion-bhaji','India','south-asia','appetizer','hot','vegetarian','["onion","chickpeas","turmeric","cumin","coriander","green chili"]'),
('Raita','raita','India','south-asia','appetizer','cold','vegetarian','["yogurt","cucumber","cumin","mint","cilantro","salt"]'),
('Paneer Tikka','paneer-tikka','India','south-asia','appetizer','hot','vegetarian','["cheese","yogurt","garam masala","turmeric","bell pepper","onion","lemon"]'),
('Soto Ayam','soto-ayam','Indonesia','southeast-asia','entree','hot','poultry','["chicken","turmeric","lemongrass","galangal","noodles","egg","bean sprouts","lime","scallion"]'),
('Nasi Lemak','nasi-lemak','Malaysia','southeast-asia','breakfast','hot','seafood','["rice","coconut milk","anchovy","peanuts","cucumber","egg","chili","pandan"]'),
('Chili Crab','chili-crab','Singapore','southeast-asia','entree','hot','seafood','["crab","tomato","chili","egg","garlic","ginger","bread"]'),
('Halo-Halo','halo-halo','Philippines','southeast-asia','dessert','cold','vegetarian','["shaved ice","evaporated milk","ice cream","coconut","sweet potato","banana"]'),
('Fresh Spring Rolls','fresh-spring-rolls','Vietnam','southeast-asia','appetizer','cold','seafood','["rice paper","shrimp","noodles","lettuce","mint","cilantro","peanuts"]'),
('Pad See Ew','pad-see-ew','Thailand','southeast-asia','entree','hot','poultry','["noodles","chicken","egg","soy sauce","sweet soy sauce","garlic","broccoli"]'),
('Thai Iced Tea','thai-iced-tea','Thailand','southeast-asia','drink','cold','vegetarian','["tea","condensed milk","evaporated milk","sugar","star anise"]'),
('Mango Sticky Rice','mango-sticky-rice','Thailand','southeast-asia','dessert','cold','vegetarian','["rice","mango","coconut milk","sugar","sesame"]'),
('Tom Kha Gai','tom-kha-gai','Thailand','southeast-asia','appetizer','hot','poultry','["chicken","coconut milk","galangal","lemongrass","lime leaves","mushroom","fish sauce","lime"]'),
('Onigiri','onigiri','Japan','east-asia','appetizer','cold','seafood','["rice","seaweed","salmon","salt","sesame"]'),
('Kimbap','kimbap','South Korea','east-asia','appetizer','cold','vegetarian','["rice","seaweed","carrot","egg","spinach","cucumber","sesame oil"]'),
('Mochi','mochi','Japan','east-asia','dessert','cold','vegetarian','["rice","sugar","cornstarch","red bean"]'),
('Bubble Tea','bubble-tea','Taiwan','east-asia','drink','cold','vegetarian','["tea","milk","sugar","tapioca pearl"]'),
('Sashimi','sashimi','Japan','east-asia','appetizer','cold','seafood','["tuna","salmon","soy sauce","wasabi","radish"]'),
('Egg Drop Soup','egg-drop-soup','China','east-asia','appetizer','hot','poultry','["egg","chicken broth","cornstarch","scallion","white pepper","ginger"]'),
('Baba Ganoush','baba-ganoush','Lebanon','middle-east','appetizer','cold','vegetarian','["eggplant","tahini","lemon","garlic","olive oil","cumin"]'),
('Turkish Delight','turkish-delight','Türkiye','middle-east','dessert','cold','vegetarian','["sugar","cornstarch","rose water","pistachio","powdered sugar","lemon"]'),
('Gravlax','gravlax','Sweden','europe','appetizer','cold','seafood','["salmon","dill","sugar","salt","mustard"]'),
('Pickled Herring','pickled-herring','Netherlands','europe','appetizer','cold','seafood','["herring","onion","vinegar","sugar","bay leaf"]'),
('Vichyssoise','vichyssoise','France','europe','appetizer','cold','vegetarian','["potato","leek","cream","chicken broth","butter","scallion"]'),
('Gelato','gelato','Italy','europe','dessert','cold','vegetarian','["milk","sugar","cream","egg","pistachio"]'),
('Bircher Muesli','bircher-muesli','Switzerland','europe','breakfast','cold','vegetarian','["oats","apple","yogurt","milk","lemon","honey","almond"]'),
('Porridge','porridge','Scotland','europe','breakfast','hot','vegetarian','["oats","milk","salt","butter","honey"]'),
('Danish Pastry','danish-pastry','Denmark','europe','breakfast','hot','vegetarian','["flour","butter","yeast","egg","sugar","cream cheese","almond"]'),
('Trifle','trifle','United Kingdom','europe','dessert','cold','vegetarian','["sponge cake","strawberry","cream","egg","milk","sugar","gelatin"]'),
('Potato Salad','potato-salad','Germany','europe','appetizer','cold','vegetarian','["potato","mayonnaise","onion","mustard","vinegar","pickle","egg"]'),
('Crumpets','crumpets','United Kingdom','europe','breakfast','hot','vegetarian','["flour","yeast","milk","baking powder","butter","salt"]'),
('Omelette','omelette','France','europe','breakfast','hot','vegetarian','["egg","butter","cheese","milk","salt"]'),
('Shrimp Cocktail','shrimp-cocktail','United States','north-america','appetizer','cold','seafood','["shrimp","ketchup","horseradish","lemon","celery"]'),
('Cioppino','cioppino','United States','north-america','entree','hot','seafood','["tomato","clam","mussels","crab","shrimp","white wine","garlic","bread"]'),
('Deviled Eggs','deviled-eggs','United States','north-america','appetizer','cold','vegetarian','["egg","mayonnaise","mustard","paprika","vinegar"]'),
('Breakfast Burrito','breakfast-burrito','United States','north-america','breakfast','hot','pork','["tortilla","egg","cheddar","potato","sausage","salsa"]'),
('Coleslaw','coleslaw','United States','north-america','appetizer','cold','vegetarian','["cabbage","carrot","mayonnaise","vinegar","sugar","mustard"]'),
('Waldorf Salad','waldorf-salad','United States','north-america','appetizer','cold','vegetarian','["apple","celery","walnuts","mayonnaise","lettuce","raisins"]'),
('Granola','granola','United States','north-america','breakfast','cold','vegetarian','["oats","honey","almond","raisins","yogurt","cinnamon"]'),
('Crab Rangoon','crab-rangoon','United States','north-america','appetizer','hot','seafood','["crab","cream cheese","scallion","garlic","flour"]'),
('Tuna Salad Sandwich','tuna-salad-sandwich','United States','north-america','entree','cold','seafood','["tuna","mayonnaise","celery","onion","bread","pickle"]'),
('Shrimp Scampi','shrimp-scampi','United States','north-america','entree','hot','seafood','["shrimp","garlic","butter","white wine","lemon","parsley","pasta"]'),
('Hash Browns','hash-browns','United States','north-america','breakfast','hot','vegetarian','["potato","butter","onion","salt","black pepper"]'),
('Ackee and Saltfish','ackee-and-saltfish','Jamaica','latin-america','breakfast','hot','seafood','["salt cod","ackee","onion","tomato","bell pepper","thyme"]'),
('Horchata','horchata','Mexico','latin-america','drink','cold','vegetarian','["rice","cinnamon","sugar","milk","vanilla"]'),
('Pico de Gallo','pico-de-gallo','Mexico','latin-america','appetizer','cold','vegetarian','["tomato","onion","cilantro","jalapeno","lime","salt"]'),
('Pupusas','pupusas','El Salvador','latin-america','breakfast','hot','vegetarian','["cornmeal","cheese","beans","cabbage","tomato","vinegar"]'),
('Avocado Toast','avocado-toast','Australia','oceania','breakfast','cold','vegetarian','["bread","avocado","lemon","olive oil","chili","salt"]'),
('Vegemite Toast','vegemite-toast','Australia','oceania','breakfast','hot','vegetarian','["bread","butter","yeast extract","salt"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='couscous'),1,'A staple of North Africa, from the kingdom at the continent''s northwest corner.'),
((SELECT id FROM dishes WHERE slug='couscous'),2,'Berber cooks were making it by the 13th century; UNESCO listed it as shared heritage of Morocco, Algeria, Tunisia and Mauritania in 2020.'),
((SELECT id FROM dishes WHERE slug='couscous'),3,'It is the traditional Friday family meal across the Maghreb, and the box of the instant version is in half the pantries in Europe.'),
((SELECT id FROM dishes WHERE slug='couscous'),4,'Semolina is rubbed with water into tiny pellets, then steamed — never boiled — in a perforated pot set over the stew it will be served with.'),
((SELECT id FROM dishes WHERE slug='couscous'),5,'Tiny steamed pellets of semolina, fluffed up and piled under a spiced vegetable and chickpea stew — the Friday meal of North Africa.'),
((SELECT id FROM dishes WHERE slug='fufu'),1,'A staple of West Africa, especially the country on the Gulf of Guinea once called the Gold Coast.'),
((SELECT id FROM dishes WHERE slug='fufu'),2,'Pounding starchy roots into a smooth dough is one of the region''s oldest techniques, done in a tall wooden mortar with a long pestle.'),
((SELECT id FROM dishes WHERE slug='fufu'),3,'It went viral worldwide on TikTok, where the running joke is that newcomers keep chewing it instead of swallowing.'),
((SELECT id FROM dishes WHERE slug='fufu'),4,'Boiled cassava and plantain are pounded until stretchy and springy, rolled into a ball, and dipped into soup — you tear, dip, and swallow.'),
((SELECT id FROM dishes WHERE slug='fufu'),5,'A smooth, springy pounded ball of cassava and plantain, served in a bowl of West African soup and swallowed rather than chewed.'),
((SELECT id FROM dishes WHERE slug='milk-tart'),1,'A dessert from the country at the southern tip of Africa, the one with eleven official languages.'),
((SELECT id FROM dishes WHERE slug='milk-tart'),2,'Dutch settlers at the Cape adapted a 17th-century Netherlands custard tart, using far more dairy and far less egg.'),
((SELECT id FROM dishes WHERE slug='milk-tart'),3,'It has its own national day in February, and Afrikaans speakers know it by a one-word name ending in "-tert".'),
((SELECT id FROM dishes WHERE slug='milk-tart'),4,'A thin pastry shell is filled with a pale custard set with cornflour rather than baked hard, then chilled and dusted with cinnamon.'),
((SELECT id FROM dishes WHERE slug='milk-tart'),5,'A chilled South African tart of pale, delicate milk custard in a thin crust, with cinnamon dusted over the top.'),
((SELECT id FROM dishes WHERE slug='moroccan-mint-tea'),1,'A drink poured all day long in the country at Africa''s northwest corner.'),
((SELECT id FROM dishes WHERE slug='moroccan-mint-tea'),2,'British traders offloaded surplus gunpowder green tea onto North African ports in the 1800s; local cooks added a fistful of a garden herb and a lot of sugar.'),
((SELECT id FROM dishes WHERE slug='moroccan-mint-tea'),3,'Refusing a glass is a genuine insult — three rounds are traditional, and the host pours from high above the glass to raise a foam.'),
((SELECT id FROM dishes WHERE slug='moroccan-mint-tea'),4,'Green tea steeps with a huge bundle of fresh leaves and sugar in a silver pot, then is poured in a long stream from a great height into small glasses.'),
((SELECT id FROM dishes WHERE slug='moroccan-mint-tea'),5,'Sweet green tea steeped with a fistful of fresh mint and poured theatrically from high above small glasses — the drink of Moroccan hospitality.'),
((SELECT id FROM dishes WHERE slug='aloo-paratha'),1,'A breakfast from the wheat-growing north of a very large South Asian country.'),
((SELECT id FROM dishes WHERE slug='aloo-paratha'),2,'It is Punjabi farmhouse food, built to fuel a whole morning in the fields.'),
((SELECT id FROM dishes WHERE slug='aloo-paratha'),3,'Highway truck stops across northern India serve it all day with a slab of white butter melting on top, a bowl of yogurt and a mango pickle.'),
((SELECT id FROM dishes WHERE slug='aloo-paratha'),4,'Spiced mashed potato is sealed inside a wheat dough ball, rolled flat, and griddled with plenty of ghee.'),
((SELECT id FROM dishes WHERE slug='aloo-paratha'),5,'A stuffed, pan-fried Indian flatbread filled with spiced potato, served hot with butter, yogurt and pickle for breakfast.'),
((SELECT id FROM dishes WHERE slug='pani-puri'),1,'A street snack eaten all over a large South Asian country — under about six different regional names.'),
((SELECT id FROM dishes WHERE slug='pani-puri'),2,'It probably descends from an ancient snack of the Gangetic plains, and spread nationwide from there.'),
((SELECT id FROM dishes WHERE slug='pani-puri'),3,'The vendor hands them over one at a time and you must eat each in a single bite before it collapses; arguing over whose neighbourhood cart is best is a national sport.'),
((SELECT id FROM dishes WHERE slug='pani-puri'),4,'Hollow crisp spheres are cracked open, filled with potato and chickpea, then dunked in chilled tangy mint-tamarind water.'),
((SELECT id FROM dishes WHERE slug='pani-puri'),5,'Crisp hollow shells filled with spiced potato and dunked in cold tamarind-mint water, eaten whole in one go.'),
((SELECT id FROM dishes WHERE slug='vindaloo'),1,'From a small coastal state on the western side of South Asia.'),
((SELECT id FROM dishes WHERE slug='vindaloo'),2,'It started as Portuguese carne de vinha d''alhos — meat in wine and garlic — and Goan cooks swapped palm vinegar for the wine and piled in chilies.'),
((SELECT id FROM dishes WHERE slug='vindaloo'),3,'British curry houses turned its name into a byword for the hottest thing on the menu, which is a misunderstanding: the original is about sourness, not heat.'),
((SELECT id FROM dishes WHERE slug='vindaloo'),4,'Meat marinates in vinegar with a paste of dried red chilies, garlic and warm spices, then slow-cooks until the sauce goes dark and sharp.'),
((SELECT id FROM dishes WHERE slug='vindaloo'),5,'A dark, sour-hot Goan curry of pork marinated in vinegar, garlic and red chilies — infamous as the macho order at British takeaways.'),
((SELECT id FROM dishes WHERE slug='gulab-jamun'),1,'A sweet found at every celebration across the South Asian subcontinent.'),
((SELECT id FROM dishes WHERE slug='gulab-jamun'),2,'It arrived with Persian and Central Asian cooks in the Mughal courts, adapted from a fried dough soaked in syrup called luqmat al-qadi.'),
((SELECT id FROM dishes WHERE slug='gulab-jamun'),3,'No Indian wedding, Diwali box or restaurant buffet ends without a bowl of them, usually two to a serving, warm.'),
((SELECT id FROM dishes WHERE slug='gulab-jamun'),4,'Milk solids are kneaded into small dough balls, fried gently until deep brown, then soaked in cardamom-and-rose sugar syrup.'),
((SELECT id FROM dishes WHERE slug='gulab-jamun'),5,'Warm, spongy deep-fried milk-solid balls soaked through with rose-and-cardamom syrup — the default Indian restaurant dessert.'),
((SELECT id FROM dishes WHERE slug='kulfi'),1,'A frozen sweet from the subcontinent, sold from carts on hot afternoons.'),
((SELECT id FROM dishes WHERE slug='kulfi'),2,'Mughal cooks made it in the 16th century, freezing it in metal cones packed in ice hauled down from the Himalayas with saltpetre.'),
((SELECT id FROM dishes WHERE slug='kulfi'),3,'Vendors still sell it from a cloth-wrapped clay pot, sliding the cones out and cutting them onto a leaf plate.'),
((SELECT id FROM dishes WHERE slug='kulfi'),4,'Milk is boiled down for hours until thick and faintly caramelised, flavoured with cardamom and pistachio, then frozen solid in cone moulds without any churning.'),
((SELECT id FROM dishes WHERE slug='kulfi'),5,'A dense, unchurned Indian frozen dessert of reduced milk scented with cardamom, saffron and pistachio, served on a stick.'),
((SELECT id FROM dishes WHERE slug='mango-lassi'),1,'A cold drink from the northern plains of South Asia.'),
((SELECT id FROM dishes WHERE slug='mango-lassi'),2,'The yogurt drink underneath it goes back some three thousand years in Punjab; the fruit version is a much more recent, restaurant-friendly twist.'),
((SELECT id FROM dishes WHERE slug='mango-lassi'),3,'It is what people order to put out the fire after an over-ambitious curry, and the default drink on Indian restaurant menus across the West.'),
((SELECT id FROM dishes WHERE slug='mango-lassi'),4,'Thick yogurt is blended with ripe tropical fruit pulp, milk and sugar with a pinch of cardamom, then poured over ice.'),
((SELECT id FROM dishes WHERE slug='mango-lassi'),5,'A thick, sweet, chilled yogurt drink blended with ripe tropical fruit — the standard cooler alongside a hot curry.'),
((SELECT id FROM dishes WHERE slug='masala-chai'),1,'A hot drink poured out by the millions every day across South Asia.'),
((SELECT id FROM dishes WHERE slug='masala-chai'),2,'The British planted the leaf in Assam in the 1800s to break China''s monopoly; Indian vendors stretched the expensive stuff with milk, sugar and spice.'),
((SELECT id FROM dishes WHERE slug='masala-chai'),3,'Railway platform vendors call it out all night, serving it in tiny glasses or throwaway clay cups you smash when you''re done — and Western coffee chains sell a sweetened latte version.'),
((SELECT id FROM dishes WHERE slug='masala-chai'),4,'Black tea, water, milk and sugar are boiled together with crushed ginger and whole warm spices, then strained from a height.'),
((SELECT id FROM dishes WHERE slug='masala-chai'),5,'Strong black tea boiled with milk, sugar, ginger and warm spices, strained and drunk scalding hot from a small glass.'),
((SELECT id FROM dishes WHERE slug='aloo-gobi'),1,'A homely vegetable dish from the north of a very large South Asian country.'),
((SELECT id FROM dishes WHERE slug='aloo-gobi'),2,'It is Punjabi household cooking — two cheap, sturdy vegetables that hold up to a long dry fry.'),
((SELECT id FROM dishes WHERE slug='aloo-gobi'),3,'It is the reliable vegetarian order on every Indian restaurant menu in Britain, and gets its own running joke in the film Bend It Like Beckham.'),
((SELECT id FROM dishes WHERE slug='aloo-gobi'),4,'Potato and cauliflower florets are dry-fried with turmeric, cumin and ginger until the edges catch and everything turns golden — no gravy.'),
((SELECT id FROM dishes WHERE slug='aloo-gobi'),5,'A dry, golden turmeric-stained Indian curry of potato and cauliflower, finished with fresh coriander.'),
((SELECT id FROM dishes WHERE slug='onion-bhaji'),1,'A fried starter from a very large South Asian country.'),
((SELECT id FROM dishes WHERE slug='onion-bhaji'),2,'Fritters of this kind are ancient street food across the subcontinent; the round, tightly packed restaurant version was standardised by British curry houses.'),
((SELECT id FROM dishes WHERE slug='onion-bhaji'),3,'It is one third of the standard British curry-house starter platter, alongside a samosa and a poppadom.'),
((SELECT id FROM dishes WHERE slug='onion-bhaji'),4,'Sliced onion is bound in a spiced chickpea-flour batter and deep-fried into a craggy, tangled nest.'),
((SELECT id FROM dishes WHERE slug='onion-bhaji'),5,'A craggy deep-fried nest of sliced onion in spiced chickpea-flour batter, served with mint chutney.'),
((SELECT id FROM dishes WHERE slug='raita'),1,'A cooling side from a very large South Asian country.'),
((SELECT id FROM dishes WHERE slug='raita'),2,'Yogurt has been used to temper spice on the subcontinent for millennia; recipes for this appear in Mughal-era court cookbooks.'),
((SELECT id FROM dishes WHERE slug='raita'),3,'It is the thing every Indian restaurant brings out when somebody at the table has badly overestimated their tolerance for chili.'),
((SELECT id FROM dishes WHERE slug='raita'),4,'Whisked yogurt is thinned with a little water and stirred with grated cucumber, roasted cumin and fresh herbs, then served cold.'),
((SELECT id FROM dishes WHERE slug='raita'),5,'A cold whisked-yogurt side with grated cucumber, roasted cumin and mint, served to put out the fire of a hot curry.'),
((SELECT id FROM dishes WHERE slug='paneer-tikka'),1,'A skewered starter from the north of a very large South Asian country.'),
((SELECT id FROM dishes WHERE slug='paneer-tikka'),2,'It is the meatless answer to the Punjabi clay-oven grill, developed for the vast vegetarian half of the country.'),
((SELECT id FROM dishes WHERE slug='paneer-tikka'),3,'It is the fixture of every Indian restaurant starter list and every Delhi wedding buffet, arriving on a sizzling iron platter.'),
((SELECT id FROM dishes WHERE slug='paneer-tikka'),4,'Cubes of firm fresh cheese marinate in spiced yogurt with peppers and onion, then char on skewers in a searing clay oven.'),
((SELECT id FROM dishes WHERE slug='paneer-tikka'),5,'Charred skewers of firm Indian cheese marinated in spiced yogurt, grilled with peppers and onion and served with a lemon wedge.'),
((SELECT id FROM dishes WHERE slug='soto-ayam'),1,'A soup from the world''s largest archipelago, in Southeast Asia.'),
((SELECT id FROM dishes WHERE slug='soto-ayam'),2,'Every region of Java has its own version — Lamongan, Kudus, Madura — and the dish travelled with Javanese migration to Malaysia and Suriname.'),
((SELECT id FROM dishes WHERE slug='soto-ayam'),3,'It is the standard comfort food and hangover cure across Indonesia, sold from carts and warungs at all hours with a lime wedge and prawn crackers.'),
((SELECT id FROM dishes WHERE slug='soto-ayam'),4,'Chicken simmers with lemongrass, galangal and turmeric until the broth turns bright gold, then is shredded over noodles, bean sprouts and boiled egg.'),
((SELECT id FROM dishes WHERE slug='soto-ayam'),5,'A golden turmeric chicken broth over noodles with shredded chicken, bean sprouts and boiled egg, brightened with lime and fried shallots.'),
((SELECT id FROM dishes WHERE slug='nasi-lemak'),1,'The national breakfast of a Southeast Asian country split between a peninsula and part of Borneo.'),
((SELECT id FROM dishes WHERE slug='nasi-lemak'),2,'It was Malay farmers'' field food, first written down in a 1909 book about Malay life, and traditionally wrapped in a banana-leaf parcel.'),
((SELECT id FROM dishes WHERE slug='nasi-lemak'),3,'Malaysians will argue for hours over whose stall makes it best; it is served on the national airline and at 3am roadside stalls alike.'),
((SELECT id FROM dishes WHERE slug='nasi-lemak'),4,'Rice is steamed in coconut milk with a knotted fragrant leaf, then plated with sweet-hot sambal, crisp fried anchovies, peanuts, cucumber and egg.'),
((SELECT id FROM dishes WHERE slug='nasi-lemak'),5,'Coconut-scented rice in a banana leaf with fiery sambal, fried anchovies, peanuts, cucumber and a boiled egg — Malaysia''s breakfast.'),
((SELECT id FROM dishes WHERE slug='chili-crab'),1,'From a small island city-state at the bottom of the Malay Peninsula.'),
((SELECT id FROM dishes WHERE slug='chili-crab'),2,'A woman named Cher Yam Tian started selling it from a pushcart on the East Coast in 1956, at first with nothing but bottled tomato sauce.'),
((SELECT id FROM dishes WHERE slug='chili-crab'),3,'It is the dish the national tourism board leads with, and CNN once put it on a list of the world''s fifty best foods.'),
((SELECT id FROM dishes WHERE slug='chili-crab'),4,'Whole shellfish are stir-fried in a thick sweet-savoury tomato gravy ribboned with beaten egg, and you mop the sauce up with fried buns.'),
((SELECT id FROM dishes WHERE slug='chili-crab'),5,'Whole shellfish in a sticky, egg-swirled sweet-and-spicy tomato gravy, eaten with your hands and steamed buns for the sauce.'),
((SELECT id FROM dishes WHERE slug='halo-halo'),1,'A dessert from an archipelago of over seven thousand islands in Southeast Asia.'),
((SELECT id FROM dishes WHERE slug='halo-halo'),2,'It grew out of Japanese kakigori brought over by pre-war migrants, then got piled high with local sweetened preserves.'),
((SELECT id FROM dishes WHERE slug='halo-halo'),3,'Anthony Bourdain was a public champion of it, and its name literally means "mix-mix" — which is also the instruction.'),
((SELECT id FROM dishes WHERE slug='halo-halo'),4,'Shaved ice and evaporated milk go over a tall glass layered with sweet beans, jellies, preserved fruit and purple yam, topped with ice cream.'),
((SELECT id FROM dishes WHERE slug='halo-halo'),5,'A tall glass of shaved ice and evaporated milk over sweet beans, jellies and preserved fruit, crowned with ice cream — stir it all together before eating.'),
((SELECT id FROM dishes WHERE slug='fresh-spring-rolls'),1,'A cold starter from a long, narrow country on the eastern edge of Southeast Asia.'),
((SELECT id FROM dishes WHERE slug='fresh-spring-rolls'),2,'They are the uncooked southern Vietnamese cousin of the fried rolls found all over East and Southeast Asia.'),
((SELECT id FROM dishes WHERE slug='fresh-spring-rolls'),3,'They are the health-conscious order on every Vietnamese menu in the West, and are often called summer rolls to tell them apart from the fried kind.'),
((SELECT id FROM dishes WHERE slug='fresh-spring-rolls'),4,'Translucent rice paper is dipped in water until pliable, then wrapped around herbs, noodles and shellfish — never cooked — and dipped in peanut sauce.'),
((SELECT id FROM dishes WHERE slug='fresh-spring-rolls'),5,'Translucent uncooked rice-paper rolls packed with shrimp, noodles and fresh herbs, served cold with peanut dipping sauce.'),
((SELECT id FROM dishes WHERE slug='pad-see-ew'),1,'A noodle dish from a Southeast Asian kingdom that was never colonised.'),
((SELECT id FROM dishes WHERE slug='pad-see-ew'),2,'It came to Thailand with Chinese immigrants — the name means "fried with soy sauce" — and it is a close relative of Cantonese beef chow fun.'),
((SELECT id FROM dishes WHERE slug='pad-see-ew'),3,'It is the second thing everyone orders at a Thai restaurant after the more famous tamarind noodle dish next to it on the menu.'),
((SELECT id FROM dishes WHERE slug='pad-see-ew'),4,'Wide flat rice noodles are charred hard in a screaming-hot wok with dark sweet soy, egg and Chinese broccoli until they smoke.'),
((SELECT id FROM dishes WHERE slug='pad-see-ew'),5,'Wide flat rice noodles charred in a wok with dark sweet soy sauce, egg and Chinese broccoli — Thailand''s smoky, savoury noodle plate.'),
((SELECT id FROM dishes WHERE slug='thai-iced-tea'),1,'A cold drink from a Southeast Asian kingdom famous for its street food.'),
((SELECT id FROM dishes WHERE slug='thai-iced-tea'),2,'It came out of the mid-20th century, when strong spiced black tea met imported tinned milk in Bangkok.'),
((SELECT id FROM dishes WHERE slug='thai-iced-tea'),3,'Its startling traffic-cone orange colour — from food dye in the tea mix — is the giveaway on any takeaway menu in the West.'),
((SELECT id FROM dishes WHERE slug='thai-iced-tea'),4,'Strong spiced black tea is brewed dark, sweetened hard with condensed milk, poured over ice and floated with evaporated milk.'),
((SELECT id FROM dishes WHERE slug='thai-iced-tea'),5,'A bright orange, very sweet iced spiced tea layered with condensed and evaporated milk — the standard drink with a Thai takeaway.'),
((SELECT id FROM dishes WHERE slug='mango-sticky-rice'),1,'A hot-season dessert from a Southeast Asian kingdom known for its beaches and street food.'),
((SELECT id FROM dishes WHERE slug='mango-sticky-rice'),2,'It is tied to the April harvest of a particular tropical stone fruit, and shows up in Thai texts going back centuries.'),
((SELECT id FROM dishes WHERE slug='mango-sticky-rice'),3,'A Thai rapper''s 2022 song about it sent national sales through the roof and got the dish onto tourist bucket lists worldwide.'),
((SELECT id FROM dishes WHERE slug='mango-sticky-rice'),4,'Glutinous rice is steamed, then soaked in sweet salted coconut cream and served beside slices of a ripe yellow stone fruit.'),
((SELECT id FROM dishes WHERE slug='mango-sticky-rice'),5,'Sweet coconut-soaked glutinous rice served cool beside slices of ripe yellow tropical fruit, with a drizzle of coconut cream on top.'),
((SELECT id FROM dishes WHERE slug='tom-kha-gai'),1,'A soup from a Southeast Asian kingdom whose capital is Bangkok.'),
((SELECT id FROM dishes WHERE slug='tom-kha-gai'),2,'Its name is literally a recipe: "boiled" plus the root at its heart plus the bird in it.'),
((SELECT id FROM dishes WHERE slug='tom-kha-gai'),3,'It is the milder, creamier alternative to the famous fiery sour prawn soup listed right above it on every Thai menu.'),
((SELECT id FROM dishes WHERE slug='tom-kha-gai'),4,'Coconut milk is simmered with sliced galangal, bruised lemongrass and lime leaves, then chicken and mushrooms, finished with fish sauce and lime.'),
((SELECT id FROM dishes WHERE slug='tom-kha-gai'),5,'A creamy, tangy Thai coconut soup with chicken, mushrooms, galangal and lemongrass, sharpened with lime and fish sauce.'),
((SELECT id FROM dishes WHERE slug='onigiri'),1,'A portable bite from an island country in East Asia.'),
((SELECT id FROM dishes WHERE slug='onigiri'),2,'Carbonised lumps of it have been dug out of a 2,000-year-old site, and samurai carried them as field rations.'),
((SELECT id FROM dishes WHERE slug='onigiri'),3,'Japanese convenience stores sell billions a year, in a clever wrapper you pull apart so the seaweed stays crisp until the second you eat it — and anime characters are forever eating them.'),
((SELECT id FROM dishes WHERE slug='onigiri'),4,'Salted rice is pressed into a triangle around a savoury filling and banded with a strip of dried seaweed.'),
((SELECT id FROM dishes WHERE slug='onigiri'),5,'A cold triangle of salted rice wrapped in dried seaweed, with a filling like grilled salmon tucked in the middle.'),
((SELECT id FROM dishes WHERE slug='kimbap'),1,'A packed-lunch staple from a country in East Asia.'),
((SELECT id FROM dishes WHERE slug='kimbap'),2,'It took its modern shape in the 20th century and is firmly its own thing — seasoned with sesame oil and salt rather than vinegar.'),
((SELECT id FROM dishes WHERE slug='kimbap'),3,'It is the food of school field trips and picnics, and K-dramas have made the foil-wrapped rolls instantly recognisable worldwide.'),
((SELECT id FROM dishes WHERE slug='kimbap'),4,'Seasoned rice and strips of vegetables, egg and pickled radish are rolled up in a sheet of dried seaweed and cut into rounds.'),
((SELECT id FROM dishes WHERE slug='kimbap'),5,'Cold seaweed-and-rice rolls filled with strips of vegetables and egg, sliced into coins for a Korean picnic lunch.'),
((SELECT id FROM dishes WHERE slug='mochi'),1,'A chewy sweet from an island country in East Asia.'),
((SELECT id FROM dishes WHERE slug='mochi'),2,'It has been pounded for New Year offerings since the Heian period, in a two-person ritual where one strikes and the other turns the dough between blows.'),
((SELECT id FROM dishes WHERE slug='mochi'),3,'The ice-cream-filled version is in freezer aisles worldwide — and every New Year Japanese news warns people not to choke on it.'),
((SELECT id FROM dishes WHERE slug='mochi'),4,'Glutinous rice is steamed and pounded into a soft, springy, sticky dough, then wrapped around a sweet filling and dusted with starch.'),
((SELECT id FROM dishes WHERE slug='mochi'),5,'Soft, chewy pounded-rice cakes dusted with starch and wrapped around sweet red bean paste or a scoop of ice cream.'),
((SELECT id FROM dishes WHERE slug='bubble-tea'),1,'A cold drink invented on an island off the southeast coast of China.'),
((SELECT id FROM dishes WHERE slug='bubble-tea'),2,'Two Taichung tea houses both claim to have invented it in the 1980s, and they fought a ten-year court case over it that neither won.'),
((SELECT id FROM dishes WHERE slug='bubble-tea'),3,'It conquered the world in the 2010s, complete with its own emoji, and is drunk through a fat straw wide enough for the chewy bits.'),
((SELECT id FROM dishes WHERE slug='bubble-tea'),4,'Sweet milky tea is shaken with ice and poured over chewy black tapioca balls that sit at the bottom of a sealed plastic cup.'),
((SELECT id FROM dishes WHERE slug='bubble-tea'),5,'Sweet iced milk tea with chewy black tapioca balls at the bottom, drunk through an oversized straw.'),
((SELECT id FROM dishes WHERE slug='sashimi'),1,'A cold plate from an island country in East Asia.'),
((SELECT id FROM dishes WHERE slug='sashimi'),2,'Its name means "pierced body" — supposedly because the fish''s tail and fin were once pinned to the plate to identify the species being served.'),
((SELECT id FROM dishes WHERE slug='sashimi'),3,'It is what people mean when they say the more famous rice-based dish "without the rice", and the top grades are auctioned at Tokyo fish markets for staggering sums.'),
((SELECT id FROM dishes WHERE slug='sashimi'),4,'Raw fish is sliced by hand at a precise angle with a single-bevel knife, arranged over shredded daikon, and served with soy sauce and a green horseradish paste.'),
((SELECT id FROM dishes WHERE slug='sashimi'),5,'Precisely sliced raw fish served cold with no rice — just soy sauce, wasabi and shredded daikon.'),
((SELECT id FROM dishes WHERE slug='egg-drop-soup'),1,'A simple soup from the largest country in East Asia.'),
((SELECT id FROM dishes WHERE slug='egg-drop-soup'),2,'It is home cooking from the north, where the Mandarin name describes the strands as looking like flower petals.'),
((SELECT id FROM dishes WHERE slug='egg-drop-soup'),3,'In the United States it is one of the two default soups at the top of every Chinese-American takeaway menu, alongside the hot and sour one.'),
((SELECT id FROM dishes WHERE slug='egg-drop-soup'),4,'Beaten egg is poured in a thin stream into simmering broth that has been thickened with cornflour, so it sets into delicate ribbons.'),
((SELECT id FROM dishes WHERE slug='egg-drop-soup'),5,'A thin, silky chicken broth with beaten egg swirled in to set as delicate ribbons, topped with scallion and white pepper.'),
((SELECT id FROM dishes WHERE slug='baba-ganoush'),1,'A cold dip from the eastern Mediterranean, from the country whose capital is Beirut.'),
((SELECT id FROM dishes WHERE slug='baba-ganoush'),2,'Its Arabic name translates roughly as "pampered daddy", and there is a story about a courtier''s daughter making it for her toothless father.'),
((SELECT id FROM dishes WHERE slug='baba-ganoush'),3,'It is the smoky one next to the chickpea dip on every mezze platter and supermarket shelf in the Western world.'),
((SELECT id FROM dishes WHERE slug='baba-ganoush'),4,'A whole aubergine is charred over open flame until the skin blackens and collapses, then the smoky flesh is mashed with sesame paste, lemon and garlic.'),
((SELECT id FROM dishes WHERE slug='baba-ganoush'),5,'A cold, smoky Levantine dip of fire-roasted aubergine mashed with sesame paste, lemon and garlic, pooled with olive oil.'),
((SELECT id FROM dishes WHERE slug='turkish-delight'),1,'A confection from a country that straddles Europe and Asia.'),
((SELECT id FROM dishes WHERE slug='turkish-delight'),2,'An Ottoman confectioner named Bekir Efendi began selling it in Istanbul in 1777, and his shop is still trading today.'),
((SELECT id FROM dishes WHERE slug='turkish-delight'),3,'The White Witch uses an enchanted box of it to buy Edmund''s loyalty in The Lion, the Witch and the Wardrobe.'),
((SELECT id FROM dishes WHERE slug='turkish-delight'),4,'Sugar syrup is cooked with cornflour for hours until it sets into a soft, springy gel, scented with rose water and cut into cubes rolled in icing sugar.'),
((SELECT id FROM dishes WHERE slug='turkish-delight'),5,'Soft, springy rose-scented sugar-gel cubes dusted heavily in icing sugar — the Ottoman sweet Edmund sold out his siblings for.'),
((SELECT id FROM dishes WHERE slug='gravlax'),1,'A cold starter from Scandinavia, from the largest country on that peninsula.'),
((SELECT id FROM dishes WHERE slug='gravlax'),2,'Medieval fishermen buried the fish in sand above the tide line to ferment it — the name literally means "grave salmon".'),
((SELECT id FROM dishes WHERE slug='gravlax'),3,'It is a fixture of the Swedish Christmas smorgasbord and the midsummer table, sliced paper-thin next to a sweet mustard-dill sauce.'),
((SELECT id FROM dishes WHERE slug='gravlax'),4,'Raw fillets are cured for days under a weighted blanket of salt, sugar and dill — never cooked, and never smoked.'),
((SELECT id FROM dishes WHERE slug='gravlax'),5,'Salt-and-sugar cured raw salmon packed in dill, sliced thin and served cold with sweet mustard sauce.'),
((SELECT id FROM dishes WHERE slug='pickled-herring'),1,'A cold snack from a low-lying country in northwestern Europe.'),
((SELECT id FROM dishes WHERE slug='pickled-herring'),2,'A 14th-century Dutch method of gutting and brining the catch at sea built the country''s trading fortune — Amsterdam is said to be built on its bones.'),
((SELECT id FROM dishes WHERE slug='pickled-herring'),3,'Street carts still sell it whole, and the traditional way to eat it is to tip your head back and lower it in by the tail.'),
((SELECT id FROM dishes WHERE slug='pickled-herring'),4,'Small oily fish are cured in a salt-and-vinegar brine and served cold with raw chopped onion.'),
((SELECT id FROM dishes WHERE slug='pickled-herring'),5,'Cold brined oily fish fillets served with raw onion — eaten from a Dutch street cart, head tilted back.'),
((SELECT id FROM dishes WHERE slug='vichyssoise'),1,'A chilled soup with a French name, though where it was actually invented is contested.'),
((SELECT id FROM dishes WHERE slug='vichyssoise'),2,'A French-born chef at the Ritz-Carlton in New York created it in 1917, chilling a rustic soup from his childhood and naming it after a spa town near his home.'),
((SELECT id FROM dishes WHERE slug='vichyssoise'),3,'It became the emblem of mid-century fine dining — the sophisticated cold soup on every hotel menu in the 1950s and 60s.'),
((SELECT id FROM dishes WHERE slug='vichyssoise'),4,'Potatoes and leeks simmer in broth, get puréed silky smooth and enriched with cream, then are served thoroughly chilled.'),
((SELECT id FROM dishes WHERE slug='vichyssoise'),5,'A silky cold soup of puréed potato and leek finished with cream, served in a chilled bowl with snipped chives.'),
((SELECT id FROM dishes WHERE slug='gelato'),1,'A frozen dessert from a peninsula in southern Europe shaped like a boot.'),
((SELECT id FROM dishes WHERE slug='gelato'),2,'A Florentine architect is credited with perfecting it for the Medici court in the 1500s, though Sicilians had been freezing sweets with mountain snow long before.'),
((SELECT id FROM dishes WHERE slug='gelato'),3,'Audrey Hepburn eats one on the Spanish Steps in Roman Holiday, and the queue outside a good Florence shop is a tourist landmark in itself.'),
((SELECT id FROM dishes WHERE slug='gelato'),4,'It uses more milk and less cream than its American cousin and is churned slowly with far less air, so it stays dense and is served warmer and softer.'),
((SELECT id FROM dishes WHERE slug='gelato'),5,'Italy''s denser, silkier frozen dessert — less cream, less air, served a little warmer and scraped from the tub with a flat paddle.'),
((SELECT id FROM dishes WHERE slug='bircher-muesli'),1,'A cold breakfast from a small, mountainous, neutral country in central Europe.'),
((SELECT id FROM dishes WHERE slug='bircher-muesli'),2,'A Zurich physician invented it around 1900 as a raw-food therapy for patients at his sanatorium, and it carries his surname.'),
((SELECT id FROM dishes WHERE slug='bircher-muesli'),3,'It escaped the clinic to become the standard hotel-buffet health breakfast worldwide, and gave English the generic word for dry cereal.'),
((SELECT id FROM dishes WHERE slug='bircher-muesli'),4,'Rolled oats are soaked overnight in milk or yogurt, then stirred together with grated raw apple, lemon, honey and nuts.'),
((SELECT id FROM dishes WHERE slug='bircher-muesli'),5,'Cold overnight-soaked rolled oats with grated raw apple, yogurt, honey and nuts — the original Swiss health breakfast.'),
((SELECT id FROM dishes WHERE slug='porridge'),1,'A hot breakfast from the northern part of a British island, where the grain grows well in poor soil.'),
((SELECT id FROM dishes WHERE slug='porridge'),2,'It has been the everyday morning meal there for centuries — traditionally stirred clockwise with a wooden stick called a spurtle.'),
((SELECT id FROM dishes WHERE slug='porridge'),3,'There is a world championship for it held annually in a Highland village, and Goldilocks famously found three bowls of it at varying temperatures.'),
((SELECT id FROM dishes WHERE slug='porridge'),4,'Rolled or pinhead oats are simmered slowly in milk or water and stirred until they break down into a thick, creamy mass.'),
((SELECT id FROM dishes WHERE slug='porridge'),5,'A thick, hot bowl of slow-cooked oats in milk, traditionally salted — the Scottish breakfast Goldilocks broke into a house for.'),
((SELECT id FROM dishes WHERE slug='danish-pastry'),1,'A breakfast baked good named for a small Scandinavian country.'),
((SELECT id FROM dishes WHERE slug='danish-pastry'),2,'It is not actually native there: Austrian bakers brought in during a Copenhagen bakers'' strike in 1850 left the laminated technique behind — which is why Danes call it "Viennese bread".'),
((SELECT id FROM dishes WHERE slug='danish-pastry'),3,'It is the pastry on every American office breakfast platter and hotel continental buffet, usually with a spoonful of fruit or cheese in the middle.'),
((SELECT id FROM dishes WHERE slug='danish-pastry'),4,'A yeasted dough is folded repeatedly around a slab of butter to build dozens of layers, then shaped into a spiral or pinwheel and filled before baking.'),
((SELECT id FROM dishes WHERE slug='danish-pastry'),5,'A flaky, buttery laminated pastry spiral with a dab of fruit jam or sweet cheese in the middle — the classic continental-breakfast bake.'),
((SELECT id FROM dishes WHERE slug='trifle'),1,'A layered cold dessert from an island nation in northwestern Europe.'),
((SELECT id FROM dishes WHERE slug='trifle'),2,'A 16th-century version was just flavoured cream; by the 1750s the sponge, the booze and the custard had all arrived.'),
((SELECT id FROM dishes WHERE slug='trifle'),3,'Rachel accidentally makes one with beef sautéed with peas and onions in Friends, after two recipe pages stick together.'),
((SELECT id FROM dishes WHERE slug='trifle'),4,'Sponge soaked in sherry is layered in a glass bowl with fruit, set jelly and custard, then topped with a thick blanket of whipped cream.'),
((SELECT id FROM dishes WHERE slug='trifle'),5,'A glass bowl layered with sherry-soaked sponge, fruit, jelly, custard and whipped cream, served cold with a spoon straight down through it.'),
((SELECT id FROM dishes WHERE slug='potato-salad'),1,'A cold side from central Europe, from a country famous for sausage and beer.'),
((SELECT id FROM dishes WHERE slug='potato-salad'),2,'Germans have made it since at least the 1600s; emigrants carried it to the United States, where mayonnaise replaced the warm vinegar-and-bacon dressing.'),
((SELECT id FROM dishes WHERE slug='potato-salad'),3,'It is the essential thing next to the grill at every American cookout, and the northern German version is Christmas Eve dinner with sausages.'),
((SELECT id FROM dishes WHERE slug='potato-salad'),4,'Boiled waxy potatoes are cooled, then folded with onion, pickle, mustard and either a vinegar dressing or a heavy dose of mayonnaise.'),
((SELECT id FROM dishes WHERE slug='potato-salad'),5,'Cold boiled potatoes dressed with mayonnaise, mustard, onion and pickle — the picnic and barbecue side dish.'),
((SELECT id FROM dishes WHERE slug='crumpets'),1,'A hot breakfast bread from an island nation in northwestern Europe.'),
((SELECT id FROM dishes WHERE slug='crumpets'),2,'Anglo-Saxons cooked a hard griddle cake by this name; the soft, spongy, holey version arrived with Victorian bakers adding a raising agent.'),
((SELECT id FROM dishes WHERE slug='crumpets'),3,'It is the fireside teatime food of British childhood, and the phrase "tea and —" is practically shorthand for English domestic comfort.'),
((SELECT id FROM dishes WHERE slug='crumpets'),4,'A loose yeasted batter is poured into metal rings on a griddle so bubbles rise and burst through the top, leaving a surface full of holes to trap melted butter.'),
((SELECT id FROM dishes WHERE slug='crumpets'),5,'A soft, spongy round griddle bread riddled with holes on top, toasted and drowned in melting butter.'),
((SELECT id FROM dishes WHERE slug='omelette'),1,'A breakfast staple with a French name, though nearly every country has a version.'),
((SELECT id FROM dishes WHERE slug='omelette'),2,'The French word appears in the 16th century, and the technique was codified by the great Paris chefs into a test of skill.'),
((SELECT id FROM dishes WHERE slug='omelette'),3,'Making a perfect one — pale gold, no browning, rolled into a smooth cylinder — is the classic interview task for a new cook, and Julia Child devoted a whole lesson to it.'),
((SELECT id FROM dishes WHERE slug='omelette'),4,'Beaten eggs hit foaming butter in a hot pan, are stirred briefly, then folded over a filling while the middle is still barely set.'),
((SELECT id FROM dishes WHERE slug='omelette'),5,'Beaten eggs cooked fast in butter and folded over a filling of cheese or vegetables — the breakfast test of a cook''s technique.'),
((SELECT id FROM dishes WHERE slug='shrimp-cocktail'),1,'A cold starter that became an institution in North America.'),
((SELECT id FROM dishes WHERE slug='shrimp-cocktail'),2,'Oyster versions were served in San Francisco saloons in the 1860s; the shellfish version took over American menus once Prohibition ended.'),
((SELECT id FROM dishes WHERE slug='shrimp-cocktail'),3,'It was the height of dinner-party sophistication in the 1960s, and Las Vegas casinos famously sold one for 99 cents for decades to keep gamblers in the building.'),
((SELECT id FROM dishes WHERE slug='shrimp-cocktail'),4,'Poached shellfish are chilled and hung around the rim of a stemmed glass over a sauce of ketchup, horseradish and lemon.'),
((SELECT id FROM dishes WHERE slug='shrimp-cocktail'),5,'Chilled poached shellfish hooked over the edge of a stemmed glass, with a tangy red horseradish dipping sauce.'),
((SELECT id FROM dishes WHERE slug='cioppino'),1,'A fisherman''s stew from the west coast of North America.'),
((SELECT id FROM dishes WHERE slug='cioppino'),2,'Genoese immigrants working the wharves of San Francisco made it in the late 1800s from whatever hadn''t sold that day.'),
((SELECT id FROM dishes WHERE slug='cioppino'),3,'It is the signature dish of San Francisco''s Fisherman''s Wharf, and the Italian-American Christmas Eve centrepiece there.'),
((SELECT id FROM dishes WHERE slug='cioppino'),4,'Assorted shellfish and fish simmer in a garlicky tomato and white wine broth, served with sourdough for dunking and a bib for the mess.'),
((SELECT id FROM dishes WHERE slug='cioppino'),5,'A San Francisco tomato-and-wine seafood stew loaded with crab, clams, mussels and shrimp, mopped up with sourdough.'),
((SELECT id FROM dishes WHERE slug='deviled-eggs'),1,'A cold party staple most associated with North America, though the Romans were doing something similar.'),
((SELECT id FROM dishes WHERE slug='deviled-eggs'),2,'The word for spicing a dish this way appeared in 18th-century Britain; the mayonnaise version is American, and southern cooks made it a household standard.'),
((SELECT id FROM dishes WHERE slug='deviled-eggs'),3,'It is the potluck and church-supper dish that has its own specially dimpled carrying plate.'),
((SELECT id FROM dishes WHERE slug='deviled-eggs'),4,'Hard-boiled eggs are halved, the yolks mashed with mayonnaise, mustard and vinegar, then piped back into the whites and dusted with paprika.'),
((SELECT id FROM dishes WHERE slug='deviled-eggs'),5,'Halved hard-boiled eggs with the yolks whipped smooth with mayonnaise and mustard, piped back in and dusted with paprika.'),
((SELECT id FROM dishes WHERE slug='breakfast-burrito'),1,'A morning handheld from the American Southwest.'),
((SELECT id FROM dishes WHERE slug='breakfast-burrito'),2,'A restaurant in Santa Fe, New Mexico put it on the menu in 1975, and the state has been arguing about the proper chile ever since.'),
((SELECT id FROM dishes WHERE slug='breakfast-burrito'),3,'It is the road-trip and hangover breakfast of the western United States, sold everywhere from gas stations to drive-thru windows.'),
((SELECT id FROM dishes WHERE slug='breakfast-burrito'),4,'Scrambled eggs, potato, cheese and sausage are piled onto a warm flour tortilla and rolled into a sealed cylinder.'),
((SELECT id FROM dishes WHERE slug='breakfast-burrito'),5,'A warm flour tortilla rolled around scrambled eggs, potato, cheese and sausage, with salsa or green chile on the side.'),
((SELECT id FROM dishes WHERE slug='coleslaw'),1,'A cold side, now inseparable from North American cooking.'),
((SELECT id FROM dishes WHERE slug='coleslaw'),2,'The name is a straight borrowing of the Dutch koolsla, "cabbage salad", brought to New York by settlers — the creamy version arrived when mayonnaise was bottled commercially.'),
((SELECT id FROM dishes WHERE slug='coleslaw'),3,'It comes in the little paper cup next to the fried chicken, the barbecue and the fish and chips, and half of America pile it straight into the sandwich.'),
((SELECT id FROM dishes WHERE slug='coleslaw'),4,'Cabbage and carrot are shredded fine, then dressed with mayonnaise sharpened with vinegar, sugar and mustard, and left to soften in the fridge.'),
((SELECT id FROM dishes WHERE slug='coleslaw'),5,'Finely shredded cabbage and carrot in a creamy, tangy dressing — the cold cup that comes with the barbecue.'),
((SELECT id FROM dishes WHERE slug='waldorf-salad'),1,'A cold salad named after a grand hotel in a North American city.'),
((SELECT id FROM dishes WHERE slug='waldorf-salad'),2,'The maître d''hôtel of a Manhattan hotel invented it in 1896 for a charity ball; nuts were not in the original and got added later.'),
((SELECT id FROM dishes WHERE slug='waldorf-salad'),3,'A whole episode of Fawlty Towers turns on Basil being unable to produce one for an American guest.'),
((SELECT id FROM dishes WHERE slug='waldorf-salad'),4,'Diced apple and celery are folded through mayonnaise with walnuts and grapes or raisins, then spooned onto a bed of lettuce.'),
((SELECT id FROM dishes WHERE slug='waldorf-salad'),5,'A cold Manhattan hotel salad of diced apple and celery bound in mayonnaise with walnuts, served on lettuce.'),
((SELECT id FROM dishes WHERE slug='granola'),1,'A cold breakfast invented in North America.'),
((SELECT id FROM dishes WHERE slug='granola'),2,'A 19th-century American sanitarium doctor created the original health food; a rival at a competing sanitarium was sued over the near-identical name.'),
((SELECT id FROM dishes WHERE slug='granola'),3,'It became shorthand for a whole hippie aesthetic in the 1960s — calling someone that word still means crunchy and outdoorsy.'),
((SELECT id FROM dishes WHERE slug='granola'),4,'Rolled oats are tossed with honey and oil, baked slowly until they clump and turn golden, then mixed with nuts and dried fruit.'),
((SELECT id FROM dishes WHERE slug='granola'),5,'Baked, sweetened clusters of oats with nuts and dried fruit, eaten cold with milk or spooned over yogurt.'),
((SELECT id FROM dishes WHERE slug='crab-rangoon'),1,'A fried starter invented in North America, despite a name pointing at Southeast Asia.'),
((SELECT id FROM dishes WHERE slug='crab-rangoon'),2,'It was created at Trader Vic''s tiki restaurant in San Francisco in the 1950s — the Burmese city in its name has nothing to do with it.'),
((SELECT id FROM dishes WHERE slug='crab-rangoon'),3,'It is the guilty-pleasure order on every American Chinese takeaway menu, and there is no such thing anywhere in China.'),
((SELECT id FROM dishes WHERE slug='crab-rangoon'),4,'Cream cheese is beaten with shellfish and scallion, spooned into wonton wrappers folded into little purses, and deep-fried until blistered.'),
((SELECT id FROM dishes WHERE slug='crab-rangoon'),5,'Deep-fried wonton purses stuffed with cream cheese and crab, served with sweet-and-sour dipping sauce at American Chinese restaurants.'),
((SELECT id FROM dishes WHERE slug='tuna-salad-sandwich'),1,'A cold lunchbox staple from North America.'),
((SELECT id FROM dishes WHERE slug='tuna-salad-sandwich'),2,'It took off once canned fish became cheap and mayonnaise was sold in jars, around the start of the 20th century.'),
((SELECT id FROM dishes WHERE slug='tuna-salad-sandwich'),3,'It is the diner counter and school-cafeteria default, and the smell of it in an office microwave is a well-worn grievance.'),
((SELECT id FROM dishes WHERE slug='tuna-salad-sandwich'),4,'Flaked canned fish is mashed with mayonnaise, chopped celery and onion, then spread cold between two slices of bread.'),
((SELECT id FROM dishes WHERE slug='tuna-salad-sandwich'),5,'Flaked canned fish mashed with mayonnaise, celery and onion, spread cold between two slices of bread.'),
((SELECT id FROM dishes WHERE slug='shrimp-scampi'),1,'A garlicky seafood plate, Italian in name but American in the form most people know.'),
((SELECT id FROM dishes WHERE slug='shrimp-scampi'),2,'The second word is Italian for the small langoustines the dish originally used; Italian-American cooks swapped in the shellfish that was cheap and local and kept the old name.'),
((SELECT id FROM dishes WHERE slug='shrimp-scampi'),3,'It is the standard order at every red-sauce Italian-American restaurant, and the reason "scampi" on a British menu means something breaded and entirely different.'),
((SELECT id FROM dishes WHERE slug='shrimp-scampi'),4,'Shellfish are sautéed hard in butter and a great deal of garlic, deglazed with white wine and lemon, and tossed with linguine and parsley.'),
((SELECT id FROM dishes WHERE slug='shrimp-scampi'),5,'Shellfish sautéed in garlic butter with white wine and lemon, tossed through linguine — the Italian-American restaurant standard.'),
((SELECT id FROM dishes WHERE slug='hash-browns'),1,'A fried breakfast side from North America.'),
((SELECT id FROM dishes WHERE slug='hash-browns'),2,'They appeared on New York breakfast menus in the 1890s under a longer name — "hashed browned potatoes" — which got shortened over time.'),
((SELECT id FROM dishes WHERE slug='hash-browns'),3,'American diners ask if you want them "scattered, smothered and covered", and the fast-food version comes in a paper sleeve.'),
((SELECT id FROM dishes WHERE slug='hash-browns'),4,'Potato is grated, squeezed bone dry, then pressed into a hot buttered pan and left alone until one side forms a solid golden crust.'),
((SELECT id FROM dishes WHERE slug='hash-browns'),5,'Grated potato pressed into a pan and fried until crisp and golden on both sides — the diner breakfast side.'),
((SELECT id FROM dishes WHERE slug='ackee-and-saltfish'),1,'The national dish of a Caribbean island.'),
((SELECT id FROM dishes WHERE slug='ackee-and-saltfish'),2,'The fruit came from West Africa on slave ships in the 1700s; the cured fish came down from the North Atlantic cod trade — two continents on one plate.'),
((SELECT id FROM dishes WHERE slug='ackee-and-saltfish'),3,'It is the Sunday-morning breakfast of the island, eaten with fried dumplings, boiled green bananas and roasted breadfruit.'),
((SELECT id FROM dishes WHERE slug='ackee-and-saltfish'),4,'A yellow tropical fruit — poisonous unless picked fully open — is sautéed with rehydrated salted cod, peppers, onion and thyme until it looks like scrambled egg.'),
((SELECT id FROM dishes WHERE slug='ackee-and-saltfish'),5,'Jamaica''s breakfast of salted cod sautéed with a soft yellow tropical fruit that scrambles like egg, with peppers, onion and thyme.'),
((SELECT id FROM dishes WHERE slug='horchata'),1,'A cold drink from the country directly south of the United States.'),
((SELECT id FROM dishes WHERE slug='horchata'),2,'Spanish colonists brought the idea over from Valencia, where it is made from tiger nuts; Mexican cooks rebuilt it with a grain instead.'),
((SELECT id FROM dishes WHERE slug='horchata'),3,'It sits in the big plastic barrel next to the hibiscus one at every taqueria, and is the standard thing to drink with something too spicy.'),
((SELECT id FROM dishes WHERE slug='horchata'),4,'Raw rice is soaked and blended with cinnamon, then strained through cloth and sweetened with milk and sugar.'),
((SELECT id FROM dishes WHERE slug='horchata'),5,'A cold, milky-white cinnamon-and-rice drink served over ice from a barrel at the taqueria.'),
((SELECT id FROM dishes WHERE slug='pico-de-gallo'),1,'A cold, chopped relish from the country directly south of the United States.'),
((SELECT id FROM dishes WHERE slug='pico-de-gallo'),2,'Its name translates as "rooster''s beak" — nobody agrees why, though one theory is that people once ate it by pinching pieces up with their fingers.'),
((SELECT id FROM dishes WHERE slug='pico-de-gallo'),3,'It is the fresh, chunky one that arrives in a bowl next to the guacamole, as distinct from the smooth blended sauce in the jar.'),
((SELECT id FROM dishes WHERE slug='pico-de-gallo'),4,'Tomato, white onion, chili and coriander are diced by hand, never blended, then dressed with lime juice and salt and left to sit raw.'),
((SELECT id FROM dishes WHERE slug='pico-de-gallo'),5,'A raw, hand-chopped Mexican relish of tomato, onion, chili and coriander in lime juice — chunky, never blended.'),
((SELECT id FROM dishes WHERE slug='pupusas'),1,'The national dish of the smallest country in Central America.'),
((SELECT id FROM dishes WHERE slug='pupusas'),2,'The Pipil people were making them long before the Spanish arrived; archaeologists have found the cooking implements at sites over a thousand years old.'),
((SELECT id FROM dishes WHERE slug='pupusas'),3,'El Salvador has a national day for them on the second Sunday of November, and Salvadoran communities in Los Angeles and Washington DC have made them a US staple.'),
((SELECT id FROM dishes WHERE slug='pupusas'),4,'A ball of corn masa is stuffed with cheese and beans, patted flat between wet hands, and griddled until it blisters — then topped with pickled cabbage slaw.'),
((SELECT id FROM dishes WHERE slug='pupusas'),5,'A thick griddled corn cake stuffed with cheese and beans, served with pickled cabbage slaw and a thin tomato sauce.'),
((SELECT id FROM dishes WHERE slug='avocado-toast'),1,'A café breakfast that a large southern-hemisphere country claims as its own invention.'),
((SELECT id FROM dishes WHERE slug='avocado-toast'),2,'A Sydney chef put it on a menu in 1993, and Australia''s café culture exported it to the world.'),
((SELECT id FROM dishes WHERE slug='avocado-toast'),3,'In 2017 an Australian millionaire blamed it for young people being unable to buy houses, and the internet has never let it go.'),
((SELECT id FROM dishes WHERE slug='avocado-toast'),4,'Ripe green fruit is mashed with lemon, salt and chili flakes, then piled onto toasted sourdough with a drizzle of olive oil.'),
((SELECT id FROM dishes WHERE slug='avocado-toast'),5,'Mashed ripe green fruit spread thick on toasted sourdough with lemon, salt and chili — the brunch order that became a generational punchline.'),
((SELECT id FROM dishes WHERE slug='vegemite-toast'),1,'Breakfast in a large southern-hemisphere country known for its wildlife.'),
((SELECT id FROM dishes WHERE slug='vegemite-toast'),2,'A Melbourne chemist created the dark spread in 1922 out of leftover brewer''s yeast, after wartime shipping cut off the British equivalent.'),
((SELECT id FROM dishes WHERE slug='vegemite-toast'),3,'Men at Work sang about a sandwich made with it in "Down Under", and watching a foreigner spread it far too thick is a national spectator sport.'),
((SELECT id FROM dishes WHERE slug='vegemite-toast'),4,'Hot toast is buttered first so the butter melts in, then the near-black salty paste is scraped on in the thinnest possible layer.'),
((SELECT id FROM dishes WHERE slug='vegemite-toast'),5,'Buttered hot toast smeared thinly with a dark, intensely salty yeast-extract spread that Australians adore and almost nobody else does.');
