-- Backfill: clue rewrites against the beat sheet (CLUES.md).
-- 88 clues across 88 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'A pounded dough eaten with West African stews.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 1;
UPDATE clues SET text = 'A pale custard tart from southern Africa.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milk-tart') AND order_index = 1;
UPDATE clues SET text = 'A glossy roasted meat hanging in East Asian shop windows.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'char-siu') AND order_index = 1;
UPDATE clues SET text = 'A crustless sandwich from East Asia, sold at every corner shop.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'katsu-sando') AND order_index = 1;
UPDATE clues SET text = 'A breaded, deep-fried cutlet from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tonkatsu') AND order_index = 1;
UPDATE clues SET text = 'A slow-baked bean and meat stew from southwest Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cassoulet') AND order_index = 1;
UPDATE clues SET text = 'A rich cold starter from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 1;
UPDATE clues SET text = 'A composed salad from the Mediterranean coast of Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nicoise-salad') AND order_index = 1;
UPDATE clues SET text = 'A laminated breakfast pastry from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 1;
UPDATE clues SET text = 'An upside-down fruit tart from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tarte-tatin') AND order_index = 1;
UPDATE clues SET text = 'A chilled soup with a Western European name and a disputed birthplace.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vichyssoise') AND order_index = 1;
UPDATE clues SET text = 'A grilled sausage from Central Europe''s beer gardens.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bratwurst') AND order_index = 1;
UPDATE clues SET text = 'A thin crisp flatbread from a border region of Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flammkuchen') AND order_index = 1;
UPDATE clues SET text = 'A rolled and braised beef entree from Central Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rouladen') AND order_index = 1;
UPDATE clues SET text = 'A soft, irregular egg noodle from Central Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaetzle') AND order_index = 1;
UPDATE clues SET text = 'A cold leaf-wrapped starter from the eastern Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 1;
UPDATE clues SET text = 'Small hot fried dough balls from the eastern Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 1;
UPDATE clues SET text = 'A pale, slow-simmered supper from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coddle') AND order_index = 1;
UPDATE clues SET text = 'A toasted bread starter from the Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bruschetta') AND order_index = 1;
UPDATE clues SET text = 'A two-ingredient pasta from southern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cacio-e-pepe') AND order_index = 1;
UPDATE clues SET text = 'A folded, stuffed cousin of pizza from the Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'calzone') AND order_index = 1;
UPDATE clues SET text = 'A dimpled, oil-slicked flatbread from southern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 1;
UPDATE clues SET text = 'A baked egg dish from the northern Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 1;
UPDATE clues SET text = 'A soft potato dumpling from southern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gnocchi') AND order_index = 1;
UPDATE clues SET text = 'A fried dough pastry from southern Europe, tied to one saint''s day.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 1;
UPDATE clues SET text = 'A small boiled dumpling from the cold end of Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 1;
UPDATE clues SET text = 'A hot grain breakfast from northern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'porridge') AND order_index = 1;
UPDATE clues SET text = 'A ridged fried dough stick from southwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'churros') AND order_index = 1;
UPDATE clues SET text = 'A fried, creamy tapa from southwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jamon-croquetas') AND order_index = 1;
UPDATE clues SET text = 'A layered dessert from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banoffee-pie') AND order_index = 1;
UPDATE clues SET text = 'A baked pudding from northwestern Europe that starts as leftovers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bread-pudding') AND order_index = 1;
UPDATE clues SET text = 'A fried leftovers dish from northwestern Europe, named for its noise.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-and-squeak') AND order_index = 1;
UPDATE clues SET text = 'Its spices say South Asia, its birth certificate says Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-tikka-masala') AND order_index = 1;
UPDATE clues SET text = 'A deliberately untidy cold dessert from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eton-mess') AND order_index = 1;
UPDATE clues SET text = 'A baked seafood supper from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 1;
UPDATE clues SET text = 'A baked minced-meat supper from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shepherds-pie') AND order_index = 1;
UPDATE clues SET text = 'A steamed suet pudding from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spotted-dick') AND order_index = 1;
UPDATE clues SET text = 'An oven-baked batter dish from Western Europe, containing no frogs.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'toad-in-the-hole') AND order_index = 1;
UPDATE clues SET text = 'A layered teatime bake from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'victoria-sponge-cake') AND order_index = 1;
UPDATE clues SET text = 'A savory cheese toast from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'welsh-rarebit') AND order_index = 1;
UPDATE clues SET text = 'A pressed and griddled sandwich from the Caribbean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cubano') AND order_index = 1;
UPDATE clues SET text = 'A shareable snack invented on a Latin American border.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nachos') AND order_index = 1;
UPDATE clues SET text = 'A wok-fired beef dish from South America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lomo-saltado') AND order_index = 1;
UPDATE clues SET text = 'A thin oval flatbread from the eastern Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lahmacun') AND order_index = 1;
UPDATE clues SET text = 'A lumpy fried North American dessert.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 1;
UPDATE clues SET text = 'A fried dough treat from the American Gulf Coast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beignets') AND order_index = 1;
UPDATE clues SET text = 'A regional meat sauce from the American Midwest.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cincinnati-chili') AND order_index = 1;
UPDATE clues SET text = 'A sweet baked breakfast from North America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 1;
UPDATE clues SET text = 'A hot North American breakfast porridge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 1;
UPDATE clues SET text = 'A cold North American party starter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 1;
UPDATE clues SET text = 'A rich layered North American dessert.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 1;
UPDATE clues SET text = 'A breakfast plate from the American Northeast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-york-bagel-with-lox') AND order_index = 1;
UPDATE clues SET text = 'A plain North American breakfast, eaten from a bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 1;
UPDATE clues SET text = 'An uncooked North American lunchbox standard.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peanut-butter-and-jelly-sandwich') AND order_index = 1;
UPDATE clues SET text = 'The most-cooked breakfast in North America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scrambled-eggs') AND order_index = 1;
UPDATE clues SET text = 'A soft North American cookie with a German-sounding name.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 1;
UPDATE clues SET text = 'A hot North American starter, ordered for the table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 1;
UPDATE clues SET text = 'Smoked meat from the American Southwest.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'texas-beef-brisket') AND order_index = 1;
UPDATE clues SET text = 'A cold North American breakfast, layered in a cup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 1;
UPDATE clues SET text = 'A cafe breakfast from Oceania, claimed there as an invention.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'avocado-toast') AND order_index = 1;
UPDATE clues SET text = 'A children''s party treat from Oceania.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 1;
UPDATE clues SET text = 'A desert dish from South Asia, built to keep.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-baati') AND order_index = 1;
UPDATE clues SET text = 'A street snack from South Asia with six regional names.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pani-puri') AND order_index = 1;
UPDATE clues SET text = 'A national breakfast plate from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-lemak') AND order_index = 1;
UPDATE clues SET text = 'A sizzling late-night plate from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 1;
UPDATE clues SET text = 'A hot-season dessert from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-sticky-rice') AND order_index = 1;
UPDATE clues SET text = 'A pasta from southern Europe, built on egg and cured pork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-carbonara') AND order_index = 1;
UPDATE clues SET text = 'A cold summer soup from southern Europe, eaten with a spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gazpacho') AND order_index = 1;
UPDATE clues SET text = 'A dip eaten across the Middle East and claimed by most of it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hummus') AND order_index = 1;
UPDATE clues SET text = 'A dessert a whole country claims to be as American as.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-pie') AND order_index = 1;
UPDATE clues SET text = 'A thrifty North American family supper, and a blue-plate special.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'meatloaf') AND order_index = 1;
UPDATE clues SET text = 'A portable stuffed pastry eaten across South America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'empanadas') AND order_index = 1;
UPDATE clues SET text = 'A grilled deli stack named for a disputed person.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'reuben-sandwich') AND order_index = 1;
UPDATE clues SET text = 'A breakfast flatbread from the Levant.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manakish') AND order_index = 1;
UPDATE clues SET text = 'A savory oat-and-offal pudding from northern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'haggis') AND order_index = 1;
UPDATE clues SET text = 'A flambeed dessert from Western Europe with a disputed origin story.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crepe-suzette') AND order_index = 1;
UPDATE clues SET text = 'A spiraled pastry from Northern Europe with its own national holiday.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kanelbulle') AND order_index = 1;
UPDATE clues SET text = 'A cold spread eaten all over the American South.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pimento-cheese-sandwich') AND order_index = 1;
UPDATE clues SET text = 'A fried cornmeal side from the American South.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hush-puppies') AND order_index = 1;
UPDATE clues SET text = 'A hot sandwich from American diners and lunch counters.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'grilled-cheese') AND order_index = 1;
UPDATE clues SET text = 'A composed leaf dish from Latin America, despite the Italian name.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caesar-salad') AND order_index = 1;
UPDATE clues SET text = 'A milk-soaked sponge from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tres-leches-cake') AND order_index = 1;
UPDATE clues SET text = 'A steamed grain dish from North Africa.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 1;
UPDATE clues SET text = 'A stuffed breakfast flatbread from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-paratha') AND order_index = 1;
UPDATE clues SET text = 'A homely dry vegetable dish from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-gobi') AND order_index = 1;
UPDATE clues SET text = 'A crisp fried starter from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onion-bhaji') AND order_index = 1;
UPDATE clues SET text = 'A cooling yogurt side from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'raita') AND order_index = 1;
UPDATE clues SET text = 'A skewered vegetarian starter from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paneer-tikka') AND order_index = 1;
