-- Backfill: clue rewrites against the beat sheet (CLUES.md).
-- 78 clues across 78 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'You stretch dough thin, dress it with tomato, mozzarella and basil, and blast it in a wood oven.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'margherita-pizza') AND order_index = 4;
UPDATE clues SET text = 'You batter a white fillet, drop it in hot oil, and serve it with thick-cut fried potato.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-and-chips') AND order_index = 4;
UPDATE clues SET text = 'Sliced sausage drowns in a curried tomato sauce, with fries on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'currywurst') AND order_index = 4;
UPDATE clues SET text = 'Beef simmers with onions and a heavy hand of sweet red paprika.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'goulash') AND order_index = 4;
UPDATE clues SET text = 'You grind chickpeas with herbs, roll them into balls and fry them green inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'falafel') AND order_index = 4;
UPDATE clues SET text = 'Rice arrives under neat piles of vegetables, beef and a fried egg, and you stir it together with chili paste.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bibimbap') AND order_index = 4;
UPDATE clues SET text = 'Chilies, nuts and spices simmer for hours, with a famous touch of chocolate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mole-poblano') AND order_index = 4;
UPDATE clues SET text = 'You roll dough paper-thin, spread it with spiced minced lamb, and bake it until crisp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lahmacun') AND order_index = 4;
UPDATE clues SET text = 'Ground corn simmers into a creamy porridge, and sauteed shellfish and bacon go on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-and-grits') AND order_index = 4;
UPDATE clues SET text = 'Fried potato cubes take a smoky paprika-tomato sauce and a garlicky mayonnaise.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patatas-bravas') AND order_index = 4;
UPDATE clues SET text = 'You fold whipped egg whites into a chocolate base and bake it so it towers above the ramekin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 4;
UPDATE clues SET text = 'You rub semolina into tiny pellets, then steam them over the stew they will be served with.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 4;
UPDATE clues SET text = 'You pound boiled cassava and plantain until springy, roll it into a ball, and swallow it dipped in soup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 4;
UPDATE clues SET text = 'A pale custard set with cornflour fills a thin pastry shell, then chills under a dusting of cinnamon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milk-tart') AND order_index = 4;
UPDATE clues SET text = 'Green leaves steep with sugar in a silver pot, and you pour from a great height into small glasses.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moroccan-mint-tea') AND order_index = 4;
UPDATE clues SET text = 'Meat marinates in vinegar with dried red chilies and garlic, then slow-cooks until the sauce turns dark and sharp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vindaloo') AND order_index = 4;
UPDATE clues SET text = 'You boil milk down for hours until it caramelises, flavour it with cardamom, then freeze it solid without churning.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kulfi') AND order_index = 4;
UPDATE clues SET text = 'Potato and cauliflower dry-fry with turmeric, cumin and ginger until the edges catch, and no gravy goes near it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-gobi') AND order_index = 4;
UPDATE clues SET text = 'Chicken simmers with lemongrass, galangal and turmeric until the broth turns gold, then shreds over noodles and egg.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'soto-ayam') AND order_index = 4;
UPDATE clues SET text = 'Rice steams in coconut milk with a knotted leaf, then shares the plate with hot sambal, fried anchovies and cucumber.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-lemak') AND order_index = 4;
UPDATE clues SET text = 'Whole shellfish stir-fry in a thick sweet tomato gravy ribboned with egg, and you mop it up with fried buns.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-crab') AND order_index = 4;
UPDATE clues SET text = 'Shaved ice and evaporated milk go over sweet beans, jellies, preserved fruit and purple yam, topped with ice cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'halo-halo') AND order_index = 4;
UPDATE clues SET text = 'You dip rice paper in water until it turns pliable, then wrap it raw around herbs, noodles and shellfish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fresh-spring-rolls') AND order_index = 4;
UPDATE clues SET text = 'Coconut milk simmers with galangal, lemongrass and lime leaves, then chicken and mushrooms go in with fish sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-kha-gai') AND order_index = 4;
UPDATE clues SET text = 'You steam glutinous rice and pound it into a springy dough, then wrap it around a sweet filling and dust it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 4;
UPDATE clues SET text = 'A cook slices raw fish at a precise angle with a single-bevel knife and lays it over shredded daikon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 4;
UPDATE clues SET text = 'You pour a beaten yolk mixture in a thin stream into thickened broth so it sets into delicate ribbons.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egg-drop-soup') AND order_index = 4;
UPDATE clues SET text = 'You char a whole aubergine over flame until the skin collapses, then mash the smoky flesh with sesame paste.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baba-ganoush') AND order_index = 4;
UPDATE clues SET text = 'Sugar syrup cooks with cornflour for hours into a soft springy gel, scented with rose water and cut into cubes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'turkish-delight') AND order_index = 4;
UPDATE clues SET text = 'Raw fillets cure for days under a weighted blanket of salt, sugar and dill, never cooked and never smoked.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gravlax') AND order_index = 4;
UPDATE clues SET text = 'A churn turns it slowly, beating in far less air than ice cream, so it stays dense enough to spread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 4;
UPDATE clues SET text = 'You fold yeasted dough around a slab of butter again and again to build dozens of layers, then shape a spiral.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'danish-pastry') AND order_index = 4;
UPDATE clues SET text = 'Sherry-soaked sponge layers up in a glass bowl with fruit, set jelly and custard, under a thick blanket of cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'trifle') AND order_index = 4;
UPDATE clues SET text = 'Boiled waxy tubers cool, then fold together with onion, pickle, mustard and a heavy dose of mayonnaise.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 4;
UPDATE clues SET text = 'You pour loose yeasted batter into metal rings on a griddle so bubbles burst through and leave holes for butter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 4;
UPDATE clues SET text = 'Shellfish and fish simmer in a garlicky tomato and white wine broth, served with sourdough for dunking.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cioppino') AND order_index = 4;
UPDATE clues SET text = 'Halved and hollowed, the yolks mash with mayonnaise and mustard, then pipe back into the whites under paprika.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 4;
UPDATE clues SET text = 'Cabbage and carrot shred fine, then dress in mayonnaise sharpened with vinegar and mustard, and soften in the fridge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coleslaw') AND order_index = 4;
UPDATE clues SET text = 'Cream cheese beats together with shellfish and scallion, spoons into wonton wrappers folded into purses, and fries.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-rangoon') AND order_index = 4;
UPDATE clues SET text = 'Shellfish saute hard in butter and a great deal of garlic, deglaze with white wine and lemon, then meet linguine.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-scampi') AND order_index = 4;
UPDATE clues SET text = 'You grate potato, squeeze it bone dry, press it into a hot buttered pan and leave it alone until one side sets.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 4;
UPDATE clues SET text = 'A yellow tropical fruit, poisonous unless picked fully open, sautes with rehydrated salted cod, peppers and thyme.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ackee-and-saltfish') AND order_index = 4;
UPDATE clues SET text = 'Tomato, white onion, chili and coriander get diced by hand, never blended, dressed with lime and left to sit raw.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 4;
UPDATE clues SET text = 'You stuff a ball of corn masa with cheese and beans, pat it flat between wet hands, and griddle it until it blisters.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pupusas') AND order_index = 4;
UPDATE clues SET text = 'You butter soft white slices right to the crusts, shower them with tiny sugar beads, and cut them into triangles.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 4;
UPDATE clues SET text = 'Its frosting defines it, egg yolks and evaporated milk cooked into custard, stirred full of pecans and coconut.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 4;
UPDATE clues SET text = 'You drizzle thin batter into hot oil in overlapping loops, fry it crisp, and bury it in powdered sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'funnel-cake') AND order_index = 4;
UPDATE clues SET text = 'A beaten mixture goes into melted butter over low heat, and you push it slowly around the pan into soft folds.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scrambled-eggs') AND order_index = 4;
UPDATE clues SET text = 'Roast pork and ham layer with Swiss cheese, mustard and dill pickles, then flatten in a press until the bread crackles.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cubano') AND order_index = 4;
UPDATE clues SET text = 'A beef round goes down with a heap of browned onions and cheese, griddled between buttered slices until dark and crisp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patty-melt') AND order_index = 4;
UPDATE clues SET text = 'Two spreads meet on soft white bread, one ground from a roasted legume, the other boiled down from fruit and sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peanut-butter-and-jelly-sandwich') AND order_index = 4;
UPDATE clues SET text = 'A shoulder rubbed with paprika and brown sugar smokes low and slow until it shreds by hand, then piles on a soft roll.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pulled-pork-sandwich') AND order_index = 4;
UPDATE clues SET text = 'You blanch grape leaves until pliable, roll them tight around rice with dill and mint, and simmer them under a plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 4;
UPDATE clues SET text = 'You drop loose yeasted batter by the spoonful into hot oil, then drench the puffed balls in warm honey syrup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 4;
UPDATE clues SET text = 'Butter creams with egg and vanilla into a pale dough, rolled flat and cut into shapes before it barely colours.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sugar-cookies') AND order_index = 4;
UPDATE clues SET text = 'Cream of tartar gives the dough a distinct tang, and you bake it until it puffs and falls into a crackled top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 4;
UPDATE clues SET text = 'Shredded poultry stirs into softened cream cheese with cayenne sauce and cheddar, then bakes until it bubbles.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 4;
UPDATE clues SET text = 'A leafy green and the heart of a thistle chop into cream cheese, sour cream and parmesan, then bake until brown.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 4;
UPDATE clues SET text = 'Refried beans go down first, then mashed avocado, sour cream, cheese, tomato, olives and scallion, each spread flat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 4;
UPDATE clues SET text = 'Torn stale loaf soaks in a custard of milk, egg, sugar and vanilla with raisins, then bakes until the top crisps.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bread-pudding') AND order_index = 4;
UPDATE clues SET text = 'Thin unleavened dough pinches around raw minced beef and pork with onion, then boils and arrives with sour cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 4;
UPDATE clues SET text = 'Chopped orchard fruit and cinnamon fold through a wet dough, drop into hot oil in an untidy lump, and take a glaze.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 4;
UPDATE clues SET text = 'Choux pastry pipes into a ring and fries hollow, then fills with vanilla cream under a candied sour cherry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 4;
UPDATE clues SET text = 'Thick strained cultured milk spoons into a clear cup in layers with toasted oat clusters and fruit, stripes showing.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 4;
UPDATE clues SET text = 'A rolled cereal grain simmers in milk until it thickens, then takes brown sugar, butter and a shake of cinnamon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 4;
UPDATE clues SET text = 'Finely milled semolina rains into hot milk and you whisk it constantly until it thickens smooth and lump-free.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 4;
UPDATE clues SET text = 'Beaten eggs pour over vegetables softening in olive oil, cook slowly without stirring, then finish under the broiler.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 4;
UPDATE clues SET text = 'You spread enriched dough with butter and brown sugar, cut it into spirals and bake them shoulder to shoulder.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 4;
UPDATE clues SET text = 'A wet, slack dough proves in an oiled tray, and you dimple it all over so the pools hold oil and salt.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 4;
UPDATE clues SET text = 'The enlarged liver of a fattened duck is deveined, packed into a terrine, cooked gently and chilled for toast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 4;
UPDATE clues SET text = 'Flour and shredded suet bind with milk and sugar, dotted with dried currants, then steam for hours under hot custard.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spotted-dick') AND order_index = 4;
UPDATE clues SET text = 'Pork sausages and rashers of bacon layer with sliced potato and onion, then simmer in stock until everything gives.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coddle') AND order_index = 4;
UPDATE clues SET text = 'Pig''s head and ears boil, then grill, then chop fine with onion and chili, and arrive on a sizzling plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 4;
UPDATE clues SET text = 'Sour red stone fruit thickens with sugar and cornstarch in a butter pastry shell, under strips woven into a lattice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 4;
UPDATE clues SET text = 'The puree of a large orange gourd whisks with eggs, condensed milk, cinnamon and ginger into a single pastry shell.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pumpkin-pie') AND order_index = 4;
UPDATE clues SET text = 'Sharp yellow citrus juice cooks with sugar and egg yolks into a thick curd, then takes a crown of browned whites.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 4;
UPDATE clues SET text = 'You spread thick boiled-milk caramel on a crumb base, layer sliced banana over it and cover the lot with cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banoffee-pie') AND order_index = 4;
UPDATE clues SET text = 'Chunks of white and smoked seafood fold into a thick parsley bechamel under a mashed potato lid, forked into ridges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 4;
