-- Backfill: clue rewrites against the beat sheet (CLUES.md).
-- 89 clues across 89 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'Roman legend ties it to charcoal workers, or to American rations after the war.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-carbonara') AND order_index = 2;
UPDATE clues SET text = 'Cooks in the Veneto built it in the 1960s, which is remarkably young for a classic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tiramisu') AND order_index = 2;
UPDATE clues SET text = 'Iberian shepherds claim it, and so does a theory about Chinese youtiao met at sea.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'churros') AND order_index = 2;
UPDATE clues SET text = 'Magyar herdsmen cooked it in kettles, and the name still means herdsman.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'goulash') AND order_index = 2;
UPDATE clues SET text = 'A 1930s prime minister promoted it to build national identity and save rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-thai') AND order_index = 2;
UPDATE clues SET text = 'Thrift built it: yesterday''s rice became this morning''s breakfast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-goreng') AND order_index = 2;
UPDATE clues SET text = 'Peranakan cooks made it, Chinese noodles meeting Malay spice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'laksa') AND order_index = 2;
UPDATE clues SET text = 'Scottish frying and West African seasoning met in Southern kitchens, largely in the hands of enslaved cooks.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'southern-fried-chicken') AND order_index = 2;
UPDATE clues SET text = 'Louisiana stirred West African okra, French roux and Choctaw file into one pot.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gumbo') AND order_index = 2;
UPDATE clues SET text = 'Rice porridge has fed China for two thousand years, above all the sick and the newborn.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'congee') AND order_index = 2;
UPDATE clues SET text = 'Hungarian cooks built it around paprika after the spice took root there in the 1700s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-paprikash') AND order_index = 2;
UPDATE clues SET text = 'A Texas snack-food saleswoman gets the credit for first spooning chili into a chip bag.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frito-pie') AND order_index = 2;
UPDATE clues SET text = 'Japanese cooks refined the glazing technique, and their restaurants carried it abroad.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'teriyaki-chicken') AND order_index = 2;
UPDATE clues SET text = 'A 19th-century French chef put his name to the finished version.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eclair') AND order_index = 2;
UPDATE clues SET text = 'Berber cooks were making it by the 13th century, and UNESCO listed it as shared heritage in 2020.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 2;
UPDATE clues SET text = 'Pounding starchy roots into a smooth dough is one of West Africa''s oldest kitchen techniques.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 2;
UPDATE clues SET text = 'British traders dumped surplus green leaf on North African ports in the 1800s; cooks added a herb and sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moroccan-mint-tea') AND order_index = 2;
UPDATE clues SET text = 'Cooks on the Gangetic plains made the ancestor, and it spread across India from there.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pani-puri') AND order_index = 2;
UPDATE clues SET text = 'Portuguese sailors brought meat in wine and garlic, and Goan cooks swapped in palm vinegar and chilies.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vindaloo') AND order_index = 2;
UPDATE clues SET text = 'Persian and Central Asian cooks brought it to the Mughal courts, adapted from a fried dough soaked in syrup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gulab-jamun') AND order_index = 2;
UPDATE clues SET text = 'Punjab has drunk the yogurt version for three thousand years; the fruit one is a restaurant-era twist.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-lassi') AND order_index = 2;
UPDATE clues SET text = 'The British planted the leaf in Assam to break China''s monopoly; vendors stretched it with milk and spice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-chai') AND order_index = 2;
UPDATE clues SET text = 'Punjabi households built it from two cheap vegetables that hold up to a long dry fry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-gobi') AND order_index = 2;
UPDATE clues SET text = 'Cooks fried these across the subcontinent for centuries; British curry houses standardised the round one.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onion-bhaji') AND order_index = 2;
UPDATE clues SET text = 'Punjabi cooks in mid-century Delhi built a meatless answer to the tandoori grill.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paneer-tikka') AND order_index = 2;
UPDATE clues SET text = 'Every region of Java has a version, and Javanese migrants carried it to Malaysia and Suriname.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'soto-ayam') AND order_index = 2;
UPDATE clues SET text = 'Malay farmers ate it in the fields, and a 1909 book about Malay life first wrote it down.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-lemak') AND order_index = 2;
UPDATE clues SET text = 'Cher Yam Tian sold it from a pushcart on the East Coast in 1956, at first with bottled tomato sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-crab') AND order_index = 2;
UPDATE clues SET text = 'Chinese immigrants brought it to Thailand, and the name means fried with soy sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-see-ew') AND order_index = 2;
UPDATE clues SET text = 'Korean cooks took their own turn in the 20th century, seasoning the rice with sesame oil rather than vinegar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimbap') AND order_index = 2;
UPDATE clues SET text = 'Cooks have pounded it for New Year since the Heian period, one striking while the other turns the dough.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 2;
UPDATE clues SET text = 'Two Taichung shops both claim the 1980s invention and fought a ten-year court case neither won.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-tea') AND order_index = 2;
UPDATE clues SET text = 'The name means pierced body, from pinning the tail and fin to the plate to show the species.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 2;
UPDATE clues SET text = 'The Arabic name means pampered daddy, from a story about a daughter cooking for her toothless father.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baba-ganoush') AND order_index = 2;
UPDATE clues SET text = 'Medieval fishermen buried the catch in sand above the tide line to ferment it, hence grave salmon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gravlax') AND order_index = 2;
UPDATE clues SET text = 'A 14th-century Dutch method of gutting and brining at sea built the country''s trading fortune.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pickled-herring') AND order_index = 2;
UPDATE clues SET text = 'A French chef at the Ritz-Carlton in New York chilled his childhood soup in 1917 and named it for a spa town.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vichyssoise') AND order_index = 2;
UPDATE clues SET text = 'A Florentine architect gets the credit for perfecting it for the Medici court in the 1500s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 2;
UPDATE clues SET text = 'Scots have eaten it every morning for centuries, stirred clockwise with a stick called a spurtle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'porridge') AND order_index = 2;
UPDATE clues SET text = 'Austrian bakers hired during a Copenhagen strike in 1850 left the laminated technique behind.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'danish-pastry') AND order_index = 2;
UPDATE clues SET text = 'Germans have made it since the 1600s, and emigrants carried it to America, where mayonnaise took over.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 2;
UPDATE clues SET text = 'Anglo-Saxons cooked a hard griddle cake by the name; Victorian bakers added a raising agent.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 2;
UPDATE clues SET text = 'San Francisco saloons served oyster versions in the 1860s, and the shellfish one took over after Prohibition.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-cocktail') AND order_index = 2;
UPDATE clues SET text = 'Britain used the word for spicing a dish this way in the 1700s, and southern cooks made it a standard.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 2;
UPDATE clues SET text = 'Dutch settlers brought koolsla, cabbage salad, to New York, and bottled mayonnaise made it creamy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coleslaw') AND order_index = 2;
UPDATE clues SET text = 'A 19th-century sanitarium doctor created the health food, and a rival sued him over the near-identical name.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'granola') AND order_index = 2;
UPDATE clues SET text = 'Trader Vic''s in San Francisco created it in the 1950s, and the Burmese city in the name is unrelated.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-rangoon') AND order_index = 2;
UPDATE clues SET text = 'Italian-American cooks swapped local shellfish for the small langoustines the name still refers to.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-scampi') AND order_index = 2;
UPDATE clues SET text = 'New York breakfast menus carried them in the 1890s as hashed browned potatoes, which got shortened.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 2;
UPDATE clues SET text = 'The fruit came from West Africa on slave ships in the 1700s, the cured cod down from the North Atlantic trade.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ackee-and-saltfish') AND order_index = 2;
UPDATE clues SET text = 'Spanish colonists brought it from Valencia, where tiger nuts do the job; Mexican cooks used a grain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'horchata') AND order_index = 2;
UPDATE clues SET text = 'The name means rooster''s beak, and one theory says people once pinched pieces up by hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 2;
UPDATE clues SET text = 'The Pipil people made them long before the Spanish came, and archaeologists found the griddles to prove it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pupusas') AND order_index = 2;
UPDATE clues SET text = 'A Melbourne chemist made the dark spread in 1922 from leftover brewer''s yeast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vegemite-toast') AND order_index = 2;
UPDATE clues SET text = 'A Robert Louis Stevenson poem of 1885 probably gave the name; Australian papers had the food by the 1920s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 2;
UPDATE clues SET text = 'Samuel German made a dark baking bar in 1852, and a Texas homemaker''s 1957 recipe dropped his apostrophe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 2;
UPDATE clues SET text = 'Pennsylvania Dutch settlers brought the poured-batter method from German-speaking Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'funnel-cake') AND order_index = 2;
UPDATE clues SET text = 'Romans cooked them much this way, and Escoffier later codified the slow version with plenty of butter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scrambled-eggs') AND order_index = 2;
UPDATE clues SET text = 'Cigar-factory workers in Key West and Ybor City built it from the shops that shared their street.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cubano') AND order_index = 2;
UPDATE clues SET text = 'A Tokyo cutlet restaurant put fried pork between bread in the 1930s so geishas could eat one-handed.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'katsu-sando') AND order_index = 2;
UPDATE clues SET text = 'A US magazine printed the pairing in 1901, and 1940s ration kits put both spreads in one box.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peanut-butter-and-jelly-sandwich') AND order_index = 2;
UPDATE clues SET text = 'Cooks across the old Ottoman world wrapped food in leaves this way, and the name comes from a Turkish verb.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 2;
UPDATE clues SET text = 'Ancient Greek writing calls fried dough in honey honey tokens, handed to winners at the earliest games.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 2;
UPDATE clues SET text = 'German settlers in Nazareth, Pennsylvania baked the round version in the 1700s, and the town''s name stuck.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sugar-cookies') AND order_index = 2;
UPDATE clues SET text = 'New England cookbooks printed it by the late 1800s; the name traces to a German noodle or to plain nonsense.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 2;
UPDATE clues SET text = 'A cereal company printed a version on its canister around 1900, borrowing from Scottish oatcakes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal-raisin-cookies') AND order_index = 2;
UPDATE clues SET text = 'A bar in western New York gets the 1990s credit, using the sauce that made that city''s wings famous.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 2;
UPDATE clues SET text = 'American chains put it on starter menus in the 1980s, borrowing from older French ways of creaming greens.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 2;
UPDATE clues SET text = 'Texas cooks assembled it in the 1970s, and a glass dish made it famous because the stripes show.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 2;
UPDATE clues SET text = 'English cooks soaked stale loaves like this by the 1200s and called it the poor man''s supper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bread-pudding') AND order_index = 2;
UPDATE clues SET text = 'Cooks in Siberia took the idea from their eastern neighbours, and the name means ear bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 2;
UPDATE clues SET text = 'Dutch settlers brought batter-fried fruit to New York, and the bakery counter made it a craggy glazed slab.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 2;
UPDATE clues SET text = 'Naples ties it to Saint Joseph''s feast on the 19th of March, and convent kitchens get the credit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 2;
UPDATE clues SET text = 'The French word once meant a frozen dessert in a mould; American cafeterias borrowed it for layers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 2;
UPDATE clues SET text = 'Scottish households lived on it for centuries, and American cereal companies put it in a round canister.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 2;
UPDATE clues SET text = 'A North Dakota mill was stuck with a by-product in 1893, and the head miller cooked it into breakfast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 2;
UPDATE clues SET text = 'Italian cooks built it to use up whatever was left, and its name is their verb for frying.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 2;
UPDATE clues SET text = 'Swedish bakers had a cardamom-scented version first; Seattle''s mall bakeries piled on the frosting in 1985.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 2;
UPDATE clues SET text = 'The name descends from the Latin for hearth bread, and Liguria has claimed it since Roman times.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 2;
UPDATE clues SET text = 'Egyptian tombs show geese being fattened; the practice reached Rome, then Alsace and southwest France.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 2;
UPDATE clues SET text = 'Victorian cookbooks had it by the 1840s, and the second half of the name may be an old word for pudding.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spotted-dick') AND order_index = 2;
UPDATE clues SET text = 'Dublin cooks recorded it from the 1700s to use up what was left before the Friday fast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coddle') AND order_index = 2;
UPDATE clues SET text = 'Pampanga claims it, and Lucia Cunanan gets the 1970s credit, using what a nearby air base threw out.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 2;
UPDATE clues SET text = 'Colonists carried the trees over, and Michigan orchards made the sour red kind cheap and canned by the 1940s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 2;
UPDATE clues SET text = 'English colonists filled the native gourd with milk and spices and baked it in the embers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pumpkin-pie') AND order_index = 2;
UPDATE clues SET text = 'A Philadelphia baker named Elizabeth Goodfellow gets the credit for joining the curd and the whipped whites.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 2;
UPDATE clues SET text = 'Cooks at a Sussex restaurant built it in 1971 and spent years correcting people who swore it was older.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banoffee-pie') AND order_index = 2;
UPDATE clues SET text = 'Cooks stretched the cheap end of the catch with it, and it became a Friday dinner and canteen regular.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 2;
UPDATE clues SET text = 'The Aztecs called it ahuacamolli, avocado sauce, centuries before the conquistadors landed.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'guacamole') AND order_index = 2;
