-- Backfill: clue rewrites against the beat sheet (CLUES.md).
-- 175 clues across 175 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'Cooks name it for the wide shallow pan, and stirring it is the one thing you must not do.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paella') AND order_index = 3;
UPDATE clues SET text = 'Britain kept it off the ration through both World Wars, judging it that important.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-and-chips') AND order_index = 3;
UPDATE clues SET text = 'Swap the lamb for beef and the name changes, which is reliable pub-quiz gold.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shepherds-pie') AND order_index = 3;
UPDATE clues SET text = 'Austrian law reserves the name for veal, so pork versions must be called something else.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wiener-schnitzel') AND order_index = 3;
UPDATE clues SET text = 'A whole Catskills resort circuit took its name, and the comedians who worked it built American stand-up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'borscht') AND order_index = 3;
UPDATE clues SET text = 'South Africans call it their national dish, egg custard baked over spiced mince.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bobotie') AND order_index = 3;
UPDATE clues SET text = 'India orders more of it for delivery than anything else, one going out every few seconds.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-biryani') AND order_index = 3;
UPDATE clues SET text = 'Cooks turn it out longer than your arm, and the crepe shatters when you break it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-dosa') AND order_index = 3;
UPDATE clues SET text = 'It keeps for weeks without a fridge, which is why families cook it for the journey home at Eid.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-rendang') AND order_index = 3;
UPDATE clues SET text = 'A Kentucky colonel franchised it with eleven secret herbs and spices.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'southern-fried-chicken') AND order_index = 3;
UPDATE clues SET text = 'Soda fountains built it as the showpiece of the menu, this diner included.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banana-split') AND order_index = 3;
UPDATE clues SET text = 'Mexico treats it as the national dish, and families guard their recipe for generations.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mole-poblano') AND order_index = 3;
UPDATE clues SET text = 'Peru gave it a national holiday, which falls on the 28th of June.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ceviche') AND order_index = 3;
UPDATE clues SET text = 'Australia and New Zealand still argue over who invented it, and it lands at a midsummer Christmas.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pavlova') AND order_index = 3;
UPDATE clues SET text = 'Hong Kong street vendors sell it before dawn, and the sick get it first.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'congee') AND order_index = 3;
UPDATE clues SET text = 'Diners cook it themselves at the table, on a griddle built into the counter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'okonomiyaki') AND order_index = 3;
UPDATE clues SET text = 'Lay it over rice with egg and onion and it becomes a different dish with its own name.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tonkatsu') AND order_index = 3;
UPDATE clues SET text = 'Seoul street carts line whole alleys with it, and school kids empty them by four.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tteokbokki') AND order_index = 3;
UPDATE clues SET text = 'Korean holiday tables put it in the middle, and the noodles are made from sweet potato.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'japchae') AND order_index = 3;
UPDATE clues SET text = 'Korean cooks save the sourest, oldest jar for it, once it has gone too funky to eat raw.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimchi-jjigae') AND order_index = 3;
UPDATE clues SET text = 'The clay oven runs near 480 degrees, which is why the outside chars before the inside dries.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tandoori-chicken') AND order_index = 3;
UPDATE clues SET text = 'Vendors mash it flat on a griddle the size of a table, working it with two blunt blades.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pav-bhaji') AND order_index = 3;
UPDATE clues SET text = 'The batter ferments overnight, so the steamed cake rises with no raising agent at all.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'idli') AND order_index = 3;
UPDATE clues SET text = 'Roadside stalls pair it with a fried bread for breakfast across North India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chana-masala') AND order_index = 3;
UPDATE clues SET text = 'Its sour, fiery steam is the smell people abroad name first when they think of Thai food.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-yum-goong') AND order_index = 3;
UPDATE clues SET text = 'Its spices came up the trade routes with Muslim merchants, cardamom and cinnamon in a Thai pot.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'massaman-curry') AND order_index = 3;
UPDATE clues SET text = 'Hawker stalls across half a dozen countries grill it, each claiming the peanut sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'satay') AND order_index = 3;
UPDATE clues SET text = 'Television cooking shows use it as the test that breaks a home cook''s nerve.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-wellington') AND order_index = 3;
UPDATE clues SET text = 'Bavarian beer gardens use it as an unofficial mascot, and the arms cross in prayer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pretzel') AND order_index = 3;
UPDATE clues SET text = 'Its layers are so thin you can read through them, and they shatter on the first bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spanakopita') AND order_index = 3;
UPDATE clues SET text = 'Athens eats it walking, wrapped in pita with chips tucked inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souvlaki') AND order_index = 3;
UPDATE clues SET text = 'Cooks salt and wring the cucumber first, or it waters the yogurt down within the hour.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tzatziki') AND order_index = 3;
UPDATE clues SET text = 'Florida named it the official state dessert by act of the legislature.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'key-lime-pie') AND order_index = 3;
UPDATE clues SET text = 'Its neat parallel rows became a template diners copied all over America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cobb-salad') AND order_index = 3;
UPDATE clues SET text = 'Mexico eats it on Independence Day, and the corn is treated with lime until it blooms open.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pozole') AND order_index = 3;
UPDATE clues SET text = 'A dozen Latin American countries each cook a version and each insists theirs came first.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arroz-con-pollo') AND order_index = 3;
UPDATE clues SET text = 'Argentine households eat it more than steak, which in Argentina is saying something.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milanesa') AND order_index = 3;
UPDATE clues SET text = 'Lima grills it on skewers outside the stadiums, and the meat is beef heart.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'anticuchos') AND order_index = 3;
UPDATE clues SET text = 'Peru''s Chinese kitchens show plainest here, in a wok tradition they call chifa.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lomo-saltado') AND order_index = 3;
UPDATE clues SET text = 'You mash it in a wooden mortar and serve it in the dome shape the mortar left.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mofongo') AND order_index = 3;
UPDATE clues SET text = 'African and Portuguese kitchens both claim it, and the chili crossed on Portuguese ships.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'piri-piri-prawns') AND order_index = 3;
UPDATE clues SET text = 'Durban sells it by the quarter loaf, and no rabbit has ever been involved.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bunny-chow') AND order_index = 3;
UPDATE clues SET text = 'South Africans reach for it on road trips, air-dried rather than smoked like jerky.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biltong') AND order_index = 3;
UPDATE clues SET text = 'Egypt sells it from carts on almost every corner, three starches in one bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'koshari') AND order_index = 3;
UPDATE clues SET text = 'Beirut buys it from corner bakeries on the way to work, flat and still warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manakish') AND order_index = 3;
UPDATE clues SET text = 'Its slow-turning vertical spit lights up shop windows on six continents.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shawarma') AND order_index = 3;
UPDATE clues SET text = 'Hungarians spoon the red sauce over nokedli, small dumplings pinched off a board.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-paprikash') AND order_index = 3;
UPDATE clues SET text = 'A proper Sunday roast will not go out without it, and the batter needs a screaming-hot tin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yorkshire-pudding') AND order_index = 3;
UPDATE clues SET text = 'A London department store claims the 1738 invention, though picnic hampers made the name.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scotch-egg') AND order_index = 3;
UPDATE clues SET text = 'Norwegian pantries keep it in a tin, and the catch is ground to a paste before shaping.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-cakes') AND order_index = 3;
UPDATE clues SET text = 'The shops that sell it are licensed as appetizing stores, a category of their own.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-york-bagel-with-lox') AND order_index = 3;
UPDATE clues SET text = 'The white sauce is peppery pork drippings, and diners ladle it over the top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 3;
UPDATE clues SET text = 'A novel and film named for a whistle-stop cafe made it famous across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-green-tomatoes') AND order_index = 3;
UPDATE clues SET text = 'Harlem jazz clubs fed it to musicians finishing a set, breakfast and supper at once.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-and-waffles') AND order_index = 3;
UPDATE clues SET text = 'American Thanksgiving tables carry it beside the pumpkin one, and the filling is corn syrup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pecan-pie') AND order_index = 3;
UPDATE clues SET text = 'Southern cooks bristle when holiday guests mistake it for the pumpkin one.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-potato-pie') AND order_index = 3;
UPDATE clues SET text = 'Hawaii built it at a lunch counter for teenagers who wanted something cheap and enormous.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 3;
UPDATE clues SET text = 'The whole country jokes that it cures a hangover, and the plate has no fixed contents.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'full-english-breakfast') AND order_index = 3;
UPDATE clues SET text = 'Bake the same sausages into batter and you get a different pub dish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bangers-and-mash') AND order_index = 3;
UPDATE clues SET text = 'British baking competitions judge it first, looking for a light and even crumb.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'victoria-sponge-cake') AND order_index = 3;
UPDATE clues SET text = 'The offal in it splits a pub crowd faster than any other filling.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'steak-and-kidney-pie') AND order_index = 3;
UPDATE clues SET text = 'German beer festivals sell it by the mile, split down the middle in a hard roll.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bratwurst') AND order_index = 3;
UPDATE clues SET text = 'German law protects the name, so a version without the cherry brandy cannot use it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'black-forest-cake') AND order_index = 3;
UPDATE clues SET text = 'Bars serve it at room temperature in wedges, and the argument is whether onion belongs.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tortilla-espanola') AND order_index = 3;
UPDATE clues SET text = 'French children buy it on the way to school, and the south of the country calls it something else.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 3;
UPDATE clues SET text = 'The garlic gets rubbed on the hot toast, not chopped into anything.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bruschetta') AND order_index = 3;
UPDATE clues SET text = 'Its red, white and green lay out the Italian flag on the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caprese-salad') AND order_index = 3;
UPDATE clues SET text = 'A frilly toothpick holds it together, and the third slice of bread is the point.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'club-sandwich') AND order_index = 3;
UPDATE clues SET text = 'The acid in the soured milk hits the soda and makes the whole stack rise.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buttermilk-pancakes') AND order_index = 3;
UPDATE clues SET text = 'Cooks made it to rescue yesterday''s loaf, which is why one country calls it lost bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-toast') AND order_index = 3;
UPDATE clues SET text = 'A hungover Wall Street broker ordering breakfast in 1894 gets the credit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eggs-benedict') AND order_index = 3;
UPDATE clues SET text = 'Fairgrounds sell it on a wooden stick so you can eat it walking the midway.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'corn-dog') AND order_index = 3;
UPDATE clues SET text = 'The pastry lid is the whole trick, holding the steam in until you break it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-pot-pie') AND order_index = 3;
UPDATE clues SET text = 'Grandmothers serve it for a cold, and a 1978 study found the steam really does help.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-noodle-soup') AND order_index = 3;
UPDATE clues SET text = 'The sugar coat goes on while it is still hot, so it sets to a shell as it cools.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'glazed-donut') AND order_index = 3;
UPDATE clues SET text = 'Italy does not have it, and Italian-Americans built it out of a cutlet and red sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-parmesan') AND order_index = 3;
UPDATE clues SET text = 'There is no fixed recipe, only whatever the garden gave up that week.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'minestrone') AND order_index = 3;
UPDATE clues SET text = 'Stale tortillas become this the morning after, softened but never soggy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chilaquiles') AND order_index = 3;
UPDATE clues SET text = 'You turn it out of the mould and the caramel runs down it as a pool.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flan') AND order_index = 3;
UPDATE clues SET text = 'Yesterday''s cold leftovers work better than fresh, because dry grains stay separate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 3;
UPDATE clues SET text = 'The bright orange takeout version is a long way from the Cantonese original.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-and-sour-pork') AND order_index = 3;
UPDATE clues SET text = 'The wrappers are rolled so thin the filling shows grey through them.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wonton-soup') AND order_index = 3;
UPDATE clues SET text = 'White pepper brings the heat and black vinegar the sharpness, not chili.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-and-sour-soup') AND order_index = 3;
UPDATE clues SET text = 'Cooks never let the paste boil, and the bowl arrives before the meal rather than with it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'miso-soup') AND order_index = 3;
UPDATE clues SET text = 'It cooks stuck to the wall of a clay oven and peels off when it puffs.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'naan') AND order_index = 3;
UPDATE clues SET text = 'Mughal court kitchens built it, and diners order it to dodge the heat entirely.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-korma') AND order_index = 3;
UPDATE clues SET text = 'Open the oven too soon and it falls, which has made it a sitcom disaster for sixty years.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 3;
UPDATE clues SET text = 'The Maghreb eats it as the Friday family meal, and half of Europe keeps the instant box.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 3;
UPDATE clues SET text = 'It went viral on TikTok, where the running joke is that newcomers keep chewing instead of swallowing.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 3;
UPDATE clues SET text = 'Refusing a glass is a real insult, three rounds are traditional, and the host pours from high up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moroccan-mint-tea') AND order_index = 3;
UPDATE clues SET text = 'Highway truck stops serve it all day with a slab of white butter melting on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-paratha') AND order_index = 3;
UPDATE clues SET text = 'The vendor hands them over one at a time, and each must go in whole before it collapses.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pani-puri') AND order_index = 3;
UPDATE clues SET text = 'British curry houses made the name mean heat, but the original is about sourness.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vindaloo') AND order_index = 3;
UPDATE clues SET text = 'No Indian wedding or Diwali box ends without a bowl of them, two to a serving, warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gulab-jamun') AND order_index = 3;
UPDATE clues SET text = 'People order it to put out the fire after an over-ambitious curry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-lassi') AND order_index = 3;
UPDATE clues SET text = 'Railway platform vendors call it out all night, in clay cups you smash when you''re done.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-chai') AND order_index = 3;
UPDATE clues SET text = 'Bend It Like Beckham gives it a running joke, and Britain treats it as the safe meatless order.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-gobi') AND order_index = 3;
UPDATE clues SET text = 'It comes out when somebody at the table has badly overestimated their tolerance for chili.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'raita') AND order_index = 3;
UPDATE clues SET text = 'The cheese softens over fire without melting, which is the only reason it stays on a skewer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paneer-tikka') AND order_index = 3;
UPDATE clues SET text = 'Indonesian carts sell it at all hours, and most people reach for it the morning after.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'soto-ayam') AND order_index = 3;
UPDATE clues SET text = 'The national airline serves it, and so does every 3am roadside stall.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-lemak') AND order_index = 3;
UPDATE clues SET text = 'Singapore''s tourism board leads with it, and you get a bib and a hammer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-crab') AND order_index = 3;
UPDATE clues SET text = 'Its name means mix-mix, which is also the instruction before you eat it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'halo-halo') AND order_index = 3;
UPDATE clues SET text = 'Western menus give them a second name to keep them apart from the fried kind.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fresh-spring-rolls') AND order_index = 3;
UPDATE clues SET text = 'Diners order it second at a Thai restaurant, after the tamarind noodles beside it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-see-ew') AND order_index = 3;
UPDATE clues SET text = 'Its traffic-cone orange comes from dye in the mix, and gives it away on any menu.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-iced-tea') AND order_index = 3;
UPDATE clues SET text = 'A Thai rapper''s 2022 song about it sent national sales through the roof.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-sticky-rice') AND order_index = 3;
UPDATE clues SET text = 'Menus list it right above the fiery sour prawn soup, and it is the milder one.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-kha-gai') AND order_index = 3;
UPDATE clues SET text = 'Convenience stores sell billions a year in a wrapper you pull apart so the seaweed stays crisp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onigiri') AND order_index = 3;
UPDATE clues SET text = 'K-dramas made the foil-wrapped rolls recognisable, and they travel to every school picnic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimbap') AND order_index = 3;
UPDATE clues SET text = 'Japanese news warns people every New Year not to choke on it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 3;
UPDATE clues SET text = 'It has its own emoji, and the straw is fat enough to pull the chewy pearls up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-tea') AND order_index = 3;
UPDATE clues SET text = 'Tokyo fish markets auction the top grades for staggering sums.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 3;
UPDATE clues SET text = 'American Chinese takeaway menus put it at the top beside the hot and sour bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egg-drop-soup') AND order_index = 3;
UPDATE clues SET text = 'It sits next to the chickpea dip on every mezze platter, and it is the smoky one.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baba-ganoush') AND order_index = 3;
UPDATE clues SET text = 'Swedish Christmas tables slice it paper-thin next to a sweet mustard and dill sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gravlax') AND order_index = 3;
UPDATE clues SET text = 'Street carts sell it whole, and you tip your head back and lower it in by the tail.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pickled-herring') AND order_index = 3;
UPDATE clues SET text = 'It became the emblem of 1950s hotel dining, the sophisticated cold soup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vichyssoise') AND order_index = 3;
UPDATE clues SET text = 'Audrey Hepburn eats one on the Spanish Steps in Roman Holiday.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 3;
UPDATE clues SET text = 'A Swiss clinic invented it for patients, and English took its name for dry cereal.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bircher-muesli') AND order_index = 3;
UPDATE clues SET text = 'A Highland village holds an annual world championship, and Goldilocks found three bowls.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'porridge') AND order_index = 3;
UPDATE clues SET text = 'American office platters and hotel buffets run on it, with fruit or cheese in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'danish-pastry') AND order_index = 3;
UPDATE clues SET text = 'Every American cookout puts it beside the grill, and northern Germany eats it on Christmas Eve.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 3;
UPDATE clues SET text = 'The holes exist to trap the butter, and British childhood ate them by the fire.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 3;
UPDATE clues SET text = 'Making a pale gold one with no browning is the classic interview task for a new cook.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'omelette') AND order_index = 3;
UPDATE clues SET text = 'Las Vegas casinos sold one for 99 cents for decades to keep gamblers in the building.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-cocktail') AND order_index = 3;
UPDATE clues SET text = 'San Francisco''s Fisherman''s Wharf leads with it, and it anchors Christmas Eve there.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cioppino') AND order_index = 3;
UPDATE clues SET text = 'It has its own specially dimpled carrying plate, which is a potluck institution.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 3;
UPDATE clues SET text = 'Gas stations across the American West sell it, and it is the road-trip morning order.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'breakfast-burrito') AND order_index = 3;
UPDATE clues SET text = 'It comes in the little paper cup, and half of America pile it straight into the sandwich.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coleslaw') AND order_index = 3;
UPDATE clues SET text = 'The word became shorthand for a hippie aesthetic, and still means crunchy and outdoorsy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'granola') AND order_index = 3;
UPDATE clues SET text = 'No such thing exists anywhere in China, and American takeaway menus lead with it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-rangoon') AND order_index = 3;
UPDATE clues SET text = 'The smell of it in an office microwave is a well-worn grievance.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tuna-salad-sandwich') AND order_index = 3;
UPDATE clues SET text = 'On a British menu that second word means something breaded and entirely different.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-scampi') AND order_index = 3;
UPDATE clues SET text = 'American diners ask whether you want them scattered, smothered and covered.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 3;
UPDATE clues SET text = 'The island eats it Sunday morning with fried dumplings and boiled green bananas.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ackee-and-saltfish') AND order_index = 3;
UPDATE clues SET text = 'It sits in a plastic barrel next to the hibiscus one at every taqueria.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'horchata') AND order_index = 3;
UPDATE clues SET text = 'The chunky fresh one in a bowl, not the smooth blended sauce out of a jar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 3;
UPDATE clues SET text = 'El Salvador gives them a national day on the second Sunday of November.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pupusas') AND order_index = 3;
UPDATE clues SET text = 'In 2017 an Australian millionaire blamed it for young people not buying houses.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'avocado-toast') AND order_index = 3;
UPDATE clues SET text = 'Men at Work sang about a sandwich made with it, and foreigners always spread it too thick.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vegemite-toast') AND order_index = 3;
UPDATE clues SET text = 'No Australian kid''s birthday is properly catered without a platter of it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 3;
UPDATE clues SET text = 'That newspaper printing sent baking-bar sales up several hundred percent.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 3;
UPDATE clues SET text = 'The smell of a carnival midway in July, sold from a trailer window.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'funnel-cake') AND order_index = 3;
UPDATE clues SET text = 'Chefs use it as the trial task for a new line cook, because it exposes everything.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scrambled-eggs') AND order_index = 3;
UPDATE clues SET text = 'Tampa insists on a layer of Genoa salami, and Miami calls that heresy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cubano') AND order_index = 3;
UPDATE clues SET text = 'Convenience stores sell them by the million, and wagyu versions cost as much as a steak dinner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'katsu-sando') AND order_index = 3;
UPDATE clues SET text = 'Ordering it marks you as a regular, because only the serious counters keep it on.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patty-melt') AND order_index = 3;
UPDATE clues SET text = 'It starts an argument about sauce: vinegar east, mustard in South Carolina, sweet tomato west.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pulled-pork-sandwich') AND order_index = 3;
UPDATE clues SET text = 'Every Greek taverna keeps a tray in the cold case, and the tinned kind travelled first.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 3;
UPDATE clues SET text = 'Athens has shops that have sold nothing else since the 1920s, in paper cones.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 3;
UPDATE clues SET text = 'Children decorate them at Christmas and leave a plate out for the visitor down the chimney.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sugar-cookies') AND order_index = 3;
UPDATE clues SET text = 'The name gets it picked off the bake-sale table first, on nothing but sound.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 3;
UPDATE clues SET text = 'The internet''s favorite cruel prank, looking exactly like something else until you bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal-raisin-cookies') AND order_index = 3;
UPDATE clues SET text = 'The bowl is empty at a Super Bowl party before the first quarter ends.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 3;
UPDATE clues SET text = 'One chain''s version is among the most searched copycat recipes online.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 3;
UPDATE clues SET text = 'Rajasthani weddings serve it on a leaf plate with clarified butter poured over.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-baati') AND order_index = 3;
UPDATE clues SET text = 'Families made hundreds at a time and left them outside to freeze in the snow.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 3;
UPDATE clues SET text = 'People argue it is not really a doughnut, and it is the biggest thing on the tray.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 3;
UPDATE clues SET text = 'Bakery lines run down the block in Italian-American neighborhoods every March.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 3;
UPDATE clues SET text = 'McDonald''s put one on the breakfast menu in the 1990s, and airports followed.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 3;
UPDATE clues SET text = 'A man in a wide-brimmed Quaker hat has smiled off that canister for a century.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 3;
UPDATE clues SET text = 'The box has carried a smiling chef in a white toque for over a century.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 3;
UPDATE clues SET text = 'Italian-American households make it out of whatever the night before left in the pan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 3;
UPDATE clues SET text = 'Mall bakeries pipe the oven smell into the corridor on purpose, to turn you around mid-concourse.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 3;
UPDATE clues SET text = 'Genoa eats it for breakfast dunked in coffee, which visitors find hard to believe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 3;
UPDATE clues SET text = 'Some cities ban it outright, and French law protects it as national culinary heritage.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 3;
UPDATE clues SET text = 'A British council renamed it on the canteen menu in 2009 and had to change it back.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spotted-dick') AND order_index = 3;
UPDATE clues SET text = 'Dublin argues only about whether the sausages may be browned first, and traditionally they may not.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coddle') AND order_index = 3;
UPDATE clues SET text = 'Anthony Bourdain called it the dish most likely to win the world over, and it arrives spitting.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 3;
UPDATE clues SET text = 'A slice and a cup of damn fine coffee is the standing order of an FBI agent in Twin Peaks.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 3;
UPDATE clues SET text = 'The spice blend invented for it now flavours a coffee chain''s autumn latte.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pumpkin-pie') AND order_index = 3;
UPDATE clues SET text = 'Church bake sales judge it on how high the peaks stand and whether they wept overnight.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 3;
UPDATE clues SET text = 'Cooks boil the unopened tin for hours, and the makers print a warning because the tins can burst.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banoffee-pie') AND order_index = 3;
UPDATE clues SET text = 'Every gastropub trying to prove it takes the classics seriously puts it on.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 3;
