-- Backfill: clue rewrites against the beat sheet (CLUES.md).
-- 252 clues across 252 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'Italy''s glossy Roman pasta, slicked yellow and speckled black with pepper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-carbonara') AND order_index = 5;
UPDATE clues SET text = 'Italy''s blistered wood-fired round, red and white under torn green leaves.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'margherita-pizza') AND order_index = 5;
UPDATE clues SET text = 'Italy''s baked slab, served in squares that hold their shape on the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lasagna') AND order_index = 5;
UPDATE clues SET text = 'Italy''s deep-gold saffron rice, loose enough to spread slowly across the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'risotto-alla-milanese') AND order_index = 5;
UPDATE clues SET text = 'The French summer vegetable stew, glossy with oil and no meat in sight.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ratatouille') AND order_index = 5;
UPDATE clues SET text = 'France''s dark broth under a raft of bread and a blistered cheese lid.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-onion-soup') AND order_index = 5;
UPDATE clues SET text = 'The French custard under a glass sheet of caramel you crack with a spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'creme-brulee') AND order_index = 5;
UPDATE clues SET text = 'The French wine braise, meat falling off the bone into a dark purple sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coq-au-vin') AND order_index = 5;
UPDATE clues SET text = 'Spain''s cold red soup, poured from a jug and drunk as much as eaten.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gazpacho') AND order_index = 5;
UPDATE clues SET text = 'Spain''s long ridged sticks, sugared and stood upright in a cup of chocolate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'churros') AND order_index = 5;
UPDATE clues SET text = 'Britain''s browned potato roof over a dish of dark minced meat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shepherds-pie') AND order_index = 5;
UPDATE clues SET text = 'Britain''s orange curry-house standard, thick and mild in a small steel dish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-tikka-masala') AND order_index = 5;
UPDATE clues SET text = 'The Greek tray of aubergine under a pale set custard, cut into squares.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moussaka') AND order_index = 5;
UPDATE clues SET text = 'Austria''s pale golden cutlet, wider than the plate and thin as card.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wiener-schnitzel') AND order_index = 5;
UPDATE clues SET text = 'Germany''s paper tray of chopped sausage under red sauce and curry powder.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'currywurst') AND order_index = 5;
UPDATE clues SET text = 'Hungary''s deep red bowl, somewhere between a soup and a stew.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'goulash') AND order_index = 5;
UPDATE clues SET text = 'Ukraine''s shocking magenta bowl, swirled pink where the sour cream goes in.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'borscht') AND order_index = 5;
UPDATE clues SET text = 'Sweden''s browned rounds in pale cream sauce, with lingonberry jam beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'swedish-meatballs') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s diamond-cut pastry, glassy with syrup and green with pistachio.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baklava') AND order_index = 5;
UPDATE clues SET text = 'The beige Lebanese dip you scoop with warm pita.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hummus') AND order_index = 5;
UPDATE clues SET text = 'Egypt''s green-centred fritters, stuffed into pita under a drizzle of tahini.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'falafel') AND order_index = 5;
UPDATE clues SET text = 'Tunisia''s skillet of eggs in red sauce, mopped up with torn bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shakshuka') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s shaved meat in flatbread, wrapped tight in paper to hold it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'doner-kebab') AND order_index = 5;
UPDATE clues SET text = 'Nigeria''s orange-red one-pot, argued over by every neighbouring country.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jollof-rice') AND order_index = 5;
UPDATE clues SET text = 'The South African mince bake under a set egg custard, bay leaf on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bobotie') AND order_index = 5;
UPDATE clues SET text = 'India''s orange gateway curry, thick and silky in a small steel bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'butter-chicken') AND order_index = 5;
UPDATE clues SET text = 'India''s layered rice, saffron-streaked and steaming when the lid comes off.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-biryani') AND order_index = 5;
UPDATE clues SET text = 'The Indian fried triangle, dipped in tamarind and mint chutney.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'samosa') AND order_index = 5;
UPDATE clues SET text = 'Japan''s noodle bowl, cloudy broth under a halved jammy egg.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ramen') AND order_index = 5;
UPDATE clues SET text = 'China''s lacquered mahogany skin, carved at the table into thin pancakes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peking-duck') AND order_index = 5;
UPDATE clues SET text = 'China''s dark stir-fry, glossy with peanuts and whole dried chilies.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kung-pao-chicken') AND order_index = 5;
UPDATE clues SET text = 'China''s fiery red-oil bowl, the white cubes barely holding together.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mapo-tofu') AND order_index = 5;
UPDATE clues SET text = 'Vietnam''s clear beef broth under a pile of raw herbs and bean sprouts.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pho') AND order_index = 5;
UPDATE clues SET text = 'America''s beef patty in a bun, and this diner''s best seller.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hamburger') AND order_index = 5;
UPDATE clues SET text = 'America''s baked orange pasta, crusted brown across the top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mac-and-cheese') AND order_index = 5;
UPDATE clues SET text = 'The American South''s craggy golden bird, served with biscuits and gravy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'southern-fried-chicken') AND order_index = 5;
UPDATE clues SET text = 'America''s thick white shellfish soup, sometimes poured into a hollowed loaf.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-england-clam-chowder') AND order_index = 5;
UPDATE clues SET text = 'America''s long boat of ice cream over a fruit halved lengthwise.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banana-split') AND order_index = 5;
UPDATE clues SET text = 'America''s sliced brown loaf, mashed potato beside it and a red glaze on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'meatloaf') AND order_index = 5;
UPDATE clues SET text = 'America''s dark New Orleans stew, ladled over a scoop of white rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gumbo') AND order_index = 5;
UPDATE clues SET text = 'Canada''s late-night plate, where the fries go soft and the curds squeak.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'poutine') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s spit-shaved pork on small tortillas, with a sliver of pineapple.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s green mash, served in a stone bowl with chips to break in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'guacamole') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s near-black sauce poured over chicken, with sesame scattered on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mole-poblano') AND order_index = 5;
UPDATE clues SET text = 'Peru''s white fish gone opaque in lime, with corn and sweet potato beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ceviche') AND order_index = 5;
UPDATE clues SET text = 'New Zealand''s meringue shell, cracked open under cream and green fruit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pavlova') AND order_index = 5;
UPDATE clues SET text = 'China''s pleated soup dumpling, hot enough to burn if you rush it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'xiaolongbao') AND order_index = 5;
UPDATE clues SET text = 'China''s red-edged glossy pork, sliced and fanned out over rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'char-siu') AND order_index = 5;
UPDATE clues SET text = 'China''s chili-oil bowl, the sauce pooling red at the bottom until you toss it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dan-dan-noodles') AND order_index = 5;
UPDATE clues SET text = 'Japan''s golf-ball spheres under waving bonito flakes, too hot to bite whole.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'takoyaki') AND order_index = 5;
UPDATE clues SET text = 'India''s near-black lentils, thick and velvet with a swirl of cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-makhani') AND order_index = 5;
UPDATE clues SET text = 'India''s brick-red Kashmiri lamb, the gravy clinging to the spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rogan-josh') AND order_index = 5;
UPDATE clues SET text = 'India''s orange mash on a griddle, with buttered buns to push it around.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pav-bhaji') AND order_index = 5;
UPDATE clues SET text = 'Indonesia''s charred skewers under a thick brown peanut sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'satay') AND order_index = 5;
UPDATE clues SET text = 'The Filipino braise gone pale with coconut milk, sharp underneath with vinegar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'adobo-sa-gata') AND order_index = 5;
UPDATE clues SET text = 'The French Burgundy braise, purple-brown and falling apart at a fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-bourguignon') AND order_index = 5;
UPDATE clues SET text = 'France''s deep egg tart, set pale gold and studded dark with bacon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quiche-lorraine') AND order_index = 5;
UPDATE clues SET text = 'France''s Marseille fish pot, orange with saffron and served with rouille.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bouillabaisse') AND order_index = 5;
UPDATE clues SET text = 'Portugal''s small custard cup, its top blistered black in patches.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pastel-de-nata') AND order_index = 5;
UPDATE clues SET text = 'Italy''s braised veal shank, the marrow still sitting in the bone.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ossobuco') AND order_index = 5;
UPDATE clues SET text = 'Italy''s fried rice ball, breadcrumbed orange and molten in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arancini') AND order_index = 5;
UPDATE clues SET text = 'Italy''s white dome, wobbling whenever the plate moves.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'panna-cotta') AND order_index = 5;
UPDATE clues SET text = 'America''s Louisiana rice pot, brown and studded through with sausage.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jambalaya') AND order_index = 5;
UPDATE clues SET text = 'America''s orange-slicked bar snack, with celery and blue cheese beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-wings') AND order_index = 5;
UPDATE clues SET text = 'America''s pale yellow Florida custard under a drift of meringue or cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'key-lime-pie') AND order_index = 5;
UPDATE clues SET text = 'America''s steaming pile of shellfish and corn tipped straight onto paper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'clam-bake') AND order_index = 5;
UPDATE clues SET text = 'America''s thick Texan bowl, dark red and eaten with a spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-con-carne') AND order_index = 5;
UPDATE clues SET text = 'America''s neat parallel rows of chopped things on a long white plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cobb-salad') AND order_index = 5;
UPDATE clues SET text = 'America''s grilled rye stack, dressing running out at the sides.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'reuben-sandwich') AND order_index = 5;
UPDATE clues SET text = 'Canada''s small gooey pastry, its filling still runny when you bite it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'butter-tart') AND order_index = 5;
UPDATE clues SET text = 'Canada''s Quebec Christmas bake, pale pastry over spiced ground pork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tourtiere') AND order_index = 5;
UPDATE clues SET text = 'Canada''s three-layer square, chocolate over yellow over crumb.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nanaimo-bar') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s battered green chili, the cheese pulling when you cut it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chiles-rellenos') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s raw shrimp in a green pool, cucumber sliced thin on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aguachile') AND order_index = 5;
UPDATE clues SET text = 'Colombia''s yellow rice pot, with the chicken buried down in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arroz-con-pollo') AND order_index = 5;
UPDATE clues SET text = 'Nigeria''s thick green stew, grainy with ground melon seed.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egusi-soup') AND order_index = 5;
UPDATE clues SET text = 'South Africa''s curry served inside a hollowed-out quarter loaf, eaten by hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bunny-chow') AND order_index = 5;
UPDATE clues SET text = 'The Lebanese wrap of shaved meat, pickles bright pink inside it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shawarma') AND order_index = 5;
UPDATE clues SET text = 'Syria''s brick-red dip, sweet and rough with crushed walnut.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'muhammara') AND order_index = 5;
UPDATE clues SET text = 'Iran''s dark brown stew, sour and thick from ground walnut.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khoresh-fesenjan') AND order_index = 5;
UPDATE clues SET text = 'Palestine''s orange shredded pastry over hot cheese that pulls when you lift it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baklava-cheesecake-knafeh') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s charred skewers of spiced lamb, straight off the grill.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kofta') AND order_index = 5;
UPDATE clues SET text = 'America''s Hawaiian dish of raw cubes over rice, glossy with soy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'poke-bowl') AND order_index = 5;
UPDATE clues SET text = 'The Czech hollow sugar tube, sold hot off the spit at a market stall.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'trdelnik') AND order_index = 5;
UPDATE clues SET text = 'Britain''s puffed hollow batter cup, waiting for gravy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yorkshire-pudding') AND order_index = 5;
UPDATE clues SET text = 'Britain''s crimped pastry parcel, made to be held by the thick edge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cornish-pasty') AND order_index = 5;
UPDATE clues SET text = 'France''s shells set in a dimpled dish, green butter bubbling in each.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'escargot') AND order_index = 5;
UPDATE clues SET text = 'Italy''s dimpled oiled flatbread, with salt crystals in every hollow.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'osso-focaccia') AND order_index = 5;
UPDATE clues SET text = 'Italy''s paper-thin cheese sheet, blistered brown and cut into wedges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia-di-recco') AND order_index = 5;
UPDATE clues SET text = 'America''s Philadelphia roll, dripping and folded up in foil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'philly-cheesesteak') AND order_index = 5;
UPDATE clues SET text = 'America''s deep-panned slice, standing two inches tall on the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicago-deep-dish-pizza') AND order_index = 5;
UPDATE clues SET text = 'America''s chewy boiled ring, orange fish draped over a white smear.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-york-bagel-with-lox') AND order_index = 5;
UPDATE clues SET text = 'America''s dark-crusted smoked slab, sliced against the grain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'texas-beef-brisket') AND order_index = 5;
UPDATE clues SET text = 'The American South''s pale creamy bowl under pink shellfish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-and-grits') AND order_index = 5;
UPDATE clues SET text = 'America''s split toasted bun overflowing with cold shellfish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lobster-roll') AND order_index = 5;
UPDATE clues SET text = 'America''s red shellfish soup, the one with no cream in it at all.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manhattan-clam-chowder') AND order_index = 5;
UPDATE clues SET text = 'America''s Cajun stew, dark brown and smothered over white rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crawfish-etouffee') AND order_index = 5;
UPDATE clues SET text = 'America''s fried bird under a red crust that stains the paper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nashville-hot-chicken') AND order_index = 5;
UPDATE clues SET text = 'America''s sticky glazed bones, dark red and pulling clean away.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kansas-city-bbq-ribs') AND order_index = 5;
UPDATE clues SET text = 'America''s cinnamon-scented sauce buried under shredded cheese.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cincinnati-chili') AND order_index = 5;
UPDATE clues SET text = 'America''s loaded sausage in a poppy-seed bun, and never with ketchup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicago-hot-dog') AND order_index = 5;
UPDATE clues SET text = 'America''s New Orleans sandwich on crackling French bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'po-boy') AND order_index = 5;
UPDATE clues SET text = 'America''s New Orleans squares under a snowdrift of powdered sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beignets') AND order_index = 5;
UPDATE clues SET text = 'The American South''s orange-flecked spread on soft white slices.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pimento-cheese-sandwich') AND order_index = 5;
UPDATE clues SET text = 'America''s soul-food plate, syrup running off the crisp onto the grid.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-and-waffles') AND order_index = 5;
UPDATE clues SET text = 'The American South''s golden fried balls, served beside the fryer''s main event.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hush-puppies') AND order_index = 5;
UPDATE clues SET text = 'America''s Hawaiian plate lunch, with brown gravy over everything.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 5;
UPDATE clues SET text = 'America''s border plate, arriving at the table still sizzling and steaming.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tex-mex-fajitas') AND order_index = 5;
UPDATE clues SET text = 'America''s Southwest snack, chili poured straight into the chip bag.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frito-pie') AND order_index = 5;
UPDATE clues SET text = 'America''s Chesapeake patty, lump meat barely held together.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'maryland-crab-cakes') AND order_index = 5;
UPDATE clues SET text = 'Italy''s Roman pasta, grey-flecked and creamy with no cream at all.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cacio-e-pepe') AND order_index = 5;
UPDATE clues SET text = 'America''s golden griddled sandwich, pulling apart into strings.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'grilled-cheese') AND order_index = 5;
UPDATE clues SET text = 'America''s toasted triple-decker, quartered and pinned with picks.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'club-sandwich') AND order_index = 5;
UPDATE clues SET text = 'America''s toasted three-letter order, red and green through the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'blt') AND order_index = 5;
UPDATE clues SET text = 'America''s fluffy stack, butter sliding down it under maple syrup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buttermilk-pancakes') AND order_index = 5;
UPDATE clues SET text = 'France''s custard-soaked slices, fried golden and dusted with sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-toast') AND order_index = 5;
UPDATE clues SET text = 'America''s brunch plate, yellow sauce spilling over a poached yolk.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eggs-benedict') AND order_index = 5;
UPDATE clues SET text = 'America''s battered sausage on a stick, mustard zigzagged down it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'corn-dog') AND order_index = 5;
UPDATE clues SET text = 'America''s saucy bun, guaranteed to end up on the plate and your hands.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sloppy-joe') AND order_index = 5;
UPDATE clues SET text = 'America''s golden pastry lid over a filling that steams when broken.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-pot-pie') AND order_index = 5;
UPDATE clues SET text = 'America''s get-well bowl, steam coming off a clear gold surface.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-noodle-soup') AND order_index = 5;
UPDATE clues SET text = 'America''s dense white wedge, cracked across the top and standing tall.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-york-cheesecake') AND order_index = 5;
UPDATE clues SET text = 'America''s dark squares, fudgy in the middle and papery on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'brownies') AND order_index = 5;
UPDATE clues SET text = 'America''s round bake, the dark chips still soft if you get one warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chocolate-chip-cookies') AND order_index = 5;
UPDATE clues SET text = 'America''s shiny ring, its coat cracking slightly as you bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'glazed-donut') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s border-invented leaves, heavy with anchovy and cracked pepper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caesar-salad') AND order_index = 5;
UPDATE clues SET text = 'America''s red-sauced cutlet under a molten white blanket.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-parmesan') AND order_index = 5;
UPDATE clues SET text = 'Italy''s pale ribbons, coated glossy with nothing but fat and cheese.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fettuccine-alfredo') AND order_index = 5;
UPDATE clues SET text = 'America''s red plate, the rolled beef sitting on top of the strands.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-and-meatballs') AND order_index = 5;
UPDATE clues SET text = 'Italy''s little sealed pillows, floating in sauce with crimped edges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ravioli') AND order_index = 5;
UPDATE clues SET text = 'Italy''s sealed half-moon, steaming when you cut into the fold.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'calzone') AND order_index = 5;
UPDATE clues SET text = 'Italy''s crisp tube, with cream piped in at both ends.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cannoli') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s tight foil-wrapped log, heavy in one hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'burrito') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s browned folded round, cut into wedges that pull apart.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quesadilla') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s loaded pile, the chips underneath already going soft.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nachos') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s Baja pair, white crema running out at the ends.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-tacos') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s ranch breakfast, yolks running down into black beans under red salsa.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'huevos-rancheros') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s softened chips, gone half to pieces under crema and cheese.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chilaquiles') AND order_index = 5;
UPDATE clues SET text = 'Spain''s pale dome, sitting in the caramel that ran off it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flan') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s soaked sponge, so wet that it pools on the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tres-leches-cake') AND order_index = 5;
UPDATE clues SET text = 'China''s wok-tossed grains, glossy and flecked yellow with egg.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 5;
UPDATE clues SET text = 'China''s tangled fried noodles, browned where they hit the wok.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chow-mein') AND order_index = 5;
UPDATE clues SET text = 'China''s neon-orange takeaway bowl, pineapple bright in among it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-and-sour-pork') AND order_index = 5;
UPDATE clues SET text = 'America''s takeaway favourite, dark glossy sauce over crisp batter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'general-tsos-chicken') AND order_index = 5;
UPDATE clues SET text = 'China''s clear bowl with pale parcels drifting about in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wonton-soup') AND order_index = 5;
UPDATE clues SET text = 'China''s thick dark bowl that catches you at the back of the throat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-and-sour-soup') AND order_index = 5;
UPDATE clues SET text = 'Japan''s lacy pale coating, so light you can see the shrimp through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tempura') AND order_index = 5;
UPDATE clues SET text = 'Japan''s glossy brown glaze over grilled meat, sticky to the fingers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'teriyaki-chicken') AND order_index = 5;
UPDATE clues SET text = 'Japan''s fat white noodles, thick enough to feel between your teeth.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'udon') AND order_index = 5;
UPDATE clues SET text = 'Japan''s cloudy bowl, the sediment settling if you leave it standing.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'miso-soup') AND order_index = 5;
UPDATE clues SET text = 'Japan''s crescent dumplings, one flat side browned lace-crisp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyoza') AND order_index = 5;
UPDATE clues SET text = 'Korea''s thin grilled beef, glossy dark and cooked at the table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bulgogi') AND order_index = 5;
UPDATE clues SET text = 'India''s blistered teardrop, torn to push food around the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'naan') AND order_index = 5;
UPDATE clues SET text = 'India''s pale beige curry, mild and thick with ground nut.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-korma') AND order_index = 5;
UPDATE clues SET text = 'Greece''s tumbled tomato and cucumber under a whole white slab.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'greek-salad') AND order_index = 5;
UPDATE clues SET text = 'Greece''s paper cone of shaved meat, sauce leaking at the bottom.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyro') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s pale coconut bowl, oil beading across the surface.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 5;
UPDATE clues SET text = 'France''s long glazed finger, cream squeezing out when you bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eclair') AND order_index = 5;
UPDATE clues SET text = 'France''s flaky crescent, shattering into shards on the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'croissant') AND order_index = 5;
UPDATE clues SET text = 'Belgium''s deep-pocketed squares under a drift of powdered sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'belgian-waffles') AND order_index = 5;
UPDATE clues SET text = 'France''s tall wobbling puff, sinking the moment it leaves the oven.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 5;
UPDATE clues SET text = 'Morocco''s mound of tiny steamed pellets, piled under a spiced stew.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 5;
UPDATE clues SET text = 'Ghana''s smooth white ball, torn with the fingers and swallowed, not chewed.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 5;
UPDATE clues SET text = 'Morocco''s sweet green glass, foam on top from the height of the pour.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moroccan-mint-tea') AND order_index = 5;
UPDATE clues SET text = 'India''s stuffed flatbread, a slab of white butter melting on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-paratha') AND order_index = 5;
UPDATE clues SET text = 'India''s crisp hollow spheres, cracked and dunked, eaten whole in one go.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pani-puri') AND order_index = 5;
UPDATE clues SET text = 'India''s dark Goan curry, sour and hot at the same moment.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vindaloo') AND order_index = 5;
UPDATE clues SET text = 'India''s warm brown spheres, syrup running out when you press one.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gulab-jamun') AND order_index = 5;
UPDATE clues SET text = 'India''s dense frozen block on a stick, slower to melt than ice cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kulfi') AND order_index = 5;
UPDATE clues SET text = 'India''s thick orange glass, cold enough to fog the outside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-lassi') AND order_index = 5;
UPDATE clues SET text = 'India''s small glass of milky brown, drunk scalding on a platform.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-chai') AND order_index = 5;
UPDATE clues SET text = 'India''s craggy fried tangle, falling apart into loose strands.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onion-bhaji') AND order_index = 5;
UPDATE clues SET text = 'India''s cold white side, pale green with grated cucumber.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'raita') AND order_index = 5;
UPDATE clues SET text = 'India''s charred skewers of firm white cheese, blistered orange at the edges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paneer-tikka') AND order_index = 5;
UPDATE clues SET text = 'Indonesia''s golden bowl, yellow from turmeric and topped with fried shallots.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'soto-ayam') AND order_index = 5;
UPDATE clues SET text = 'Malaysia''s banana-leaf parcel, opened out into a plate of small piles.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-lemak') AND order_index = 5;
UPDATE clues SET text = 'Singapore''s messy red platter, eaten with your hands and a pile of napkins.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-crab') AND order_index = 5;
UPDATE clues SET text = 'The Filipino tall glass, stirred until every colour muddies together.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'halo-halo') AND order_index = 5;
UPDATE clues SET text = 'Vietnam''s translucent cold wraps, pink shrimp showing through the skin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fresh-spring-rolls') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s wide charred noodles, smoky and dark out of the wok.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-see-ew') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s bright orange glass, a white layer settling down through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-iced-tea') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s warm sweet grains beside cool yellow slices, cream poured over.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-sticky-rice') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s pale creamy bowl, sour and fragrant rather than fiery.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-kha-gai') AND order_index = 5;
UPDATE clues SET text = 'Japan''s cold rice triangle, the seaweed still crisp when you unwrap it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onigiri') AND order_index = 5;
UPDATE clues SET text = 'Japan''s soft chewy round, dusted white and yielding under the teeth.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 5;
UPDATE clues SET text = 'Taiwan''s sealed plastic cup, black pearls settled at the bottom.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-tea') AND order_index = 5;
UPDATE clues SET text = 'Japan''s cold sliced fish, with no rice anywhere near it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 5;
UPDATE clues SET text = 'China''s thin silky broth, pale ribbons suspended all through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egg-drop-soup') AND order_index = 5;
UPDATE clues SET text = 'The Lebanese smoky grey dip, pooled with oil in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baba-ganoush') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s soft rose cubes, buried in icing sugar in a wooden box.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'turkish-delight') AND order_index = 5;
UPDATE clues SET text = 'Sweden''s cured salmon, sliced thin enough to see the plate through.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gravlax') AND order_index = 5;
UPDATE clues SET text = 'The Dutch street-cart fish, eaten head tilted back with raw onion.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pickled-herring') AND order_index = 5;
UPDATE clues SET text = 'France''s cold pale soup with chives snipped over a chilled bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vichyssoise') AND order_index = 5;
UPDATE clues SET text = 'Italy''s dense frozen scoop, scraped up flat with a paddle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 5;
UPDATE clues SET text = 'The Swiss soaked breakfast bowl, cold and grainy with grated apple.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bircher-muesli') AND order_index = 5;
UPDATE clues SET text = 'Scotland''s thick grey bowl, traditionally salted rather than sweetened.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'porridge') AND order_index = 5;
UPDATE clues SET text = 'Denmark''s flaky spiral with a dab of jam sitting in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'danish-pastry') AND order_index = 5;
UPDATE clues SET text = 'Britain''s layered glass bowl, spooned straight down through every layer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'trifle') AND order_index = 5;
UPDATE clues SET text = 'Germany''s cold picnic bowl, dressed heavy and left to sit a while.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 5;
UPDATE clues SET text = 'Britain''s spongy round, butter disappearing down into the holes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 5;
UPDATE clues SET text = 'France''s pale folded roll, still barely set in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'omelette') AND order_index = 5;
UPDATE clues SET text = 'America''s stemmed glass with shellfish hooked over the rim.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-cocktail') AND order_index = 5;
UPDATE clues SET text = 'America''s San Francisco seafood pot, shells piled above the broth.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cioppino') AND order_index = 5;
UPDATE clues SET text = 'America''s halved whites with piped yellow, dusted red on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 5;
UPDATE clues SET text = 'America''s foil-wrapped cylinder, eaten one-handed on the road.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'breakfast-burrito') AND order_index = 5;
UPDATE clues SET text = 'America''s cold cup that arrives beside the barbecue whether you asked or not.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coleslaw') AND order_index = 5;
UPDATE clues SET text = 'America''s cold hotel plate, apple and walnut on a lettuce leaf.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'waldorf-salad') AND order_index = 5;
UPDATE clues SET text = 'America''s baked golden clusters, loose in the bowl under cold milk.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'granola') AND order_index = 5;
UPDATE clues SET text = 'America''s fried wonton purse, cream cheese oozing out at the seam.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-rangoon') AND order_index = 5;
UPDATE clues SET text = 'America''s pale filling on soft white slices, cold from the deli case.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tuna-salad-sandwich') AND order_index = 5;
UPDATE clues SET text = 'America''s garlicky butter pool, with linguine tangled through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-scampi') AND order_index = 5;
UPDATE clues SET text = 'America''s crisp golden patty, served beside the eggs at the diner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 5;
UPDATE clues SET text = 'Jamaica''s yellow breakfast plate, the fruit falling apart like scrambled egg.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ackee-and-saltfish') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s milky white glass, cinnamon sinking to the bottom over ice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'horchata') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s chunky red relish, sitting raw in its own lime juice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 5;
UPDATE clues SET text = 'El Salvador''s thick griddled corn cake, cheese leaking out the split edge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pupusas') AND order_index = 5;
UPDATE clues SET text = 'Australia''s brunch slab, green mash spread thick over dark sourdough.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'avocado-toast') AND order_index = 5;
UPDATE clues SET text = 'Australia''s near-black smear, scraped so thin the butter shows through.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vegemite-toast') AND order_index = 5;
UPDATE clues SET text = 'Australia''s white triangles under a coat of tiny coloured beads.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 5;
UPDATE clues SET text = 'America''s layered bake, coconut and pecan frosting between but not around.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 5;
UPDATE clues SET text = 'America''s lacy fried tangle, snowed under at the county fair.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'funnel-cake') AND order_index = 5;
UPDATE clues SET text = 'America''s soft yellow curds, pulled off the heat before they look done.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scrambled-eggs') AND order_index = 5;
UPDATE clues SET text = 'Cuba''s flattened pressed sandwich, the crust crackling when you cut it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cubano') AND order_index = 5;
UPDATE clues SET text = 'Japan''s crustless white sandwich, eaten cold out of its wrapper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'katsu-sando') AND order_index = 5;
UPDATE clues SET text = 'America''s rye-bread hybrid, half burger and half grilled cheese.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patty-melt') AND order_index = 5;
UPDATE clues SET text = 'America''s lunchbox pair of spreads, one nutty and one fruity.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peanut-butter-and-jelly-sandwich') AND order_index = 5;
UPDATE clues SET text = 'America''s heaped soft bun, slaw piled on top of the shredded meat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pulled-pork-sandwich') AND order_index = 5;
UPDATE clues SET text = 'Greece''s little green cylinders, served cold with a wedge of lemon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 5;
UPDATE clues SET text = 'Greece''s golden puffs, sticky and eaten hot with a fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 5;
UPDATE clues SET text = 'America''s pale flat rounds, tasting mostly of butter and vanilla.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sugar-cookies') AND order_index = 5;
UPDATE clues SET text = 'America''s cracked-top cookie, rolled in cinnamon before it bakes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 5;
UPDATE clues SET text = 'America''s chewy brown disc, studded with rolled grain and dried fruit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal-raisin-cookies') AND order_index = 5;
UPDATE clues SET text = 'America''s bubbling orange bowl, scooped up with celery and chips.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 5;
UPDATE clues SET text = 'America''s hot green bowl, stringy with cheese and served bubbling.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 5;
UPDATE clues SET text = 'America''s cold striped glass dish, counted off from the bottom up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 5;
UPDATE clues SET text = 'Britain''s baked square of soaked stale loaf, served warm under sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bread-pudding') AND order_index = 5;
UPDATE clues SET text = 'Russia''s small boiled parcels, eaten by the bowlful with sour cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 5;
UPDATE clues SET text = 'America''s craggy glazed slab, the biggest thing on the doughnut tray.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 5;
UPDATE clues SET text = 'Italy''s fried ring, crowned with a single candied cherry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 5;
UPDATE clues SET text = 'America''s tall clear cup of stripes, eaten cold with a long spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 5;
UPDATE clues SET text = 'America''s plain hot bowl, brown sugar melting into the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 5;
UPDATE clues SET text = 'America''s pale silky porridge with no grain you can see in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 5;
UPDATE clues SET text = 'Italy''s thick open-faced egg cake, served in wedges warm or cold.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 5;
UPDATE clues SET text = 'America''s warm bakery spiral under a cap of cream cheese frosting.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 5;
UPDATE clues SET text = 'Italy''s thick dimpled flatbread, torn into squares off a tray.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 5;
UPDATE clues SET text = 'France''s pale rich terrine, sliced cold onto toast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 5;
UPDATE clues SET text = 'The Filipino sizzling plate, an egg stirred through it at the table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 5;
UPDATE clues SET text = 'America''s lattice-topped diner slice, warm under a melting scoop.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 5;
UPDATE clues SET text = 'America''s chilled orange custard tart under a swirl of whipped cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pumpkin-pie') AND order_index = 5;
UPDATE clues SET text = 'America''s towering dessert under a browned cloud of whipped white.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 5;
UPDATE clues SET text = 'Britain''s cold caramel-and-banana dessert under a thick drift of cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banoffee-pie') AND order_index = 5;
UPDATE clues SET text = 'Britain''s forked potato crust over a creamy parsley sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 5;
