-- Backfill: clue rewrites against the beat sheet (CLUES.md).
-- 172 clues across 125 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'Peru''s dark skewers, blackened at the tips and eaten off the stick.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'anticuchos') AND order_index = 5;
UPDATE clues SET text = 'English settlers brought the recipe, and the fruit itself traces back to Kazakhstan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-pie') AND order_index = 2;
UPDATE clues SET text = 'A fried ball from southern Europe, named for a small orange.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arancini') AND order_index = 1;
UPDATE clues SET text = 'You beat the potato smooth with butter and milk, grill the sausages, and pour dark onion gravy over both.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bangers-and-mash') AND order_index = 4;
UPDATE clues SET text = 'Britain''s pub plate, two fat sausages leaning on a white mound with gravy running off it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bangers-and-mash') AND order_index = 5;
UPDATE clues SET text = 'Depression-era farm families stretched pork drippings and flour into a filling morning sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 2;
UPDATE clues SET text = 'You split buttery baked rounds and ladle over a peppery, sausage-flecked white sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 4;
UPDATE clues SET text = 'The American South''s breakfast plate, everything under a pale flecked blanket.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 5;
UPDATE clues SET text = 'A layered chocolate bake from a wooded part of Central Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'black-forest-cake') AND order_index = 1;
UPDATE clues SET text = 'Bakers in that shadowy region layered chocolate sponge with the cherry brandy distilled locally.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'black-forest-cake') AND order_index = 2;
UPDATE clues SET text = 'Households there have simmered this beet soup for generations, passing the recipe down each family line.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'borsch-ukrainian-style') AND order_index = 2;
UPDATE clues SET text = 'A potato pancake from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'boxty') AND order_index = 1;
UPDATE clues SET text = 'A bar owner in western New York fried leftovers in 1964 and doused them in hot sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-wings') AND order_index = 2;
UPDATE clues SET text = 'Chicken pieces deep-fry plain, then get tossed in melted butter and cayenne sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-wings') AND order_index = 4;
UPDATE clues SET text = 'Tandoori pieces simmer in a silky tomato and cream sauce, finished with plenty of fat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'butter-chicken') AND order_index = 4;
UPDATE clues SET text = 'A batter of flour, egg and soured milk hits the griddle and flips once bubbles form.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buttermilk-pancakes') AND order_index = 4;
UPDATE clues SET text = 'A simple plate from a Mediterranean island, coloured like a flag.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caprese-salad') AND order_index = 1;
UPDATE clues SET text = 'A deep-panned bake from a windy Midwestern American city.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicago-deep-dish-pizza') AND order_index = 1;
UPDATE clues SET text = 'A downtown restaurant near that city''s river baked it in a buttery pan in 1943.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicago-deep-dish-pizza') AND order_index = 2;
UPDATE clues SET text = 'Poultry simmers with pasta strands, carrot and celery in a clear golden broth.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-noodle-soup') AND order_index = 4;
UPDATE clues SET text = 'Its recipe famously appears on the back of the bag whose contents it needs.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chocolate-chip-cookies') AND order_index = 3;
UPDATE clues SET text = 'Butter, sugar, flour and egg are studded with dark morsels and baked until golden.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chocolate-chip-cookies') AND order_index = 4;
UPDATE clues SET text = 'America''s round bake, the dark morsels still soft if you get one warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chocolate-chip-cookies') AND order_index = 5;
UPDATE clues SET text = 'Shellfish, lobster, corn and potatoes steam together over hot rocks and seaweed.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'clam-bake') AND order_index = 4;
UPDATE clues SET text = 'A triple-decker from North American diner and hotel menus.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'club-sandwich') AND order_index = 1;
UPDATE clues SET text = 'It first appeared in American social establishments in the late 1800s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'club-sandwich') AND order_index = 2;
UPDATE clues SET text = 'Tin miners in the 19th century ate it underground, holding the crimped edge as a handle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cornish-pasty') AND order_index = 2;
UPDATE clues SET text = 'Freshwater tails smother in a dark roux with bell pepper, onion and celery, over rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crawfish-etouffee') AND order_index = 4;
UPDATE clues SET text = 'Scotland''s pale thick bowl, smoky and flecked through with white flakes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cullen-skink') AND order_index = 5;
UPDATE clues SET text = 'Legend says a dropped dessert at that school''s sports day was scooped up and served anyway.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eton-mess') AND order_index = 2;
UPDATE clues SET text = 'You fold broken meringue, whipped cream and crushed strawberries together in a bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eton-mess') AND order_index = 4;
UPDATE clues SET text = 'White fillets simmer in coconut milk with turmeric and chili until the sauce turns yellow.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-curry') AND order_index = 4;
UPDATE clues SET text = 'Fiji''s yellow coconut bowl, soft white pieces breaking apart in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-curry') AND order_index = 5;
UPDATE clues SET text = 'A wobbly caramel-topped custard from southwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flan') AND order_index = 1;
UPDATE clues SET text = 'Soaking stale bread in egg and milk dates to ancient Rome, and France calls it lost bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-toast') AND order_index = 2;
UPDATE clues SET text = 'Southern home cooks found a use for fruit picked before it ripened, frying it before the frost.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-green-tomatoes') AND order_index = 2;
UPDATE clues SET text = 'The American South''s crisp cornmeal rounds, tart underneath the crust.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-green-tomatoes') AND order_index = 5;
UPDATE clues SET text = 'Green ones are sliced, fried, smashed flat, then returned to the oil until crisp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-plantains') AND order_index = 4;
UPDATE clues SET text = 'Cold leftover grains hit a screaming wok with egg, scallion and vegetables.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 4;
UPDATE clues SET text = 'Britain''s loaded morning plate of eggs, bacon and beans.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'full-english-breakfast') AND order_index = 5;
UPDATE clues SET text = 'It is named for a 19th-century Chinese commander who never tasted it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'general-tsos-chicken') AND order_index = 3;
UPDATE clues SET text = 'A man''s surname on an 1852 baking bar became the dish, and a 1957 Texas recipe dropped his apostrophe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 2;
UPDATE clues SET text = 'Shredded unripe fruit is pounded with chili, lime, fish sauce and dried shrimp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'green-papaya-salad') AND order_index = 4;
UPDATE clues SET text = 'Thailand''s pounded shreds, sharp with lime and studded with peanut.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'green-papaya-salad') AND order_index = 5;
UPDATE clues SET text = 'Immigrants from a southern Chinese island brought it, and hawker stalls perfected it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hainanese-chicken-rice') AND order_index = 2;
UPDATE clues SET text = 'Poached bird rests over grains cooked in its own fat, with ginger-scallion and chili sauces.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hainanese-chicken-rice') AND order_index = 4;
UPDATE clues SET text = 'Singapore''s pale silky poultry over fragrant grains, three sauces alongside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hainanese-chicken-rice') AND order_index = 5;
UPDATE clues SET text = 'New York breakfast menus carried them in the 1890s under a longer name that got shortened.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 2;
UPDATE clues SET text = 'Korea''s translucent tangle, glossy dark and shot through with colour.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'japchae') AND order_index = 5;
UPDATE clues SET text = 'The rivalry between Nigeria and Ghana over it is the internet''s tastiest war.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jollof-rice') AND order_index = 3;
UPDATE clues SET text = 'A barbecue style from a Midwestern town split across a state line.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kansas-city-bbq-ribs') AND order_index = 1;
UPDATE clues SET text = 'Its smokehouses built their fame on a thick, sweet tomato-and-molasses sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kansas-city-bbq-ribs') AND order_index = 2;
UPDATE clues SET text = 'Pork bones smoke for hours, then take a sweet, sticky tomato glaze.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kansas-city-bbq-ribs') AND order_index = 4;
UPDATE clues SET text = 'Georgia''s edible boat, the yolk still trembling in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khachapuri') AND order_index = 5;
UPDATE clues SET text = 'Korean households turned to it when a jar had fermented past eating raw.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimchi-jjigae') AND order_index = 2;
UPDATE clues SET text = 'Korea''s bubbling red pot, sour steam coming off the top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimchi-jjigae') AND order_index = 5;
UPDATE clues SET text = 'Chilled shellfish meat is tossed in mayonnaise or butter and piled into a split bun.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lobster-roll') AND order_index = 4;
UPDATE clues SET text = 'A red soup from the same American coast as a creamier white rival.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manhattan-clam-chowder') AND order_index = 1;
UPDATE clues SET text = 'New York cooks broke from tradition by adding tomato instead of cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manhattan-clam-chowder') AND order_index = 2;
UPDATE clues SET text = 'Shellfish simmer with tomato, potato and vegetables in a broth left cream-free.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manhattan-clam-chowder') AND order_index = 4;
UPDATE clues SET text = 'Silken white cubes and minced pork sit in a fiery chili-bean sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mapo-tofu') AND order_index = 4;
UPDATE clues SET text = 'A starter from a mid-Atlantic American state famous for its bay.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'maryland-crab-cakes') AND order_index = 1;
UPDATE clues SET text = 'Watermen along that state''s bay have pan-fried lump patties for generations.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'maryland-crab-cakes') AND order_index = 2;
UPDATE clues SET text = 'Purists judge one by how little filler it uses, letting the meat show.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'maryland-crab-cakes') AND order_index = 3;
UPDATE clues SET text = 'Lump shellfish meat is bound lightly with egg and breadcrumbs, then pan-fried golden.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'maryland-crab-cakes') AND order_index = 4;
UPDATE clues SET text = 'Argentina''s flat golden slab, hanging over the edge of the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milanesa') AND order_index = 5;
UPDATE clues SET text = 'South Africa''s pale set custard in a thin crust, cinnamon dusted over it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milk-tart') AND order_index = 5;
UPDATE clues SET text = 'Shellfish, potatoes and salt pork in thick cream, with oyster crackers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-england-clam-chowder') AND order_index = 4;
UPDATE clues SET text = 'A folded egg dish from Western Europe with versions everywhere.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'omelette') AND order_index = 1;
UPDATE clues SET text = 'Now the litmus test of every restaurant of its kind on Earth.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-thai') AND order_index = 3;
UPDATE clues SET text = 'Thailand''s sweet-sour tangle, peanut and lime waiting on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-thai') AND order_index = 5;
UPDATE clues SET text = 'Bakers there layered butter into yeasted dough, folding in dark batons before the morning bake.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 2;
UPDATE clues SET text = 'Buttery laminated dough wraps two dark batons and bakes until flaky and golden.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 4;
UPDATE clues SET text = 'France''s flaky rectangle with two dark seams running through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 5;
UPDATE clues SET text = 'A baked pasta dish from the eastern Mediterranean, built in layers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pastitsio') AND order_index = 1;
UPDATE clues SET text = 'A corn-syrup custard studded with nut halves bakes inside a flaky crust until set.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pecan-pie') AND order_index = 4;
UPDATE clues SET text = 'The American South''s sticky brown slice, nuts crowded across the top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pecan-pie') AND order_index = 5;
UPDATE clues SET text = 'Roasted for Ming emperors, and Beijing''s oldest house for it dates to 1416.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peking-duck') AND order_index = 2;
UPDATE clues SET text = 'Portugal''s flattened bird, blackened at the edges and glossy with oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'piri-piri-chicken') AND order_index = 5;
UPDATE clues SET text = 'Mozambique''s red-slicked shells, served with bread to mop the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'piri-piri-prawns') AND order_index = 5;
UPDATE clues SET text = 'An onion tart from a sunny stretch of the Western European coast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pissaladiere') AND order_index = 1;
UPDATE clues SET text = 'Mainland shops have since piled it high with dozens of trendy toppings.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'poke-bowl') AND order_index = 3;
UPDATE clues SET text = 'Mexico''s red bowl, bloated white kernels floating all through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pozole') AND order_index = 5;
UPDATE clues SET text = 'German-influenced kitchens in that region developed the bacon-and-custard tart centuries ago.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quiche-lorraine') AND order_index = 2;
UPDATE clues SET text = 'It became a 1980s American brunch cliché, and a book title told men not to eat it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quiche-lorraine') AND order_index = 3;
UPDATE clues SET text = 'Germany''s dark rolled bundles, sliced to show the spiral inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rouladen') AND order_index = 5;
UPDATE clues SET text = 'Britain''s halved sphere, yellow centre ringed with meat and crumb.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scotch-egg') AND order_index = 5;
UPDATE clues SET text = 'Scottish frying and West African seasoning met in plantation kitchens, largely in the hands of enslaved cooks.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'southern-fried-chicken') AND order_index = 2;
UPDATE clues SET text = 'Buttermilk-brined pieces are shaken in seasoned flour and fried to a craggy crust.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'southern-fried-chicken') AND order_index = 4;
UPDATE clues SET text = 'Chunks of beef and offal braise in a dark gravy, then bake under a golden pastry lid.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'steak-and-kidney-pie') AND order_index = 4;
UPDATE clues SET text = 'Britain''s deep brown filling under a burnished crust, steam escaping the slit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'steak-and-kidney-pie') AND order_index = 5;
UPDATE clues SET text = 'A moist date sponge is soaked in a warm buttery caramel sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sticky-toffee-pudding') AND order_index = 4;
UPDATE clues SET text = 'Britain''s dark wet square in a pool of sauce, with cream poured over.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sticky-toffee-pudding') AND order_index = 5;
UPDATE clues SET text = 'You roll seasoned beef and pork small, brown them, and finish them in a cream sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'swedish-meatballs') AND order_index = 4;
UPDATE clues SET text = 'Battered pieces fry hard, then get tossed with pineapple and peppers in a tart glaze.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-and-sour-pork') AND order_index = 4;
UPDATE clues SET text = 'The orange root is mashed, spiced with cinnamon and nutmeg, and baked into a crust.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-potato-pie') AND order_index = 4;
UPDATE clues SET text = 'The American South''s dark orange custard slice, spiced and served cold.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-potato-pie') AND order_index = 5;
UPDATE clues SET text = 'Netflix devoted a whole documentary series to it and crowned it king.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 3;
UPDATE clues SET text = 'Lamb braises slowly with dried fruit, cinnamon and almonds in a cone-lidded pot.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tagine-of-lamb-and-prunes') AND order_index = 4;
UPDATE clues SET text = 'India''s red-stained bird, charred at the edges and served with lemon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tandoori-chicken') AND order_index = 5;
UPDATE clues SET text = 'Britain''s puffed golden raft with sausages set down into it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'toad-in-the-hole') AND order_index = 5;
UPDATE clues SET text = 'Japan''s thick breaded slab, sliced into strips beside shredded cabbage.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tonkatsu') AND order_index = 5;
UPDATE clues SET text = 'Korea''s glossy red cylinders, chewy enough to need a second bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tteokbokki') AND order_index = 5;
UPDATE clues SET text = 'Wales'' browned bubbling slab, the topping set just before it burns.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'welsh-rarebit') AND order_index = 5;
UPDATE clues SET text = 'A slow-cooked meat dish from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-rendang') AND order_index = 1;
UPDATE clues SET text = 'A farm breakfast from the American South.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 1;
UPDATE clues SET text = 'A fisherman''s stew from a Mediterranean port.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bouillabaisse') AND order_index = 1;
UPDATE clues SET text = 'A hot North American bowl made for a crowd.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 1;
UPDATE clues SET text = 'A rolled, handheld meal from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'burrito') AND order_index = 1;
UPDATE clues SET text = 'A North American slice from under the counter dome.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 1;
UPDATE clues SET text = 'A tangy braise from an archipelago in Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-adobo') AND order_index = 1;
UPDATE clues SET text = 'A mild, creamy curry from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-korma') AND order_index = 1;
UPDATE clues SET text = 'A slow-braised dish out of North Africa.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-tagine') AND order_index = 1;
UPDATE clues SET text = 'A Latin American breakfast built out of leftovers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chilaquiles') AND order_index = 1;
UPDATE clues SET text = 'A stir-fried noodle dish from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chow-mein') AND order_index = 1;
UPDATE clues SET text = 'A fisherman''s pot from the North American west coast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cioppino') AND order_index = 1;
UPDATE clues SET text = 'A flaky crescent pastry from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'croissant') AND order_index = 1;
UPDATE clues SET text = 'A hot breakfast bread from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 1;
UPDATE clues SET text = 'A long cream-filled pastry from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eclair') AND order_index = 1;
UPDATE clues SET text = 'A breakfast made from yesterday''s loaf, out of Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-toast') AND order_index = 1;
UPDATE clues SET text = 'A fried starter from the American South, made with unripe produce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-green-tomatoes') AND order_index = 1;
UPDATE clues SET text = 'A hearty morning plate from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'full-english-breakfast') AND order_index = 1;
UPDATE clues SET text = 'A pan-fried dumpling from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyoza') AND order_index = 1;
UPDATE clues SET text = 'A deceptively plain poached dish from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hainanese-chicken-rice') AND order_index = 1;
UPDATE clues SET text = 'A cold, milky drink from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'horchata') AND order_index = 1;
UPDATE clues SET text = 'A peppery, tangy bowl from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-and-sour-soup') AND order_index = 1;
UPDATE clues SET text = 'A farmhand''s breakfast from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'huevos-rancheros') AND order_index = 1;
UPDATE clues SET text = 'The tallest thing in the North American bakery case.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 1;
UPDATE clues SET text = 'A savoury starter poured at nearly every East Asian meal.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'miso-soup') AND order_index = 1;
UPDATE clues SET text = 'A chewy pounded sweet from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 1;
UPDATE clues SET text = 'A soft leavened flatbread from South Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'naan') AND order_index = 1;
UPDATE clues SET text = 'A portable rice bite from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onigiri') AND order_index = 1;
UPDATE clues SET text = 'A charred wide-noodle plate from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-see-ew') AND order_index = 1;
UPDATE clues SET text = 'A nutty slice from the American South, named for a native tree.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pecan-pie') AND order_index = 1;
UPDATE clues SET text = 'A cold chopped relish from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 1;
UPDATE clues SET text = 'A cold picnic side from Central Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 1;
UPDATE clues SET text = 'A melted-cheese snack from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quesadilla') AND order_index = 1;
UPDATE clues SET text = 'A cold plate of raw fish from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 1;
UPDATE clues SET text = 'A cold North American bowl with nothing cooked in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 1;
UPDATE clues SET text = 'A delicate baked dish from Western Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 1;
UPDATE clues SET text = 'A tangy fried stir-fry from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-and-sour-pork') AND order_index = 1;
UPDATE clues SET text = 'A spiced dessert from the American South, built on an orange root.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-potato-pie') AND order_index = 1;
UPDATE clues SET text = 'A lightly fried dish from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tempura') AND order_index = 1;
UPDATE clues SET text = 'A glossy grilled dish from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'teriyaki-chicken') AND order_index = 1;
UPDATE clues SET text = 'A cold sweet drink from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-iced-tea') AND order_index = 1;
UPDATE clues SET text = 'A coconut soup from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-kha-gai') AND order_index = 1;
UPDATE clues SET text = 'A layered cold dessert from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'trifle') AND order_index = 1;
UPDATE clues SET text = 'A thick wheat noodle from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'udon') AND order_index = 1;
UPDATE clues SET text = 'A brothy bowl of filled dumplings from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wonton-soup') AND order_index = 1;
UPDATE clues SET text = 'A cold yogurt side from the eastern Mediterranean.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tzatziki') AND order_index = 1;
UPDATE clues SET text = 'Chicken braises slowly in red wine alongside bacon, mushrooms and pearl onions.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coq-au-vin') AND order_index = 4;
UPDATE clues SET text = 'Rajasthan tells it as a soldier''s meal, dough balls buried in hot sand at dawn and dug up baked.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-baati') AND order_index = 2;
UPDATE clues SET text = 'Competing legends credit an Omaha grocer or a New York deli owner around 1920.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'reuben-sandwich') AND order_index = 2;
UPDATE clues SET text = 'You fill a flaky shell with egg custard and bake it until the top blisters and blackens.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pastel-de-nata') AND order_index = 4;
UPDATE clues SET text = 'You pour an egg custard studded with bacon and cheese into a buttery shell and bake it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quiche-lorraine') AND order_index = 4;
UPDATE clues SET text = 'Its name is built straight out of the Spanish word for cheese.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quesadilla') AND order_index = 3;
UPDATE clues SET text = 'A tortilla folds over cheese and griddles until crisp and molten inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quesadilla') AND order_index = 4;
UPDATE clues SET text = 'Long pasta goes under tomato sauce and rolled balls of seasoned ground beef.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-and-meatballs') AND order_index = 4;
UPDATE clues SET text = 'Punjabi tandoor cooks in Delhi began slow-cooking black lentils overnight around 1950.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-makhani') AND order_index = 2;
UPDATE clues SET text = 'A Lake District hotel chef made this date sponge famous in the 1970s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sticky-toffee-pudding') AND order_index = 2;
UPDATE clues SET text = 'Ancient Romans made thick pottages from whatever the garden gave up; this is the heir.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'minestrone') AND order_index = 2;
UPDATE clues SET text = 'The name comes from the Greek word for turn, like the spit it comes off.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyro') AND order_index = 3;
UPDATE clues SET text = 'French kitchens made it famous in the early 1800s, and the name means to puff up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 2;
UPDATE clues SET text = 'Restaurant owners fed striking streetcar workers free, and named the sandwich for them.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'po-boy') AND order_index = 2;
UPDATE clues SET text = 'You drop loose yeasted batter into hot oil a spoon at a time, then drench the puffs in honey syrup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 4;
UPDATE clues SET text = 'Fermented soybean paste has anchored the diet there for more than a millennium.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'miso-soup') AND order_index = 2;
UPDATE clues SET text = 'Sliced onion is bound in a spiced chickpea-flour batter and fried into a craggy, tangled nest.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onion-bhaji') AND order_index = 4;
UPDATE clues SET text = 'Making them impossibly small is treated as a mark of a patient cook.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manti') AND order_index = 3;
UPDATE clues SET text = 'It has a national day in February, and Afrikaans speakers use a one-word name ending in -tert.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milk-tart') AND order_index = 3;
UPDATE clues SET text = 'Chicken simmers in coconut milk under a paste of green chilies, basil and lime leaves.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 4;
UPDATE clues SET text = 'Shanghai cooks worked out in the 1800s how to trap gelatinized broth inside a wrapper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'xiaolongbao') AND order_index = 2;
UPDATE clues SET text = 'It came to fame in mid-20th-century Mexico, promoted on condensed-milk can labels.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tres-leches-cake') AND order_index = 2;
