-- Backfill: clue rewrites against the beat sheet.
-- 12 clues across 10 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'The slow, simmered rice porridge of China.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'congee') AND order_index = 5;
UPDATE clues SET text = 'Traditionally known as a breakfast soup from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pho') AND order_index = 1;
UPDATE clues SET text = 'Ripe green fruit is mashed with lemon, salt, and chili flakes; don’t forget the olive oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'avocado-toast') AND order_index = 4;
UPDATE clues SET text = 'A popular Latin American street food with an immigrant backstory.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 1;
UPDATE clues SET text = 'A classic version of this dish included goose or duck liver pâté'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-wellington') AND order_index = 1;
UPDATE clues SET text = 'A breakfast cake named for a small Western European country.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'belgian-waffles') AND order_index = 1;
UPDATE clues SET text = 'A stir-fried staple from one of the world''s most populous countries.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 1;
UPDATE clues SET text = 'A fragrant, spicy dish from a country in Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 1;
UPDATE clues SET text = 'A hearty plate lunch dish from a Pacific American archipelago.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 1;
UPDATE clues SET text = 'A drive-in invented this dish in the late 1940s for hungry teenagers on a budget.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 2;
UPDATE clues SET text = 'Swap the patty for Spam, kalua pork or teriyaki chicken and the counter still calls it the same order.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 3;
UPDATE clues SET text = 'Soviet cosmonauts ate it from squeeze tubes, and it still flies up to the space station.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'borscht') AND order_index = 3;
