-- Backfill: clue rewrites against the beat sheet.
-- 10 clues across 7 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'A pastry-wrapped roast from northwestern Europe.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-wellington') AND order_index = 1;
UPDATE clues SET text = 'Victorian chefs named it for a famous Duke, and food historians still dispute the link.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-wellington') AND order_index = 2;
UPDATE clues SET text = 'A spit-grilled street food from Latin America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 1;
UPDATE clues SET text = 'You mash ripe green fruit with lemon, salt and chili flakes, then pile it onto toasted bread with olive oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'avocado-toast') AND order_index = 4;
UPDATE clues SET text = 'A breakfast bowl found across East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'congee') AND order_index = 1;
UPDATE clues SET text = 'China''s plain white bowl, eaten hot with pickles and fried dough alongside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'congee') AND order_index = 5;
UPDATE clues SET text = 'A stir-fried grain dish from East Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 1;
UPDATE clues SET text = 'A fragrant, spicy curry from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 1;
UPDATE clues SET text = 'Cooks pound fresh green chilies raw for the color, and it burns hotter than the red one.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 3;
UPDATE clues SET text = 'A breakfast soup from Southeast Asia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pho') AND order_index = 1;
