-- The opening back bar: 40 drinks, 28 of them alcoholic (70%).
--
-- Pool only. Deliberately no `INSERT INTO drink_schedule` rows, for the same
-- reason no dish migration ever writes to `schedule`: nights are booked by hand
-- in /admin and that booking exists nowhere but prod D1. An unbooked night runs
-- on the deterministic fallback pick and never 404s.
--
-- Keyed by slug throughout, never by id. A drink renamed in /admin regenerates
-- its slug, which is what silently broke seven dishes' backfill migrations in
-- Aug 2026; the failure mode is the same here and so is the rule.
--
-- Three coasters each, written against the coaster sheet in shared/clues.ts and
-- checked by worker/data-integrity.test.ts, which fails CI.

INSERT INTO drinks (name, slug, country, region, spirit, temperature, profile, is_alcoholic, ingredients) VALUES
('Margarita','margarita','Mexico','latin-america','tequila','cold','sour',1,'["tequila","lime","orange liqueur","salt","ice"]'),
('Old Fashioned','old-fashioned','United States','north-america','whiskey','cold','strong',1,'["whiskey","sugar","bitters","orange","ice"]'),
('Negroni','negroni','Italy','europe','gin','cold','bitter',1,'["gin","vermouth","campari","orange","ice"]'),
('Mojito','mojito','Cuba','latin-america','rum','cold','sour',1,'["rum","lime","mint","sugar","soda water","ice"]'),
('Caipirinha','caipirinha','Brazil','latin-america','other','cold','sour',1,'["cachaca","lime","sugar","ice"]'),
('Pisco Sour','pisco-sour','Peru','latin-america','brandy','cold','sour',1,'["pisco","lime","sugar","egg white","bitters","ice"]'),
('Aperol Spritz','aperol-spritz','Italy','europe','wine','cold','bitter',1,'["prosecco","aperol","soda water","orange","ice"]'),
('Sangria','sangria','Spain','europe','wine','cold','sweet',1,'["red wine","orange","lemon","sugar","brandy","ice"]'),
('Irish Coffee','irish-coffee','Ireland','europe','whiskey','hot','creamy',1,'["whiskey","coffee","sugar","cream"]'),
('Bloody Mary','bloody-mary','United States','north-america','vodka','cold','sour',1,'["vodka","tomato juice","lemon","hot sauce","worcestershire","celery","ice"]'),
('Daiquiri','daiquiri','Cuba','latin-america','rum','cold','sour',1,'["rum","lime","sugar","ice"]'),
('Manhattan','manhattan','United States','north-america','whiskey','cold','strong',1,'["whiskey","vermouth","bitters","cherry"]'),
('Martini','martini','United States','north-america','gin','cold','strong',1,'["gin","vermouth","olive","ice"]'),
('Moscow Mule','moscow-mule','United States','north-america','vodka','cold','sour',1,'["vodka","ginger beer","lime","ice"]'),
('Tom Collins','tom-collins','United Kingdom','europe','gin','cold','sour',1,'["gin","lemon","sugar","soda water","ice"]'),
('Pina Colada','pina-colada','Puerto Rico','latin-america','rum','cold','creamy',1,'["rum","pineapple","coconut cream","ice"]'),
('Bellini','bellini','Italy','europe','wine','cold','sweet',1,'["prosecco","peach","raspberry","sugar"]'),
('Port','port','Portugal','europe','wine','cold','sweet',1,'["grape","brandy","sugar"]'),
('Sidecar','sidecar','France','europe','brandy','cold','sour',1,'["cognac","orange liqueur","lemon","sugar","ice"]'),
('Kir Royale','kir-royale','France','europe','wine','cold','sweet',1,'["champagne","blackcurrant liqueur","sugar"]'),
('Michelada','michelada','Mexico','latin-america','beer','cold','sour',1,'["beer","lime","hot sauce","worcestershire","salt","tomato juice"]'),
('Gluhwein','gluhwein','Germany','europe','wine','hot','sweet',1,'["red wine","cinnamon","clove","orange","sugar","star anise"]'),
('Ouzo','ouzo','Greece','europe','other','cold','strong',1,'["anise","grape","sugar","water"]'),
('Sake','sake','Japan','east-asia','other','hot','strong',1,'["rice","water","koji","yeast"]'),
('Soju','soju','South Korea','east-asia','other','cold','strong',1,'["rice","water","sweet potato","yeast"]'),
('Arak','arak','Lebanon','middle-east','other','cold','strong',1,'["anise","grape","water","ice"]'),
('Hot Toddy','hot-toddy','Scotland','europe','whiskey','hot','sweet',1,'["whiskey","honey","lemon","hot water","clove"]'),
('Espresso Martini','espresso-martini','United Kingdom','europe','vodka','cold','bitter',1,'["vodka","coffee liqueur","espresso","sugar"]'),
('Shirley Temple','shirley-temple','United States','north-america','none','cold','sweet',0,'["ginger ale","grenadine","cherry","ice"]'),
('Horchata','horchata','Mexico','latin-america','none','cold','creamy',0,'["rice","cinnamon","sugar","milk","vanilla"]'),
('Masala Chai','masala-chai','India','south-asia','none','hot','sweet',0,'["tea","milk","ginger","cardamom","sugar","cinnamon"]'),
('Bubble Tea','bubble-tea','Taiwan','east-asia','none','cold','sweet',0,'["tea","milk","tapioca","sugar","ice"]'),
('Egg Cream','egg-cream','United States','north-america','none','cold','sweet',0,'["milk","chocolate syrup","seltzer"]'),
('Ayran','ayran','Turkiye','middle-east','none','cold','sour',0,'["yogurt","water","salt","ice"]'),
('Root Beer Float','root-beer-float','United States','north-america','none','cold','creamy',0,'["ice cream","sassafras","vanilla","sugar","soda water"]'),
('Sorrel','sorrel','Jamaica','latin-america','none','cold','sour',0,'["hibiscus","ginger","clove","sugar","water"]'),
('Sahlab','sahlab','Lebanon','middle-east','none','hot','creamy',0,'["orchid root","milk","sugar","cinnamon","pistachio"]'),
('Sujeonggwa','sujeonggwa','South Korea','east-asia','none','cold','sweet',0,'["cinnamon","ginger","persimmon","sugar","pine nut"]'),
('Cendol','cendol','Malaysia','southeast-asia','none','cold','creamy',0,'["coconut milk","palm sugar","rice flour","pandan","ice"]'),
('Rooibos','rooibos','South Africa','africa','none','hot','sweet',0,'["red bush","honey","milk","water"]');

INSERT INTO drink_clues (drink_id, order_index, text) VALUES
((SELECT id FROM drinks WHERE slug='margarita'), 1, 'A sharp, salt-rimmed cocktail from Latin America.'),
((SELECT id FROM drinks WHERE slug='margarita'), 2, 'Half a dozen bartenders claim they poured the first. You shake tequila with lime and orange liqueur, then drag the rim through salt.'),
((SELECT id FROM drinks WHERE slug='margarita'), 3, 'Mexico''s pale green sour, served up or on the rocks with a crust along the lip.'),
((SELECT id FROM drinks WHERE slug='old-fashioned'), 1, 'A short, brown, stirred drink from North America.'),
((SELECT id FROM drinks WHERE slug='old-fashioned'), 2, 'A Louisville club claimed it in 1881. You muddle sugar with bitters, pour bourbon over one big cube and twist orange peel across the top.'),
((SELECT id FROM drinks WHERE slug='old-fashioned'), 3, 'America''s whiskey-and-sugar original, one huge ice cube and a curl of citrus peel.'),
((SELECT id FROM drinks WHERE slug='negroni'), 1, 'A blood-red aperitivo from southern Europe, stirred and never shaken.'),
((SELECT id FROM drinks WHERE slug='negroni'), 2, 'A count in Florence asked for his aperitivo stiffened with gin in 1919, and got equal parts of three bottles poured over ice.'),
((SELECT id FROM drinks WHERE slug='negroni'), 3, 'Italy''s bitter orange short glass, one fat cube and a wide strip of peel.'),
((SELECT id FROM drinks WHERE slug='mojito'), 1, 'A tall green highball from the Caribbean, crowded with herbs.'),
((SELECT id FROM drinks WHERE slug='mojito'), 2, 'Havana bartenders press the mint against the glass rather than bruise it to shreds, then top rum and lime with soda over crushed ice.'),
((SELECT id FROM drinks WHERE slug='mojito'), 3, 'Cuba''s summer cooler, a bright thicket of leaves standing in a frosted tumbler.'),
((SELECT id FROM drinks WHERE slug='caipirinha'), 1, 'A rough cane-spirit drink from South America, all lime and sugar.'),
((SELECT id FROM drinks WHERE slug='caipirinha'), 2, 'Farmers mixed it as a cold remedy long before it reached the cities. You crush lime wedges with sugar and pour raw cane spirit over the lot.'),
((SELECT id FROM drinks WHERE slug='caipirinha'), 3, 'Brazil''s national short drink, cloudy with pulp and grit still at the bottom.'),
((SELECT id FROM drinks WHERE slug='pisco-sour'), 1, 'A foamy grape-brandy cocktail from South America.'),
((SELECT id FROM drinks WHERE slug='pisco-sour'), 2, 'An American barman in Lima built it in the 1920s, shaking grape brandy with lime, sugar and egg white until it capped.'),
((SELECT id FROM drinks WHERE slug='pisco-sour'), 3, 'Peru''s pale gold shaker drink under a white collar, dotted with bitters on top.'),
((SELECT id FROM drinks WHERE slug='aperol-spritz'), 1, 'A bright orange patio drink from southern Europe, mostly bubbles.'),
((SELECT id FROM drinks WHERE slug='aperol-spritz'), 2, 'Padua brothers bottled the bitter orange liqueur in 1919, and Venetians later stretched it three-two-one with sparkling wine and soda.'),
((SELECT id FROM drinks WHERE slug='aperol-spritz'), 3, 'Italy''s sunset-coloured wine glass of fizz, a fat citrus slice wedged in the ice.'),
((SELECT id FROM drinks WHERE slug='sangria'), 1, 'A fruit-loaded wine punch from southern Europe.'),
((SELECT id FROM drinks WHERE slug='sangria'), 2, 'Field workers stretched cheap red wine with chopped fruit and water to make it last a hot afternoon, and the pitcher stayed on the table.'),
((SELECT id FROM drinks WHERE slug='sangria'), 3, 'Spain''s jug of chilled red, choked with citrus wheels and ladled out by the glass.'),
((SELECT id FROM drinks WHERE slug='irish-coffee'), 1, 'A hot layered drink from northwestern Europe, served in a stemmed glass.'),
((SELECT id FROM drinks WHERE slug='irish-coffee'), 2, 'A chef at Foynes airbase warmed up stranded transatlantic passengers in 1943, floating cream on a sweetened, whiskey-spiked cup.'),
((SELECT id FROM drinks WHERE slug='irish-coffee'), 3, 'Ireland''s answer to a cold runway, black under a white collar you drink straight through.'),
((SELECT id FROM drinks WHERE slug='bloody-mary'), 1, 'A savoury red morning-after drink from North America.'),
((SELECT id FROM drinks WHERE slug='bloody-mary'), 2, 'A Paris barman poured the first, but New York hotels made it a brunch order, stirring vodka into tomato juice with pepper and hot sauce.'),
((SELECT id FROM drinks WHERE slug='bloody-mary'), 3, 'America''s thick red brunch glass, a celery stalk standing in it like an oar.'),
((SELECT id FROM drinks WHERE slug='daiquiri'), 1, 'A pale, tart rum cocktail from the Caribbean, shaken and served up.'),
((SELECT id FROM drinks WHERE slug='daiquiri'), 2, 'An American engineer working an iron mine named it after the village he was in, shaking rum with lime and sugar over ice.'),
((SELECT id FROM drinks WHERE slug='daiquiri'), 3, 'Cuba''s plain cold sour, no garnish and nothing at all to hide behind.'),
((SELECT id FROM drinks WHERE slug='manhattan'), 1, 'A stirred, cherry-topped whiskey drink from North America.'),
((SELECT id FROM drinks WHERE slug='manhattan'), 2, 'A New York club poured it in the 1870s, and bartenders have argued about rye against bourbon ever since. You stir it, you do not shake it.'),
((SELECT id FROM drinks WHERE slug='manhattan'), 3, 'America''s dark red stemmed glass, two parts spirit to one of sweet vermouth.'),
((SELECT id FROM drinks WHERE slug='martini'), 1, 'A cold, clear, stemmed cocktail from the American bar canon.'),
((SELECT id FROM drinks WHERE slug='martini'), 2, 'Bartenders have cut the vermouth down for a century, from half the glass to a rinse, until what is left is chilled gin and an olive.'),
((SELECT id FROM drinks WHERE slug='martini'), 3, 'America''s stemmed triangle, so cold the glass frosts, with an olive or a twist.'),
((SELECT id FROM drinks WHERE slug='moscow-mule'), 1, 'A ginger highball from North America, served in a metal cup.'),
((SELECT id FROM drinks WHERE slug='moscow-mule'), 2, 'Two Los Angeles men with unsellable stock, one of vodka and one of ginger beer, put them together in a copper mug in 1941.'),
((SELECT id FROM drinks WHERE slug='moscow-mule'), 3, 'America''s copper-mug cooler, frosted on the outside with a spent lime shell in it.'),
((SELECT id FROM drinks WHERE slug='tom-collins'), 1, 'A tall, fizzy gin cooler from northwestern Europe.'),
((SELECT id FROM drinks WHERE slug='tom-collins'), 2, 'A London bar manual printed it in 1876, after a hoax about a man badmouthing you swept New York. You build it in the glass.'),
((SELECT id FROM drinks WHERE slug='tom-collins'), 3, 'Britain''s long lemon fizz, cloudy over ice with a straw and a cherry on top.'),
((SELECT id FROM drinks WHERE slug='pina-colada'), 1, 'A thick, frozen, tropical blender drink from the Caribbean.'),
((SELECT id FROM drinks WHERE slug='pina-colada'), 2, 'A San Juan hotel barman blended it in 1954, once a canned coconut cream came along that would not split in the glass.'),
((SELECT id FROM drinks WHERE slug='pina-colada'), 3, 'Puerto Rico''s white slush in a hurricane glass, a pineapple wedge on the rim.'),
((SELECT id FROM drinks WHERE slug='bellini'), 1, 'A pale pink sparkling drink from southern Europe, served in a flute.'),
((SELECT id FROM drinks WHERE slug='bellini'), 2, 'A Venice bar owner named it after a painter''s pink robe in the 1940s, folding white peach puree into cold sparkling wine.'),
((SELECT id FROM drinks WHERE slug='bellini'), 3, 'Italy''s blush-coloured flute, peach pulp still clouding the bottom of the glass.'),
((SELECT id FROM drinks WHERE slug='port'), 1, 'A fortified sweet wine from southwestern Europe.'),
((SELECT id FROM drinks WHERE slug='port'), 2, 'Shippers stopped the ferment with grape brandy so the barrels would survive a sea voyage north, and the unfermented sugar stayed behind.'),
((SELECT id FROM drinks WHERE slug='port'), 3, 'Portugal''s dark fortified glass, poured small and passed to the left after dinner.'),
((SELECT id FROM drinks WHERE slug='sidecar'), 1, 'A sharp, sugar-rimmed brandy cocktail from western Europe.'),
((SELECT id FROM drinks WHERE slug='sidecar'), 2, 'A soldier arrived at a Paris bar in a motorcycle''s passenger seat, and the barman shook cognac with orange liqueur and lemon for him.'),
((SELECT id FROM drinks WHERE slug='sidecar'), 3, 'France''s amber shaker drink, a crust of sugar around a small stemmed glass.'),
((SELECT id FROM drinks WHERE slug='kir-royale'), 1, 'A blackcurrant-tinted sparkling drink from western Europe.'),
((SELECT id FROM drinks WHERE slug='kir-royale'), 2, 'A Dijon mayor pushed his region''s blackcurrant liqueur after the war, and the grand version swaps the white wine for champagne.'),
((SELECT id FROM drinks WHERE slug='kir-royale'), 3, 'France''s deep pink flute, the liqueur sinking through the bubbles to the bottom.'),
((SELECT id FROM drinks WHERE slug='michelada'), 1, 'A spiced, salt-rimmed beer drink from Latin America.'),
((SELECT id FROM drinks WHERE slug='michelada'), 2, 'Cantina drinkers rescue a plain lager with lime, hot sauce and a rim of chilli salt, and some pour tomato juice in as well.'),
((SELECT id FROM drinks WHERE slug='michelada'), 3, 'Mexico''s red-tinged pint, the rim crusted dark and a lime wedge jammed on top.'),
((SELECT id FROM drinks WHERE slug='gluhwein'), 1, 'A hot spiced wine from central Europe, drunk outdoors in winter.'),
((SELECT id FROM drinks WHERE slug='gluhwein'), 2, 'Market stalls have ladled it since the Middle Ages, steeping red wine with cinnamon, cloves and orange peel and never letting it boil.'),
((SELECT id FROM drinks WHERE slug='gluhwein'), 3, 'Germany''s Christmas-market mug, steaming and red with a wheel of citrus in it.'),
((SELECT id FROM drinks WHERE slug='ouzo'), 1, 'A clear anise spirit from southern Europe that clouds with water.'),
((SELECT id FROM drinks WHERE slug='ouzo'), 2, 'Distillers in Tyrnavos have made it since the 1800s, and the anise oil turns it milky the moment ice hits the glass.'),
((SELECT id FROM drinks WHERE slug='ouzo'), 3, 'Greece''s aniseed pour, served cold beside small plates and gone cloudy in the glass.'),
((SELECT id FROM drinks WHERE slug='sake'), 1, 'A brewed rice drink from East Asia, served warm or chilled.'),
((SELECT id FROM drinks WHERE slug='sake'), 2, 'Brewers polish the grain down, then let a mould convert its starch to sugar while yeast ferments it in the same tank at the same time.'),
((SELECT id FROM drinks WHERE slug='sake'), 3, 'Japan''s clear rice brew, poured from a small flask into cups the size of a thimble.'),
((SELECT id FROM drinks WHERE slug='soju'), 1, 'A clear grain spirit from East Asia, drunk in small shots.'),
((SELECT id FROM drinks WHERE slug='soju'), 2, 'Distillers switched from rice to sweet potato when wartime shortages banned grain, and the cheaper version stuck around long after.'),
((SELECT id FROM drinks WHERE slug='soju'), 3, 'Korea''s green bottle poured into shot glasses, and you fill a neighbour''s before your own.'),
((SELECT id FROM drinks WHERE slug='arak'), 1, 'An anise spirit from the Middle East, poured before the ice goes in.'),
((SELECT id FROM drinks WHERE slug='arak'), 2, 'Distillers age it in clay jars with aniseed, and the order matters at the table: spirit first, then water, then ice, or it curdles.'),
((SELECT id FROM drinks WHERE slug='arak'), 3, 'Lebanon''s milky white spirit, cloudy in a small tumbler beside a spread of mezze.'),
((SELECT id FROM drinks WHERE slug='hot-toddy'), 1, 'A hot sweetened spirit drink from northern Europe, taken for a cold.'),
((SELECT id FROM drinks WHERE slug='hot-toddy'), 2, 'Drinkers have treated a sore throat with it for centuries, stirring honey and lemon into whisky and topping the mug up with boiling water.'),
((SELECT id FROM drinks WHERE slug='hot-toddy'), 3, 'Scotland''s bedtime mug, steaming and gold with a clove-studded lemon slice in it.'),
((SELECT id FROM drinks WHERE slug='espresso-martini'), 1, 'A dark, foam-capped cocktail from northwestern Europe.'),
((SELECT id FROM drinks WHERE slug='espresso-martini'), 2, 'A model asked a Soho bartender in 1983 for something to wake her up and knock her out, so he shook vodka with coffee and its liqueur.'),
((SELECT id FROM drinks WHERE slug='espresso-martini'), 3, 'Britain''s late-night pick-me-up, three coffee beans floating on a tan crema.'),
((SELECT id FROM drinks WHERE slug='shirley-temple'), 1, 'A sweet red drink from North America, poured for children in a real glass.'),
((SELECT id FROM drinks WHERE slug='shirley-temple'), 2, 'Hollywood restaurants mixed it in the 1930s for a child star who could not order what the adults at her table were having.'),
((SELECT id FROM drinks WHERE slug='shirley-temple'), 3, 'America''s pink ginger fizz, a maraschino cherry sunk at the bottom on a stick.'),
((SELECT id FROM drinks WHERE slug='horchata'), 1, 'A cloudy white rice drink from Latin America, drunk cold.'),
((SELECT id FROM drinks WHERE slug='horchata'), 2, 'Cooks soak rice and cinnamon overnight, blend the lot and strain it, then sweeten the milky liquid and pour it over ice.'),
((SELECT id FROM drinks WHERE slug='horchata'), 3, 'Mexico''s chalky white cooler, ladled from a glass barrel beside the taco counter.'),
((SELECT id FROM drinks WHERE slug='masala-chai'), 1, 'A sweet spiced milk tea from South Asia, boiled and not steeped.'),
((SELECT id FROM drinks WHERE slug='masala-chai'), 2, 'Railway platform vendors boil leaves, milk, sugar and crushed spices together in one pot, then pour it from a height to froth it up.'),
((SELECT id FROM drinks WHERE slug='masala-chai'), 3, 'India''s roadside glass of tan, sweet tea, sold scalding in a tiny clay cup.'),
((SELECT id FROM drinks WHERE slug='bubble-tea'), 1, 'A sweet iced tea from East Asia, drunk through a straw wide as a pen.'),
((SELECT id FROM drinks WHERE slug='bubble-tea'), 2, 'Taichung shops dropped chewy tapioca pearls into iced milk tea in the 1980s, and the straw had to be widened to fit them through.'),
((SELECT id FROM drinks WHERE slug='bubble-tea'), 3, 'Taiwan''s tan cup with a layer of dark spheres rolling around at the bottom.'),
((SELECT id FROM drinks WHERE slug='egg-cream'), 1, 'A fizzy chocolate soda-fountain drink from North America.'),
((SELECT id FROM drinks WHERE slug='egg-cream'), 2, 'Brooklyn candy stores built it from syrup, cold milk and a hard spray of seltzer, and the name lies about both of its halves.'),
((SELECT id FROM drinks WHERE slug='egg-cream'), 3, 'America''s soda-counter glass, chocolate under a white head you drink before it falls.'),
((SELECT id FROM drinks WHERE slug='ayran'), 1, 'A salty yogurt drink from the Middle East, served ice cold.'),
((SELECT id FROM drinks WHERE slug='ayran'), 2, 'Herders thinned yogurt with water and salt to make it keep and to rehydrate in the heat, and it still arrives beside grilled meat.'),
((SELECT id FROM drinks WHERE slug='ayran'), 3, 'Turkiye''s white, salty, foam-topped cup, poured alongside a plate of kebab.'),
((SELECT id FROM drinks WHERE slug='root-beer-float'), 1, 'A tall North American drink where dessert and soda share one glass.'),
((SELECT id FROM drinks WHERE slug='root-beer-float'), 2, 'A Colorado shop owner dropped vanilla ice cream into a dark sassafras soda in 1893, and the whole thing foamed up over the sides.'),
((SELECT id FROM drinks WHERE slug='root-beer-float'), 3, 'America''s brown fizz under a white scoop, drunk through a straw beside a long spoon.'),
((SELECT id FROM drinks WHERE slug='sorrel'), 1, 'A deep red spiced flower drink from the Caribbean, made at Christmas.'),
((SELECT id FROM drinks WHERE slug='sorrel'), 2, 'Households steep dried hibiscus with ginger and cloves for days, strain it and sweeten it hard, and some spike the jug with rum.'),
((SELECT id FROM drinks WHERE slug='sorrel'), 3, 'Jamaica''s ruby Christmas glass, tart and gingery with a bite that builds on you.'),
((SELECT id FROM drinks WHERE slug='sahlab'), 1, 'A hot milk drink thick enough to eat with a spoon, from the Middle East.'),
((SELECT id FROM drinks WHERE slug='sahlab'), 2, 'Vendors thicken hot milk with ground orchid tubers until it coats a spoon, then dust it with cinnamon and chopped pistachio.'),
((SELECT id FROM drinks WHERE slug='sahlab'), 3, 'Lebanon''s winter cup, pale and gluey under a snow of green nuts and spice.'),
((SELECT id FROM drinks WHERE slug='sujeonggwa'), 1, 'A dark cinnamon punch from East Asia, served cold after a meal.'),
((SELECT id FROM drinks WHERE slug='sujeonggwa'), 2, 'Cooks boil the bark and the ginger separately so neither bullies the other, then chill the liquid and drop dried persimmon in to soften.'),
((SELECT id FROM drinks WHERE slug='sujeonggwa'), 3, 'Korea''s near-black dessert cup, floating pine nuts and a wrinkled dried fruit.'),
((SELECT id FROM drinks WHERE slug='cendol'), 1, 'A shaved-ice dessert drink from Southeast Asia, green worms and all.'),
((SELECT id FROM drinks WHERE slug='cendol'), 2, 'Hawkers press pandan-dyed rice batter through a sieve into cold water so it sets in short green threads, then bury it under shaved ice.'),
((SELECT id FROM drinks WHERE slug='cendol'), 3, 'Malaysia''s bowl of coconut milk and palm sugar, green squiggles sunk in the ice.'),
((SELECT id FROM drinks WHERE slug='rooibos'), 1, 'A caffeine-free red tea from southern Africa, drunk hot with milk.'),
((SELECT id FROM drinks WHERE slug='rooibos'), 2, 'Farmers on the Cederberg slopes cut, bruise and sun-dry the needles of a wild bush, which turns them from green to a deep red.'),
((SELECT id FROM drinks WHERE slug='rooibos'), 3, 'South Africa''s rust-red brew, drunk with milk and honey and no caffeine in it.');
