-- The back bar, doubled: 60 more drinks, 36 of them alcoholic.
--
-- The opening 40 ran 70% alcoholic, which sat near the top of the 55-75% band
-- worker/data-integrity.test.ts holds the pool to. This batch is 60% alcoholic
-- and lands the pool of 100 at 64%, back toward the middle of it.
--
-- The brief was recognisable first, international second. Where a region had no
-- widely-known drink left, it got none rather than an obscure one written up to
-- fill a quota: South Asia takes no alcoholic entry for that reason.
--
-- Pool only. No `INSERT INTO drink_schedule` rows, same rule as 0040 and the
-- same rule every dish migration follows about `schedule`.
--
-- Keyed by slug throughout, never by id.
--
-- Three coasters each, written against the sheet in shared/clues.ts and checked
-- by worker/data-integrity.test.ts, which fails CI.
INSERT INTO drinks (name, slug, country, region, spirit, temperature, profile, is_alcoholic, ingredients) VALUES
('Whiskey Sour','whiskey-sour','United States','north-america','whiskey','cold','sour',1,'["whiskey","lemon","sugar","egg white","bitters","ice"]'),
('Mint Julep','mint-julep','United States','north-america','whiskey','cold','strong',1,'["whiskey","sugar","mint","ice","water"]'),
('Cosmopolitan','cosmopolitan','United States','north-america','vodka','cold','sour',1,'["vodka","cranberry","lime","orange liqueur","ice"]'),
('Long Island Iced Tea','long-island-iced-tea','United States','north-america','vodka','cold','strong',1,'["vodka","gin","rum","tequila","orange liqueur","cola","lemon","ice"]'),
('Sazerac','sazerac','United States','north-america','whiskey','cold','strong',1,'["whiskey","sugar","bitters","absinthe","lemon"]'),
('White Russian','white-russian','United States','north-america','vodka','cold','creamy',1,'["vodka","coffee liqueur","cream","ice"]'),
('Mai Tai','mai-tai','United States','north-america','rum','cold','sour',1,'["rum","lime","orange liqueur","almond","ice","mint"]'),
('Eggnog','eggnog','United States','north-america','brandy','cold','creamy',1,'["egg","milk","cream","sugar","nutmeg","brandy"]'),
('Hurricane','hurricane','United States','north-america','rum','cold','sweet',1,'["rum","passion fruit","lemon","grenadine","ice"]'),
('Tequila Sunrise','tequila-sunrise','United States','north-america','tequila','cold','sweet',1,'["tequila","orange","grenadine","ice"]'),
('Dark and Stormy','dark-and-stormy','Bermuda','north-america','rum','cold','sour',1,'["rum","ginger beer","lime","ice"]'),
('Ice Wine','ice-wine','Canada','north-america','wine','cold','sweet',1,'["grape","sugar","yeast"]'),
('Cuba Libre','cuba-libre','Cuba','latin-america','rum','cold','sweet',1,'["rum","cola","lime","ice"]'),
('Paloma','paloma','Mexico','latin-america','tequila','cold','sour',1,'["tequila","grapefruit","lime","salt","soda water","ice"]'),
('Mezcal','mezcal','Mexico','latin-america','other','cold','strong',1,'["agave","water","yeast","salt"]'),
('Rum Punch','rum-punch','Barbados','latin-america','rum','cold','sweet',1,'["rum","lime","sugar","water","nutmeg","ice"]'),
('Gin and Tonic','gin-and-tonic','United Kingdom','europe','gin','cold','bitter',1,'["gin","tonic water","lime","ice"]'),
('Pimm''s Cup','pimms-cup','United Kingdom','europe','gin','cold','sweet',1,'["gin","lemonade","cucumber","strawberry","mint","orange"]'),
('Cider','cider','United Kingdom','europe','other','cold','sour',1,'["apple","yeast","sugar","water"]'),
('Stout','stout','Ireland','europe','beer','cold','bitter',1,'["barley","hops","water","yeast"]'),
('French 75','french-75','France','europe','gin','cold','sour',1,'["gin","champagne","lemon","sugar","ice"]'),
('Mimosa','mimosa','France','europe','wine','cold','sweet',1,'["champagne","orange","orange liqueur"]'),
('Absinthe','absinthe','Switzerland','europe','other','cold','strong',1,'["anise","wormwood","fennel","sugar","water"]'),
('Limoncello','limoncello','Italy','europe','other','cold','sweet',1,'["lemon","sugar","water","grain alcohol"]'),
('Grappa','grappa','Italy','europe','brandy','cold','strong',1,'["grape","water","yeast"]'),
('Sherry','sherry','Spain','europe','wine','cold','strong',1,'["grape","brandy","yeast"]'),
('Pilsner','pilsner','Czech Republic','europe','beer','cold','bitter',1,'["barley","hops","water","yeast"]'),
('Hefeweizen','hefeweizen','Germany','europe','beer','cold','sweet',1,'["wheat","barley","hops","water","yeast"]'),
('Aquavit','aquavit','Norway','europe','other','cold','strong',1,'["potato","caraway","dill","water"]'),
('Raki','raki','Turkiye','middle-east','other','cold','strong',1,'["anise","grape","water","ice"]'),
('Baijiu','baijiu','China','east-asia','other','cold','strong',1,'["sorghum","water","yeast","wheat"]'),
('Umeshu','umeshu','Japan','east-asia','other','cold','sweet',1,'["plum","sugar","rice","water"]'),
('Makgeolli','makgeolli','South Korea','east-asia','other','cold','creamy',1,'["rice","wheat","water","yeast"]'),
('Singapore Sling','singapore-sling','Singapore','southeast-asia','gin','cold','sweet',1,'["gin","cherry","pineapple","lime","grenadine","bitters"]'),
('Tej','tej','Ethiopia','africa','other','cold','sweet',1,'["honey","water","yeast","gesho"]'),
('Palm Wine','palm-wine','Nigeria','africa','other','cold','sour',1,'["palm sap","yeast","water"]'),
('Lemonade','lemonade','United States','north-america','none','cold','sour',0,'["lemon","sugar","water","ice"]'),
('Arnold Palmer','arnold-palmer','United States','north-america','none','cold','sweet',0,'["tea","lemon","sugar","water","ice"]'),
('Milkshake','milkshake','United States','north-america','none','cold','creamy',0,'["ice cream","milk","sugar","vanilla"]'),
('Cold Brew','cold-brew','United States','north-america','none','cold','bitter',0,'["coffee","water","ice"]'),
('Sweet Tea','sweet-tea','United States','north-america','none','cold','sweet',0,'["tea","sugar","water","ice","lemon"]'),
('Chicha Morada','chicha-morada','Peru','latin-america','none','cold','sweet',0,'["corn","pineapple","cinnamon","clove","sugar","lime"]'),
('Yerba Mate','yerba-mate','Argentina','latin-america','none','hot','bitter',0,'["yerba mate","water","sugar"]'),
('Cappuccino','cappuccino','Italy','europe','none','hot','creamy',0,'["espresso","milk","cocoa"]'),
('Kvass','kvass','Russia','europe','none','cold','sour',0,'["rye bread","yeast","sugar","water"]'),
('Hot Chocolate','hot-chocolate','Spain','europe','none','hot','creamy',0,'["chocolate","milk","sugar","cornstarch"]'),
('Turkish Coffee','turkish-coffee','Turkiye','middle-east','none','hot','bitter',0,'["coffee","sugar","water","cardamom"]'),
('Mint Tea','mint-tea','Morocco','africa','none','hot','sweet',0,'["tea","mint","sugar","water"]'),
('Mango Lassi','mango-lassi','India','south-asia','none','cold','creamy',0,'["yogurt","mango","sugar","cardamom","ice"]'),
('Falooda','falooda','Pakistan','south-asia','none','cold','creamy',0,'["milk","rose water","vermicelli","basil seed","ice cream"]'),
('Matcha','matcha','Japan','east-asia','none','hot','bitter',0,'["tea","water","milk","sugar"]'),
('Ramune','ramune','Japan','east-asia','none','cold','sweet',0,'["lemon","lime","sugar","soda water"]'),
('Jasmine Tea','jasmine-tea','China','east-asia','none','hot','sweet',0,'["tea","jasmine","water"]'),
('Kombucha','kombucha','China','east-asia','none','cold','sour',0,'["tea","sugar","yeast","water"]'),
('Thai Iced Tea','thai-iced-tea','Thailand','southeast-asia','none','cold','creamy',0,'["tea","condensed milk","evaporated milk","sugar","star anise","ice"]'),
('Vietnamese Coffee','vietnamese-coffee','Vietnam','southeast-asia','none','cold','sweet',0,'["coffee","condensed milk","ice"]'),
('Halo-Halo','halo-halo','Philippines','southeast-asia','none','cold','creamy',0,'["shaved ice","evaporated milk","ice cream","red bean","coconut","ube"]'),
('Kava','kava','Fiji','oceania','other','cold','bitter',0,'["kava root","water","coconut"]'),
('Flat White','flat-white','Australia','oceania','none','hot','creamy',0,'["coffee","milk","water"]'),
('Lemon Lime and Bitters','lemon-lime-and-bitters','Australia','oceania','none','cold','sour',0,'["lemonade","lime","bitters","ice"]');

INSERT INTO drink_clues (drink_id, order_index, text) VALUES
((SELECT id FROM drinks WHERE slug='whiskey-sour'), 1, 'A shaken, foam-topped bourbon drink from North America.'),
((SELECT id FROM drinks WHERE slug='whiskey-sour'), 2, 'Bartenders have shaken it since the 1860s, cutting bourbon with lemon and sugar and beating egg white in for the collar.'),
((SELECT id FROM drinks WHERE slug='whiskey-sour'), 3, 'America''s tan short glass under a pale cap, a cherry and a lemon wheel dropped on top.'),
((SELECT id FROM drinks WHERE slug='mint-julep'), 1, 'A frosted silver cup from North America, packed to the brim with crushed ice.'),
((SELECT id FROM drinks WHERE slug='mint-julep'), 2, 'Kentucky racegoers have drunk it at the Derby since the 1870s, muddling sugar with green leaves and burying bourbon in shaved ice.'),
((SELECT id FROM drinks WHERE slug='mint-julep'), 3, 'America''s Derby cup, so cold the metal beads, with a bouquet of herb crushed under your nose.'),
((SELECT id FROM drinks WHERE slug='cosmopolitan'), 1, 'A pink stemmed cocktail from the North American bar canon.'),
((SELECT id FROM drinks WHERE slug='cosmopolitan'), 2, 'New York and Miami bartenders both claimed it in the 1980s, shaking citrus vodka with lime, orange liqueur and cranberry.'),
((SELECT id FROM drinks WHERE slug='cosmopolitan'), 3, 'America''s pale red stemmed glass, a flamed strip of orange peel laid across it.'),
((SELECT id FROM drinks WHERE slug='long-island-iced-tea'), 1, 'A tall brown highball from North America, five spirits deep.'),
((SELECT id FROM drinks WHERE slug='long-island-iced-tea'), 2, 'A Tennessee man entered a 1970s contest for drinks using orange liqueur, and stacked vodka, gin, rum and tequila under a splash of cola.'),
((SELECT id FROM drinks WHERE slug='long-island-iced-tea'), 3, 'America''s most misleading tall glass, the colour of tea with a lemon wedge on the rim.'),
((SELECT id FROM drinks WHERE slug='sazerac'), 1, 'An anise-rinsed rye drink from North America, stirred in the glass itself.'),
((SELECT id FROM drinks WHERE slug='sazerac'), 2, 'A New Orleans pharmacist mixed bitters into brandy in the 1830s, and bartenders later swapped rye in and rinsed the glass with absinthe.'),
((SELECT id FROM drinks WHERE slug='sazerac'), 3, 'America''s no-ice short glass, oily with anise and finished with a twist of lemon peel.'),
((SELECT id FROM drinks WHERE slug='white-russian'), 1, 'A layered cream drink from North America, served over ice in a short glass.'),
((SELECT id FROM drinks WHERE slug='white-russian'), 2, 'Bartenders poured vodka into coffee liqueur in the 1940s, and floating cream on top made a second, paler drink with its own name.'),
((SELECT id FROM drinks WHERE slug='white-russian'), 3, 'America''s two-tone tumbler, the cream sinking through it in ribbons if you leave it alone.'),
((SELECT id FROM drinks WHERE slug='mai-tai'), 1, 'A rum cooler from North America, born in a Polynesian-themed bar.'),
((SELECT id FROM drinks WHERE slug='mai-tai'), 2, 'An Oakland bar owner served it to Tahitian friends in 1944, shaking aged rum with almond syrup, orange liqueur and lime.'),
((SELECT id FROM drinks WHERE slug='mai-tai'), 3, 'America''s tiki pour, dark rum floated on top, mint standing over a heap of crushed ice.'),
((SELECT id FROM drinks WHERE slug='eggnog'), 1, 'A thick, spiced holiday drink from North America, ladled from a bowl.'),
((SELECT id FROM drinks WHERE slug='eggnog'), 2, 'Colonial farmers had dairy and rum to hand where they had no wine, so they beat eggs with sugar, milk and spirit and let it sit.'),
((SELECT id FROM drinks WHERE slug='eggnog'), 3, 'America''s December punch bowl, pale yellow and dusted with grated nutmeg.'),
((SELECT id FROM drinks WHERE slug='hurricane'), 1, 'A tall red rum drink from North America, heavy on tropical fruit.'),
((SELECT id FROM drinks WHERE slug='hurricane'), 2, 'A French Quarter bar owner in the 1940s had to buy crates of rum to get any whiskey, so he dumped it into passion fruit and lemon.'),
((SELECT id FROM drinks WHERE slug='hurricane'), 3, 'America''s carnival glass, deep red and shaped like a storm lamp, an orange slice on the rim.'),
((SELECT id FROM drinks WHERE slug='tequila-sunrise'), 1, 'A layered orange-and-red highball from North America, poured and not stirred.'),
((SELECT id FROM drinks WHERE slug='tequila-sunrise'), 2, 'A Sausalito bar poured it for the Rolling Stones on tour in 1972, dropping grenadine through agave spirit and orange juice.'),
((SELECT id FROM drinks WHERE slug='tequila-sunrise'), 3, 'America''s two-tone tall glass, red settling at the bottom under a band of orange.'),
((SELECT id FROM drinks WHERE slug='dark-and-stormy'), 1, 'A two-ingredient rum highball from a North American island, built and not shaken.'),
((SELECT id FROM drinks WHERE slug='dark-and-stormy'), 2, 'A Royal Navy officers'' club poured local black rum over spicy ginger beer once the first war ended, and a distiller trademarked it.'),
((SELECT id FROM drinks WHERE slug='dark-and-stormy'), 3, 'Bermuda''s cloudy brown highball, the rum floated last so it sits over the fizz in a bruise-coloured band.'),
((SELECT id FROM drinks WHERE slug='ice-wine'), 1, 'A syrupy dessert pour from North America, picked in the middle of winter.'),
((SELECT id FROM drinks WHERE slug='ice-wine'), 2, 'Growers leave grapes hanging until a hard freeze, then press them frozen so the water stays behind as ice and only sugar runs out.'),
((SELECT id FROM drinks WHERE slug='ice-wine'), 3, 'Canada''s tiny half-bottle, gold and thick, poured in small glasses after the plates go.'),
((SELECT id FROM drinks WHERE slug='cuba-libre'), 1, 'A rum-and-cola highball from the Caribbean, with a wedge of lime.'),
((SELECT id FROM drinks WHERE slug='cuba-libre'), 2, 'American soldiers on the island after 1898 poured a new bottled soft drink over local rum and toasted the fight for independence.'),
((SELECT id FROM drinks WHERE slug='cuba-libre'), 3, 'The Cuban long glass, brown over ice with the lime squeezed in and dropped after it.'),
((SELECT id FROM drinks WHERE slug='paloma'), 1, 'A pink grapefruit cooler from Latin America, salted around the rim.'),
((SELECT id FROM drinks WHERE slug='paloma'), 2, 'Cantina drinkers order it more than the shaken export, topping agave spirit with grapefruit soda and a squeeze of lime over ice.'),
((SELECT id FROM drinks WHERE slug='paloma'), 3, 'Mexico''s tall salted glass, pale pink and fizzing, drunk cold in the afternoon heat.'),
((SELECT id FROM drinks WHERE slug='mezcal'), 1, 'A smoky agave spirit from Latin America, sipped and not shot.'),
((SELECT id FROM drinks WHERE slug='mezcal'), 2, 'Oaxacan producers roast agave hearts in a rock-lined pit for days, crush them under a stone wheel and ferment them in open vats.'),
((SELECT id FROM drinks WHERE slug='mezcal'), 3, 'Mexico''s smoke-tasting pour, served neat in a clay cup beside orange slices and chilli salt.'),
((SELECT id FROM drinks WHERE slug='rum-punch'), 1, 'A rum drink from the Caribbean, measured by a rhyme instead of a recipe.'),
((SELECT id FROM drinks WHERE slug='rum-punch'), 2, 'Islanders learned it as one of sour, two of sweet, three of strong and four of weak, and the last line tells you to add spice.'),
((SELECT id FROM drinks WHERE slug='rum-punch'), 3, 'Barbados''s ruby jug over ice, grated nutmeg on top and a slice of lime on the glass.'),
((SELECT id FROM drinks WHERE slug='gin-and-tonic'), 1, 'A clear, bitter highball from northwestern Europe, all ice and bubbles.'),
((SELECT id FROM drinks WHERE slug='gin-and-tonic'), 2, 'Officers of the East India Company cut their bitter quinine ration with gin, sugar and citrus, and the mixer was bottled by 1858.'),
((SELECT id FROM drinks WHERE slug='gin-and-tonic'), 3, 'Britain''s tall glass of gin over quinine water, a wheel of lime and more ice than liquid.'),
((SELECT id FROM drinks WHERE slug='pimms-cup'), 1, 'A fruit-crowded jug drink from northwestern Europe, poured all summer.'),
((SELECT id FROM drinks WHERE slug='pimms-cup'), 2, 'A London oyster bar owner bottled a gin-based herbal cordial in the 1840s, and drinkers stretch it with lemonade, cucumber and berries.'),
((SELECT id FROM drinks WHERE slug='pimms-cup'), 3, 'Britain''s Wimbledon jug, red-brown with fruit and a cucumber ribbon hanging over the side.'),
((SELECT id FROM drinks WHERE slug='cider'), 1, 'A pressed-apple drink from northwestern Europe, drawn flat out of a barrel.'),
((SELECT id FROM drinks WHERE slug='cider'), 2, 'West Country farms paid part of a labourer''s wages in it for centuries, milling apples to pulp and pressing the juice out through cloth.'),
((SELECT id FROM drinks WHERE slug='cider'), 3, 'Britain''s cloudy pint from an orchard county, dry, still and sharp enough to make you blink.'),
((SELECT id FROM drinks WHERE slug='stout'), 1, 'A near-black beer from northwestern Europe, poured in two goes.'),
((SELECT id FROM drinks WHERE slug='stout'), 2, 'Dublin brewers scorched the barley black, and the strongest of their porters took a name that once just meant thick.'),
((SELECT id FROM drinks WHERE slug='stout'), 3, 'Ireland''s dark pint under a creamy head, settled from the bottom up before you touch it.'),
((SELECT id FROM drinks WHERE slug='french-75'), 1, 'A gin and champagne coupe from western Europe, named for a field gun.'),
((SELECT id FROM drinks WHERE slug='french-75'), 2, 'A Paris bar mixed gin with champagne after the first war, and drinkers said it kicked like the artillery piece it borrowed from.'),
((SELECT id FROM drinks WHERE slug='french-75'), 3, 'France''s flute of gin and fizz, a long lemon twist coiled down inside it.'),
((SELECT id FROM drinks WHERE slug='mimosa'), 1, 'A two-part brunch fizz from western Europe, named after a yellow flower.'),
((SELECT id FROM drinks WHERE slug='mimosa'), 2, 'A Ritz bartender in Paris poured equal parts sparkling wine and orange juice in 1925, and hotels have served it before noon since.'),
((SELECT id FROM drinks WHERE slug='mimosa'), 3, 'France''s pale gold flute, half champagne and half juice, refilled from a jug at the table.'),
((SELECT id FROM drinks WHERE slug='absinthe'), 1, 'A green herbal spirit from western Europe, clouded with dripped water.'),
((SELECT id FROM drinks WHERE slug='absinthe'), 2, 'A Val-de-Travers doctor sold it as a remedy in the 1790s, and Paris cafes later drank wormwood and anise by the litre.'),
((SELECT id FROM drinks WHERE slug='absinthe'), 3, 'Switzerland''s green pour, gone milky under a slotted spoon and a sugar cube.'),
((SELECT id FROM drinks WHERE slug='limoncello'), 1, 'A bright yellow after-dinner liqueur from southern Europe, served freezing.'),
((SELECT id FROM drinks WHERE slug='limoncello'), 2, 'Families on the Amalfi coast steep thick lemon peel in neutral spirit for weeks, then cut it with sugar syrup and freeze the bottle.'),
((SELECT id FROM drinks WHERE slug='limoncello'), 3, 'Italy''s small frozen glass, cloudy yellow and thick, poured from a bottle kept in the freezer.'),
((SELECT id FROM drinks WHERE slug='grappa'), 1, 'A clear spirit from southern Europe, distilled from what the winery throws out.'),
((SELECT id FROM drinks WHERE slug='grappa'), 2, 'Alpine distillers took the skins, seeds and stems left after pressing and ran them through a still rather than waste them.'),
((SELECT id FROM drinks WHERE slug='grappa'), 3, 'Italy''s small stemmed glass after dinner, clear and hot in the throat, tipped into the empty coffee cup.'),
((SELECT id FROM drinks WHERE slug='sherry'), 1, 'A fortified wine from southwestern Europe, aged under a film of yeast.'),
((SELECT id FROM drinks WHERE slug='sherry'), 2, 'Bodegas in Jerez stack barrels in tiers and draw from the bottom row, refilling it from the one above so no vintage stands alone.'),
((SELECT id FROM drinks WHERE slug='sherry'), 3, 'Spain''s pale dry glass, chilled and poured small beside olives and cured ham.'),
((SELECT id FROM drinks WHERE slug='pilsner'), 1, 'A pale gold lager from central Europe, clear enough to read through.'),
((SELECT id FROM drinks WHERE slug='pilsner'), 2, 'A Bavarian brewer set up in Plzen in 1842 with soft local water and pale malt, and the bright lager he made was copied across Europe.'),
((SELECT id FROM drinks WHERE slug='pilsner'), 3, 'The Czech gold pint under a thick white head, bitter and clean with nothing left on the tongue.'),
((SELECT id FROM drinks WHERE slug='hefeweizen'), 1, 'A cloudy wheat beer from central Europe, served in a tall vase of a glass.'),
((SELECT id FROM drinks WHERE slug='hefeweizen'), 2, 'Bavarian dukes kept wheat brewing to themselves for two centuries, and the yeast they used throws banana and clove into the glass.'),
((SELECT id FROM drinks WHERE slug='hefeweizen'), 3, 'Germany''s hazy half-litre, orange-gold under a tall foam head with a lemon slice on the rim.'),
((SELECT id FROM drinks WHERE slug='aquavit'), 1, 'A caraway spirit from northern Europe, drunk cold with heavy food.'),
((SELECT id FROM drinks WHERE slug='aquavit'), 2, 'Distillers send barrels across the equator and back, because the rolling and the heat were found to age the spirit faster than a cellar.'),
((SELECT id FROM drinks WHERE slug='aquavit'), 3, 'Norway''s clear caraway pour, tipped back in one go beside pickled herring at Christmas.'),
((SELECT id FROM drinks WHERE slug='raki'), 1, 'A clear aniseed spirit that whitens with water, from the Middle East.'),
((SELECT id FROM drinks WHERE slug='raki'), 2, 'Drinkers call it lion''s milk and treat it as the spine of a meal, ordering it by the bottle with cheese, melon and grilled fish.'),
((SELECT id FROM drinks WHERE slug='raki'), 3, 'Turkiye''s tall thin glass beside a water glass, gone chalk white, working through a table of mezze.'),
((SELECT id FROM drinks WHERE slug='baijiu'), 1, 'A fierce clear spirit from East Asia, distilled from grain and poured at banquets.'),
((SELECT id FROM drinks WHERE slug='baijiu'), 2, 'Distillers ferment sorghum in earthen pits with a brick of mould-grown starter, and the result runs past fifty percent alcohol.'),
((SELECT id FROM drinks WHERE slug='baijiu'), 3, 'China''s toasting spirit, poured into thimble glasses and drained on a shout of ganbei.'),
((SELECT id FROM drinks WHERE slug='umeshu'), 1, 'A sweet steeped-fruit liqueur from East Asia, drunk over ice or with soda.'),
((SELECT id FROM drinks WHERE slug='umeshu'), 2, 'Households pack unripe green fruit and rock sugar into a jar of clear spirit each June and leave it alone for a year.'),
((SELECT id FROM drinks WHERE slug='umeshu'), 3, 'Japan''s amber jar liqueur, syrupy and tart at once, with a wrinkled plum sitting at the bottom.'),
((SELECT id FROM drinks WHERE slug='makgeolli'), 1, 'A cloudy white farmer''s brew from East Asia, poured from a kettle.'),
((SELECT id FROM drinks WHERE slug='makgeolli'), 2, 'Field workers drank it between shifts for centuries, fermenting rice with a wheat starter cake and stopping it before it ran clear.'),
((SELECT id FROM drinks WHERE slug='makgeolli'), 3, 'Korea''s milky bowl, chalky and half fizzy, ladled out and drunk with fried pancake on rainy days.'),
((SELECT id FROM drinks WHERE slug='singapore-sling'), 1, 'A pink hotel-bar cocktail from Southeast Asia, long and full of fruit.'),
((SELECT id FROM drinks WHERE slug='singapore-sling'), 2, 'A Raffles Hotel barman built it around 1915 so a woman could drink in public and look like she was not, hiding gin under fruit.'),
((SELECT id FROM drinks WHERE slug='singapore-sling'), 3, 'The Singaporean pink long drink, cloudy with pineapple foam and a cherry on a stick.'),
((SELECT id FROM drinks WHERE slug='tej'), 1, 'A honey brew from East Africa, served in a round-bottomed flask.'),
((SELECT id FROM drinks WHERE slug='tej'), 2, 'Brewers ferment honey and water with a bitter shrub that stands in for hops, and it sits in a clay pot until it turns cloudy gold.'),
((SELECT id FROM drinks WHERE slug='tej'), 3, 'Ethiopia''s sweet yellow flask, swirled and drunk from the neck alongside raw beef and injera.'),
((SELECT id FROM drinks WHERE slug='palm-wine'), 1, 'A milky tree-sap drink from West Africa, fermenting from the moment it is tapped.'),
((SELECT id FROM drinks WHERE slug='palm-wine'), 2, 'Tappers climb the trunk with a rope, cut the crown and hang a gourd under it overnight, and the sap ferments on its own by morning.'),
((SELECT id FROM drinks WHERE slug='palm-wine'), 3, 'Nigeria''s cloudy white calabash, sweet at dawn and sour by evening, drunk before it turns.'),
((SELECT id FROM drinks WHERE slug='lemonade'), 1, 'A cloudy sweet-sour cooler from North America, sold from a card table.'),
((SELECT id FROM drinks WHERE slug='lemonade'), 2, 'Children set up a stand on the sidewalk with a pitcher, squeezing lemons into sugar and cold water and charging by the cup.'),
((SELECT id FROM drinks WHERE slug='lemonade'), 3, 'America''s summer pitcher, pale and pulpy over ice with a lemon wheel floating in it.'),
((SELECT id FROM drinks WHERE slug='arnold-palmer'), 1, 'A two-part iced drink from North America, named after a golfer.'),
((SELECT id FROM drinks WHERE slug='arnold-palmer'), 2, 'The golfer ordered it at his own clubhouse, half sweet tea and half lemonade, and a woman at the next table asked for the same thing.'),
((SELECT id FROM drinks WHERE slug='arnold-palmer'), 3, 'America''s tall brown-gold glass, tea cut with citrus and drunk between nine holes and ten.'),
((SELECT id FROM drinks WHERE slug='milkshake'), 1, 'A thick blended dessert drink from North America, drunk through a straw.'),
((SELECT id FROM drinks WHERE slug='milkshake'), 2, 'Soda fountains spun ice cream and milk on an upright spindle from the 1920s, and served the leftover in the metal cup beside the glass.'),
((SELECT id FROM drinks WHERE slug='milkshake'), 3, 'America''s tall fluted diner glass, so thick the straw stands up in it, under whipped cream.'),
((SELECT id FROM drinks WHERE slug='cold-brew'), 1, 'A dark, unheated coffee drink from North America, steeped overnight.'),
((SELECT id FROM drinks WHERE slug='cold-brew'), 2, 'Roasters steep coarse grounds in room-temperature water for half a day and filter them out, which leaves the acid behind in the grounds.'),
((SELECT id FROM drinks WHERE slug='cold-brew'), 3, 'America''s tall black glass over ice, smooth and low on bite, poured straight from a tap.'),
((SELECT id FROM drinks WHERE slug='sweet-tea'), 1, 'A hard-sugared iced tea from the American South.'),
((SELECT id FROM drinks WHERE slug='sweet-tea'), 2, 'Cooks dissolve the sugar into the pot while it is still hot, because it will not go into the pitcher once the whole thing is cold.'),
((SELECT id FROM drinks WHERE slug='sweet-tea'), 3, 'America''s amber jug on the table, poured over a full glass of ice with a lemon wedge.'),
((SELECT id FROM drinks WHERE slug='chicha-morada'), 1, 'A deep purple corn drink from South America, boiled and then chilled.'),
((SELECT id FROM drinks WHERE slug='chicha-morada'), 2, 'Andean cooks boil dried purple maize with pineapple rind, cinnamon and cloves, then strain the liquid and sweeten it with lime.'),
((SELECT id FROM drinks WHERE slug='chicha-morada'), 3, 'Peru''s near-black glass at lunch, sweet and spiced, poured from a jug beside the plate.'),
((SELECT id FROM drinks WHERE slug='yerba-mate'), 1, 'A bitter green leaf infusion from South America, shared from one cup.'),
((SELECT id FROM drinks WHERE slug='yerba-mate'), 2, 'Guarani people ground the holly leaf long before Jesuit missions farmed it, and a group still passes one gourd and one metal straw around.'),
((SELECT id FROM drinks WHERE slug='yerba-mate'), 3, 'Argentina''s shared gourd, packed with green dust and refilled from a thermos under the arm.'),
((SELECT id FROM drinks WHERE slug='cappuccino'), 1, 'A milk-topped espresso from southern Europe, drunk before eleven.'),
((SELECT id FROM drinks WHERE slug='cappuccino'), 2, 'The drink took its name from the brown hoods of a friars'' order, and baristas build it in equal thirds of shot, hot milk and foam.'),
((SELECT id FROM drinks WHERE slug='cappuccino'), 3, 'Italy''s breakfast cup, a white dome of foam over dark espresso, ordered before the day starts.'),
((SELECT id FROM drinks WHERE slug='kvass'), 1, 'A dark fizzy drink made from bread, out of eastern Europe.'),
((SELECT id FROM drinks WHERE slug='kvass'), 2, 'Households pour hot water over stale dark loaves, add sugar and yeast, and two days later it comes out holding under one percent alcohol.'),
((SELECT id FROM drinks WHERE slug='kvass'), 3, 'Russia''s brown street cup, tangy with a taste of crust, poured from a barrel on the corner.'),
((SELECT id FROM drinks WHERE slug='hot-chocolate'), 1, 'A thick cocoa drink from southwestern Europe, closer to a sauce than a drink.'),
((SELECT id FROM drinks WHERE slug='hot-chocolate'), 2, 'Friars brought cacao back from the Americas in the 1500s and sweetened it, and cafes thicken the cup with a spoon of cornflour.'),
((SELECT id FROM drinks WHERE slug='hot-chocolate'), 3, 'Spain''s near-solid cup at breakfast, dark and glossy, with fried dough sticks to dip in it.'),
((SELECT id FROM drinks WHERE slug='turkish-coffee'), 1, 'A tiny cup of unfiltered grounds from the Middle East, boiled with its sugar.'),
((SELECT id FROM drinks WHERE slug='turkish-coffee'), 2, 'You boil powder-fine beans with sugar in a long-handled copper pot, let it rise three times and pour the lot in.'),
((SELECT id FROM drinks WHERE slug='turkish-coffee'), 3, 'Turkiye''s thimble cup with a sludge at the bottom, and someone reads your fortune in what is left.'),
((SELECT id FROM drinks WHERE slug='mint-tea'), 1, 'A sugared green tea from North Africa, drunk hot in the middle of the day.'),
((SELECT id FROM drinks WHERE slug='mint-tea'), 2, 'A host rinses gunpowder leaves, packs a long-spouted pot with fresh herb and a lump of sugar, and pours three rounds from it.'),
((SELECT id FROM drinks WHERE slug='mint-tea'), 3, 'Morocco''s small gilded glass, raised high on the pour so a head of foam forms, a bruised sprig inside.'),
((SELECT id FROM drinks WHERE slug='mango-lassi'), 1, 'A thick blended yogurt drink from South Asia, served cold with spice.'),
((SELECT id FROM drinks WHERE slug='mango-lassi'), 2, 'Punjab households whip and thin curd into a drink, and restaurants sweeten it with sugar, cardamom and heavy fruit pulp.'),
((SELECT id FROM drinks WHERE slug='mango-lassi'), 3, 'India''s pale orange glass beside a hot plate, thick, cold and sweet enough to put a fire out.'),
((SELECT id FROM drinks WHERE slug='falooda'), 1, 'A layered dessert in a glass from South Asia, eaten with a spoon and a straw.'),
((SELECT id FROM drinks WHERE slug='falooda'), 2, 'Persian cooks carried a chilled noodle sweet east, and vendors stack rose syrup, swollen seeds, vermicelli and a scoop of ice cream.'),
((SELECT id FROM drinks WHERE slug='falooda'), 3, 'Pakistan''s tall pink glass, jelly-slick seeds at the bottom and a spoon standing in the top.'),
((SELECT id FROM drinks WHERE slug='matcha'), 1, 'A bright green whisked tea from East Asia, powder and all in the cup.'),
((SELECT id FROM drinks WHERE slug='matcha'), 2, 'Growers shade the bushes for weeks before picking, then stone-mill the dried leaf to powder you whisk into water rather than steep.'),
((SELECT id FROM drinks WHERE slug='matcha'), 3, 'Japan''s jade-green bowl with a foam collar, bitter and thick, or the same powder poured over milk.'),
((SELECT id FROM drinks WHERE slug='ramune'), 1, 'A clear fizzy soda from East Asia, opened by pushing something into it.'),
((SELECT id FROM drinks WHERE slug='ramune'), 2, 'A Kobe pharmacist sold a British-style lemon soda in the 1880s, and the bottle keeps its glass ball, pushed in with a plastic plunger.'),
((SELECT id FROM drinks WHERE slug='ramune'), 3, 'Japan''s dimpled blue bottle at a summer festival, the marble rattling in the throat as you drink.'),
((SELECT id FROM drinks WHERE slug='jasmine-tea'), 1, 'A scented green tea from East Asia, perfumed by a night-blooming flower.'),
((SELECT id FROM drinks WHERE slug='jasmine-tea'), 2, 'Fujian makers layer leaves with flowers picked at dusk and let them sit overnight, repeating it seven times before throwing the petals out.'),
((SELECT id FROM drinks WHERE slug='jasmine-tea'), 3, 'China''s pale yellow cup, floral on the nose before it reaches your mouth, drunk with dim sum.'),
((SELECT id FROM drinks WHERE slug='kombucha'), 1, 'A sour fermented tea from East Asia, fizzy with a vinegar edge.'),
((SELECT id FROM drinks WHERE slug='kombucha'), 2, 'Brewers feed sweetened tea to a rubbery mat of yeast and bacteria that floats on the surface, and it eats the sugar over a week or two.'),
((SELECT id FROM drinks WHERE slug='kombucha'), 3, 'China''s cloudy bottled tea, tart and gassy, with strands of the culture drifting in it.'),
((SELECT id FROM drinks WHERE slug='thai-iced-tea'), 1, 'A bright orange milk tea from Southeast Asia, sweetened twice over.'),
((SELECT id FROM drinks WHERE slug='thai-iced-tea'), 2, 'Street stalls brew a hard-spiced black tea, sweeten it with condensed milk and float evaporated milk on top in a separate layer.'),
((SELECT id FROM drinks WHERE slug='thai-iced-tea'), 3, 'Thailand''s two-tone plastic cup, deep orange under a pale collar, stirred together with a straw.'),
((SELECT id FROM drinks WHERE slug='vietnamese-coffee'), 1, 'A strong sweet drip drink from Southeast Asia, poured onto condensed milk.'),
((SELECT id FROM drinks WHERE slug='vietnamese-coffee'), 2, 'French colonists brought the beans and no fresh dairy kept in the heat, so tins of sweetened milk went into the cup instead.'),
((SELECT id FROM drinks WHERE slug='vietnamese-coffee'), 3, 'Vietnam''s small glass over ice, layered dark on white until you stir it grey.'),
((SELECT id FROM drinks WHERE slug='halo-halo'), 1, 'A shaved-ice dessert from Southeast Asia, eaten from a tall glass with a spoon.'),
((SELECT id FROM drinks WHERE slug='halo-halo'), 2, 'Japanese migrants sold sweet beans on ice before the war, and vendors kept adding until a dozen things sat under the shavings.'),
((SELECT id FROM drinks WHERE slug='halo-halo'), 3, 'The Philippine glass of everything at once, purple ice cream on top and beans and jelly hiding underneath.'),
((SELECT id FROM drinks WHERE slug='kava'), 1, 'An earthy root drink from Oceania, drunk from a shell in one go.'),
((SELECT id FROM drinks WHERE slug='kava'), 2, 'Elders pound the root of a pepper plant, knead the pulp through cloth into a wooden bowl of water, and pass a coconut shell around.'),
((SELECT id FROM drinks WHERE slug='kava'), 3, 'Fiji''s muddy grey bowl, drunk in one swallow with a clap before and after, and your lips go numb.'),
((SELECT id FROM drinks WHERE slug='flat-white'), 1, 'A small milk coffee from Oceania, with no foam to speak of.'),
((SELECT id FROM drinks WHERE slug='flat-white'), 2, 'Sydney and Wellington both claim it from the mid-1980s, and the argument turns on steaming the milk to a thin gloss instead of a head.'),
((SELECT id FROM drinks WHERE slug='flat-white'), 3, 'Australia''s short white cup, a stretched shot under silky milk with a dot of art on top.'),
((SELECT id FROM drinks WHERE slug='lemon-lime-and-bitters'), 1, 'A pink pub soda from Oceania, poured for whoever is driving home.'),
((SELECT id FROM drinks WHERE slug='lemon-lime-and-bitters'), 2, 'Publicans shake a few drops of an aromatic tincture around an empty glass, then fill it with citrus soda and cordial over ice.'),
((SELECT id FROM drinks WHERE slug='lemon-lime-and-bitters'), 3, 'Australia''s blush-tinted tall glass, a wedge of lime on the rim and no alcohol in it.');
