-- Fall and winter: thirteen dishes and eight drinks for the cold months.
-- Pool only. The admin books dates and nights; no schedule rows here.

INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('Cheese Fondue','cheese-fondue','Switzerland','europe','entree','hot','vegetarian','["gruyere","emmental","white wine","garlic","kirsch","cornstarch","bread"]'),
('Tartiflette','tartiflette','France','europe','entree','hot','pork','["potato","reblochon","bacon","onion","white wine","cream"]'),
('Irish Stew','irish-stew','Ireland','europe','entree','hot','lamb','["lamb","potato","onion","carrot","thyme","parsley"]'),
('Bigos','bigos','Poland','europe','entree','hot','pork','["sauerkraut","cabbage","pork","sausage","mushroom","prunes","bay leaf"]'),
('Stollen','stollen','Germany','europe','dessert','cold','vegetarian','["flour","butter","raisins","candied peel","almond","marzipan","powdered sugar"]'),
('Bûche de Noël','buche-de-noel','France','europe','dessert','cold','vegetarian','["egg","sugar","flour","cocoa","cream","chocolate","meringue"]'),
('Pan de Muerto','pan-de-muerto','Mexico','latin-america','dessert','cold','vegetarian','["flour","butter","egg","sugar","orange","anise","yeast"]'),
('Oden','oden','Japan','east-asia','entree','hot','seafood','["daikon","egg","fish cake","konjac","dashi","soy sauce","mustard"]'),
('Tangyuan','tangyuan','China','east-asia','dessert','hot','vegetarian','["glutinous rice flour","black sesame","sugar","lard","ginger"]'),
('Sarson ka Saag','sarson-ka-saag','India','south-asia','entree','hot','vegetarian','["mustard greens","spinach","ghee","garlic","ginger","green chili","cornmeal"]'),
('Pot Roast','pot-roast','United States','north-america','entree','hot','beef','["beef","potato","carrot","onion","beef broth","thyme","bay leaf"]'),
('Green Bean Casserole','green-bean-casserole','United States','north-america','appetizer','hot','vegetarian','["green bean","mushroom","milk","soy sauce","fried onion","black pepper"]'),
('Kabak Tatlısı','kabak-tatlisi','Türkiye','middle-east','dessert','cold','vegetarian','["pumpkin","sugar","walnuts","tahini","clove"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='cheese-fondue'), 1, 'A shared pot for a cold night, from the mountains of central Europe.'),
((SELECT id FROM dishes WHERE slug='cheese-fondue'), 2, 'A dairy cartel pushed it as a national dish in the 1930s, to move more of what its members made.'),
((SELECT id FROM dishes WHERE slug='cheese-fondue'), 3, 'Lose your bread cube off the long fork and table custom says you buy the next round.'),
((SELECT id FROM dishes WHERE slug='cheese-fondue'), 4, 'You rub the pot with garlic, melt gruyere and emmental into white wine, and loosen it with a shot of kirsch.'),
((SELECT id FROM dishes WHERE slug='cheese-fondue'), 5, 'Switzerland''s bubbling caquelon over a burner, ringed by long forks spearing cubes of crusty loaf.'),
((SELECT id FROM dishes WHERE slug='tartiflette'), 1, 'A baked potato gratin from the ski slopes of western Europe.'),
((SELECT id FROM dishes WHERE slug='tartiflette'), 2, 'Savoie cheesemakers dreamed it up in the 1980s to sell more reblochon, and dressed it up as an old mountain recipe.'),
((SELECT id FROM dishes WHERE slug='tartiflette'), 3, 'Mountain dialect lent it an old word for potato, though the recipe is younger than most of the ski lifts.'),
((SELECT id FROM dishes WHERE slug='tartiflette'), 4, 'You layer sliced potato with bacon, onion, cream and a splash of white wine, then crown it with a halved reblochon, rind up.'),
((SELECT id FROM dishes WHERE slug='tartiflette'), 5, 'France''s Alpine après-ski supper, bubbling brown in its baking dish with a crackling orange crust.'),
((SELECT id FROM dishes WHERE slug='irish-stew'), 1, 'A one-pot meat and root supper from northwestern Europe.'),
((SELECT id FROM dishes WHERE slug='irish-stew'), 2, 'Cottagers simmered old mutton with roots in a single pot hung over a turf fire, since the hearth held no more.'),
((SELECT id FROM dishes WHERE slug='irish-stew'), 3, 'Cooks fight over carrot: purists say mutton, spuds and onion are the whole recipe, and orange is a Dublin affectation.'),
((SELECT id FROM dishes WHERE slug='irish-stew'), 4, 'You layer lamb neck chops between rounds of potato and onion, add water and thyme, and simmer it for two hours.'),
((SELECT id FROM dishes WHERE slug='irish-stew'), 5, 'Ireland''s pale brothy bowl of floury spuds and tender meat, scattered with parsley beside a hunk of soda bread.'),
((SELECT id FROM dishes WHERE slug='bigos'), 1, 'A dark, sour meat and cabbage pot from eastern Europe.'),
((SELECT id FROM dishes WHERE slug='bigos'), 2, 'Noble hunting parties cooked it at camp from whatever they shot, which is why it still goes by hunter''s stew.'),
((SELECT id FROM dishes WHERE slug='bigos'), 3, 'Families reheat one pot for a week and swear day three is best, and the national epic poem gives it a verse.'),
((SELECT id FROM dishes WHERE slug='bigos'), 4, 'You simmer sauerkraut and fresh cabbage for hours with pork, sausage, dried mushroom, prunes and bay leaf.'),
((SELECT id FROM dishes WHERE slug='bigos'), 5, 'Poland''s brown winter hotpot, sharp and smoky, spooned from a crock beside dark rye.'),
((SELECT id FROM dishes WHERE slug='stollen'), 1, 'A heavy fruit loaf from central Europe, baked for Christmas.'),
((SELECT id FROM dishes WHERE slug='stollen'), 2, 'Saxon bakers wrote to the Pope asking to use butter during the Advent fast, and a papal letter let them.'),
((SELECT id FROM dishes WHERE slug='stollen'), 3, 'Bakers shape it to look like the swaddled Christ child, and Dresden parades a giant one through town each December.'),
((SELECT id FROM dishes WHERE slug='stollen'), 4, 'You knead raisins and candied peel into a yeast dough rich with butter and almond, and roll a log of marzipan into the middle.'),
((SELECT id FROM dishes WHERE slug='stollen'), 5, 'Germany''s snow-white holiday bread under a thick dusting of powdered sugar, cut in thin slices through Advent.'),
((SELECT id FROM dishes WHERE slug='buche-de-noel'), 1, 'A rolled chocolate cake from western Europe, made for the winter holidays.'),
((SELECT id FROM dishes WHERE slug='buche-de-noel'), 2, 'Paris pastry cooks in the 1800s swapped the great block of wood families burned on the hearth for a cake shaped like it.'),
((SELECT id FROM dishes WHERE slug='buche-de-noel'), 3, 'You drag a fork through the frosting to make bark, and little meringue mushrooms sprout along its side.'),
((SELECT id FROM dishes WHERE slug='buche-de-noel'), 4, 'You bake a thin cocoa sponge, roll it around whipped cream, and coat the outside in chocolate ganache.'),
((SELECT id FROM dishes WHERE slug='buche-de-noel'), 5, 'France''s Christmas yule log, one end cut off at a slant like a sawn branch and dusted with sugar snow.'),
((SELECT id FROM dishes WHERE slug='pan-de-muerto'), 1, 'A sugared sweet bun from Latin America, baked for an autumn holiday.'),
((SELECT id FROM dishes WHERE slug='pan-de-muerto'), 2, 'Families bake it for the first days of November, and historians still argue whether it began as a Spanish or Aztec offering.'),
((SELECT id FROM dishes WHERE slug='pan-de-muerto'), 3, 'Bakers lay dough bones across the top and a skull on the crown, and families leave a loaf on home altars for the dead.'),
((SELECT id FROM dishes WHERE slug='pan-de-muerto'), 4, 'You scent an egg-rich yeast dough with orange zest and anise, bake it, then brush it with butter and roll it in sugar.'),
((SELECT id FROM dishes WHERE slug='pan-de-muerto'), 5, 'Mexico''s bread of the dead, a round sugar-crusted bun sitting on an ofrenda among marigolds and candles.'),
((SELECT id FROM dishes WHERE slug='oden'), 1, 'A winter one-pot of simmered odds and ends from East Asia.'),
((SELECT id FROM dishes WHERE slug='oden'), 2, 'Edo vendors took a skewered tofu snack and started simmering it in broth, and the pot grew to hold dozens of items.'),
((SELECT id FROM dishes WHERE slug='oden'), 3, 'Convenience store clerks keep a heated tray of it by the till all winter, and you fish out your own pieces with tongs.'),
((SELECT id FROM dishes WHERE slug='oden'), 4, 'You simmer daikon, boiled egg, fish cake and konjac in a light dashi seasoned with soy sauce, for hours and never at a boil.'),
((SELECT id FROM dishes WHERE slug='oden'), 5, 'Japan''s steaming divided pot of broth-soaked radish and tofu pouches, eaten with a dab of hot yellow mustard.'),
((SELECT id FROM dishes WHERE slug='tangyuan'), 1, 'A warm sweet soup of dumplings from East Asia.'),
((SELECT id FROM dishes WHERE slug='tangyuan'), 2, 'Families eat them at the winter solstice and the Lantern Festival, a custom going back to the Song dynasty.'),
((SELECT id FROM dishes WHERE slug='tangyuan'), 3, 'Diners hear the word for reunion in the name, so a shared bowl on a holiday means the family came home.'),
((SELECT id FROM dishes WHERE slug='tangyuan'), 4, 'You wrap black sesame paste creamed with sugar and lard in glutinous rice dough, roll balls, and boil them until they float.'),
((SELECT id FROM dishes WHERE slug='tangyuan'), 5, 'China''s glossy white rice balls bobbing in ginger syrup, spilling dark filling when you bite.'),
((SELECT id FROM dishes WHERE slug='sarson-ka-saag'), 1, 'A slow-cooked dish of winter greens from South Asia.'),
((SELECT id FROM dishes WHERE slug='sarson-ka-saag'), 2, 'Punjabi farm households cook it in the cold months, when the leaves come straight off their own winter fields.'),
((SELECT id FROM dishes WHERE slug='sarson-ka-saag'), 3, 'Cooks pair it with a crumbly flatbread of maize, and you top it with a lump of white butter.'),
((SELECT id FROM dishes WHERE slug='sarson-ka-saag'), 4, 'You simmer bitter leaves with spinach, ginger and green chili for hours, churn them with a wooden masher, and add cornmeal.'),
((SELECT id FROM dishes WHERE slug='sarson-ka-saag'), 5, 'India''s dark green mash of mustard greens, glossy with ghee and fried garlic, scooped up with yellow corn roti.'),
((SELECT id FROM dishes WHERE slug='pot-roast'), 1, 'A Sunday beef dinner from the American Midwest.'),
((SELECT id FROM dishes WHERE slug='pot-roast'), 2, 'Depression-era families bought the cheapest chuck and let a heavy lidded kettle turn it tender over one long afternoon.'),
((SELECT id FROM dishes WHERE slug='pot-roast'), 3, 'An internet version drops a packet of ranch mix and a jar of pepperoncini on top and walks away.'),
((SELECT id FROM dishes WHERE slug='pot-roast'), 4, 'You sear a chuck in a Dutch oven, add beef broth, carrot, potato, onion, thyme and bay leaf, and braise it for hours.'),
((SELECT id FROM dishes WHERE slug='pot-roast'), 5, 'America''s Sunday dinner, a fork-tender slab sliced beside its vegetables under brown gravy.'),
((SELECT id FROM dishes WHERE slug='green-bean-casserole'), 1, 'A creamy holiday side from North America, baked in a glass dish.'),
((SELECT id FROM dishes WHERE slug='green-bean-casserole'), 2, 'Dorcas Reilly worked it out in a Campbell''s test kitchen in 1955, to sell more cream of mushroom soup.'),
((SELECT id FROM dishes WHERE slug='green-bean-casserole'), 3, 'Her family gave the original handwritten card to the National Inventors Hall of Fame, and a museum keeps it there.'),
((SELECT id FROM dishes WHERE slug='green-bean-casserole'), 4, 'You stir snapped pods into canned mushroom soup with milk, soy sauce and black pepper, then bake it under crisp fried onion.'),
((SELECT id FROM dishes WHERE slug='green-bean-casserole'), 5, 'America''s Thanksgiving side, grey-green and bubbling under a crunchy crown of canned shallots.'),
((SELECT id FROM dishes WHERE slug='kabak-tatlisi'), 1, 'A candied autumn sweet from the Middle East, served cool.'),
((SELECT id FROM dishes WHERE slug='kabak-tatlisi'), 2, 'Anatolian households make it in autumn, when the markets fill with thick-skinned winter squash sold by the slice.'),
((SELECT id FROM dishes WHERE slug='kabak-tatlisi'), 3, 'Cooks pour tahini over the top and scatter crushed walnuts, a pairing that surprises diners who expect cream.'),
((SELECT id FROM dishes WHERE slug='kabak-tatlisi'), 4, 'You bury peeled wedges in sugar with a few cloves overnight, then simmer them in their own juice until they turn glassy.'),
((SELECT id FROM dishes WHERE slug='kabak-tatlisi'), 5, 'Türkiye''s pumpkin dessert, translucent orange slabs under a drizzle of sesame paste and nut crumbs.');

INSERT INTO drinks (name, slug, country, region, spirit, temperature, profile, is_alcoholic, ingredients) VALUES
('Hot Buttered Rum','hot-buttered-rum','United States','north-america','rum','hot','sweet',1,'["rum","butter","brown sugar","cinnamon","nutmeg","clove","water"]'),
('Tom and Jerry','tom-and-jerry','United States','north-america','brandy','hot','creamy',1,'["brandy","rum","egg","sugar","milk","nutmeg"]'),
('Canelazo','canelazo','Ecuador','latin-america','other','hot','sweet',1,'["aguardiente","naranjilla","cinnamon","sugar","water"]'),
('Coquito','coquito','Puerto Rico','latin-america','rum','cold','creamy',1,'["rum","coconut milk","condensed milk","cinnamon","nutmeg","vanilla"]'),
('Champurrado','champurrado','Mexico','latin-america','none','hot','creamy',0,'["corn","chocolate","brown sugar","cinnamon","milk","water"]'),
('Ponche Navideño','ponche-navideno','Mexico','latin-america','none','hot','sweet',0,'["guava","tejocote","sugar cane","apple","cinnamon","prunes","brown sugar"]'),
('Yuja Tea','yuja-tea','South Korea','east-asia','none','hot','sweet',0,'["yuzu","honey","sugar","water"]'),
('Pumpkin Spice Latte','pumpkin-spice-latte','United States','north-america','none','hot','sweet',0,'["espresso","milk","pumpkin","cinnamon","nutmeg","clove","sugar"]');

INSERT INTO drink_clues (drink_id, order_index, text) VALUES
((SELECT id FROM drinks WHERE slug='hot-buttered-rum'), 1, 'A steaming winter mug from colonial North America.'),
((SELECT id FROM drinks WHERE slug='hot-buttered-rum'), 2, 'New England distillers ran Caribbean molasses into cheap spirit, and taverns stirred it into hot water with brown sugar, clove and nutmeg.'),
((SELECT id FROM drinks WHERE slug='hot-buttered-rum'), 3, 'America''s dark amber mug, a pat melting on top into a golden slick with a cinnamon stick standing in it.'),
((SELECT id FROM drinks WHERE slug='tom-and-jerry'), 1, 'A frothy holiday mug from North America, built on a sweet batter.'),
((SELECT id FROM drinks WHERE slug='tom-and-jerry'), 2, 'A bartender and a London novelist both claim the origin. You beat eggs with sugar, then stretch a spoonful with brandy, rum and hot milk.'),
((SELECT id FROM drinks WHERE slug='tom-and-jerry'), 3, 'America''s Midwest Christmas cup, ladled from a milk-glass bowl with its name in gold, and nutmeg on the foam.'),
((SELECT id FROM drinks WHERE slug='canelazo'), 1, 'A hot fruit punch sold at street stalls in the high Andes of Latin America.'),
((SELECT id FROM drinks WHERE slug='canelazo'), 2, 'Highland vendors boil naranjilla juice with cane sugar and water, and you choose how much sugarcane aguardiente they pour in.'),
((SELECT id FROM drinks WHERE slug='canelazo'), 3, 'Ecuador''s cinnamon-steeped cup for cold nights, handed out steaming in Quito''s plazas during the December fiestas.'),
((SELECT id FROM drinks WHERE slug='coquito'), 1, 'A creamy chilled holiday drink from the Caribbean, poured into small glasses.'),
((SELECT id FROM drinks WHERE slug='coquito'), 2, 'Families on the island make it for December parties, blending white rum with coconut milk, condensed milk, cinnamon and vanilla.'),
((SELECT id FROM drinks WHERE slug='coquito'), 3, 'Puerto Rican households hand it out as gifts in recycled liquor bottles, and you sip it cold under grated nutmeg.'),
((SELECT id FROM drinks WHERE slug='champurrado'), 1, 'A hot drink from Latin America thick enough to coat the spoon.'),
((SELECT id FROM drinks WHERE slug='champurrado'), 2, 'Aztec cooks thickened cacao with ground maize before sugar arrived. Cooks now whisk masa into chocolate, milk and brown sugar.'),
((SELECT id FROM drinks WHERE slug='champurrado'), 3, 'Mexico''s December mug beside a plate of tamales, dark brown and gluey enough to grow a skin on top.'),
((SELECT id FROM drinks WHERE slug='ponche-navideno'), 1, 'A hot fruit brew ladled from a clay pot in Latin America, in winter.'),
((SELECT id FROM drinks WHERE slug='ponche-navideno'), 2, 'Families simmer it through the posadas in December, with guava, tejocote, apple, prunes and sticks of sugar cane in one big pot.'),
((SELECT id FROM drinks WHERE slug='ponche-navideno'), 3, 'Mexico''s Christmas punch, a clay mug of amber syrup with chunks of fruit and a stalk to chew.'),
((SELECT id FROM drinks WHERE slug='yuja-tea'), 1, 'A hot citrus cup from East Asia, spooned out of a jar of marmalade.'),
((SELECT id FROM drinks WHERE slug='yuja-tea'), 2, 'Households slice the bumpy citron thin in late autumn and pack it in jars with honey and sugar. You stir a spoonful into hot water.'),
((SELECT id FROM drinks WHERE slug='yuja-tea'), 3, 'Korea''s cold-season cure, a cup of cloudy gold with strands of peel left in for you to chew.'),
((SELECT id FROM drinks WHERE slug='pumpkin-spice-latte'), 1, 'A sweetened coffee-shop drink from North America, sold in autumn.'),
((SELECT id FROM drinks WHERE slug='pumpkin-spice-latte'), 2, 'A Seattle coffee chain launched it in 2003, and baristas pump a cinnamon, nutmeg and clove syrup into espresso and steamed milk.'),
((SELECT id FROM drinks WHERE slug='pumpkin-spice-latte'), 3, 'Americans line up for its return in late August, a milky orange cup under whipped cream and a dusting of cinnamon.');
