-- American diner and county-fair classics, plus staples missing from the
-- East and Southeast Asian, South Asian, and Latin American benches (Korean
-- fried chicken, kimchi, yakitori, katsu curry, roti canai, lechon, jalebi,
-- carnitas, birria) and a few gaps elsewhere (spaghetti bolognese, pepperoni
-- pizza, duck confit). Pool only; autofill assigns dates in /admin.

INSERT INTO dishes (name, slug, country, region, course, temperature, protein, ingredients) VALUES
('French Fries','french-fries','United States','north-america','appetizer','hot','vegetarian','["potato","vegetable oil","salt"]'),
('Onion Rings','onion-rings','United States','north-america','appetizer','hot','vegetarian','["onion","flour","egg","breadcrumbs","vegetable oil"]'),
('Chicken Tenders','chicken-tenders','United States','north-america','appetizer','hot','poultry','["chicken","flour","egg","breadcrumbs","vegetable oil"]'),
('Tater Tots','tater-tots','United States','north-america','appetizer','hot','vegetarian','["potato","vegetable oil","salt","cornstarch"]'),
('Ice Cream Sundae','ice-cream-sundae','United States','north-america','dessert','cold','vegetarian','["ice cream","chocolate syrup","whipped cream","cherry","sprinkles"]'),
('Root Beer Float','root-beer-float','United States','north-america','drink','cold','vegetarian','["soda water","sassafras","sugar","ice cream"]'),
('Milkshake','milkshake','United States','north-america','drink','cold','vegetarian','["milk","ice cream","sugar","vanilla"]'),
('Corned Beef Hash','corned-beef-hash','United States','north-america','breakfast','hot','beef','["beef","potato","onion","black pepper"]'),
('Chicken Fried Steak','chicken-fried-steak','United States','north-america','entree','hot','beef','["beef","flour","egg","buttermilk","gravy"]'),
('Chicken and Dumplings','chicken-and-dumplings','United States','north-america','entree','hot','poultry','["chicken","flour","butter","carrot","celery"]'),
('Cornbread','cornbread','United States','north-america','appetizer','hot','vegetarian','["cornmeal","flour","buttermilk","egg","honey"]'),
('Red Beans and Rice','red-beans-and-rice','United States','north-america','entree','hot','pork','["red bean","rice","sausage","onion","celery"]'),
('Baked Ziti','baked-ziti','United States','north-america','entree','hot','beef','["pasta","tomato","mozzarella","ricotta","beef"]'),
('Stromboli','stromboli','United States','north-america','entree','hot','pork','["flour","mozzarella","ham","pepperoni","tomato"]'),
('Meatball Sub','meatball-sub','United States','north-america','entree','hot','beef','["beef","tomato","mozzarella","hoagie roll","garlic"]'),
('Buffalo Chicken Sandwich','buffalo-chicken-sandwich','United States','north-america','entree','hot','poultry','["chicken","hot sauce","butter","bread roll","blue cheese"]'),
('Egg Salad Sandwich','egg-salad-sandwich','United States','north-america','appetizer','cold','vegetarian','["egg","mayonnaise","mustard","celery","bread"]'),
('Fried Cheese Curds','fried-cheese-curds','United States','north-america','appetizer','hot','vegetarian','["cheese curds","flour","egg","breadcrumbs","vegetable oil"]'),
('Peach Cobbler','peach-cobbler','United States','north-america','dessert','hot','vegetarian','["peach","flour","butter","sugar","cinnamon"]'),
('Banana Pudding','banana-pudding','United States','north-america','dessert','cold','vegetarian','["banana","vanilla wafer","milk","sugar","whipped cream"]'),
('Rice Pudding','rice-pudding','United States','north-america','dessert','cold','vegetarian','["rice","milk","sugar","cinnamon","raisins"]'),
('Whoopie Pie','whoopie-pie','United States','north-america','dessert','cold','vegetarian','["flour","cocoa","sugar","butter","marshmallow"]'),
('Rice Krispie Treats','rice-krispie-treats','United States','north-america','dessert','cold','vegetarian','["rice cereal","marshmallow","butter","sugar"]'),
('S''mores','smores','United States','north-america','dessert','hot','vegetarian','["marshmallow","chocolate","graham cracker"]'),
('Split Pea Soup','split-pea-soup','Canada','north-america','appetizer','hot','pork','["peas","ham","onion","carrot","bay leaf"]'),
('Orange Chicken','orange-chicken','China','east-asia','entree','hot','poultry','["chicken","orange","soy sauce","cornstarch","garlic"]'),
('Beef and Broccoli','beef-and-broccoli','China','east-asia','entree','hot','beef','["beef","broccoli","soy sauce","garlic","ginger"]'),
('Lo Mein','lo-mein','China','east-asia','entree','hot','vegetarian','["noodles","cabbage","carrot","scallion","soy sauce"]'),
('Egg Roll','egg-roll','China','east-asia','appetizer','hot','pork','["cabbage","pork","carrot","flour","egg"]'),
('Hot Pot','hot-pot','China','east-asia','entree','hot','beef','["beef","tofu","mushroom","cabbage","chili"]'),
('Bao Buns','bao-buns','China','east-asia','appetizer','hot','pork','["flour","yeast","pork","hoisin sauce","scallion"]'),
('Korean Fried Chicken','korean-fried-chicken','South Korea','east-asia','entree','hot','poultry','["chicken","cornstarch","gochujang","garlic","soy sauce"]'),
('Kimchi','kimchi','South Korea','east-asia','appetizer','cold','vegetarian','["cabbage","garlic","ginger","fish sauce","chili powder"]'),
('Yakitori','yakitori','Japan','east-asia','appetizer','hot','poultry','["chicken","soy sauce","mirin","sugar","scallion"]'),
('Katsu Curry','katsu-curry','Japan','east-asia','entree','hot','pork','["pork","breadcrumbs","curry powder","potato","carrot"]'),
('Thai Basil Chicken','thai-basil-chicken','Thailand','southeast-asia','entree','hot','poultry','["chicken","basil","chili","fish sauce","garlic"]'),
('Roti Canai','roti-canai','Malaysia','southeast-asia','breakfast','hot','vegetarian','["flour","ghee","butter","egg"]'),
('Lechon','lechon','Philippines','southeast-asia','entree','hot','pork','["pork","lemongrass","garlic","bay leaf"]'),
('Jalebi','jalebi','India','south-asia','dessert','hot','vegetarian','["flour","sugar","saffron","cardamom"]'),
('Carnitas','carnitas','Mexico','latin-america','entree','hot','pork','["pork","orange","garlic","cumin","bay leaf"]'),
('Birria','birria','Mexico','latin-america','entree','hot','beef','["beef","chili","cumin","bay leaf","cinnamon"]'),
('Spaghetti Bolognese','spaghetti-bolognese','Italy','europe','entree','hot','beef','["spaghetti","beef","tomato","onion","red wine"]'),
('Pepperoni Pizza','pepperoni-pizza','United States','north-america','entree','hot','pork','["flour","tomato","mozzarella","pepperoni","yeast"]'),
('Duck Confit','duck-confit','France','europe','entree','hot','poultry','["duck","garlic","thyme","salt","duck fat"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
((SELECT id FROM dishes WHERE slug='french-fries'), 1, 'A fried potato side that hitches a ride with almost any fast-food order.'),
((SELECT id FROM dishes WHERE slug='french-fries'), 2, 'Vendors near the Belgian border were frying potato batons by the 1680s, long before the dish crossed the Atlantic.'),
((SELECT id FROM dishes WHERE slug='french-fries'), 3, 'Belgians dunk this side in mayonnaise, not ketchup, and bristle when tourists ask for the red bottle.'),
((SELECT id FROM dishes WHERE slug='french-fries'), 4, 'You cut a potato into batons, soak them to pull out starch, then fry them twice for a shell that stays crisp.'),
((SELECT id FROM dishes WHERE slug='french-fries'), 5, 'America''s fast-food classic, a paper sleeve of golden potato batons dusted with salt.'),
((SELECT id FROM dishes WHERE slug='onion-rings'), 1, 'A fried starter that shows up wherever a drive-in flips a burger.'),
((SELECT id FROM dishes WHERE slug='onion-rings'), 2, 'A Texas curb-service chain battered and deep-fried sliced onion for parked customers back in the 1920s.'),
((SELECT id FROM dishes WHERE slug='onion-rings'), 3, 'Cutting the onion crosswise into loops, not lengthwise into strips, is what gives this snack its shape.'),
((SELECT id FROM dishes WHERE slug='onion-rings'), 4, 'The cook dips onion loops in batter and crumbs, then fries them until the coating turns deep gold.'),
((SELECT id FROM dishes WHERE slug='onion-rings'), 5, 'An American diner basket of crisp golden loops, stacked beside a bowl of dipping sauce.'),
((SELECT id FROM dishes WHERE slug='chicken-tenders'), 1, 'A breaded fried snack that took over school trays and drive-in menus alike.'),
((SELECT id FROM dishes WHERE slug='chicken-tenders'), 2, 'Fast-food chains built a whole 1980s menu item around a strip of breast muscle cooks once ground into scraps.'),
((SELECT id FROM dishes WHERE slug='chicken-tenders'), 3, 'Only one strip like this comes from each bird, cut from the muscle nearest the breastbone.'),
((SELECT id FROM dishes WHERE slug='chicken-tenders'), 4, 'The cook breads a strip of breast meat, then fries it until the crust cracks and the center stays juicy.'),
((SELECT id FROM dishes WHERE slug='chicken-tenders'), 5, 'An American lunch-counter basket of breaded golden strips, served with a ramekin of dipping sauce.'),
((SELECT id FROM dishes WHERE slug='tater-tots'), 1, 'A fried potato side shaped by a school-lunch tray rather than a knife.'),
((SELECT id FROM dishes WHERE slug='tater-tots'), 2, 'An Oregon processor in 1953 pressed leftover potato scraps into small cylinders instead of discarding them.'),
((SELECT id FROM dishes WHERE slug='tater-tots'), 3, 'The shape is a small cylinder built entirely from potato scraps, never from a whole sliced potato.'),
((SELECT id FROM dishes WHERE slug='tater-tots'), 4, 'The cook shreds potato, presses the scraps into short cylinders, and deep-fries them until the outside turns crisp.'),
((SELECT id FROM dishes WHERE slug='tater-tots'), 5, 'America''s cafeteria-tray favorite, a pile of crisp golden cylinders beside a pool of ketchup.'),
((SELECT id FROM dishes WHERE slug='ice-cream-sundae'), 1, 'A soda-fountain dessert served in a tall glass dish.'),
((SELECT id FROM dishes WHERE slug='ice-cream-sundae'), 2, 'Several towns claim the invention, built to dodge blue laws that banned soda sales on the Sabbath.'),
((SELECT id FROM dishes WHERE slug='ice-cream-sundae'), 3, 'Every town that claims the invention swears its own soda counter did it first.'),
((SELECT id FROM dishes WHERE slug='ice-cream-sundae'), 4, 'The fountain worker scoops dessert into a dish, pours on flavored syrup, then tops it with cream and a cherry.'),
((SELECT id FROM dishes WHERE slug='ice-cream-sundae'), 5, 'America''s soda-fountain classic, a scoop drowned in syrup under cream and a bright red cherry.'),
((SELECT id FROM dishes WHERE slug='root-beer-float'), 1, 'A fizzy soda-fountain drink where dessert and soda share one glass.'),
((SELECT id FROM dishes WHERE slug='root-beer-float'), 2, 'A Colorado shopkeeper dropped frozen dessert into his dark, spiced soda in 1893, and it foamed over the rim.'),
((SELECT id FROM dishes WHERE slug='root-beer-float'), 3, 'The scoop drops into the glass whole and only breaks apart once you start spooning it out.'),
((SELECT id FROM dishes WHERE slug='root-beer-float'), 4, 'The server pours dark, spice-scented soda over a scoop of frozen dessert and lets the foam rise before serving.'),
((SELECT id FROM dishes WHERE slug='root-beer-float'), 5, 'America''s fizzy brown glass under a white scoop, sipped through a straw beside a long spoon.'),
((SELECT id FROM dishes WHERE slug='milkshake'), 1, 'A thick blended drink spun up behind a soda-fountain counter.'),
((SELECT id FROM dishes WHERE slug='milkshake'), 2, 'Soda jerks in the 1920s began spinning frozen dessert on an upright mixer into a much thicker drink.'),
((SELECT id FROM dishes WHERE slug='milkshake'), 3, 'The drinker needs a spoon before the straw does any real work.'),
((SELECT id FROM dishes WHERE slug='milkshake'), 4, 'The fountain worker blends milk with ice cream and flavoring on a spindle mixer until it turns thick and pale.'),
((SELECT id FROM dishes WHERE slug='milkshake'), 5, 'America''s tall fluted glass, so dense the straw stands upright, poured with extra in a metal cup.'),
((SELECT id FROM dishes WHERE slug='corned-beef-hash'), 1, 'A skillet breakfast plate found at diners across the Northeast.'),
((SELECT id FROM dishes WHERE slug='corned-beef-hash'), 2, 'New England cooks chopped up Monday''s leftover salted meat and boiled potato to build this skillet plate.'),
((SELECT id FROM dishes WHERE slug='corned-beef-hash'), 3, 'A fried egg lands on top nine times out of ten, judged by the crust that forms underneath before the flip.'),
((SELECT id FROM dishes WHERE slug='corned-beef-hash'), 4, 'The cook dices cured meat with potato and onion, then presses it flat in a hot pan until a crust forms underneath.'),
((SELECT id FROM dishes WHERE slug='corned-beef-hash'), 5, 'America''s diner skillet, a browned heap of chopped meat and potato topped with a fried egg.'),
((SELECT id FROM dishes WHERE slug='chicken-fried-steak'), 1, 'A breaded skillet entree from Texas and the American South.'),
((SELECT id FROM dishes WHERE slug='chicken-fried-steak'), 2, 'German and Austrian settlers in nineteenth-century Texas adapted their breaded veal cutlet to a cheaper cut of beef.'),
((SELECT id FROM dishes WHERE slug='chicken-fried-steak'), 3, 'The name describes a cooking method, not a bird, which confuses diners expecting poultry on the plate.'),
((SELECT id FROM dishes WHERE slug='chicken-fried-steak'), 4, 'The cook pounds a tough cut thin, dredges it in seasoned flour, dips it in buttermilk and egg, then cooks it in a skillet.'),
((SELECT id FROM dishes WHERE slug='chicken-fried-steak'), 5, 'America''s Texas diner plate, a breaded cutlet buried under peppery white gravy beside mashed potato.'),
((SELECT id FROM dishes WHERE slug='chicken-and-dumplings'), 1, 'A one-pot skillet dinner from Appalachia and the American South.'),
((SELECT id FROM dishes WHERE slug='chicken-and-dumplings'), 2, 'Depression-era cooks stretched one bird across a whole family by dropping dough balls into the simmering pot.'),
((SELECT id FROM dishes WHERE slug='chicken-and-dumplings'), 3, 'A single bird has to feed a table of six or more, so the pot fills out with dough instead of meat.'),
((SELECT id FROM dishes WHERE slug='chicken-and-dumplings'), 4, 'The cook simmers meat with carrot and celery, then drops spoonfuls of soft dough on top to steam until puffed.'),
((SELECT id FROM dishes WHERE slug='chicken-and-dumplings'), 5, 'The American South''s simmered pot, torn meat and pillowy dough afloat in thick pale broth.'),
((SELECT id FROM dishes WHERE slug='cornbread'), 1, 'A skillet-baked side served across the American South.'),
((SELECT id FROM dishes WHERE slug='cornbread'), 2, 'Indigenous farmers across the Americas ground this dish''s grain into meal centuries before settlers adopted the recipe.'),
((SELECT id FROM dishes WHERE slug='cornbread'), 3, 'Bakers heat the empty skillet in the oven first, so the batter starts sizzling the instant it hits the metal.'),
((SELECT id FROM dishes WHERE slug='cornbread'), 4, 'The baker mixes ground grain with buttermilk and egg, pours it into a scorching skillet, and bakes it until dark.'),
((SELECT id FROM dishes WHERE slug='cornbread'), 5, 'A Southern American wedge, golden and slightly gritty, split open and slicked with melting butter.'),
((SELECT id FROM dishes WHERE slug='red-beans-and-rice'), 1, 'A simmered pot dish from Louisiana''s bayou kitchens.'),
((SELECT id FROM dishes WHERE slug='red-beans-and-rice'), 2, 'Creole households in one southern city cooked this pot every washday, using Sunday''s leftover ham bone.'),
((SELECT id FROM dishes WHERE slug='red-beans-and-rice'), 3, 'A jazz trumpeter from that city signed his letters with a phrase built from this pot''s own name.'),
((SELECT id FROM dishes WHERE slug='red-beans-and-rice'), 4, 'The cook simmers dried legumes for hours with sausage, onion and celery, then spoons it over steamed grain.'),
((SELECT id FROM dishes WHERE slug='red-beans-and-rice'), 5, 'America''s Monday pot from Louisiana, a thick reddish stew ladled over white rice with a link of sausage.'),
((SELECT id FROM dishes WHERE slug='baked-ziti'), 1, 'A baked pasta casserole from Italian-American kitchens.'),
((SELECT id FROM dishes WHERE slug='baked-ziti'), 2, 'Immigrant cooks in early-1900s American cities stretched an Italian oven-pasta habit with cheap ground meat.'),
((SELECT id FROM dishes WHERE slug='baked-ziti'), 3, 'One pan reheats in the dish it baked in and stretches to feed a crowd, which is why potlucks lean on it.'),
((SELECT id FROM dishes WHERE slug='baked-ziti'), 4, 'The cook tosses tube pasta with tomato sauce and ground meat, layers in two cheeses, and bakes until it browns.'),
((SELECT id FROM dishes WHERE slug='baked-ziti'), 5, 'An American red-sauce casserole, tubes of pasta bound in melted cheese under a browned, bubbling top.'),
((SELECT id FROM dishes WHERE slug='stromboli'), 1, 'A rolled, baked entree from Italian-American pizzerias.'),
((SELECT id FROM dishes WHERE slug='stromboli'), 2, 'A Pennsylvania pizzeria owner in the 1950s rolled dough around meat and cheese, naming it after a volcanic island.'),
((SELECT id FROM dishes WHERE slug='stromboli'), 3, 'Diners cut it into rounds rather than wedges, since the filling spirals through the dough instead of sitting flat.'),
((SELECT id FROM dishes WHERE slug='stromboli'), 4, 'The cook layers cured meats and cheese onto flattened dough, rolls the sheet into a log, and bakes it until golden.'),
((SELECT id FROM dishes WHERE slug='stromboli'), 5, 'An American pizzeria log, sliced into spirals of melted cheese and cured meat inside a golden crust.'),
((SELECT id FROM dishes WHERE slug='meatball-sub'), 1, 'A hot sandwich from Italian-American delis in the Northeast.'),
((SELECT id FROM dishes WHERE slug='meatball-sub'), 2, 'Italian butchers in early-twentieth-century American cities ground scrap cuts into balls, since the whole cut cost too much.'),
((SELECT id FROM dishes WHERE slug='meatball-sub'), 3, 'The bread has to survive a soaking in sauce without falling apart, which is the real test of the right roll.'),
((SELECT id FROM dishes WHERE slug='meatball-sub'), 4, 'The cook simmers ground meat in tomato sauce, piles it into a long roll, and melts cheese over it under a broiler.'),
((SELECT id FROM dishes WHERE slug='meatball-sub'), 5, 'An American deli favorite, a long roll packed with sauced meat and stretched, browned cheese.'),
((SELECT id FROM dishes WHERE slug='buffalo-chicken-sandwich'), 1, 'A spicy sandwich that grew out of a bar snack from upstate New York.'),
((SELECT id FROM dishes WHERE slug='buffalo-chicken-sandwich'), 2, 'A bar in a New York border city tossed fried wings in a butter-hot sauce blend in 1964, and the coating later moved to a roll.'),
((SELECT id FROM dishes WHERE slug='buffalo-chicken-sandwich'), 3, 'The tangy pale cheese served with it once cooled the same sauce on the bar snack, not a sandwich topping.'),
((SELECT id FROM dishes WHERE slug='buffalo-chicken-sandwich'), 4, 'The cook batters and fries a piece, tosses it in a butter-hot sauce blend, and sets it on a roll with cool cheese.'),
((SELECT id FROM dishes WHERE slug='buffalo-chicken-sandwich'), 5, 'America''s upstate New York sandwich, a fiery orange-red cutlet on a soft roll with pale, tangy cheese.'),
((SELECT id FROM dishes WHERE slug='egg-salad-sandwich'), 1, 'A cold sandwich built for lunch counters and church-potluck tables.'),
((SELECT id FROM dishes WHERE slug='egg-salad-sandwich'), 2, 'Boardinghouse cooks in the late 1800s chopped up a cheap breakfast staple and bound it with a creamy sauce for lunch.'),
((SELECT id FROM dishes WHERE slug='egg-salad-sandwich'), 3, 'The filling has almost no crunch on its own, so celery gets folded in to give it something to bite against.'),
((SELECT id FROM dishes WHERE slug='egg-salad-sandwich'), 4, 'The cook chops a boiled staple, binds it with a creamy sauce and mustard, and folds in diced celery.'),
((SELECT id FROM dishes WHERE slug='egg-salad-sandwich'), 5, 'An American deli-counter favorite, a chunky pale yellow filling between two slices of soft bread.'),
((SELECT id FROM dishes WHERE slug='fried-cheese-curds'), 1, 'A fried appetizer sold at dairy-state fairs in the Midwest.'),
((SELECT id FROM dishes WHERE slug='fried-cheese-curds'), 2, 'Small dairy plants in one Midwestern state started battering fresh cheese pieces and frying them for fairgoers.'),
((SELECT id FROM dishes WHERE slug='fried-cheese-curds'), 3, 'The pieces squeak against your teeth as you chew, a trait that only lasts before a batch ages into a proper wheel.'),
((SELECT id FROM dishes WHERE slug='fried-cheese-curds'), 4, 'The cook batters small fresh pieces, drops them in hot oil, and pulls them the moment the shell turns golden.'),
((SELECT id FROM dishes WHERE slug='fried-cheese-curds'), 5, 'America''s Wisconsin fairground basket, golden nuggets that squeak when you bite through the crisp shell.'),
((SELECT id FROM dishes WHERE slug='peach-cobbler'), 1, 'A warm baked fruit dessert spooned from kitchens across the American South.'),
((SELECT id FROM dishes WHERE slug='peach-cobbler'), 2, 'Frontier cooks lacking the equipment for a proper pastry lid dropped rough spoonfuls of dough over the fruit instead.'),
((SELECT id FROM dishes WHERE slug='peach-cobbler'), 3, 'The topping is deliberately uneven, dropped rather than rolled, which is what earned this dessert its name.'),
((SELECT id FROM dishes WHERE slug='peach-cobbler'), 4, 'The cook tosses sliced fruit with sugar and spice, drops biscuit dough on top, and bakes it until deep gold.'),
((SELECT id FROM dishes WHERE slug='peach-cobbler'), 5, 'A Southern American dessert, bubbling orange fruit under a craggy, golden biscuit crust.'),
((SELECT id FROM dishes WHERE slug='banana-pudding'), 1, 'A chilled layered dessert built in Southern American kitchens.'),
((SELECT id FROM dishes WHERE slug='banana-pudding'), 2, 'A biscuit company printed the layered recipe on its box in the early 1900s, and Southern cooks kept the layout.'),
((SELECT id FROM dishes WHERE slug='banana-pudding'), 3, 'The biscuits at the bottom go soft on purpose, soaking into custard until they taste closer to cake than cracker.'),
((SELECT id FROM dishes WHERE slug='banana-pudding'), 4, 'The cook layers sliced fruit and crisp biscuits with custard, then chills the dish until the biscuits soften.'),
((SELECT id FROM dishes WHERE slug='banana-pudding'), 5, 'A Southern American trifle dish, sliced fruit and softened wafers under a cloud of whipped cream.'),
((SELECT id FROM dishes WHERE slug='rice-pudding'), 1, 'A creamy chilled dessert that turns up in nursery kitchens and diner pie cases.'),
((SELECT id FROM dishes WHERE slug='rice-pudding'), 2, 'Home cooks turned a cheap grain and leftover milk into a nursery dessert, spiced with whatever sat in the cupboard.'),
((SELECT id FROM dishes WHERE slug='rice-pudding'), 3, 'The grain keeps its shape completely, so every spoonful still carries a bite against the creamy base.'),
((SELECT id FROM dishes WHERE slug='rice-pudding'), 4, 'The cook simmers grain slowly in milk and sugar until thick and creamy, then stirs in spice and dried fruit.'),
((SELECT id FROM dishes WHERE slug='rice-pudding'), 5, 'An American comfort bowl, plump pale grains suspended in a sweet, cinnamon-flecked cream.'),
((SELECT id FROM dishes WHERE slug='whoopie-pie'), 1, 'A handheld sandwich dessert from New England and Pennsylvania Dutch country.'),
((SELECT id FROM dishes WHERE slug='whoopie-pie'), 2, 'Amish farm wives baked spare cake batter into small rounds and packed them with a sweet filling for lunch pails.'),
((SELECT id FROM dishes WHERE slug='whoopie-pie'), 3, 'Farm children are said to have shouted a two-word exclamation on finding one packed in their lunch, and the name stuck.'),
((SELECT id FROM dishes WHERE slug='whoopie-pie'), 4, 'The baker bakes two soft cake-like rounds, spreads a sweet fluffy filling between them, and presses the halves shut.'),
((SELECT id FROM dishes WHERE slug='whoopie-pie'), 5, 'America''s New England farm-stand treat, two dark cake rounds sandwiched around a thick white filling.'),
((SELECT id FROM dishes WHERE slug='rice-krispie-treats'), 1, 'A no-bake bar dessert that lives in lunchboxes and bake-sale tables.'),
((SELECT id FROM dishes WHERE slug='rice-krispie-treats'), 2, 'A cereal company employee invented this bar in 1939 for a girls'' club to sell door to door.'),
((SELECT id FROM dishes WHERE slug='rice-krispie-treats'), 3, 'No oven ever touches the finished bar, since melted binder alone holds the puffed grain together.'),
((SELECT id FROM dishes WHERE slug='rice-krispie-treats'), 4, 'The cook melts butter and a soft sugary binder, folds in puffed grain cereal, and presses it flat before it sets.'),
((SELECT id FROM dishes WHERE slug='rice-krispie-treats'), 5, 'An American lunchbox square, pale puffed grain bound into a chewy, faintly sticky bar.'),
((SELECT id FROM dishes WHERE slug='smores'), 1, 'A campfire dessert assembled by hand around any fire pit with marshmallows nearby.'),
((SELECT id FROM dishes WHERE slug='smores'), 2, 'A 1927 guidebook for a girls'' outdoor club printed the recipe under a name shortened from campers asking for seconds.'),
((SELECT id FROM dishes WHERE slug='smores'), 3, 'A stick held over open flame does the only cooking this dessert ever needs, no oven involved.'),
((SELECT id FROM dishes WHERE slug='smores'), 4, 'The camper toasts a soft sugary puff over open flame, then presses it with chocolate between two crackers.'),
((SELECT id FROM dishes WHERE slug='smores'), 5, 'America''s campfire treat, a molten white puff and melting chocolate squeezed between two crisp crackers.'),
((SELECT id FROM dishes WHERE slug='split-pea-soup'), 1, 'A thick simmered soup built to survive a long, cold-winter haul.'),
((SELECT id FROM dishes WHERE slug='split-pea-soup'), 2, 'Fur traders and lumber camps needed a filling meal that kept without refrigeration, so this dried-legume pot traveled with them.'),
((SELECT id FROM dishes WHERE slug='split-pea-soup'), 3, 'The finished pot turns thick enough that a spoon stands up in it, which is exactly why camps trusted it to travel.'),
((SELECT id FROM dishes WHERE slug='split-pea-soup'), 4, 'The cook simmers a ham bone with peas, onion and carrot for hours until the pot turns thick and green.'),
((SELECT id FROM dishes WHERE slug='split-pea-soup'), 5, 'Canada''s dense green pot from Quebec, a smoky ham bone poking through a thick, velvety puree.'),
((SELECT id FROM dishes WHERE slug='orange-chicken'), 1, 'A sweet, sticky fried entree popularized at American mall food courts.'),
((SELECT id FROM dishes WHERE slug='orange-chicken'), 2, 'A chef at a Hawaii fast-casual chain created this dish in 1987, aiming for a citrus glaze sweeter than sour Hunan sauces.'),
((SELECT id FROM dishes WHERE slug='orange-chicken'), 3, 'Almost every piece on the plate wears the same glossy sauce, so the fruit in the name rarely shows up as actual fruit.'),
((SELECT id FROM dishes WHERE slug='orange-chicken'), 4, 'The cook fries battered meat until crisp, then tosses it in a sticky, citrus-sweetened glaze thickened with cornstarch.'),
((SELECT id FROM dishes WHERE slug='orange-chicken'), 5, 'A Chinese-American takeout carton, glossy citrus-glazed pieces piled over steamed white rice.'),
((SELECT id FROM dishes WHERE slug='beef-and-broccoli'), 1, 'A quick stir-fried entree that rides home in a folded paper carton.'),
((SELECT id FROM dishes WHERE slug='beef-and-broccoli'), 2, 'Cantonese cooks who emigrated to nineteenth-century American cities swapped in a Western vegetable their new customers knew.'),
((SELECT id FROM dishes WHERE slug='beef-and-broccoli'), 3, 'The green vegetable in the name only entered the recipe once the dish crossed the Pacific from Cantonese kitchens.'),
((SELECT id FROM dishes WHERE slug='beef-and-broccoli'), 4, 'The cook sears thin-sliced meat over high heat, adds chopped florets, and finishes both in a glossy garlic-ginger sauce.'),
((SELECT id FROM dishes WHERE slug='beef-and-broccoli'), 5, 'A Chinese-American takeout classic, dark glazed strips of meat tangled with bright green florets over rice.'),
((SELECT id FROM dishes WHERE slug='lo-mein'), 1, 'A tangled noodle entree tossed to order behind a takeout counter''s glass window.'),
((SELECT id FROM dishes WHERE slug='lo-mein'), 2, 'Cantonese cooks named this plate for the tossing motion used to coat cooked strands, not for how the strands were cooked.'),
((SELECT id FROM dishes WHERE slug='lo-mein'), 3, 'The strands boil first and only meet sauce afterward in a hot pan, never simmered together like a soupier noodle dish.'),
((SELECT id FROM dishes WHERE slug='lo-mein'), 4, 'The cook boils wheat strands separately, then tosses them through a hot pan with shredded vegetables and a dark sauce.'),
((SELECT id FROM dishes WHERE slug='lo-mein'), 5, 'China''s takeout-counter tangle, glossy dark strands threaded with slivers of vegetable.'),
((SELECT id FROM dishes WHERE slug='egg-roll'), 1, 'A deep-fried appetizer that rounds out almost any combo-plate order.'),
((SELECT id FROM dishes WHERE slug='egg-roll'), 2, 'A New York City chef published one of the first English recipes for this thick-skinned fried starter in 1917.'),
((SELECT id FROM dishes WHERE slug='egg-roll'), 3, 'The wrapper fries up thick and craggy rather than thin and shattering, unlike its lighter cousin abroad.'),
((SELECT id FROM dishes WHERE slug='egg-roll'), 4, 'The cook wraps shredded cabbage and minced meat in a thick wrapper, seals the edge, and deep-fries it until it blisters.'),
((SELECT id FROM dishes WHERE slug='egg-roll'), 5, 'A Chinese-American restaurant starter, a blistered golden cylinder cut open to show shredded cabbage inside.'),
((SELECT id FROM dishes WHERE slug='hot-pot'), 1, 'A communal simmering meal where the diners do the cooking, not the kitchen.'),
((SELECT id FROM dishes WHERE slug='hot-pot'), 2, 'Mongolian cavalry are said to have cooked meals this way over open fires between marches, centuries before it moved indoors.'),
((SELECT id FROM dishes WHERE slug='hot-pot'), 3, 'No diner at the table gets a finished plate; each one cooks their own share a few pieces at a time.'),
((SELECT id FROM dishes WHERE slug='hot-pot'), 4, 'Diners drop thin-sliced meat, tofu and vegetables straight into a simmering pot and fish them out with chopsticks.'),
((SELECT id FROM dishes WHERE slug='hot-pot'), 5, 'China''s shared tabletop pot, a bubbling broth crowded with meat, tofu and vegetables diners cook themselves.'),
((SELECT id FROM dishes WHERE slug='bao-buns'), 1, 'A steamed appetizer from Cantonese dim sum kitchens.'),
((SELECT id FROM dishes WHERE slug='bao-buns'), 2, 'Cantonese cooks in southern China have steamed dough around a savory filling for teahouse carts since the 1800s.'),
((SELECT id FROM dishes WHERE slug='bao-buns'), 3, 'Steam alone puffs the dough, since no oven ever touches this parcel before it reaches the table.'),
((SELECT id FROM dishes WHERE slug='bao-buns'), 4, 'The cook steams a pillowy dough parcel over simmering water until it puffs, then fills it with sweet glazed meat.'),
((SELECT id FROM dishes WHERE slug='bao-buns'), 5, 'China''s Cantonese teahouse-cart favorite, a pale pillowy parcel pulled open to show glazed meat inside.'),
((SELECT id FROM dishes WHERE slug='korean-fried-chicken'), 1, 'A fried entree that built a whole late-night delivery culture around one bird.'),
((SELECT id FROM dishes WHERE slug='korean-fried-chicken'), 2, 'American army bases introduced fried poultry to the region after a mid-century war, and cooks reworked it with a sticky glaze.'),
((SELECT id FROM dishes WHERE slug='korean-fried-chicken'), 3, 'The crust survives a dunk in sticky glaze without turning soggy, since it gets fried twice before any sauce touches it.'),
((SELECT id FROM dishes WHERE slug='korean-fried-chicken'), 4, 'The cook fries battered pieces once for structure, fries them again for crunch, then tosses them in a sweet, spicy glaze.'),
((SELECT id FROM dishes WHERE slug='korean-fried-chicken'), 5, 'South Korea''s late-night delivery order, glossy red-glazed pieces still crackling under the sauce.'),
((SELECT id FROM dishes WHERE slug='kimchi'), 1, 'A fermented side dish that turns sharper and redder the longer it waits.'),
((SELECT id FROM dishes WHERE slug='kimchi'), 2, 'Cooks buried jars of salted vegetables underground through winter long before chili peppers ever reached the peninsula.'),
((SELECT id FROM dishes WHERE slug='kimchi'), 3, 'Some rural households still bury whole jars underground each winter for the flavor the cold ground gives it.'),
((SELECT id FROM dishes WHERE slug='kimchi'), 4, 'The cook salts a leafy vegetable, rubs it with garlic, ginger and chili paste, then packs it into a jar to ferment.'),
((SELECT id FROM dishes WHERE slug='kimchi'), 5, 'South Korea''s tangy side dish, red-flecked leaves packed tight in a jar and served cold at every meal.'),
((SELECT id FROM dishes WHERE slug='yakitori'), 1, 'A skewered street food charred fast over a bed of glowing coals.'),
((SELECT id FROM dishes WHERE slug='yakitori'), 2, 'Vendors at seventeenth-century post towns grilled cheap cuts on sticks for travelers, at a time this bird was frowned on.'),
((SELECT id FROM dishes WHERE slug='yakitori'), 3, 'Bar cooks keep each stick down to one bite, so a whole meal there gets measured in sticks rather than plates.'),
((SELECT id FROM dishes WHERE slug='yakitori'), 4, 'The cook threads bite-size pieces onto a bamboo stick and grills them over charcoal, brushing on a sweet soy glaze.'),
((SELECT id FROM dishes WHERE slug='yakitori'), 5, 'Japan''s smoky charcoal stall, small skewers glazed dark and glistening, stacked in a jar by the register.'),
((SELECT id FROM dishes WHERE slug='katsu-curry'), 1, 'A breaded cutlet plate eaten with a spoon instead of chopsticks.'),
((SELECT id FROM dishes WHERE slug='katsu-curry'), 2, 'A European island nation''s navy introduced a spiced Western sauce in the 1800s, and cooks paired it with a breaded cutlet.'),
((SELECT id FROM dishes WHERE slug='katsu-curry'), 3, 'The sauce underneath is thicker and sweeter than the dish it borrows its spices from, closer to gravy than soup.'),
((SELECT id FROM dishes WHERE slug='katsu-curry'), 4, 'The cook fries a breaded cutlet until golden, slices it, and sets it over rice under a thick, mild sauce.'),
((SELECT id FROM dishes WHERE slug='katsu-curry'), 5, 'A Japanese lunch-counter plate, a sliced golden cutlet fanned over rice under a pool of brown sauce.'),
((SELECT id FROM dishes WHERE slug='thai-basil-chicken'), 1, 'A one-plate stir-fry cooked to order behind a rice-cart''s tiny gas burner.'),
((SELECT id FROM dishes WHERE slug='thai-basil-chicken'), 2, 'Roadside cart cooks built this fast plate around a fiery peppery herb, distinct from the sweeter herb Western kitchens use.'),
((SELECT id FROM dishes WHERE slug='thai-basil-chicken'), 3, 'A fried egg with a runny yolk lands on top more than not, breaking over the rice the moment a fork goes in.'),
((SELECT id FROM dishes WHERE slug='thai-basil-chicken'), 4, 'The cook stir-fries minced meat with garlic and chili, folds in a fistful of peppery leaves at the end, then spoons it over rice.'),
((SELECT id FROM dishes WHERE slug='thai-basil-chicken'), 5, 'Thailand''s rice-cart plate, minced meat flecked dark green under a fried egg with a runny yolk.'),
((SELECT id FROM dishes WHERE slug='roti-canai'), 1, 'A stretched flatbread slapped and spun thin enough to see daylight through it.'),
((SELECT id FROM dishes WHERE slug='roti-canai'), 2, 'Immigrant cooks from southern India settled in Southeast Asia and brought the stretched-dough technique with them.'),
((SELECT id FROM dishes WHERE slug='roti-canai'), 3, 'The cook slaps and stretches the dough against a flat griddle until it turns almost paper-thin.'),
((SELECT id FROM dishes WHERE slug='roti-canai'), 4, 'The cook flattens and stretches oiled dough into a thin sheet, folds it into layers, and fries it on a griddle until flaky.'),
((SELECT id FROM dishes WHERE slug='roti-canai'), 5, 'Malaysia''s breakfast-stall flatbread, flaky golden layers torn by hand and dipped into a bowl of curry.'),
((SELECT id FROM dishes WHERE slug='lechon'), 1, 'A whole roasted centerpiece turned slowly over open coals for hours.'),
((SELECT id FROM dishes WHERE slug='lechon'), 2, 'Colonizers introduced a whole-animal spit-roasting method centuries ago, and two rival cities still argue whose version is true.'),
((SELECT id FROM dishes WHERE slug='lechon'), 3, 'A whole animal turns on a spit for hours, so this dish only appears at gatherings large enough to justify one.'),
((SELECT id FROM dishes WHERE slug='lechon'), 4, 'The cook stuffs the cavity with lemongrass and garlic, then turns the whole animal slowly over open coals until the skin blisters.'),
((SELECT id FROM dishes WHERE slug='lechon'), 5, 'The Philippines'' festival centerpiece, a whole roasted animal with skin cracked deep amber, carved tableside.'),
((SELECT id FROM dishes WHERE slug='jalebi'), 1, 'A syrup-soaked fried sweet that stains your fingers day-glo orange.'),
((SELECT id FROM dishes WHERE slug='jalebi'), 2, 'Traders carried a coiled, syrup-soaked sweet east from the Middle East centuries ago, and cooks brightened the syrup with saffron.'),
((SELECT id FROM dishes WHERE slug='jalebi'), 3, 'Cooks pipe the batter straight into hot oil in loose spirals, so no two coils ever come out the same shape.'),
((SELECT id FROM dishes WHERE slug='jalebi'), 4, 'The cook pipes fermented batter through hot oil in loose spirals, fries it crisp, then soaks the whole coil in warm syrup.'),
((SELECT id FROM dishes WHERE slug='jalebi'), 5, 'India''s roadside sweet stall, orange spiraled coils glistening with syrup, sold hot off the pan.'),
((SELECT id FROM dishes WHERE slug='carnitas'), 1, 'A slow-cooked dish sold by the kilo at open-air weekend markets.'),
((SELECT id FROM dishes WHERE slug='carnitas'), 2, 'Cooks in one central Mexican state built this dish on simmering meat for hours in its own rendered fat.'),
((SELECT id FROM dishes WHERE slug='carnitas'), 3, 'The meat spends hours barely covered in its own fat rather than water or stock, which is what leaves it easy to shred.'),
((SELECT id FROM dishes WHERE slug='carnitas'), 4, 'The cook simmers cubed pork for hours in rendered fat with orange and garlic, until it turns soft enough to shred.'),
((SELECT id FROM dishes WHERE slug='carnitas'), 5, 'Mexico''s Sunday-market favorite, mounds of shredded meat piled beside crisped edges, ready for a warm tortilla.'),
((SELECT id FROM dishes WHERE slug='birria'), 1, 'A slow-braised stew simmered low over a wood fire until the meat falls apart.'),
((SELECT id FROM dishes WHERE slug='birria'), 2, 'Colonial-era ranchers in western Mexico stewed a strong-smelling animal Spanish settlers had little other use for.'),
((SELECT id FROM dishes WHERE slug='birria'), 3, 'Diners now dunk a folded, cheese-crisped tortilla into the pot''s own broth, turning the stew into its own dipping sauce.'),
((SELECT id FROM dishes WHERE slug='birria'), 4, 'The cook braises meat for hours in a dark chili broth with cumin and cinnamon, until it falls apart at the touch of a fork.'),
((SELECT id FROM dishes WHERE slug='birria'), 5, 'Mexico''s dark-red stew, tender shredded meat swimming in a rust-colored broth beside a stack of tortillas.'),
((SELECT id FROM dishes WHERE slug='spaghetti-bolognese'), 1, 'A slow-simmered meat sauce plate that changes shape the farther it travels from home.'),
((SELECT id FROM dishes WHERE slug='spaghetti-bolognese'), 2, 'Cooks in the northern Italian city this dish is named for build their version on flat ribbons, largely skipping the round strand.'),
((SELECT id FROM dishes WHERE slug='spaghetti-bolognese'), 3, 'The city credited with the recipe rarely serves it over the long round strand of pasta most of the world pictures.'),
((SELECT id FROM dishes WHERE slug='spaghetti-bolognese'), 4, 'The cook browns ground meat with onion, simmers it with tomato in red wine for hours, then ladles it over long pasta strands.'),
((SELECT id FROM dishes WHERE slug='spaghetti-bolognese'), 5, 'Italy''s name rides on a plate rarely eaten this way at home, long pale strands under a rich, dark red meat sauce.'),
((SELECT id FROM dishes WHERE slug='pepperoni-pizza'), 1, 'A baked flatbread topping that rides along on nearly every delivery order.'),
((SELECT id FROM dishes WHERE slug='pepperoni-pizza'), 2, 'Italian-American butchers in early-1900s New York invented a cured sausage unrelated to the sweet peppers its name echoes.'),
((SELECT id FROM dishes WHERE slug='pepperoni-pizza'), 3, 'The disks curl up at the edges into little cups of fat as they bake, a trick no other common topping pulls off.'),
((SELECT id FROM dishes WHERE slug='pepperoni-pizza'), 4, 'The cook lays thin-sliced cured sausage over melted cheese and tomato sauce, then bakes it until the disks curl and crisp.'),
((SELECT id FROM dishes WHERE slug='pepperoni-pizza'), 5, 'America''s pizzeria standard, a round of melted cheese under curled, blistered red-orange disks.'),
((SELECT id FROM dishes WHERE slug='duck-confit'), 1, 'A slow-preserved bird dish meant to outlast winter with no refrigerator in sight.'),
((SELECT id FROM dishes WHERE slug='duck-confit'), 2, 'Farmhouse cooks with no refrigeration salted a bird''s legs, then cooked them slowly submerged in their own rendered fat.'),
((SELECT id FROM dishes WHERE slug='duck-confit'), 3, 'The finished meat used to keep for months at room temperature, sealed under its own fat like a jar of preserves.'),
((SELECT id FROM dishes WHERE slug='duck-confit'), 4, 'The cook salts the legs overnight, then cooks them for hours fully submerged in rendered fat until fall-apart tender.'),
((SELECT id FROM dishes WHERE slug='duck-confit'), 5, 'Southwestern France''s farmhouse plate, a bronzed leg with skin shattering over meat that falls from the bone.');
