-- Backfill: clue rewrites against the beat sheet.
-- 301 clues across 301 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'A smooth white ball set in the middle of a bowl of soup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 1;
UPDATE clues SET text = 'Comes to the table in the same pot it cooked in, lid still on.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-tagine') AND order_index = 1;
UPDATE clues SET text = 'Eaten from one big shared platter, working in from the edges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 1;
UPDATE clues SET text = 'A sweet green-tinted brew served in a silver pot with a long spout.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moroccan-mint-tea') AND order_index = 1;
UPDATE clues SET text = 'Served at weddings and birthdays alongside fried plantain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jollof-rice') AND order_index = 1;
UPDATE clues SET text = 'A meat bake that serves its chutney and yellow rice on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bobotie') AND order_index = 1;
UPDATE clues SET text = 'A smooth pale tart that trembles when the plate moves.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milk-tart') AND order_index = 1;
UPDATE clues SET text = 'Meat hung on hooks behind the glass, chopped to order with a cleaver.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'char-siu') AND order_index = 1;
UPDATE clues SET text = 'Noodles with a crisp edge on one side and a soft tangle on the other.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chow-mein') AND order_index = 1;
UPDATE clues SET text = 'A bowl of nothing much that turns into breakfast once you add toppings.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'congee') AND order_index = 1;
UPDATE clues SET text = 'A clear, gently thickened soup you can make in about five minutes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egg-drop-soup') AND order_index = 1;
UPDATE clues SET text = 'Rice that hisses and snaps in a smoking pan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 1;
UPDATE clues SET text = 'A cold starter that arrives glistening and tingles on the lips.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fuqi-feipian') AND order_index = 1;
UPDATE clues SET text = 'A thick dark soup with a pepper kick and a tang you notice second.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-and-sour-soup') AND order_index = 1;
UPDATE clues SET text = 'A dish where the whole dried chilies are decoration, not dinner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kung-pao-chicken') AND order_index = 1;
UPDATE clues SET text = 'Served with a bowl of plain rice because you will need it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mapo-tofu') AND order_index = 1;
UPDATE clues SET text = 'Crisp fried nuggets lacquered in a sticky, shiny glaze.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'orange-chicken') AND order_index = 1;
UPDATE clues SET text = 'Carved in front of you, one slice of skin at a time.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peking-duck') AND order_index = 1;
UPDATE clues SET text = 'Fried pieces that stay crunchy only if you eat them fast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-and-sour-pork') AND order_index = 1;
UPDATE clues SET text = 'Sticky little rice balls that come in a warm, sweet soup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tangyuan') AND order_index = 1;
UPDATE clues SET text = 'A light soup built around small parcels you chase with a spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wonton-soup') AND order_index = 1;
UPDATE clues SET text = 'A pleated purse that wobbles when you lift it with chopsticks.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'xiaolongbao') AND order_index = 1;
UPDATE clues SET text = 'A small dumpling dunked in a mix of soy sauce and vinegar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyoza') AND order_index = 1;
UPDATE clues SET text = 'Soft white bread with the crust cut off and a crunch hiding inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'katsu-sando') AND order_index = 1;
UPDATE clues SET text = 'A savory broth you sip straight from the bowl, no spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'miso-soup') AND order_index = 1;
UPDATE clues SET text = 'Soft, stretchy and sticky enough to cling to the knife.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 1;
UPDATE clues SET text = 'Cold-weather comfort where you choose each piece yourself.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oden') AND order_index = 1;
UPDATE clues SET text = 'A hand-held triangle with a surprise tucked in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onigiri') AND order_index = 1;
UPDATE clues SET text = 'A bowl slurped fast at a counter, where the noise is a compliment.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ramen') AND order_index = 1;
UPDATE clues SET text = 'Slices of raw fish fanned out like a hand of cards.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 1;
UPDATE clues SET text = 'Eaten by hand, and dipped fish-side down so the rice stays whole.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sushi') AND order_index = 1;
UPDATE clues SET text = 'Fried to order, and meant to be eaten before it stops crackling.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tempura') AND order_index = 1;
UPDATE clues SET text = 'Grilled meat finished with a sauce that dries to a lacquer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'teriyaki-chicken') AND order_index = 1;
UPDATE clues SET text = 'A cutlet that arrives with a bowl of sesame seeds to grind yourself.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tonkatsu') AND order_index = 1;
UPDATE clues SET text = 'Slurped at highway rest stops and train station counters.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'udon') AND order_index = 1;
UPDATE clues SET text = 'Served in a bowl hot enough to keep cooking after it reaches you.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bibimbap') AND order_index = 1;
UPDATE clues SET text = 'Thin ruffled slices that cook in a minute flat on a hot dome.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bulgogi') AND order_index = 1;
UPDATE clues SET text = 'Packed for school trips and sports days, then eaten by hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimbap') AND order_index = 1;
UPDATE clues SET text = 'A cutlet whose crust puffs up and floats off the meat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wiener-schnitzel') AND order_index = 1;
UPDATE clues SET text = 'Sold hot from street carts and eaten out of a paper sleeve.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'belgian-waffles') AND order_index = 1;
UPDATE clues SET text = 'A breakfast treat that sheds crumbs like a snowstorm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'danish-pastry') AND order_index = 1;
UPDATE clues SET text = 'Served in two courses, the broth first and the fish after.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bouillabaisse') AND order_index = 1;
UPDATE clues SET text = 'The cake that ends a winter holiday dinner, shaped like firewood.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buche-de-noel') AND order_index = 1;
UPDATE clues SET text = 'A heavy winter pot that feeds a table of hungry farmhands.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cassoulet') AND order_index = 1;
UPDATE clues SET text = 'A farmhouse braise that turns a tough old bird tender.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coq-au-vin') AND order_index = 1;
UPDATE clues SET text = 'A thin pancake dessert finished in a pan beside your chair.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crepe-suzette') AND order_index = 1;
UPDATE clues SET text = 'A pastry that crackles when you tear it and leaves crumbs behind.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'croissant') AND order_index = 1;
UPDATE clues SET text = 'A hot sandwich you have to eat with cutlery.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'croque-monsieur') AND order_index = 1;
UPDATE clues SET text = 'Cold and silky underneath, with a hard sweet lid on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'creme-brulee') AND order_index = 1;
UPDATE clues SET text = 'A cold starter so rich it comes in slivers, with something sweet beside it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 1;
UPDATE clues SET text = 'Arrives under a lid of cheese welded to the rim of the bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-onion-soup') AND order_index = 1;
UPDATE clues SET text = 'A weekend breakfast served with a jug of syrup on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-toast') AND order_index = 1;
UPDATE clues SET text = 'A plate where each ingredient keeps its own corner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nicoise-salad') AND order_index = 1;
UPDATE clues SET text = 'Cooked in about the time it takes to pour a coffee.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'omelette') AND order_index = 1;
UPDATE clues SET text = 'A breakfast roll where the best part is buried in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 1;
UPDATE clues SET text = 'Sold by the slice at bakeries, sweet and salty in one bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pissaladiere') AND order_index = 1;
UPDATE clues SET text = 'A summer vegetable pot that tastes better the day after.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ratatouille') AND order_index = 1;
UPDATE clues SET text = 'A dessert ordered at the start of dinner because it takes its time.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 1;
UPDATE clues SET text = 'A tart with a dark, sticky top that was once its bottom.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tarte-tatin') AND order_index = 1;
UPDATE clues SET text = 'Ski-lodge fuel that is mostly cheese and potato.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tartiflette') AND order_index = 1;
UPDATE clues SET text = 'A silky soup that is ready only after a night in the fridge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vichyssoise') AND order_index = 1;
UPDATE clues SET text = 'A shiny finger of pastry that leaks when you bite it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eclair') AND order_index = 1;
UPDATE clues SET text = 'A birthday cake with cherries on top and a boozy secret inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'black-forest-cake') AND order_index = 1;
UPDATE clues SET text = 'Eaten standing up at a market stall, mustard in one hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bratwurst') AND order_index = 1;
UPDATE clues SET text = 'A snack-bar plate eaten with a tiny wooden fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'currywurst') AND order_index = 1;
UPDATE clues SET text = 'Thin enough to crackle, blistered black at the edges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flammkuchen') AND order_index = 1;
UPDATE clues SET text = 'A picnic side that gets better the longer it sits.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 1;
UPDATE clues SET text = 'Sunday dinner with red cabbage and dumplings on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rouladen') AND order_index = 1;
UPDATE clues SET text = 'Lumpy little noodles, no two the same shape.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaetzle') AND order_index = 1;
UPDATE clues SET text = 'A loaf baked in autumn and left to wait for the holidays.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'stollen') AND order_index = 1;
UPDATE clues SET text = 'Tiny hand-rolled bundles passed around before the main course.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 1;
UPDATE clues SET text = 'A summer plate that skips the lettuce and keeps the olive oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'greek-salad') AND order_index = 1;
UPDATE clues SET text = 'Late-night street food, folded up in warm bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyro') AND order_index = 1;
UPDATE clues SET text = 'Crisp shell, soft middle, and sticky fingers afterwards.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 1;
UPDATE clues SET text = 'Baked in a deep tray and left to rest before it will hold a slice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moussaka') AND order_index = 1;
UPDATE clues SET text = 'A tray of baked pasta that must rest before it can be sliced.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pastitsio') AND order_index = 1;
UPDATE clues SET text = 'Cool, garlicky, and on the table before the meat arrives.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tzatziki') AND order_index = 1;
UPDATE clues SET text = 'A stew stained deep red by one dried spice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'goulash') AND order_index = 1;
UPDATE clues SET text = 'Chewy on the inside, crisp at the rim, hot off the griddle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'boxty') AND order_index = 1;
UPDATE clues SET text = 'A stew that waits on the back burner until the whole house is home.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coddle') AND order_index = 1;
UPDATE clues SET text = 'Plain on purpose, and built for a cold night.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'irish-stew') AND order_index = 1;
UPDATE clues SET text = 'A breadcrumbed bite that pulls a string of cheese when you break it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arancini') AND order_index = 1;
UPDATE clues SET text = 'A starter whose name trips up half the people who order it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bruschetta') AND order_index = 1;
UPDATE clues SET text = 'Pasta glossed with a pale sauce and cracked pepper on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cacio-e-pepe') AND order_index = 1;
UPDATE clues SET text = 'A sealed pocket that stays scalding in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'calzone') AND order_index = 1;
UPDATE clues SET text = 'Filled to order, so the shell stays crunchy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cannoli') AND order_index = 1;
UPDATE clues SET text = 'Three ingredients, one plate, and no cooking at all.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caprese-salad') AND order_index = 1;
UPDATE clues SET text = 'Bakery bread sold by the square and eaten still warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 1;
UPDATE clues SET text = 'An egg dish sliced like a pie and packed for picnics.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 1;
UPDATE clues SET text = 'A scoop served warmer than ice cream, so it stays soft.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 1;
UPDATE clues SET text = 'Soft pillows that go in the pot and float when they are ready.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gnocchi') AND order_index = 1;
UPDATE clues SET text = 'A tray bake where the family argues over the crispy corner piece.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lasagna') AND order_index = 1;
UPDATE clues SET text = 'A pie with so few toppings that nothing can hide.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'margherita-pizza') AND order_index = 1;
UPDATE clues SET text = 'A soup thick enough to count as a whole meal.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'minestrone') AND order_index = 1;
UPDATE clues SET text = 'A pantry soup that costs almost nothing and feeds the whole table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pasta-e-fagioli') AND order_index = 1;
UPDATE clues SET text = 'A rice dish the color of a gold coin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'risotto-alla-milanese') AND order_index = 1;
UPDATE clues SET text = 'A pasta made in the time it takes the water to boil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-carbonara') AND order_index = 1;
UPDATE clues SET text = 'Assembled in a dish and left overnight in the fridge, not an oven.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tiramisu') AND order_index = 1;
UPDATE clues SET text = 'Airy, hollow inside, and filled with cream once it cools.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 1;
UPDATE clues SET text = 'Sold at harbor stands, salty and sharp and not for the timid.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pickled-herring') AND order_index = 1;
UPDATE clues SET text = 'Ladled from a crock at winter markets and holiday tables.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bigos') AND order_index = 1;
UPDATE clues SET text = 'Dough half-moons pinched shut by whole families before an Eastern European holiday.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pierogi') AND order_index = 1;
UPDATE clues SET text = 'A sharp, tangy soup traditionally eaten around Easter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zurek') AND order_index = 1;
UPDATE clues SET text = 'Tender strips in a velvety sauce with a tang underneath.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-stroganoff') AND order_index = 1;
UPDATE clues SET text = 'A dumpling the whole family folds together on a flour-dusted table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 1;
UPDATE clues SET text = 'Peppery, crumbly, and served with mashed turnip and potato.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'haggis') AND order_index = 1;
UPDATE clues SET text = 'A winter breakfast that sticks to your ribs until lunchtime.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'porridge') AND order_index = 1;
UPDATE clues SET text = 'Ridged, fried, and built for dunking in something thick.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'churros') AND order_index = 1;
UPDATE clues SET text = 'A chilled custard that wobbles when you set the plate down.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flan') AND order_index = 1;
UPDATE clues SET text = 'A soup made without turning on the stove.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gazpacho') AND order_index = 1;
UPDATE clues SET text = 'Crisp shell, molten middle, passed across a bar counter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jamon-croquetas') AND order_index = 1;
UPDATE clues SET text = 'Cooked outdoors in a pan wide enough to feed the whole family.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paella') AND order_index = 1;
UPDATE clues SET text = 'Silky, translucent orange slices laid on dark bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gravlax') AND order_index = 1;
UPDATE clues SET text = 'A spiral bun that perfumes the whole street from the bakery door.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kanelbulle') AND order_index = 1;
UPDATE clues SET text = 'Bite-sized, gravy-soaked, and served with sweet-tart jam.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'swedish-meatballs') AND order_index = 1;
UPDATE clues SET text = 'Prepared the night before, so breakfast does the work itself.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bircher-muesli') AND order_index = 1;
UPDATE clues SET text = 'One pot, one burner, and a table of people reaching in.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cheese-fondue') AND order_index = 1;
UPDATE clues SET text = 'A soup that stains the spoon, the bowl and your napkin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'borscht') AND order_index = 1;
UPDATE clues SET text = 'A no-bake dessert that is mostly sweet, soft and sticky.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banoffee-pie') AND order_index = 1;
UPDATE clues SET text = 'A roast sealed in pastry so you cannot see how it was cooked.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-wellington') AND order_index = 1;
UPDATE clues SET text = 'A dessert built to rescue the heel of a loaf.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bread-pudding') AND order_index = 1;
UPDATE clues SET text = 'A pan-fried cake that crackles at the edges.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-and-squeak') AND order_index = 1;
UPDATE clues SET text = 'A spiced dessert where the vegetable hides in plain sight.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'carrot-cake') AND order_index = 1;
UPDATE clues SET text = 'A curry-house order mild enough for first-timers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-tikka-masala') AND order_index = 1;
UPDATE clues SET text = 'Spongy and full of holes, which is the whole point.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 1;
UPDATE clues SET text = 'A dessert that gets smashed up before it is served.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eton-mess') AND order_index = 1;
UPDATE clues SET text = 'A family dinner baked under a crust you can sink a fork into.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 1;
UPDATE clues SET text = 'Eaten slowly on a weekend, with a pot of strong tea.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'full-english-breakfast') AND order_index = 1;
UPDATE clues SET text = 'Browned on top under the broiler, soft and steaming beneath.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shepherd-s-pie') AND order_index = 1;
UPDATE clues SET text = 'A pudding with a name that makes visitors giggle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spotted-dick') AND order_index = 1;
UPDATE clues SET text = 'A baked dinner that rises like a pudding around its meat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'toad-in-the-hole') AND order_index = 1;
UPDATE clues SET text = 'Wheeled out at Christmas in a clear bowl so the layers show.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'trifle') AND order_index = 1;
UPDATE clues SET text = 'Cut at the tea table and eaten with a small fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'victoria-sponge-cake') AND order_index = 1;
UPDATE clues SET text = 'A pub snack that dresses up cheese on toast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'welsh-rarebit') AND order_index = 1;
UPDATE clues SET text = 'Flaky pockets passed around at birthdays and picnics.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'empanadas') AND order_index = 1;
UPDATE clues SET text = 'A restaurant pot that comes with a tray of side dishes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'feijoada') AND order_index = 1;
UPDATE clues SET text = 'A lunch counter sandwich with a ham-and-pickle tang.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cubano') AND order_index = 1;
UPDATE clues SET text = 'A hot street snack eaten with a pile of tangy slaw.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pupusas') AND order_index = 1;
UPDATE clues SET text = 'A breakfast that mixes a salty fish with a fruit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ackee-and-saltfish') AND order_index = 1;
UPDATE clues SET text = 'A roadside lunch whose heat builds with each bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jerk-chicken') AND order_index = 1;
UPDATE clues SET text = 'A lunch that eats like a sandwich and weighs like a brick.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'burrito') AND order_index = 1;
UPDATE clues SET text = 'A bowl of crisp lettuce dressed to taste of garlic and salt.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caesar-salad') AND order_index = 1;
UPDATE clues SET text = 'A hangover cure served sizzling in a skillet, egg and all.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chilaquiles') AND order_index = 1;
UPDATE clues SET text = 'A restaurant dessert that rides the line between hot and cold.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-ice-cream') AND order_index = 1;
UPDATE clues SET text = 'A sweet cold drink that tames a spicy meal.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'horchata') AND order_index = 1;
UPDATE clues SET text = 'A brunch plate where the yolk is meant to run.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'huevos-rancheros') AND order_index = 1;
UPDATE clues SET text = 'A game-day platter eaten with the fingers and a lot of napkins.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nachos') AND order_index = 1;
UPDATE clues SET text = 'Baked once a year for guests who cannot eat it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pan-de-muerto') AND order_index = 1;
UPDATE clues SET text = 'Scooped onto chips and tacos, and made again the next day.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 1;
UPDATE clues SET text = 'A kids'' menu favorite that grown-ups keep ordering.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quesadilla') AND order_index = 1;
UPDATE clues SET text = 'Meat shaved off a tall, spinning stack and caught on a tortilla.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 1;
UPDATE clues SET text = 'A cake that must sit overnight before it is ready to serve.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tres-leches-cake') AND order_index = 1;
UPDATE clues SET text = 'Tossed in a flaming-hot pan that sends up a burst of fire.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lomo-saltado') AND order_index = 1;
UPDATE clues SET text = 'A street snack that fills a pita with crunch instead of meat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'falafel') AND order_index = 1;
UPDATE clues SET text = 'A mezze dip with a campfire smell and a pool of oil on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baba-ganoush') AND order_index = 1;
UPDATE clues SET text = 'A pale, smooth spread finished with a pool of oil and a dusting of red.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hummus') AND order_index = 1;
UPDATE clues SET text = 'Breakfast for people who want something warm, salty and herby.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manakish') AND order_index = 1;
UPDATE clues SET text = 'Served straight from the pan with bread for scooping.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shakshuka') AND order_index = 1;
UPDATE clues SET text = 'A sweet that turns a winter vegetable translucent.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kabak-tatlisi') AND order_index = 1;
UPDATE clues SET text = 'Pizza''s thinner, spicier cousin, eaten rolled up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lahmacun') AND order_index = 1;
UPDATE clues SET text = 'A boxed gift sweet that is chewy, perfumed and dusty with sugar.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'turkish-delight') AND order_index = 1;
UPDATE clues SET text = 'Truck stops and hockey arenas serve it hot, heavy and messy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'poutine') AND order_index = 1;
UPDATE clues SET text = 'A doughnut-shop pastry with a crisp crust and a soft, fruity middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 1;
UPDATE clues SET text = 'A dessert that smells of cinnamon and cools on a windowsill.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-pie') AND order_index = 1;
UPDATE clues SET text = 'Ordered at a deli counter by the half pound, sliced thin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bagel-with-lox') AND order_index = 1;
UPDATE clues SET text = 'A banquet showpiece that looks like a snow-capped mountain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baked-alaska') AND order_index = 1;
UPDATE clues SET text = 'A red-sauce pan that shows up at graduations and christenings.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baked-ziti') AND order_index = 1;
UPDATE clues SET text = 'A church-supper dessert that is better the next day.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banana-pudding') AND order_index = 1;
UPDATE clues SET text = 'Smoked for most of a day, and sold until it runs out.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-brisket') AND order_index = 1;
UPDATE clues SET text = 'Pillowy squares served hot with a cup of chicory coffee.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beignets') AND order_index = 1;
UPDATE clues SET text = 'A hearty diner breakfast that is more sauce than plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 1;
UPDATE clues SET text = 'A chain-restaurant starter that arrives opened like a flower.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'blooming-onion') AND order_index = 1;
UPDATE clues SET text = 'A commuter''s morning meal that fits in a cup holder.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'breakfast-burrito') AND order_index = 1;
UPDATE clues SET text = 'Kept warm in a slow cooker at tailgates and holiday gatherings.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 1;
UPDATE clues SET text = 'A fall fair treat that is chewy outside and crisp inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caramel-apple') AND order_index = 1;
UPDATE clues SET text = 'A diner-case slice with a deep red filling that runs onto the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 1;
UPDATE clues SET text = 'A diner platter big enough to hang over the plate''s edge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-fried-steak') AND order_index = 1;
UPDATE clues SET text = 'A red-sauce restaurant order with spaghetti on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-parmesan') AND order_index = 1;
UPDATE clues SET text = 'A comfort dinner for the first cold night of the year.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-pot-pie') AND order_index = 1;
UPDATE clues SET text = 'Ladled out when somebody in the house is under the weather.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-and-dumplings') AND order_index = 1;
UPDATE clues SET text = 'A plate that argues with itself: sweet on one side, salty on the other.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-and-waffles') AND order_index = 1;
UPDATE clues SET text = 'A thin, sweet-spiced meat sauce served at parlors.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cincinnati-chili') AND order_index = 1;
UPDATE clues SET text = 'A warm spiral that you unwind from the outside in, one layer at a time.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 1;
UPDATE clues SET text = 'A seafood pot served with a bib and a bowl for the shells.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cioppino') AND order_index = 1;
UPDATE clues SET text = 'Cut into four triangles so it can stand up on the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'club-sandwich') AND order_index = 1;
UPDATE clues SET text = 'Crunchy, cold and tangy, and meant to cut through something fried.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'coleslaw') AND order_index = 1;
UPDATE clues SET text = 'A fair-day lunch that doesn''t need a plate or a fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'corn-dog') AND order_index = 1;
UPDATE clues SET text = 'Baked in cast iron, crumbly and a little sweet.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cornbread') AND order_index = 1;
UPDATE clues SET text = 'A sugar treat that is mostly air and sticks to your fingers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cotton-candy') AND order_index = 1;
UPDATE clues SET text = 'A seafood patty served with tartar sauce and a lemon wedge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-cakes') AND order_index = 1;
UPDATE clues SET text = 'Crunchy corners, creamy middle, and a sweet-and-sour dip.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-rangoon') AND order_index = 1;
UPDATE clues SET text = 'A restaurant plate where the sauce is the main event.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crawfish-etouffee') AND order_index = 1;
UPDATE clues SET text = 'A smooth hot cereal served with a pat of butter.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 1;
UPDATE clues SET text = 'Tall as a pie, and eaten with a knife and fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deep-dish-pizza') AND order_index = 1;
UPDATE clues SET text = 'A fairground sweet that arrives in a paper boat, still too hot to hold.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deep-fried-oreo') AND order_index = 1;
UPDATE clues SET text = 'A holiday-table bite that disappears before the main course.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 1;
UPDATE clues SET text = 'Stretched thin and fried, with a chewy middle and crisp rim.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'elephant-ear') AND order_index = 1;
UPDATE clues SET text = 'A crisp appetizer with a tart bite and a creamy dip.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-green-tomatoes') AND order_index = 1;
UPDATE clues SET text = 'A concession-stand meal eaten straight out of a single-serving bag.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frito-pie') AND order_index = 1;
UPDATE clues SET text = 'A fair sweet that is crisp, lacy and gone in five minutes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'funnel-cake') AND order_index = 1;
UPDATE clues SET text = 'A takeout order with a dark, sticky sauce and a bit of heat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'general-tsos-chicken') AND order_index = 1;
UPDATE clues SET text = 'A layer cake where the frosting steals the show.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'german-chocolate-cake') AND order_index = 1;
UPDATE clues SET text = 'A coffee-shop dozen that comes in a flat pink box.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'glazed-donut') AND order_index = 1;
UPDATE clues SET text = 'Crunchy clusters that go soggy the second milk hits them.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'granola') AND order_index = 1;
UPDATE clues SET text = 'A holiday side that brings its own crunchy topping.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'green-bean-casserole') AND order_index = 1;
UPDATE clues SET text = 'The first sandwich most kids learn to make on a stove.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'grilled-cheese') AND order_index = 1;
UPDATE clues SET text = 'A drive-in order that comes with a side of fries and a shake.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hamburger') AND order_index = 1;
UPDATE clues SET text = 'A diner side that crackles when the fork goes in.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 1;
UPDATE clues SET text = 'Served on white bread with pickle slices to soak up the oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-chicken-sandwich') AND order_index = 1;
UPDATE clues SET text = 'Golden nuggets of cornmeal that arrive in a paper-lined basket.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hush-puppies') AND order_index = 1;
UPDATE clues SET text = 'A clear soup full of tiny things that fit on a spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'italian-wedding-soup') AND order_index = 1;
UPDATE clues SET text = 'A pie with a sunny filling under a toasted cloud.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 1;
UPDATE clues SET text = 'A plate lunch served with two scoops of rice and a lot of gravy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 1;
UPDATE clues SET text = 'A brothy red soup with oyster crackers on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manhattan-clam-chowder') AND order_index = 1;
UPDATE clues SET text = 'Eaten over the wrapper, because it will not stay in the bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'meatball-sub') AND order_index = 1;
UPDATE clues SET text = 'A weeknight dinner baked in a pan and sliced like bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'meatloaf') AND order_index = 1;
UPDATE clues SET text = 'A dessert so dense it needs a hot knife to cut cleanly.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'new-york-cheesecake') AND order_index = 1;
UPDATE clues SET text = 'A bowl that steams on the stove and thickens as you stir.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 1;
UPDATE clues SET text = 'A chewy cookie with a healthy reputation and a sweet streak.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal-raisin-cookies') AND order_index = 1;
UPDATE clues SET text = 'A diner sandwich for people who can''t choose between two orders.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patty-melt') AND order_index = 1;
UPDATE clues SET text = 'Scooped from a deep dish while it is still bubbling.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peach-cobbler') AND order_index = 1;
UPDATE clues SET text = 'A packed lunch assembled from two jars and a knife.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peanut-butter-and-jelly-sandwich') AND order_index = 1;
UPDATE clues SET text = 'A slice so sweet that a small portion does the job.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pecan-pie') AND order_index = 1;
UPDATE clues SET text = 'A griddle sandwich eaten leaning forward, over the paper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'philly-cheesesteak') AND order_index = 1;
UPDATE clues SET text = 'An orange spread scooped onto crackers or celery at porch parties.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pimento-cheese-sandwich') AND order_index = 1;
UPDATE clues SET text = 'Crusty bread that shatters, around something fried and hot.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'po-boy') AND order_index = 1;
UPDATE clues SET text = 'A heavy dinner that spends the afternoon in a covered pot.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pot-roast') AND order_index = 1;
UPDATE clues SET text = 'A bun heaped so high with smoky meat you squash it to bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pulled-pork-sandwich') AND order_index = 1;
UPDATE clues SET text = 'The dessert that closes out a November feast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pumpkin-pie') AND order_index = 1;
UPDATE clues SET text = 'A breakfast that is ruined by a minute of inattention.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scrambled-eggs') AND order_index = 1;
UPDATE clues SET text = 'A potluck dish in clear glass, so the stripes show.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 1;
UPDATE clues SET text = 'A steakhouse opener served on ice with a sharp red sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-cocktail') AND order_index = 1;
UPDATE clues SET text = 'A restaurant plate that smells of garlic from across the room.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-scampi') AND order_index = 1;
UPDATE clues SET text = 'A Lowcountry bowl that works at breakfast or dinner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-and-grits') AND order_index = 1;
UPDATE clues SET text = 'Eaten over a plate because the filling won''t stay put.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sloppy-joe') AND order_index = 1;
UPDATE clues SET text = 'Soft in the middle, crackled on top, and tangy at the back.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 1;
UPDATE clues SET text = 'Crunchy outside, juicy inside, and eaten with the fingers.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'southern-fried-chicken') AND order_index = 1;
UPDATE clues SET text = 'A family dinner served in a big bowl and passed around.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-and-meatballs') AND order_index = 1;
UPDATE clues SET text = 'Ordered for the table, scooped up with chips or bread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 1;
UPDATE clues SET text = 'Sold in thick slices from a pizzeria counter, steaming inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'stromboli') AND order_index = 1;
UPDATE clues SET text = 'A plain cookie that waits for icing and sprinkles.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sugar-cookies') AND order_index = 1;
UPDATE clues SET text = 'A smooth, spiced holiday slice with a darker color than you expect.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-potato-pie') AND order_index = 1;
UPDATE clues SET text = 'A dinner with its own soundtrack as it crosses the dining room.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tex-mex-fajitas') AND order_index = 1;
UPDATE clues SET text = 'A creamy red soup with small pasta pockets floating in it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tomato-tortellini-soup') AND order_index = 1;
UPDATE clues SET text = 'A deli order that comes cold, with pickles on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tuna-salad-sandwich') AND order_index = 1;
UPDATE clues SET text = 'Crisp, creamy and sweet-tart, with a crunch on the fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'waldorf-salad') AND order_index = 1;
UPDATE clues SET text = 'A grab-and-go breakfast built in a clear cup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 1;
UPDATE clues SET text = 'A brunch-menu order that costs more than its ingredients.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'avocado-toast') AND order_index = 1;
UPDATE clues SET text = 'A birthday-party snack that leaves colored dots on the table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 1;
UPDATE clues SET text = 'Homestyle vegetable cooking that goes with flatbread or rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-gobi') AND order_index = 1;
UPDATE clues SET text = 'Griddled until it blisters, with a filling you cannot see.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-paratha') AND order_index = 1;
UPDATE clues SET text = 'A curry gentle enough to win over people who say they dislike curry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'butter-chicken') AND order_index = 1;
UPDATE clues SET text = 'Cooked in big pots for weddings, Eid and Friday-night orders.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-biryani') AND order_index = 1;
UPDATE clues SET text = 'A pale, nutty curry that rarely makes anyone sweat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-korma') AND order_index = 1;
UPDATE clues SET text = 'A meal you crack open, crush and soak before you eat it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-baati') AND order_index = 1;
UPDATE clues SET text = 'A spongy fried sweet that soaks up its syrup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gulab-jamun') AND order_index = 1;
UPDATE clues SET text = 'A sunny yellow drink so thick it needs a wide straw.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-lassi') AND order_index = 1;
UPDATE clues SET text = 'Brewed in a battered pot by a vendor at the corner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-chai') AND order_index = 1;
UPDATE clues SET text = 'A crisp sheet that''s served rolled, with small bowls on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-dosa') AND order_index = 1;
UPDATE clues SET text = 'Torn by hand and used as a spoon for the curry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'naan') AND order_index = 1;
UPDATE clues SET text = 'Crunchy, oily and ordered before the curry comes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onion-bhaji') AND order_index = 1;
UPDATE clues SET text = 'Chunks that char at the edges and squeak against the teeth.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paneer-tikka') AND order_index = 1;
UPDATE clues SET text = 'A street snack with a splash of cold water inside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pani-puri') AND order_index = 1;
UPDATE clues SET text = 'A cool side served in a small bowl next to the curry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'raita') AND order_index = 1;
UPDATE clues SET text = 'Sold hot in twos and threes from a tray by the road.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'samosa') AND order_index = 1;
UPDATE clues SET text = 'A cold-season dish where the bitter greens are the point.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sarson-ka-saag') AND order_index = 1;
UPDATE clues SET text = 'A curry with a sharp, sour edge before the heat arrives.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vindaloo') AND order_index = 1;
UPDATE clues SET text = 'Dark, dry and rich, served at ceremonies and festivals.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-rendang') AND order_index = 1;
UPDATE clues SET text = 'A soup you doctor yourself with lime, chili and sweet soy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'soto-ayam') AND order_index = 1;
UPDATE clues SET text = 'A bowl with a spicy, sour or creamy broth depending on the stall.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'laksa') AND order_index = 1;
UPDATE clues SET text = 'Workers and schoolchildren grab it by the packet on the way out.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-lemak') AND order_index = 1;
UPDATE clues SET text = 'A sour, salty braise that sticks to a plate of plain rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-adobo') AND order_index = 1;
UPDATE clues SET text = 'A dessert that arrives as a tower and leaves as a puddle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'halo-halo') AND order_index = 1;
UPDATE clues SET text = 'Served on a wide tray at birthdays and fiestas.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'palabok') AND order_index = 1;
UPDATE clues SET text = 'Chopped fine, crunchy at the edges, and ordered with cold beer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 1;
UPDATE clues SET text = 'A hawker-stall lunch that looks plain and is all about technique.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hainanese-chicken-rice') AND order_index = 1;
UPDATE clues SET text = 'A dark, intense broth sold in portions that fit in one hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'boat-noodles') AND order_index = 1;
UPDATE clues SET text = 'A dessert that arrives warm and cold at the same time.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-sticky-rice') AND order_index = 1;
UPDATE clues SET text = 'Slippery, chewy ribbons with a smoky edge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-see-ew') AND order_index = 1;
UPDATE clues SET text = 'Served with a small tray of seasonings to adjust it yourself.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-thai') AND order_index = 1;
UPDATE clues SET text = 'A sweet-hot curry that comes with a bowl of jasmine rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 1;
UPDATE clues SET text = 'A to-go drink poured over crushed ice in a tall plastic cup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-iced-tea') AND order_index = 1;
UPDATE clues SET text = 'A soup you sip around the herbs, not through them.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-kha-gai') AND order_index = 1;
UPDATE clues SET text = 'A sandwich that balances crunch, fat, herbs and sour.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banh-mi') AND order_index = 1;
UPDATE clues SET text = 'A cold, chewy wrapper around crisp herbs, with a dipping sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fresh-spring-rolls') AND order_index = 1;
UPDATE clues SET text = 'Sold from steaming street stalls before the sun is up.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pho') AND order_index = 1;
UPDATE clues SET text = 'A one-pot dinner that families fight over the bottom of.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arroz-con-pollo') AND order_index = 1;
UPDATE clues SET text = 'A rack of bones that arrives with a roll of paper towels.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bbq-ribs') AND order_index = 1;
UPDATE clues SET text = 'A toasted sandwich that tastes of summer when the tomato is right.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'blt') AND order_index = 1;
UPDATE clues SET text = 'The breakfast that makes a lazy weekend feel official.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buttermilk-pancakes') AND order_index = 1;
UPDATE clues SET text = 'A hot dog piled so high with toppings that it needs both hands.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicago-hot-dog') AND order_index = 1;
UPDATE clues SET text = 'A bowl that goes on the stove the minute someone sneezes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-noodle-soup') AND order_index = 1;
UPDATE clues SET text = 'A seafood platter you wear as much as you eat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-crab') AND order_index = 1;
UPDATE clues SET text = 'A diner breakfast judged by how brown the underside gets.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'corned-beef-hash') AND order_index = 1;
UPDATE clues SET text = 'Eaten out of paper with a wooden fork on a windy seafront.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-and-chips') AND order_index = 1;
UPDATE clues SET text = 'Hot, crunchy and gone fast, with a ranch cup beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-cheese-curds') AND order_index = 1;
UPDATE clues SET text = 'A Gulf Coast pot that starts with flour stirred in oil until it darkens.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gumbo') AND order_index = 1;
UPDATE clues SET text = 'A shack lunch where the bun is only a delivery system.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lobster-roll') AND order_index = 1;
UPDATE clues SET text = 'A tall white dessert that cracks like an eggshell under the spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pavlova') AND order_index = 1;
UPDATE clues SET text = 'Creamy without cream, thanks to hours of patient simmering.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'red-beans-and-rice') AND order_index = 1;
UPDATE clues SET text = 'A palm-sized dessert sandwich with cream where the meat would be.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'whoopie-pie') AND order_index = 1;
