-- Backfill: clue rewrites against the beat sheet.
-- 128 clues across 105 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'You pour syrup over the chicken as well as the waffle, and the grid holds the pool.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-and-waffles') AND order_index = 3;
UPDATE clues SET text = 'Puerto Rico''s golden, crumbly heap, served with a cup of broth for dunking.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mofongo') AND order_index = 5;
UPDATE clues SET text = 'Piled in dozens on a mezze table, still crackling from the fryer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kibbeh') AND order_index = 1;
UPDATE clues SET text = 'Lebanon''s deep-brown, crisp-edged oval, split open to show a steaming filling.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kibbeh') AND order_index = 5;
UPDATE clues SET text = 'Peru''s beef-and-fries plate, juices soaking the potatoes and rice alike.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lomo-saltado') AND order_index = 5;
UPDATE clues SET text = 'A round Lebanese flatbread, torn warm and dipped in yogurt or olive oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manakish') AND order_index = 5;
UPDATE clues SET text = 'Poland''s dark gingerbread, cut in hearts and stars and glazed shiny.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pierniki') AND order_index = 5;
UPDATE clues SET text = 'Smoke, salt and a squirt of green sauce, handed over in a paper napkin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'choripan') AND order_index = 1;
UPDATE clues SET text = 'Argentina''s stadium snack: a charred link in a bread roll, green herb sauce on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'choripan') AND order_index = 5;
UPDATE clues SET text = 'A tangle of tomato-red strands served beside rice and black beans.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ropa-vieja') AND order_index = 1;
UPDATE clues SET text = 'Cuba''s family-table platter: frayed meat in red sauce with black beans and fried plantains.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ropa-vieja') AND order_index = 5;
UPDATE clues SET text = 'A lunch built on one slice, with no top slice to hide under.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'smorrebrod') AND order_index = 1;
UPDATE clues SET text = 'Denmark''s rye canvas under neat toppings: pickled herring, roast beef, a dill sprig.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'smorrebrod') AND order_index = 5;
UPDATE clues SET text = 'In Mexico, the cook flicks a sliver of pineapple off the spit and onto your tortilla.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 5;
UPDATE clues SET text = 'A noodle soup you finish with squeezed lime and a spoon of chili oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khao-soi') AND order_index = 1;
UPDATE clues SET text = 'Northern Thailand''s curry bowl in gold, with pickled mustard greens, shallot and lime on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khao-soi') AND order_index = 5;
UPDATE clues SET text = 'Britain''s golden, egg-washed pastry log, sliced to show a pink center.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-wellington') AND order_index = 5;
UPDATE clues SET text = 'Greece''s cool white dip with green flecks, dolloped beside grilled meat and pita.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tzatziki') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s pale, tender bundle, unwrapped from a corn husk and eaten with a fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tamales') AND order_index = 5;
UPDATE clues SET text = 'A soup so thick it clings to the hand that scoops it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egusi-soup') AND order_index = 1;
UPDATE clues SET text = 'The spice mix has its own name, yaji, and is sold by the jar on its own.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'suya') AND order_index = 3;
UPDATE clues SET text = 'Nigeria''s beef slivers on a stick, dusted red with spice and wrapped in paper with raw onion.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'suya') AND order_index = 5;
UPDATE clues SET text = 'Hung from hooks in a shop and sliced thin by the packet.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biltong') AND order_index = 1;
UPDATE clues SET text = 'South Africa''s dark, chewy slivers, sliced from a hanging strip and sold by weight.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biltong') AND order_index = 5;
UPDATE clues SET text = 'A fundraiser sweet that leaves your fingers dusty and brown.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lamington') AND order_index = 1;
UPDATE clues SET text = 'Australia''s tea-time cube, soft inside, with a thin chocolate shell and a coconut coat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lamington') AND order_index = 5;
UPDATE clues SET text = 'Britain''s brown-crusted wedge of Sunday leftovers, served with cold meat or a fried egg.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-and-squeak') AND order_index = 5;
UPDATE clues SET text = 'Germany''s tall dark cake with a ring of whipped cream and cherries crowning the top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'black-forest-cake') AND order_index = 5;
UPDATE clues SET text = 'Spain''s golden fingers that burst with hot, creamy ham filling when bitten.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jamon-croquetas') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s glossy, dark-brown ribbons with flecks of green and egg, a lime wedge beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-see-ew') AND order_index = 5;
UPDATE clues SET text = 'A cold dip for scooping, and nothing in it ever touches the oven.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 1;
UPDATE clues SET text = 'Peru''s glistening white cubes with a milky, lime-sour puddle, ladled out of a glass bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ceviche') AND order_index = 5;
UPDATE clues SET text = 'America''s soda-fountain boat: three scoops in a row between two curved halves of fruit.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banana-split') AND order_index = 5;
UPDATE clues SET text = 'Ethiopia''s gray, pancake-soft round, a red-brown stew pooled in the middle.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'injera-with-doro-wat') AND order_index = 5;
UPDATE clues SET text = 'A lunch you finish by eating the container.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bunny-chow') AND order_index = 1;
UPDATE clues SET text = 'South Africa''s quarter loaf brimming with red curry, the lid of bread set on top like a hat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bunny-chow') AND order_index = 5;
UPDATE clues SET text = 'Cut from a huge round pan and served hot, with syrup poured on the spot.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baklava-cheesecake-knafeh') AND order_index = 1;
UPDATE clues SET text = 'The sauce is flecked with black pepper you can see, and the biscuit is its sponge.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'biscuits-and-gravy') AND order_index = 3;
UPDATE clues SET text = 'Italy''s thick toasted slices, glossy with oil, heaped with red tomato and torn basil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bruschetta') AND order_index = 5;
UPDATE clues SET text = 'India''s roadside plate of golden, hollow balls, handed over one by one with a bowl of spicy water.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pani-puri') AND order_index = 5;
UPDATE clues SET text = 'The cook steeps saffron threads in hot broth and ladles it into the rice a spoonful at a time.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'risotto-alla-milanese') AND order_index = 4;
UPDATE clues SET text = 'Russia''s creamy brown skillet of beef strips, spooned over buttered egg noodles.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-stroganoff') AND order_index = 5;
UPDATE clues SET text = 'Jamaica''s charred, dark-red chicken pieces, chopped through the bone and sold from a foil tray.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'jerk-chicken') AND order_index = 5;
UPDATE clues SET text = 'India''s thick, deep-green sauce with soft white cubes, scooped up with naan or rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'palak-paneer') AND order_index = 5;
UPDATE clues SET text = 'Rolled by the tray, fried in batches, and gone before the party ends.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lumpia') AND order_index = 1;
UPDATE clues SET text = 'The Philippines'' golden cigar-shaped rolls, stacked on a platter with a dipping sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lumpia') AND order_index = 5;
UPDATE clues SET text = 'Germany''s thick slices of dark roast in a glossy, sweet-sour gravy, with potato dumplings beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sauerbraten') AND order_index = 5;
UPDATE clues SET text = 'Mexico''s neat row of filled tortillas, bathed in red or green salsa and scattered with onion.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'enchiladas') AND order_index = 5;
UPDATE clues SET text = 'A plate so full the waiter sets it down with two hands.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bandeja-paisa') AND order_index = 1;
UPDATE clues SET text = 'Colombia''s farmer''s tray, crowned with a sunny egg and a shard of crackling pork skin.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bandeja-paisa') AND order_index = 5;
UPDATE clues SET text = 'Sliced like a cake, but it''s cold and made of potato.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'causa-limena') AND order_index = 1;
UPDATE clues SET text = 'Peru''s sunny yellow slab, cut in neat squares with a dab of mayonnaise and olives on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'causa-limena') AND order_index = 5;
UPDATE clues SET text = 'A side dish that arrives as golden coins stacked high on a plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-plantains') AND order_index = 1;
UPDATE clues SET text = 'Cuba''s flattened, crisp-edged discs, salted and served hot beside rice and beans.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-plantains') AND order_index = 5;
UPDATE clues SET text = 'Lebanon''s green-flecked bowl, scooped up with a lettuce leaf instead of a spoon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tabbouleh') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s red-flecked thin round, rolled around parsley and onion and eaten out of the paper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lahmacun') AND order_index = 5;
UPDATE clues SET text = 'Ireland''s pale, buttery mound with a pool of melted butter in the middle and green flecks through it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'colcannon') AND order_index = 5;
UPDATE clues SET text = 'Crisp and greasy in the best way, served in a paper sleeve.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kartoffelpuffer') AND order_index = 1;
UPDATE clues SET text = 'Germany''s flat golden discs with dark, lacy edges, stacked beside a spoon of sour cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kartoffelpuffer') AND order_index = 5;
UPDATE clues SET text = 'Greece''s thick square of macaroni and spiced meat, a brown-gold crust over a white sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pastitsio') AND order_index = 5;
UPDATE clues SET text = 'America''s clear-red bowl, shellfish chunks bobbing in it and a handful of crackers on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manhattan-clam-chowder') AND order_index = 5;
UPDATE clues SET text = 'Germany''s browned sausage in a crusty bun, a stripe of yellow mustard down the length.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bratwurst') AND order_index = 5;
UPDATE clues SET text = 'A starter that is only as good as its tomato.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caprese-salad') AND order_index = 1;
UPDATE clues SET text = 'Italy''s overlapping rounds, juicy red against milky white, fanned out on a plate with leaves.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'caprese-salad') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s long, charred fingers of meat, pulled off the skewer into warm flatbread.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kofta') AND order_index = 5;
UPDATE clues SET text = 'A bread that doubles as a bowl, and arrives still bubbling.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khachapuri') AND order_index = 1;
UPDATE clues SET text = 'America''s café-table plate of puffed squares, so deep in sugar you have to dig for the dough.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beignets') AND order_index = 5;
UPDATE clues SET text = 'Island comfort food, stacked high and finished with a fork.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 1;
UPDATE clues SET text = 'America''s stacked island plate: rice at the base, brown gravy at the top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loco-moco') AND order_index = 5;
UPDATE clues SET text = 'Britain''s oval plate loaded with fried everything, a wedge of toast leaning on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'full-english-breakfast') AND order_index = 5;
UPDATE clues SET text = 'A pasta with three things in the bowl and nowhere for a mistake to hide.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cacio-e-pepe') AND order_index = 1;
UPDATE clues SET text = 'Italy''s tangle of spaghetti in a pale, glossy sauce, specked grey with pepper.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cacio-e-pepe') AND order_index = 5;
UPDATE clues SET text = 'France''s rectangular onion tart, dark with anchovy fillets and olives in a diamond pattern.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pissaladiere') AND order_index = 5;
UPDATE clues SET text = 'India''s thick, browned flatbread, split to show a spiced potato filling, with pickle and yogurt alongside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aloo-paratha') AND order_index = 5;
UPDATE clues SET text = 'Cooks shake sweet milky tea with ice, then pour it over chewy black tapioca balls.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-tea') AND order_index = 4;
UPDATE clues SET text = 'France''s smooth yellow fold with a glossy surface, cut open to a soft, creamy center.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'omelette') AND order_index = 5;
UPDATE clues SET text = 'America''s pink curls hooked on a glass, dark red sauce in the well.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-cocktail') AND order_index = 5;
UPDATE clues SET text = 'It leaves the fryer with more crags and crevices than any other pastry in the case, each catching glaze.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-fritter') AND order_index = 3;
UPDATE clues SET text = 'Ukraine''s ruby bowl with a white swirl of sour cream and a sprig of dill on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'borscht') AND order_index = 5;
UPDATE clues SET text = 'China''s glossy mahogany bird, its skin sliced into thin rafts and rolled into steamed pancakes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peking-duck') AND order_index = 5;
UPDATE clues SET text = 'Two Philadelphia hot dog vendors are credited with putting steak on a roll in the 1930s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'philly-cheesesteak') AND order_index = 2;
UPDATE clues SET text = 'A birthday and fiesta centerpiece with skin that shatters like glass.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lechon') AND order_index = 1;
UPDATE clues SET text = 'Britain''s casserole dish of dark, gravy-rich mince, a ridged potato crust browned on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shepherd-s-pie') AND order_index = 5;
UPDATE clues SET text = 'Japan''s neat rows of rice-topped slices and rolls, with wasabi, pickled ginger and soy on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sushi') AND order_index = 5;
UPDATE clues SET text = 'Indonesia''s glossy brown rice topped with a runny-yolk egg, prawn crackers and sliced cucumber beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-goreng') AND order_index = 5;
UPDATE clues SET text = 'America''s deep golden wedge, steam rising from the slits, a puddle of cream melting beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'apple-pie') AND order_index = 5;
UPDATE clues SET text = 'A dip that browns in minutes if you leave it uncovered.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'guacamole') AND order_index = 1;
UPDATE clues SET text = 'Minced pork and a jellied broth are wrapped in thin dough, pleated shut, and steamed until the jelly melts.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'xiaolongbao') AND order_index = 4;
UPDATE clues SET text = 'Tokyo cooks adapted a French veal cutlet in the 1900s, swapping in pork and a deep fryer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tonkatsu') AND order_index = 2;
UPDATE clues SET text = 'Nepal''s round dumplings with twisted tops, lined up in a bamboo steamer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'momo') AND order_index = 5;
UPDATE clues SET text = 'A soft breakfast disc that gets eaten with something to dunk it in.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'idli') AND order_index = 1;
UPDATE clues SET text = 'South India''s small white discs, soft as pillows, with a bowl of sambar beside them.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'idli') AND order_index = 5;
UPDATE clues SET text = 'North India''s glossy brick-red chickpeas, with raw onion rings and a lemon wedge beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chana-masala') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s orange-red broth, a floating raft of big prawns, torn herbs and a slick of chili oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-yum-goong') AND order_index = 5;
UPDATE clues SET text = 'Thailand''s deep-brown, nutty curry, served with jasmine rice and a few whole peanuts on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'massaman-curry') AND order_index = 5;
UPDATE clues SET text = 'Indonesia''s row of small skewers on a banana-leaf plate, with rice cakes and sliced onion beside.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'satay') AND order_index = 5;
UPDATE clues SET text = 'A tart that is more custard than filling, cut in wedges and eaten warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quiche-lorraine') AND order_index = 1;
UPDATE clues SET text = 'A bakery twist that comes with salt crystals and a chewy bite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pretzel') AND order_index = 1;
UPDATE clues SET text = 'Germany''s shiny, mahogany knot with a split belly, coarse salt on top and mustard on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pretzel') AND order_index = 5;
UPDATE clues SET text = 'A snack you rotate like a typewriter as you eat across the row.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'elote') AND order_index = 1;
UPDATE clues SET text = 'A salad with a shattering crunch, built to be eaten fast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fattoush') AND order_index = 1;
UPDATE clues SET text = 'Lebanon''s bright chopped bowl, dusted purple-red with sumac and strewn with bread shards.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fattoush') AND order_index = 5;
UPDATE clues SET text = 'A red dip that is coarse, nutty and almost sticky.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'muhammara') AND order_index = 1;
UPDATE clues SET text = 'A feast that is served hours after the fire was lit, and dug up like treasure.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hangi') AND order_index = 1;
UPDATE clues SET text = 'New Zealand''s earthy-smelling feast, lifted from a pit in baskets, with sweet kumara beside the meat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hangi') AND order_index = 5;
UPDATE clues SET text = 'Villages across central Europe baked a version of it for weddings and fairs for centuries.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'trdelnik') AND order_index = 2;
UPDATE clues SET text = 'Norway''s browned, springy patties, served with boiled potatoes and a spoon of creamy sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-cakes') AND order_index = 5;
UPDATE clues SET text = 'Sweden''s glossy brown coil with pearl sugar on top, the usual partner to a coffee break.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kanelbulle') AND order_index = 5;
UPDATE clues SET text = 'Ireland''s flat, golden-edged pancake, rolled around a filling or served with a full fry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'boxty') AND order_index = 5;
UPDATE clues SET text = 'America''s mound of fine-grained meat sauce over spaghetti, hidden under a drift of orange cheese.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cincinnati-chili') AND order_index = 5;
UPDATE clues SET text = 'America''s Southwest treat, eaten with a plastic fork out of a slit crinkly bag.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frito-pie') AND order_index = 5;
UPDATE clues SET text = 'A dessert that looks like an accident and is meant to.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eton-mess') AND order_index = 1;
UPDATE clues SET text = 'Britain''s pink-and-white heap of crumbled meringue and cream, spooned into a tall glass.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eton-mess') AND order_index = 5;
UPDATE clues SET text = 'Britain''s roasting-tin supper, sausages half-sunk in a crisp, billowing crust, gravy on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'toad-in-the-hole') AND order_index = 5;
UPDATE clues SET text = 'Home cooks there wrapped thin beef around bacon and pickle, a way to make a small roast serve a crowd.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rouladen') AND order_index = 2;
UPDATE clues SET text = 'Spain''s thick golden wedge, tender inside, with a glass of wine and a toothpick.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tortilla-espanola') AND order_index = 5;
UPDATE clues SET text = 'France''s shiny amber disc, apple slices packed tight under a glossy caramel crown.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tarte-tatin') AND order_index = 5;
UPDATE clues SET text = 'Hollandaise is the whole trick, and a split sauce ruins the plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eggs-benedict') AND order_index = 3;
UPDATE clues SET text = 'Italy''s puffy golden turnover, venting steam the second you cut into it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'calzone') AND order_index = 5;
UPDATE clues SET text = 'Greece''s coarse chunks glistening with oil, a block of white cheese on top and dried oregano over it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'greek-salad') AND order_index = 5;
UPDATE clues SET text = 'Ghana''s soft, stretchy white ball in a bowl of peppery soup, eaten with the right hand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 5;
UPDATE clues SET text = 'Morocco''s small glass of pale green, frothy tea, with sprigs of green pressed against the glass.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'moroccan-mint-tea') AND order_index = 5;
UPDATE clues SET text = 'Türkiye''s pastel, jelly-soft squares, snowed with white powder and stacked in a flat wooden box.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'turkish-delight') AND order_index = 5;
UPDATE clues SET text = 'Australia''s triangles of white bread covered in hundreds and thousands, the sprinkles every child knows.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fairy-bread') AND order_index = 5;
UPDATE clues SET text = 'America''s smooth, pale cut-outs, crisp at the edge and iced in bright colors for holidays.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sugar-cookies') AND order_index = 5;
UPDATE clues SET text = 'Italy''s golden doughnut-like ring, a swirl of custard on top and a single dark cherry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'zeppole') AND order_index = 5;
UPDATE clues SET text = 'A good one is crisp outside and soft in layers, and the cook flips the whole thing in the air.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'roti-canai') AND order_index = 3;
UPDATE clues SET text = 'A dough pinched off in small pieces and used to scoop up the soup.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fufu') AND order_index = 1;
