-- Backfill: clue rewrites against the beat sheet.
-- 197 clues across 193 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'One wide pan of rice goes down in the middle of a Spanish party, and spoons come out.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'paella') AND order_index = 5;
UPDATE clues SET text = 'Sold from a cart in Vietnam, a crisp baguette split open and stuffed so full it will not close.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'banh-mi') AND order_index = 5;
UPDATE clues SET text = 'Small ridged dumplings from Italy, each groove built to hold a spoonful of sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gnocchi') AND order_index = 5;
UPDATE clues SET text = 'Charred kernels slicked with cream and chili, sold on a stick on Mexican street corners.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'elote') AND order_index = 5;
UPDATE clues SET text = 'A dark, smoky pot ladled out on Brazilian weekends, orange slices on the side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'feijoada') AND order_index = 5;
UPDATE clues SET text = 'Grilled meat on a stick or wrapped in warm pita, a Greek fast-food order.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souvlaki') AND order_index = 5;
UPDATE clues SET text = 'Wobbly yellow custard in a crisp shell, a Hong Kong bakery favorite eaten warm.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egg-tart') AND order_index = 5;
UPDATE clues SET text = 'Sweet, sticky and dark, this Moroccan stew sits under a cone lid until the table is ready.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tagine-of-lamb-and-prunes') AND order_index = 5;
UPDATE clues SET text = 'Beef cooked over embers for hours on an Argentine Sunday, with chimichurri and salt.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'asado') AND order_index = 5;
UPDATE clues SET text = 'A golden, flaky pie from Greece, cut in squares, with spinach and feta oozing out.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spanakopita') AND order_index = 5;
UPDATE clues SET text = 'A rust-orange stew from Hungary, ladled over small dumplings and swirled with sour cream.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-paprikash') AND order_index = 5;
UPDATE clues SET text = 'A dessert plate in France with four folded quarters, a blue flame still flickering over it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crepe-suzette') AND order_index = 5;
UPDATE clues SET text = 'A palm-sized pie sold at Australian football grounds, with a squirt of tomato sauce on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'meat-pie') AND order_index = 5;
UPDATE clues SET text = 'Ladled out by Egyptian street vendors from a stack of bowls, with a splash of hot chili sauce.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'koshari') AND order_index = 5;
UPDATE clues SET text = 'Buttons of pasta the size of a thumbnail, sold in Türkiye by the plate with red butter on top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'manti') AND order_index = 5;
UPDATE clues SET text = 'A salad from the south of France where anchovy and olive oil do the dressing''s job.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nicoise-salad') AND order_index = 5;
UPDATE clues SET text = 'A café lunch in France, golden on top, with ham and cheese hiding beneath a toasty lid.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'croque-monsieur') AND order_index = 5;
UPDATE clues SET text = 'Soft, irregular little noodles served in Germany with melted cheese, onions or gravy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaetzle') AND order_index = 5;
UPDATE clues SET text = 'Chunky and tomato-red, an Italian soup with beans, pasta and a swirl of green oil.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'minestrone') AND order_index = 5;
UPDATE clues SET text = 'Golden chunks under red sauce and white sauce, the plate to order at any bar in Spain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patatas-bravas') AND order_index = 5;
UPDATE clues SET text = 'A dark, nearly dry curry from Indonesia, each piece coated in a sticky paste of spice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-rendang') AND order_index = 5;
UPDATE clues SET text = 'Cooked on a hot plate at your table in Japan, a thick pancake layered with cabbage and topped with fish flakes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'okonomiyaki') AND order_index = 5;
UPDATE clues SET text = 'A beige dip you scoop up with warm pita, the first thing set down on a Lebanese table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hummus') AND order_index = 5;
UPDATE clues SET text = 'Golden, loose and salty, a fish scramble from Portugal finished with black olives and parsley.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bacalhau-a-bras') AND order_index = 5;
UPDATE clues SET text = 'A bulging savory pudding served on Burns Night in Scotland, with neeps and tatties.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'haggis') AND order_index = 5;
UPDATE clues SET text = 'Boiled vegetables and egg buried under peanut sauce, the lunchtime salad of Indonesia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gado-gado') AND order_index = 5;
UPDATE clues SET text = 'Two golden layers with jam and cream between, a teatime classic across Britain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'victoria-sponge-cake') AND order_index = 5;
UPDATE clues SET text = 'A pale, rich terrine sliced cold onto toast, a French holiday-table tradition.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'foie-gras') AND order_index = 5;
UPDATE clues SET text = 'A tight foil-wrapped log, heavy in one hand, sold at Mexican-American taquerias.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'burrito') AND order_index = 5;
UPDATE clues SET text = 'A crisp tube with cream piped in at both ends, the sweet in an Italian pastry-shop window.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cannoli') AND order_index = 5;
UPDATE clues SET text = 'A white dome that wobbles whenever the plate moves, the soft finish to an Italian dinner.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'panna-cotta') AND order_index = 5;
UPDATE clues SET text = 'A puffed hollow batter cup, waiting for gravy beside a British Sunday roast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yorkshire-pudding') AND order_index = 5;
UPDATE clues SET text = 'A cone-lidded pot set down in Morocco with couscous or bread beside it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-tagine') AND order_index = 5;
UPDATE clues SET text = 'Golden puffs, sticky and eaten hot with a fork, a street sweet in Greece.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'loukoumades') AND order_index = 5;
UPDATE clues SET text = 'Cold, sliced fish with no rice anywhere near it, a Japanese plate of pure fish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sashimi') AND order_index = 5;
UPDATE clues SET text = 'Two folded tortillas with crisp fish, cabbage and crema, a seaside order in Mexico.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-tacos') AND order_index = 5;
UPDATE clues SET text = 'A bubbling red pot with sour steam coming off the top, shared at a table in Korea.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kimchi-jjigae') AND order_index = 5;
UPDATE clues SET text = 'A pale beige curry, mild and thick with ground nut, from an Indian kitchen.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-korma') AND order_index = 5;
UPDATE clues SET text = 'A cold white side, flecked pale green with cucumber, set down beside an Indian curry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'raita') AND order_index = 5;
UPDATE clues SET text = 'A dark Goan curry, sour and hot at the same moment, from the coast of India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vindaloo') AND order_index = 5;
UPDATE clues SET text = 'The most famous spoon dessert in Italy, heavy on the espresso.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tiramisu') AND order_index = 5;
UPDATE clues SET text = 'A cutlet under red sauce and a molten white blanket, born in Italian-American kitchens.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-parmesan') AND order_index = 5;
UPDATE clues SET text = 'A sandwich on crackling French bread, a New Orleans lunch counter order in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'po-boy') AND order_index = 5;
UPDATE clues SET text = 'A clear bowl with pale parcels drifting about in it, ordered at Chinese restaurants everywhere.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wonton-soup') AND order_index = 5;
UPDATE clues SET text = 'A slow-baked white bean and duck stew from the southwest of France.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cassoulet') AND order_index = 5;
UPDATE clues SET text = 'A dark brown stew, sour and thick from ground walnut, served at celebrations in Iran.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khoresh-fesenjan') AND order_index = 5;
UPDATE clues SET text = 'A dense frozen scoop, scraped up flat with a paddle, from an Italian gelateria.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 5;
UPDATE clues SET text = 'A soaked sponge so wet it pools on the plate, a Mexican birthday cake.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tres-leches-cake') AND order_index = 5;
UPDATE clues SET text = 'A thick green stew, grainy with ground melon seed, ladled out in Nigeria.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egusi-soup') AND order_index = 5;
UPDATE clues SET text = 'A pale dome sitting in the caramel that ran off it, a Spanish dessert-cart classic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flan') AND order_index = 5;
UPDATE clues SET text = 'A forked potato crust over a creamy parsley sauce, the Friday supper of Britain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-pie') AND order_index = 5;
UPDATE clues SET text = 'A thick orange glass, cold enough to fog the outside, poured at Indian restaurants.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mango-lassi') AND order_index = 5;
UPDATE clues SET text = 'A noodle bowl with cloudy broth under a halved jammy egg, from a shop in Japan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ramen') AND order_index = 5;
UPDATE clues SET text = 'A smoky grey dip pooled with oil in the middle, set out on a Lebanese mezze table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'baba-ganoush') AND order_index = 5;
UPDATE clues SET text = 'The ''mixed rice'' of Korea, best served in a sizzling stone bowl.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bibimbap') AND order_index = 5;
UPDATE clues SET text = 'A brick-red dip, sweet and rough with crushed walnut, from the kitchens of Syria.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'muhammara') AND order_index = 5;
UPDATE clues SET text = 'A patty of lump meat barely held together, a Chesapeake Bay classic in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-cakes') AND order_index = 5;
UPDATE clues SET text = 'A baked orange pasta crusted brown across the top, a comfort dish across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mac-and-cheese') AND order_index = 5;
UPDATE clues SET text = 'A pale creamy bowl under pink shellfish, the signature plate of the American South.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-and-grits') AND order_index = 5;
UPDATE clues SET text = 'The unofficial national dish of the Philippines, served over rice.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-adobo') AND order_index = 5;
UPDATE clues SET text = 'A thick Texan bowl, dark red and eaten with a spoon, from America''s Southwest.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chili-con-carne') AND order_index = 5;
UPDATE clues SET text = 'A beef patty in a bun, and this diner''s best seller across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hamburger') AND order_index = 5;
UPDATE clues SET text = 'A split toasted bun overflowing with cold shellfish, a summer lunch in America''s New England.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lobster-roll') AND order_index = 5;
UPDATE clues SET text = 'A dripping roll folded up in foil, the lunch of Philadelphia and all America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'philly-cheesesteak') AND order_index = 5;
UPDATE clues SET text = 'A flaky crescent that shatters into shards on the plate, the French breakfast pastry.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'croissant') AND order_index = 5;
UPDATE clues SET text = 'A cream, onion and bacon flatbread from the Franco-German border.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'flammkuchen') AND order_index = 5;
UPDATE clues SET text = 'A deep red bowl, somewhere between a soup and a stew, served all over Hungary.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'goulash') AND order_index = 5;
UPDATE clues SET text = 'Crescent dumplings with one side browned lace-crisp, from a Japanese ramen shop.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyoza') AND order_index = 5;
UPDATE clues SET text = 'A pale coconut bowl with oil beading across the surface, from a kitchen in Thailand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'thai-green-curry') AND order_index = 5;
UPDATE clues SET text = 'A dark-crusted smoked slab, sliced against the grain, from a Texas pit in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beef-brisket') AND order_index = 5;
UPDATE clues SET text = 'Halved whites piped full of yellow and dusted red, set out on a plate at an American potluck.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deviled-eggs') AND order_index = 5;
UPDATE clues SET text = 'A lacy fried tangle, snowed under with sugar, sold at county fairs across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'funnel-cake') AND order_index = 5;
UPDATE clues SET text = 'A shiny ring whose coat cracks slightly as you bite, the American coffee-shop default.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'glazed-donut') AND order_index = 5;
UPDATE clues SET text = 'Fried bird under a red crust that stains the paper, a Nashville order in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-chicken-sandwich') AND order_index = 5;
UPDATE clues SET text = 'Cut corner to corner and sealed in a baggie, the school lunch of America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'peanut-butter-and-jelly-sandwich') AND order_index = 5;
UPDATE clues SET text = 'A three-layer square, chocolate over yellow over crumb, from a bakery in Canada.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nanaimo-bar') AND order_index = 5;
UPDATE clues SET text = 'Tangled fried noodles, browned where they hit the wok, ladled from a Chinese takeout carton.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chow-mein') AND order_index = 5;
UPDATE clues SET text = 'Wok-tossed grains, glossy and flecked yellow with egg, a Chinese kitchen''s quickest meal.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fried-rice') AND order_index = 5;
UPDATE clues SET text = 'An edible boat with the yolk still trembling in the middle, baked in Georgia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'khachapuri') AND order_index = 5;
UPDATE clues SET text = 'A craggy fried tangle that falls apart into loose strands, served with chutney in India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'onion-bhaji') AND order_index = 5;
UPDATE clues SET text = 'A thick dimpled flatbread, torn into squares off a tray in an Italian bakery.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'focaccia') AND order_index = 5;
UPDATE clues SET text = 'A loaded pile with the chips underneath already going soft, a Mexican border invention.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nachos') AND order_index = 5;
UPDATE clues SET text = 'A chunky red relish sitting raw in its own lime juice, spooned out at any Mexican taco stand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pico-de-gallo') AND order_index = 5;
UPDATE clues SET text = 'Boiled-then-buttered dumplings, best with sour cream, on a Polish holiday table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pierogi') AND order_index = 5;
UPDATE clues SET text = 'A foil-wrapped cylinder eaten one-handed on the road, a morning order across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'breakfast-burrito') AND order_index = 5;
UPDATE clues SET text = 'Dark squares, fudgy in the middle and papery on top, an American bake-sale favorite.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'brownies') AND order_index = 5;
UPDATE clues SET text = 'A pale silky porridge with no grain you can see in it, an American childhood breakfast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cream-of-wheat') AND order_index = 5;
UPDATE clues SET text = 'A plain hot bowl with brown sugar melting into the middle, a breakfast across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'oatmeal') AND order_index = 5;
UPDATE clues SET text = 'Red-edged glossy pork, sliced and fanned out over rice at a Chinese barbecue shop.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'char-siu') AND order_index = 5;
UPDATE clues SET text = 'A yellow rice pot with the chicken buried down in it, served in Colombian homes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'arroz-con-pollo') AND order_index = 5;
UPDATE clues SET text = 'A flaky spiral with a dab of jam at its center, baked in Denmark.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'danish-pastry') AND order_index = 5;
UPDATE clues SET text = 'A long glazed finger with cream squeezing out when you bite, from a French patisserie.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eclair') AND order_index = 5;
UPDATE clues SET text = 'A blistered teardrop, torn to push food around the plate, served alongside Indian curries.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'naan') AND order_index = 5;
UPDATE clues SET text = 'A fried triangle dipped in tamarind and mint chutney, sold at Indian tea stalls.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'samosa') AND order_index = 5;
UPDATE clues SET text = 'A browned folded round, cut into wedges that pull apart, from a Mexican kitchen.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quesadilla') AND order_index = 5;
UPDATE clues SET text = 'Thin, glossy-dark beef cooked at the table, the Korean barbecue most diners try first.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bulgogi') AND order_index = 5;
UPDATE clues SET text = 'Sticky glazed bones, dark red and pulling clean away, from a pit in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bbq-ribs') AND order_index = 5;
UPDATE clues SET text = 'A get-well bowl with steam coming off a clear gold surface, in kitchens across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-noodle-soup') AND order_index = 5;
UPDATE clues SET text = 'A dark brown Cajun stew smothered over white rice, from Louisiana in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crawfish-etouffee') AND order_index = 5;
UPDATE clues SET text = 'A golden griddled sandwich pulling apart into strings, an American lunch-counter default.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'grilled-cheese') AND order_index = 5;
UPDATE clues SET text = 'A grilled rye stack with dressing running out at the sides, from an American deli.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'reuben-sandwich') AND order_index = 5;
UPDATE clues SET text = 'A cold hotel plate of apple and walnut on a lettuce leaf, from a grand American hotel.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'waldorf-salad') AND order_index = 5;
UPDATE clues SET text = 'Deep-pocketed squares under a drift of powdered sugar, sold at waffle stands in Belgium.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'belgian-waffles') AND order_index = 5;
UPDATE clues SET text = 'A thin silky broth with pale ribbons suspended all through it, from a Chinese kitchen.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'egg-drop-soup') AND order_index = 5;
UPDATE clues SET text = 'A neon-orange takeaway bowl with pineapple bright in among it, from Chinese restaurants.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sweet-and-sour-pork') AND order_index = 5;
UPDATE clues SET text = 'A flaky rectangle with two dark seams running through it, from a French boulangerie.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pain-au-chocolat') AND order_index = 5;
UPDATE clues SET text = 'A cold pale soup with chives snipped over a chilled bowl, served at French restaurants in New York.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'vichyssoise') AND order_index = 5;
UPDATE clues SET text = 'Dark rolled bundles, sliced to show the spiral inside, on a German Sunday table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rouladen') AND order_index = 5;
UPDATE clues SET text = 'A paper cone of shaved meat with sauce leaking at the bottom, sold on the streets of Greece.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gyro') AND order_index = 5;
UPDATE clues SET text = 'A crustless white sandwich eaten cold out of its wrapper, sold at Japanese convenience stores.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'katsu-sando') AND order_index = 5;
UPDATE clues SET text = 'A wrap of shaved meat with pickles bright pink inside it, a Lebanese street-corner order.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shawarma') AND order_index = 5;
UPDATE clues SET text = 'A sealed plastic cup with black pearls settled at the bottom, a drink from Taiwan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bubble-tea') AND order_index = 5;
UPDATE clues SET text = 'A spongy round with butter disappearing down into the holes, toasted for British tea.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crumpets') AND order_index = 5;
UPDATE clues SET text = 'A rye-bread hybrid, half burger and half grilled cheese, from an American diner flat-top.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'patty-melt') AND order_index = 5;
UPDATE clues SET text = 'An orange-flecked spread on soft white slices, a porch-party snack in the American South.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pimento-cheese-sandwich') AND order_index = 5;
UPDATE clues SET text = 'Raw cubes over rice, glossy with soy, a Hawaiian dish adopted across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'poke-bowl') AND order_index = 5;
UPDATE clues SET text = 'A flat golden slab hanging over the edge of the plate, served all over Argentina.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'milanesa') AND order_index = 5;
UPDATE clues SET text = 'A pleated soup dumpling that is hot enough to burn if you rush it, from Shanghai in China.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'xiaolongbao') AND order_index = 5;
UPDATE clues SET text = 'Warm brown spheres with syrup running out when you press one, served at Indian weddings.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gulab-jamun') AND order_index = 5;
UPDATE clues SET text = 'A small glass of milky brown, drunk scalding on an Indian railway platform.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-chai') AND order_index = 5;
UPDATE clues SET text = 'A giant golden crepe with coconut chutney and sambar, a breakfast in South India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'masala-dosa') AND order_index = 5;
UPDATE clues SET text = 'Brick-red Kashmiri lamb with the gravy clinging to the spoon, from northern India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'rogan-josh') AND order_index = 5;
UPDATE clues SET text = 'A thick open-faced egg cake, served in wedges warm or cold, in an Italian home.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'frittata') AND order_index = 5;
UPDATE clues SET text = 'A braised veal shank with the marrow still sitting in the bone, from Milan in Italy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ossobuco') AND order_index = 5;
UPDATE clues SET text = 'Raw shrimp in a green pool with cucumber sliced thin on top, from the coast of Mexico.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'aguachile') AND order_index = 5;
UPDATE clues SET text = 'A red bowl with bloated white kernels floating all through it, served on Mexican feast days.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pozole') AND order_index = 5;
UPDATE clues SET text = 'A small custard cup with its top blistered black in patches, a bakery treat in Portugal.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pastel-de-nata') AND order_index = 5;
UPDATE clues SET text = 'Glossy red cylinders chewy enough to need a second bite, sold at Korean street stalls.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tteokbokki') AND order_index = 5;
UPDATE clues SET text = 'A pale creamy bowl, sour and fragrant rather than fiery, from a Thai table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tom-kha-gai') AND order_index = 5;
UPDATE clues SET text = 'A bubbling orange bowl scooped up with celery and chips, a game-day dish in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buffalo-chicken-dip') AND order_index = 5;
UPDATE clues SET text = 'A fluffy stack with butter sliding down it under maple syrup, the American diner breakfast.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'buttermilk-pancakes') AND order_index = 5;
UPDATE clues SET text = 'A lattice-topped diner slice, warm under a melting scoop, as served across America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cherry-pie') AND order_index = 5;
UPDATE clues SET text = 'A toasted triple-decker, quartered and pinned with picks, from American hotel menus.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'club-sandwich') AND order_index = 5;
UPDATE clues SET text = 'A battered sausage on a stick with mustard zigzagged down it, a fairground meal in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'corn-dog') AND order_index = 5;
UPDATE clues SET text = 'A garlicky butter pool with linguine tangled through it, an Italian-American restaurant classic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-scampi') AND order_index = 5;
UPDATE clues SET text = 'A cracked-top cookie rolled in cinnamon before it bakes, an American lunchbox treat.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'snickerdoodles') AND order_index = 5;
UPDATE clues SET text = 'A deep egg tart, set pale gold and studded dark with bacon, from eastern France.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'quiche-lorraine') AND order_index = 5;
UPDATE clues SET text = 'A cold picnic bowl dressed heavy and left to sit a while, a German summer side.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'potato-salad') AND order_index = 5;
UPDATE clues SET text = 'A battered green chili with the cheese pulling when you cut it, on a Mexican plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chiles-rellenos') AND order_index = 5;
UPDATE clues SET text = 'A sweet-sour tangle with peanut and lime waiting on the side, from a street stall in Thailand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pad-thai') AND order_index = 5;
UPDATE clues SET text = 'A skillet of eggs in red sauce, mopped up with torn bread, as eaten in Tunisia.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shakshuka') AND order_index = 5;
UPDATE clues SET text = 'A halved sphere with a yellow center ringed in meat and crumb, a British picnic snack.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'scotch-egg') AND order_index = 5;
UPDATE clues SET text = 'A warm bakery spiral under a cap of cream cheese frosting, from the mall food courts of America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cinnamon-rolls') AND order_index = 5;
UPDATE clues SET text = 'A San Francisco seafood pot with shells piled above the broth, an American coastal classic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cioppino') AND order_index = 5;
UPDATE clues SET text = 'A fried wonton purse with cream cheese oozing out at the seam, from American takeout.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'crab-rangoon') AND order_index = 5;
UPDATE clues SET text = 'A brunch plate with yellow sauce spilling over a poached yolk, an American diner icon.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'eggs-benedict') AND order_index = 5;
UPDATE clues SET text = 'A dark glossy sauce over crisp batter, the takeaway favorite of America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'general-tsos-chicken') AND order_index = 5;
UPDATE clues SET text = 'A crisp golden patty served beside the eggs, as diners across America do.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hash-browns') AND order_index = 5;
UPDATE clues SET text = 'A towering dessert under a browned cloud of whipped white, from an American bake sale.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lemon-meringue-pie') AND order_index = 5;
UPDATE clues SET text = 'A heaped soft bun with slaw piled on top of the shredded meat, from the American South.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pulled-pork-sandwich') AND order_index = 5;
UPDATE clues SET text = 'A cold striped glass dish, counted off from the bottom up, brought to American potlucks.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'seven-layer-dip') AND order_index = 5;
UPDATE clues SET text = 'A hot green bowl, stringy with cheese and served bubbling, ordered at American restaurants.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spinach-and-artichoke-dip') AND order_index = 5;
UPDATE clues SET text = 'A tall clear cup of stripes, eaten cold with a long spoon, sold at American cafes.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'yogurt-parfait') AND order_index = 5;
UPDATE clues SET text = 'A thick dark bowl that catches you at the back of the throat, from a Chinese kitchen.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'hot-and-sour-soup') AND order_index = 5;
UPDATE clues SET text = 'A dark stir-fry, glossy with peanuts and whole dried chilies, from Sichuan in China.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'kung-pao-chicken') AND order_index = 5;
UPDATE clues SET text = 'A weeknight dinner scooped over rice and finished with a squeeze of lime.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-curry') AND order_index = 1;
UPDATE clues SET text = 'A yellow coconut bowl with soft white pieces breaking apart in it, from the islands of Fiji.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-curry') AND order_index = 5;
UPDATE clues SET text = 'Custard-soaked slices, fried golden and dusted with sugar, called lost bread in France.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'french-toast') AND order_index = 5;
UPDATE clues SET text = 'A tall wobbling puff that sinks the moment it leaves the oven, a French restaurant classic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'souffle') AND order_index = 5;
UPDATE clues SET text = 'Little green cylinders served cold with a wedge of lemon, passed around in Greece.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dolmades') AND order_index = 5;
UPDATE clues SET text = 'Near-black lentils, thick and velvet with a swirl of cream, a Punjabi restaurant favorite in India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'dal-makhani') AND order_index = 5;
UPDATE clues SET text = 'Fat white noodles thick enough to feel between your teeth, from a Japanese noodle shop.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'udon') AND order_index = 5;
UPDATE clues SET text = 'A mound of tiny steamed pellets piled under a spiced stew, the Friday meal in Morocco.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'couscous') AND order_index = 5;
UPDATE clues SET text = 'Dark skewers blackened at the tips and eaten off the stick, sold on Peruvian street corners.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'anticuchos') AND order_index = 5;
UPDATE clues SET text = 'Cured salmon sliced thin enough to see the plate through, served at a Swedish holiday table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gravlax') AND order_index = 5;
UPDATE clues SET text = 'Pounded shreds sharp with lime and studded with peanut, from a night market in Thailand.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'green-papaya-salad') AND order_index = 5;
UPDATE clues SET text = 'A crimped pastry parcel made to be held by the thick edge, from the west of Britain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'cornish-pasty') AND order_index = 5;
UPDATE clues SET text = 'A chip-shop classic wrapped in paper, best with malt vinegar and mushy peas, from Britain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fish-and-chips') AND order_index = 5;
UPDATE clues SET text = 'A browned bubbling slab with the topping set just before it burns, a pub plate in Wales.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'welsh-rarebit') AND order_index = 5;
UPDATE clues SET text = 'A chewy boiled ring with orange fish draped over a white smear, a New York brunch in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'bagel-with-lox') AND order_index = 5;
UPDATE clues SET text = 'A golden pastry lid over a filling that steams when broken, a cold-night dinner in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chicken-pot-pie') AND order_index = 5;
UPDATE clues SET text = 'A deep-panned slice standing two inches tall on the plate, from a Chicago pizzeria in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'deep-dish-pizza') AND order_index = 5;
UPDATE clues SET text = 'Baked golden clusters, loose in the bowl under cold milk, a breakfast invented in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'granola') AND order_index = 5;
UPDATE clues SET text = 'A dark New Orleans stew ladled over a scoop of white rice, the pride of Louisiana in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gumbo') AND order_index = 5;
UPDATE clues SET text = 'Pink curls hooked on a glass, dark red sauce in the well, a retro starter in America.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'shrimp-cocktail') AND order_index = 5;
UPDATE clues SET text = 'A red plate with the rolled beef sitting on top of the strands, an Italian-American classic.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'spaghetti-and-meatballs') AND order_index = 5;
UPDATE clues SET text = 'A pale golden cutlet wider than the plate and thin as card, from a Viennese kitchen in Austria.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'wiener-schnitzel') AND order_index = 5;
UPDATE clues SET text = 'A Quebec Christmas bake, pale pastry over spiced ground pork, from Canada.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tourtiere') AND order_index = 5;
UPDATE clues SET text = 'A fiery red-oil bowl with the white cubes barely holding together, from Sichuan in China.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mapo-tofu') AND order_index = 5;
UPDATE clues SET text = 'An orange gateway curry, thick and silky in a small steel bowl, from a Delhi restaurant in India.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'butter-chicken') AND order_index = 5;
UPDATE clues SET text = 'A pasta tossed at the table, where the sauce forms as the ribbons are turned.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fettuccine-alfredo') AND order_index = 1;
UPDATE clues SET text = 'Pale ribbons coated glossy with nothing but fat and cheese, a Roman restaurant dish in Italy.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'fettuccine-alfredo') AND order_index = 5;
UPDATE clues SET text = 'A dimpled oiled flatbread with salt crystals in each hollow, from an Italian bakery.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'osso-focaccia') AND order_index = 5;
UPDATE clues SET text = 'A pasta that comes already stuffed, boiled in batches and lifted out gently.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ravioli') AND order_index = 1;
UPDATE clues SET text = 'Little sealed pillows floating in sauce, with crimped edges, on an Italian table.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'ravioli') AND order_index = 5;
UPDATE clues SET text = 'A cloudy bowl with the sediment settling if you leave it standing, served in Japan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'miso-soup') AND order_index = 5;
UPDATE clues SET text = 'A soft chewy round dusted white and yielding under the teeth, a New Year sweet in Japan.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'mochi') AND order_index = 5;
UPDATE clues SET text = 'A glossy brown glaze over grilled meat, sticky to the fingers, from a Japanese grill.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'teriyaki-chicken') AND order_index = 5;
UPDATE clues SET text = 'Softened chips gone half to pieces under crema and cheese, a Mexican breakfast plate.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'chilaquiles') AND order_index = 5;
UPDATE clues SET text = 'A milky white glass with cinnamon sinking to the bottom over ice, poured in Mexico.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'horchata') AND order_index = 5;
UPDATE clues SET text = 'Red-slicked shells served with bread to mop the plate, grilled on the coast of Mozambique.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'piri-piri-prawns') AND order_index = 5;
UPDATE clues SET text = 'A sizzling plate with an egg stirred through it at the table, served in the Philippines.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'sisig') AND order_index = 5;
UPDATE clues SET text = 'A cookie baked early because it gets softer and better with age.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pierniki') AND order_index = 1;
UPDATE clues SET text = 'Dark gingerbread cut in hearts and stars and glazed shiny, baked in Poland.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pierniki') AND order_index = 5;
UPDATE clues SET text = 'Small boiled parcels eaten by the bowlful with sour cream, a Russian winter dish.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pelmeni') AND order_index = 5;
UPDATE clues SET text = 'A cold red soup poured from a jug and drunk as much as eaten, from Spain.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gazpacho') AND order_index = 5;
UPDATE clues SET text = 'Sold from carts after dark, stirred to order in a roaring wok.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'nasi-goreng') AND order_index = 1;
