-- Backfill: clue rewrites against the beat sheet.
-- 7 clues across 7 dishes.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE clues SET text = 'A Ginza restaurant adapted a French veal cutlet in 1899, swapping in pork and a deep fryer.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tonkatsu') AND order_index = 2;
UPDATE clues SET text = 'A cookie whose dough is left to mature for weeks before it is baked.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'pierniki') AND order_index = 1;
UPDATE clues SET text = 'In Mexico, a taquero slices straight off the spinning cone into your tortilla, then adds a spoon of green salsa.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tacos-al-pastor') AND order_index = 5;
UPDATE clues SET text = 'Mexico and Nicaragua both claim it, and a condensed-milk brand is credited with spreading it.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'tres-leches-cake') AND order_index = 2;
UPDATE clues SET text = 'Stir-fried over the fiercest heat, so the onions stay crisp.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'lomo-saltado') AND order_index = 1;
UPDATE clues SET text = 'Legend credits a Florentine architect with perfecting it for the Medici court in the 1500s.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'gelato') AND order_index = 2;
UPDATE clues SET text = 'French colonial settlers brought this fried dough to that city, where a café open since 1862 serves it round the clock.'
 WHERE dish_id = (SELECT id FROM dishes WHERE slug = 'beignets') AND order_index = 2;
