-- Backfill: clue rewrites against the beat sheet.
-- 108 clues across 108 drinks.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE drink_clues SET text = 'The one that arrives with a white ring around the rim.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'margarita') AND order_index = 1;
UPDATE drink_clues SET text = 'Amber and short in a heavy-bottomed tumbler, built for slow sipping.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'old-fashioned') AND order_index = 1;
UPDATE drink_clues SET text = 'A drink the colour of a brake light, built straight in the glass.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'negroni') AND order_index = 1;
UPDATE drink_clues SET text = 'A tall glass crowded with green, the straw poking out of the thicket.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mojito') AND order_index = 1;
UPDATE drink_clues SET text = 'A beach-kiosk order, mashed to order in a short, chunky glass.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'caipirinha') AND order_index = 1;
UPDATE drink_clues SET text = 'Shaken hard and long, until the tin rattles with loose froth.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pisco-sour') AND order_index = 1;
UPDATE drink_clues SET text = 'A glowing orange drink that shows up on patio tables at six o''clock.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'aperol-spritz') AND order_index = 1;
UPDATE drink_clues SET text = 'Built in a jug hours ahead and ladled out, fruit and all.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sangria') AND order_index = 1;
UPDATE drink_clues SET text = 'Sipped through a cold white lid, and stirring it ruins the point.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'irish-coffee') AND order_index = 1;
UPDATE drink_clues SET text = 'A drink dressed for brunch, with a whole snack skewered on top.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'bloody-mary') AND order_index = 1;
UPDATE drink_clues SET text = 'Served in a shallow saucer glass, pale and frosty to the touch.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'daiquiri') AND order_index = 1;
UPDATE drink_clues SET text = 'A dark red drink in a stemmed glass, finished with a single cherry.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'manhattan') AND order_index = 1;
UPDATE drink_clues SET text = 'Orders arrive with instructions: dry, dirty, wet, a twist or an olive.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'martini') AND order_index = 1;
UPDATE drink_clues SET text = 'A ginger kick that hits the nose before the tongue.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'moscow-mule') AND order_index = 1;
UPDATE drink_clues SET text = 'A long, fizzy summer glass with a cherry bobbing on top.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'tom-collins') AND order_index = 1;
UPDATE drink_clues SET text = 'Ordered at a pool bar, delivered with a paper umbrella.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pina-colada') AND order_index = 1;
UPDATE drink_clues SET text = 'The brunch drink that waits for peach season to be any good.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'bellini') AND order_index = 1;
UPDATE drink_clues SET text = 'The bottle that goes around the table in one direction only.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'port') AND order_index = 1;
UPDATE drink_clues SET text = 'A sugar-dusted rim, a stemmed glass and an orange twist on the side.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sidecar') AND order_index = 1;
UPDATE drink_clues SET text = 'The flute where the dark pour goes in first, then the fizz.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'kir-royale') AND order_index = 1;
UPDATE drink_clues SET text = 'The Sunday-morning order, red-tinged and salted at the rim.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'michelada') AND order_index = 1;
UPDATE drink_clues SET text = 'A winter-market mug you return to the stall for your deposit.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'gluhwein') AND order_index = 1;
UPDATE drink_clues SET text = 'Drunk slowly over a long table, with water on the side.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ouzo') AND order_index = 1;
UPDATE drink_clues SET text = 'A flask and thimble cups, where no one pours their own.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sake') AND order_index = 1;
UPDATE drink_clues SET text = 'Poured with two hands, and not into your own cup first.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'soju') AND order_index = 1;
UPDATE drink_clues SET text = 'The long-lunch spirit, poured at noon and still going at four.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'arak') AND order_index = 1;
UPDATE drink_clues SET text = 'The bedtime order, mostly water with a little spirit to keep it honest.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hot-toddy') AND order_index = 1;
UPDATE drink_clues SET text = 'The one that keeps the evening going past midnight.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'espresso-martini') AND order_index = 1;
UPDATE drink_clues SET text = 'The grown-up glass a child gets, cherry and all.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'shirley-temple') AND order_index = 1;
UPDATE drink_clues SET text = 'The pitcher on the counter that looks like milk and isn''t.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'horchata') AND order_index = 1;
UPDATE drink_clues SET text = 'The mid-afternoon break that stops an office for ten minutes.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'masala-chai') AND order_index = 1;
UPDATE drink_clues SET text = 'You sip and chew in the same mouthful.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'bubble-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'Stirred fast with a long spoon, and gone before the foam settles.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'egg-cream') AND order_index = 1;
UPDATE drink_clues SET text = 'Wins over anyone who expects a drink to taste sweet.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ayran') AND order_index = 1;
UPDATE drink_clues SET text = 'Dessert and drink in one glass, with a spoon and a straw both.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'root-beer-float') AND order_index = 1;
UPDATE drink_clues SET text = 'Ruby red and on the table by the first week of December.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sorrel') AND order_index = 1;
UPDATE drink_clues SET text = 'Ladled from a steaming urn and eaten as much as drunk.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sahlab') AND order_index = 1;
UPDATE drink_clues SET text = 'Served after the meal, once the plates are cleared.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sujeonggwa') AND order_index = 1;
UPDATE drink_clues SET text = 'A heatwave order you eat with a spoon, ice first.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cendol') AND order_index = 1;
UPDATE drink_clues SET text = 'A kettle favourite for anyone who wants tea without the buzz.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'rooibos') AND order_index = 1;
UPDATE drink_clues SET text = 'The foam on top is the sign the bartender shook it long enough.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'whiskey-sour') AND order_index = 1;
UPDATE drink_clues SET text = 'A frosted silver cup packed to the brim with crushed ice.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mint-julep') AND order_index = 1;
UPDATE drink_clues SET text = 'Pink as a flamingo and served in a glass with a long stem.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cosmopolitan') AND order_index = 1;
UPDATE drink_clues SET text = 'Looks like a soft drink and does not behave like one.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'long-island-iced-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'Poured from one chilled glass into another that has been rinsed.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sazerac') AND order_index = 1;
UPDATE drink_clues SET text = 'The last order of the night that tastes like dessert.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'white-russian') AND order_index = 1;
UPDATE drink_clues SET text = 'The tiki-bar standard, garnished like a small jungle.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mai-tai') AND order_index = 1;
UPDATE drink_clues SET text = 'Only on the menu in the last weeks of the year.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'eggnog') AND order_index = 1;
UPDATE drink_clues SET text = 'A street-party drink handed out in a glass shaped like a lamp.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hurricane') AND order_index = 1;
UPDATE drink_clues SET text = 'Poured and left alone: the colours sort themselves out.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'tequila-sunrise') AND order_index = 1;
UPDATE drink_clues SET text = 'A harbour-bar highball with only two things in the glass.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'dark-and-stormy') AND order_index = 1;
UPDATE drink_clues SET text = 'Sold in slim half-bottles and poured by the thimbleful.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ice-wine') AND order_index = 1;
UPDATE drink_clues SET text = 'The order you can make at any bar with a soda gun.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cuba-libre') AND order_index = 1;
UPDATE drink_clues SET text = 'The bar order that tastes more like soda than cocktail.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'paloma') AND order_index = 1;
UPDATE drink_clues SET text = 'A smoky pour you sip slowly and do not take as a shot.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mezcal') AND order_index = 1;
UPDATE drink_clues SET text = 'A beach-bar pitcher passed around until it is empty.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'rum-punch') AND order_index = 1;
UPDATE drink_clues SET text = 'Poured with a hiss and a slice of green, then left alone.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'gin-and-tonic') AND order_index = 1;
UPDATE drink_clues SET text = 'A summer-lawn jug crowded with enough fruit to be a salad.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pimms-cup') AND order_index = 1;
UPDATE drink_clues SET text = 'A farm-gate pour that is still and flat, not fizzy.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cider') AND order_index = 1;
UPDATE drink_clues SET text = 'A pint so dark you cannot see the light through it.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'stout') AND order_index = 1;
UPDATE drink_clues SET text = 'A toast-worthy flute that kicks harder than it looks.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'french-75') AND order_index = 1;
UPDATE drink_clues SET text = 'A flute that spends its mornings at brunch tables.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mimosa') AND order_index = 1;
UPDATE drink_clues SET text = 'Banned in several countries for most of a century.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'absinthe') AND order_index = 1;
UPDATE drink_clues SET text = 'The small glass that closes a long Sunday lunch.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'limoncello') AND order_index = 1;
UPDATE drink_clues SET text = 'A splash in the espresso at the end of a long dinner.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'grappa') AND order_index = 1;
UPDATE drink_clues SET text = 'A pale dry glass that sits beside a plate of salty snacks.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sherry') AND order_index = 1;
UPDATE drink_clues SET text = 'So clear and gold you could read a menu through it.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pilsner') AND order_index = 1;
UPDATE drink_clues SET text = 'Swirl the last inch of the bottle before you pour it out.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hefeweizen') AND order_index = 1;
UPDATE drink_clues SET text = 'A glass that comes with a drinking song at the holiday table.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'aquavit') AND order_index = 1;
UPDATE drink_clues SET text = 'The spirit that tells a waiter the table is staying all night.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'raki') AND order_index = 1;
UPDATE drink_clues SET text = 'A banquet pour where each guest is expected to match the host.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'baijiu') AND order_index = 1;
UPDATE drink_clues SET text = 'The sweet entry point for people who think they hate spirits.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'umeshu') AND order_index = 1;
UPDATE drink_clues SET text = 'Shaken in its bottle before the pour, so the sediment mixes in.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'makgeolli') AND order_index = 1;
UPDATE drink_clues SET text = 'A hotel-bar signature that visitors seek out on their trip.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'singapore-sling') AND order_index = 1;
UPDATE drink_clues SET text = 'A honey drink poured at weddings and long celebrations.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'tej') AND order_index = 1;
UPDATE drink_clues SET text = 'A drink collected from the top of a tree, not from a shelf.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'palm-wine') AND order_index = 1;
UPDATE drink_clues SET text = 'Squeezed to order, pulp, pips and all, over a pile of ice.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'lemonade') AND order_index = 1;
UPDATE drink_clues SET text = 'Ordered by a person''s name, and half and half in the glass.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'arnold-palmer') AND order_index = 1;
UPDATE drink_clues SET text = 'A thick pour that makes the straw the hard part.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'milkshake') AND order_index = 1;
UPDATE drink_clues SET text = 'A tap handle where you''d expect beer, serving something black.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cold-brew') AND order_index = 1;
UPDATE drink_clues SET text = 'The pitcher that arrives at the table before you have ordered.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sweet-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'Purple enough to stain the tablecloth.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'chicha-morada') AND order_index = 1;
UPDATE drink_clues SET text = 'The leafy rival to a morning coffee.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'yerba-mate') AND order_index = 1;
UPDATE drink_clues SET text = 'A morning order that raises eyebrows if you ask for it after lunch.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cappuccino') AND order_index = 1;
UPDATE drink_clues SET text = 'Sold from a barrel on wheels in summer.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'kvass') AND order_index = 1;
UPDATE drink_clues SET text = 'A cup that is closer to a sauce than a drink.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hot-chocolate') AND order_index = 1;
UPDATE drink_clues SET text = 'Poured into a small cup and left to settle before the first sip.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'turkish-coffee') AND order_index = 1;
UPDATE drink_clues SET text = 'A glass handed to every guest before any business is done.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mint-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'A thick, fruity drink that sits alongside a plate of curry.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mango-lassi') AND order_index = 1;
UPDATE drink_clues SET text = 'Layered so deep it needs a long spoon to reach the bottom.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'falooda') AND order_index = 1;
UPDATE drink_clues SET text = 'Whisked into a froth with a small bamboo brush.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'matcha') AND order_index = 1;
UPDATE drink_clues SET text = 'A festival-stall soda sold from a tub of icy water.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ramune') AND order_index = 1;
UPDATE drink_clues SET text = 'Smells like a garden before it touches your lips.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'jasmine-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'The health-shop fridge drink that keeps itself fizzing.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'kombucha') AND order_index = 1;
UPDATE drink_clues SET text = 'Orange as a traffic cone, and sweet enough to match.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'thai-iced-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'Drips slowly through a little metal filter that sits on the glass.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'vietnamese-coffee') AND order_index = 1;
UPDATE drink_clues SET text = 'A tall glass that is mostly toppings and a little ice.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'halo-halo') AND order_index = 1;
UPDATE drink_clues SET text = 'Grey, peppery and ceremonial, offered to a guest on arrival.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'kava') AND order_index = 1;
UPDATE drink_clues SET text = 'Smaller than a latte, stronger than a latte, and proud of it.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'flat-white') AND order_index = 1;
UPDATE drink_clues SET text = 'A pink pub soda poured for whoever is driving home.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'lemon-lime-and-bitters') AND order_index = 1;
UPDATE drink_clues SET text = 'A ski-lodge mug for when the lifts have closed.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hot-buttered-rum') AND order_index = 1;
UPDATE drink_clues SET text = 'A holiday drink that gets served in a matching set of mugs.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'tom-and-jerry') AND order_index = 1;
UPDATE drink_clues SET text = 'A street-stall cup that warms up chilly nights at altitude.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'canelazo') AND order_index = 1;
UPDATE drink_clues SET text = 'The December drink poured in small glasses and sipped slowly.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'coquito') AND order_index = 1;
UPDATE drink_clues SET text = 'A cold-morning breakfast cup that eats like a meal.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'champurrado') AND order_index = 1;
UPDATE drink_clues SET text = 'Ladled from a giant pot at a street party in December.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ponche-navideno') AND order_index = 1;
UPDATE drink_clues SET text = 'Spooned from a jar into a mug, no teabag in sight.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'yuja-tea') AND order_index = 1;
UPDATE drink_clues SET text = 'A cup that starts autumn at the coffee-shop counter.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pumpkin-spice-latte') AND order_index = 1;
