-- Backfill: clue rewrites against the beat sheet.
-- 47 clues across 47 drinks.
-- UPDATEs, not INSERTs: these rows already exist. Keyed by slug so the ids
-- this migration lands on do not have to match the seed's.
-- Generated by scripts/patch-clues.mjs. Edit the patch, not this file.

UPDATE drink_clues SET text = 'Clear as water in a tiny ceramic cup set on a wooden box, a Japanese rice drink.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sake') AND order_index = 3;
UPDATE drink_clues SET text = 'A pale green sour in a wide-mouthed glass, a lime wedge perched on the edge, Mexico''s bar standard.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'margarita') AND order_index = 3;
UPDATE drink_clues SET text = 'A tall frosted glass with a sprig of leaves on top, the Cuban summer cooler.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mojito') AND order_index = 3;
UPDATE drink_clues SET text = 'Under a white collar with dots of bitters on top, a pale gold cocktail from Peru.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pisco-sour') AND order_index = 3;
UPDATE drink_clues SET text = 'A tall glass of cloudy lemon fizz over ice, a straw and a cherry on top, the British highball.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'tom-collins') AND order_index = 3;
UPDATE drink_clues SET text = 'Blush-coloured in a slim flute, peach pulp clouding the bottom, the Italian brunch glass.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'bellini') AND order_index = 3;
UPDATE drink_clues SET text = 'Small, dark and sweet in a stemmed glass beside the cheese board, Portugal''s after-dinner pour.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'port') AND order_index = 3;
UPDATE drink_clues SET text = 'Amber and cold in a small coupe with an orange twist floating on top, a French classic.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sidecar') AND order_index = 3;
UPDATE drink_clues SET text = 'A pint glass rimmed dark with chilli salt and a lime jammed on the edge, a Mexican hangover cure.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'michelada') AND order_index = 3;
UPDATE drink_clues SET text = 'Steaming and red in a mug with a wheel of orange, handed out at German Christmas markets.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'gluhwein') AND order_index = 3;
UPDATE drink_clues SET text = 'A green bottle on the table at a Korean barbecue, tipped into shot glasses that never stay full.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'soju') AND order_index = 3;
UPDATE drink_clues SET text = 'Three coffee beans floating on a tan crema in a stemmed glass, a British late-night classic.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'espresso-martini') AND order_index = 3;
UPDATE drink_clues SET text = 'A deep red drink in a tall curved glass with an orange slice on the rim, America''s carnival pour.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hurricane') AND order_index = 3;
UPDATE drink_clues SET text = 'Brown over ice in a long glass, with the lime squeezed in and dropped after it, the Cuban highball.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cuba-libre') AND order_index = 3;
UPDATE drink_clues SET text = 'A long lemon twist coiled inside a pale gold flute, a classic from France.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'french-75') AND order_index = 3;
UPDATE drink_clues SET text = 'Pale gold and fizzing in a flute, a wheel of orange on the rim, the French brunch order.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mimosa') AND order_index = 3;
UPDATE drink_clues SET text = 'Pale, dry and chilled, poured small beside olives and cured ham, a Spanish bar pour.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sherry') AND order_index = 3;
UPDATE drink_clues SET text = 'Brown and tangy with a taste of crust, drunk from a plastic cup in Russian summers.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'kvass') AND order_index = 3;
UPDATE drink_clues SET text = 'A dimpled blue bottle with a marble rattling in the throat as you drink, a Japanese summer soda.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ramune') AND order_index = 3;
UPDATE drink_clues SET text = 'A pale yellow cup with a few petals floating, drunk with dim sum in Chinese teahouses.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'jasmine-tea') AND order_index = 3;
UPDATE drink_clues SET text = 'A rust-red mug with milk and honey stirred in, South Africa''s answer to black tea.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'rooibos') AND order_index = 3;
UPDATE drink_clues SET text = 'A tall cup with a deep orange body under a pale collar, stirred together with a straw, in Thailand.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'thai-iced-tea') AND order_index = 3;
UPDATE drink_clues SET text = 'Thick gold in a tiny glass after the plates go, a Canadian winter dessert pour.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ice-wine') AND order_index = 3;
UPDATE drink_clues SET text = 'Built two parts spirit to one of sweet vermouth, a classic of the American bar.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'manhattan') AND order_index = 3;
UPDATE drink_clues SET text = 'A stemmed triangle so cold the glass frosts, the American bar''s signature shape.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'martini') AND order_index = 3;
UPDATE drink_clues SET text = 'A tall glass the colour of tea with a lemon wedge on the rim, an American trick of looks.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'long-island-iced-tea') AND order_index = 3;
UPDATE drink_clues SET text = 'Chilled red wine in a jug full of citrus wheels, ladled at a Spanish table.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sangria') AND order_index = 3;
UPDATE drink_clues SET text = 'A thick red glass with a celery stalk standing in it like an oar, the American brunch order.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'bloody-mary') AND order_index = 3;
UPDATE drink_clues SET text = 'A sunset-coloured wine glass with a fat slice of orange wedged in the ice, in an Italian piazza.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'aperol-spritz') AND order_index = 3;
UPDATE drink_clues SET text = 'Cloudy with pulp and grit at the bottom of a short glass, a Brazilian bar order.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'caipirinha') AND order_index = 3;
UPDATE drink_clues SET text = 'A white slush in a tall glass, a pineapple wedge on the rim, Puerto Rico''s resort drink.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'pina-colada') AND order_index = 3;
UPDATE drink_clues SET text = 'A deep pink flute with the liqueur sinking through the bubbles, a French aperitif.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'kir-royale') AND order_index = 3;
UPDATE drink_clues SET text = 'Gone cloudy in the glass and served cold beside small plates, a Greek aniseed pour.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ouzo') AND order_index = 3;
UPDATE drink_clues SET text = 'Cloudy in a small tumbler beside a spread of mezze, a Lebanese table spirit.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'arak') AND order_index = 3;
UPDATE drink_clues SET text = 'Steaming gold in a mug, a clove-studded lemon slice floating, a Scottish remedy for colds.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'hot-toddy') AND order_index = 3;
UPDATE drink_clues SET text = 'A pink ginger fizz with a maraschino cherry sunk at the bottom, an American kids'' classic.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'shirley-temple') AND order_index = 3;
UPDATE drink_clues SET text = 'Chalky white over ice, ladled from a glass barrel beside a Mexican taco counter.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'horchata') AND order_index = 3;
UPDATE drink_clues SET text = 'A tan, sweet tea sold scalding in a tiny clay cup at a roadside stall in India.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'masala-chai') AND order_index = 3;
UPDATE drink_clues SET text = 'A tan cup with dark spheres rolling around at the bottom, a Taiwanese street drink.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'bubble-tea') AND order_index = 3;
UPDATE drink_clues SET text = 'White, salty and foam-topped in a plain cup, poured alongside a plate of kebab in Turkiye.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'ayran') AND order_index = 3;
UPDATE drink_clues SET text = 'A brown fizz under a white scoop, a long spoon alongside, the American soda-fountain treat.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'root-beer-float') AND order_index = 3;
UPDATE drink_clues SET text = 'A ruby glass, tart and gingery with a bite that builds, on a Jamaican Christmas table.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sorrel') AND order_index = 3;
UPDATE drink_clues SET text = 'Pale and gluey under a snow of green nuts and spice, a winter cup in Lebanon.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sahlab') AND order_index = 3;
UPDATE drink_clues SET text = 'Near-black with pine nuts and a wrinkled dried fruit floating in it, a Korean dessert cup.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'sujeonggwa') AND order_index = 3;
UPDATE drink_clues SET text = 'Green squiggles sunk in shaved ice, coconut milk and palm sugar, a Malaysian bowl.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'cendol') AND order_index = 3;
UPDATE drink_clues SET text = 'A tan short glass under a pale cap, with a cherry and a lemon wheel, from the American bar canon.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'whiskey-sour') AND order_index = 3;
UPDATE drink_clues SET text = 'So cold the silver cup beads, a bouquet of herb crushed under your nose, at the American Derby.'
 WHERE drink_id = (SELECT id FROM drinks WHERE slug = 'mint-julep') AND order_index = 3;
