-- Lunch Special — seed data
-- 68 dishes with canonical ingredients + 5 clues each, and a 30-day schedule.
-- Safe to re-run: clears existing content first.
-- Clue order: 1 broad hint → 2 origin/history → 3 fame/pop culture → 4 key ingredients/technique → 5 near-giveaway.

DELETE FROM clues;
DELETE FROM schedule;
DELETE FROM dishes;

INSERT INTO dishes (id, name, slug, country, region, course, temperature, protein, ingredients) VALUES
(1,'Spaghetti Carbonara','spaghetti-carbonara','Italy','europe','entree','hot','pork','["pasta","egg","pecorino","guanciale","black pepper"]'),
(2,'Margherita Pizza','margherita-pizza','Italy','europe','entree','hot','vegetarian','["flour","tomato","mozzarella","basil","olive oil","yeast"]'),
(3,'Lasagna','lasagna','Italy','europe','entree','hot','beef','["pasta","beef","tomato","mozzarella","parmesan","onion","garlic","milk"]'),
(4,'Risotto alla Milanese','risotto-alla-milanese','Italy','europe','entree','hot','vegetarian','["rice","saffron","butter","parmesan","onion","white wine"]'),
(5,'Tiramisu','tiramisu','Italy','europe','dessert','cold','vegetarian','["coffee","mascarpone","egg","sugar","cocoa","ladyfingers"]'),
(6,'Croque Monsieur','croque-monsieur','France','europe','entree','hot','pork','["bread","ham","gruyere","butter","milk","flour","mustard"]'),
(7,'Ratatouille','ratatouille','France','europe','entree','hot','vegetarian','["eggplant","zucchini","tomato","bell pepper","onion","garlic","olive oil","thyme"]'),
(8,'French Onion Soup','french-onion-soup','France','europe','appetizer','hot','beef','["onion","beef broth","gruyere","bread","butter","thyme","white wine"]'),
(9,'Crème Brûlée','creme-brulee','France','europe','dessert','cold','vegetarian','["cream","egg","sugar","vanilla"]'),
(10,'Coq au Vin','coq-au-vin','France','europe','entree','hot','poultry','["chicken","red wine","bacon","mushroom","onion","carrot","garlic"]'),
(11,'Paella','paella','Spain','europe','entree','hot','seafood','["rice","saffron","shrimp","mussels","tomato","bell pepper","peas","olive oil"]'),
(12,'Gazpacho','gazpacho','Spain','europe','appetizer','cold','vegetarian','["tomato","cucumber","bell pepper","garlic","olive oil","bread","vinegar"]'),
(13,'Churros','churros','Spain','europe','dessert','hot','vegetarian','["flour","sugar","cinnamon","chocolate","butter","egg"]'),
(14,'Fish and Chips','fish-and-chips','United Kingdom','europe','entree','hot','seafood','["white fish","potato","flour","beer","vinegar","peas"]'),
(15,'Shepherd''s Pie','shepherds-pie','United Kingdom','europe','entree','hot','lamb','["lamb","potato","onion","carrot","peas","butter","milk"]'),
(16,'Chicken Tikka Masala','chicken-tikka-masala','United Kingdom','europe','entree','hot','poultry','["chicken","yogurt","tomato","cream","garam masala","ginger","garlic","rice"]'),
(17,'Moussaka','moussaka','Greece','europe','entree','hot','lamb','["eggplant","lamb","tomato","onion","cinnamon","milk","butter","flour"]'),
(18,'Wiener Schnitzel','wiener-schnitzel','Austria','europe','entree','hot','beef','["veal","breadcrumbs","egg","flour","butter","lemon"]'),
(19,'Currywurst','currywurst','Germany','europe','entree','hot','pork','["sausage","tomato","curry powder","onion","ketchup"]'),
(20,'Goulash','goulash','Hungary','europe','entree','hot','beef','["beef","paprika","onion","tomato","bell pepper","garlic","caraway"]'),
(21,'Pierogi','pierogi','Poland','europe','entree','hot','vegetarian','["flour","egg","potato","cheese","onion","butter","sour cream"]'),
(22,'Borscht','borscht','Ukraine','europe','appetizer','hot','beef','["beetroot","cabbage","potato","carrot","onion","beef broth","dill","sour cream"]'),
(23,'Beef Stroganoff','beef-stroganoff','Russia','europe','entree','hot','beef','["beef","mushroom","onion","sour cream","butter","mustard"]'),
(24,'Swedish Meatballs','swedish-meatballs','Sweden','europe','entree','hot','beef','["beef","pork","breadcrumbs","cream","onion","egg","lingonberry"]'),
(25,'Baklava','baklava','Türkiye','middle-east','dessert','cold','vegetarian','["phyllo","walnuts","pistachio","honey","butter","sugar","cinnamon"]'),
(26,'Hummus','hummus','Lebanon','middle-east','appetizer','cold','vegetarian','["chickpeas","tahini","lemon","garlic","olive oil","cumin"]'),
(27,'Falafel','falafel','Egypt','middle-east','appetizer','hot','vegetarian','["chickpeas","parsley","cilantro","garlic","onion","cumin","coriander"]'),
(28,'Shakshuka','shakshuka','Tunisia','middle-east','breakfast','hot','vegetarian','["egg","tomato","bell pepper","onion","garlic","paprika","cumin","olive oil"]'),
(29,'Döner Kebab','doner-kebab','Türkiye','middle-east','entree','hot','lamb','["lamb","flatbread","tomato","onion","lettuce","yogurt","garlic"]'),
(30,'Chicken Tagine','chicken-tagine','Morocco','africa','entree','hot','poultry','["chicken","lemon","olives","onion","garlic","ginger","saffron","cilantro"]'),
(31,'Jollof Rice','jollof-rice','Nigeria','africa','entree','hot','vegetarian','["rice","tomato","bell pepper","onion","chili","thyme","ginger"]'),
(32,'Bobotie','bobotie','South Africa','africa','entree','hot','beef','["beef","bread","milk","egg","curry powder","onion","raisins"]'),
(33,'Butter Chicken','butter-chicken','India','south-asia','entree','hot','poultry','["chicken","butter","tomato","cream","garam masala","ginger","garlic","yogurt"]'),
(34,'Chicken Biryani','chicken-biryani','India','south-asia','entree','hot','poultry','["rice","chicken","yogurt","onion","saffron","garam masala","ginger","mint"]'),
(35,'Samosa','samosa','India','south-asia','appetizer','hot','vegetarian','["flour","potato","peas","cumin","coriander","chili","onion"]'),
(36,'Masala Dosa','masala-dosa','India','south-asia','breakfast','hot','vegetarian','["rice","lentils","potato","onion","turmeric","chili","mustard seeds"]'),
(37,'Sushi','sushi','Japan','east-asia','entree','cold','seafood','["rice","seaweed","salmon","tuna","vinegar","wasabi","soy sauce","ginger"]'),
(38,'Ramen','ramen','Japan','east-asia','entree','hot','pork','["noodles","pork","egg","scallion","soy sauce","miso","seaweed","garlic"]'),
(39,'Peking Duck','peking-duck','China','east-asia','entree','hot','poultry','["duck","scallion","cucumber","hoisin sauce","flour","honey"]'),
(40,'Kung Pao Chicken','kung-pao-chicken','China','east-asia','entree','hot','poultry','["chicken","peanuts","chili","scallion","soy sauce","garlic","ginger","sichuan peppercorn"]'),
(41,'Mapo Tofu','mapo-tofu','China','east-asia','entree','hot','pork','["tofu","pork","chili bean paste","sichuan peppercorn","scallion","garlic"]'),
(42,'Bibimbap','bibimbap','South Korea','east-asia','entree','hot','beef','["rice","beef","egg","spinach","carrot","mushroom","gochujang","sesame","scallion"]'),
(43,'Pad Thai','pad-thai','Thailand','southeast-asia','entree','hot','seafood','["noodles","shrimp","egg","peanuts","bean sprouts","tamarind","fish sauce","lime","tofu"]'),
(44,'Pho','pho','Vietnam','southeast-asia','entree','hot','beef','["noodles","beef","onion","ginger","star anise","cinnamon","fish sauce","lime","basil","bean sprouts"]'),
(45,'Banh Mi','banh-mi','Vietnam','southeast-asia','entree','cold','pork','["bread","pork","carrot","cucumber","cilantro","chili","mayonnaise"]'),
(46,'Nasi Goreng','nasi-goreng','Indonesia','southeast-asia','entree','hot','poultry','["rice","egg","chicken","onion","garlic","chili","sweet soy sauce","shrimp paste"]'),
(47,'Beef Rendang','beef-rendang','Indonesia','southeast-asia','entree','hot','beef','["beef","coconut milk","lemongrass","galangal","chili","garlic","turmeric","lime leaves"]'),
(48,'Laksa','laksa','Malaysia','southeast-asia','entree','hot','seafood','["noodles","coconut milk","shrimp","chili","lemongrass","tofu","bean sprouts","lime"]'),
(49,'Chicken Adobo','chicken-adobo','Philippines','southeast-asia','entree','hot','poultry','["chicken","soy sauce","vinegar","garlic","bay leaf","black pepper","rice"]'),
(50,'Hainanese Chicken Rice','hainanese-chicken-rice','Singapore','southeast-asia','entree','hot','poultry','["chicken","rice","ginger","scallion","garlic","cucumber","chili"]'),
(51,'Hamburger','hamburger','United States','north-america','entree','hot','beef','["beef","bread","lettuce","tomato","onion","pickles","cheddar"]'),
(52,'Mac and Cheese','mac-and-cheese','United States','north-america','entree','hot','vegetarian','["pasta","cheddar","milk","butter","flour","breadcrumbs"]'),
(53,'Southern Fried Chicken','southern-fried-chicken','United States','north-america','entree','hot','poultry','["chicken","flour","buttermilk","paprika","black pepper","chili"]'),
(54,'New England Clam Chowder','new-england-clam-chowder','United States','north-america','appetizer','hot','seafood','["clams","potato","cream","onion","bacon","butter","flour","celery"]'),
(55,'Apple Pie','apple-pie','United States','north-america','dessert','hot','vegetarian','["apple","flour","butter","sugar","cinnamon","lemon","nutmeg"]'),
(56,'Banana Split','banana-split','United States','north-america','dessert','cold','vegetarian','["banana","ice cream","chocolate","whipped cream","cherry","pineapple","strawberry"]'),
(57,'Meatloaf','meatloaf','United States','north-america','entree','hot','beef','["beef","breadcrumbs","egg","onion","ketchup","garlic"]'),
(58,'Gumbo','gumbo','United States','north-america','entree','hot','seafood','["shrimp","sausage","okra","rice","bell pepper","celery","onion","flour"]'),
(59,'Poutine','poutine','Canada','north-america','entree','hot','beef','["potato","cheese curds","gravy"]'),
(60,'Tacos al Pastor','tacos-al-pastor','Mexico','latin-america','entree','hot','pork','["pork","tortilla","pineapple","onion","cilantro","chili","achiote","lime"]'),
(61,'Guacamole','guacamole','Mexico','latin-america','appetizer','cold','vegetarian','["avocado","lime","onion","cilantro","tomato","chili"]'),
(62,'Mole Poblano','mole-poblano','Mexico','latin-america','entree','hot','poultry','["chicken","chocolate","chili","sesame","raisins","tomato","cinnamon"]'),
(63,'Ceviche','ceviche','Peru','latin-america','appetizer','cold','seafood','["white fish","lime","onion","chili","cilantro","corn","sweet potato"]'),
(64,'Empanadas','empanadas','Argentina','latin-america','appetizer','hot','beef','["flour","beef","onion","egg","olives","cumin","paprika"]'),
(65,'Feijoada','feijoada','Brazil','latin-america','entree','hot','pork','["beans","pork","sausage","rice","orange","garlic","onion","collard greens"]'),
(66,'Arepas','arepas','Venezuela','latin-america','breakfast','hot','vegetarian','["corn","cheese","butter","avocado"]'),
(67,'Jerk Chicken','jerk-chicken','Jamaica','latin-america','entree','hot','poultry','["chicken","allspice","chili","thyme","scallion","ginger","garlic","lime"]'),
(68,'Pavlova','pavlova','New Zealand','oceania','dessert','cold','vegetarian','["egg","sugar","whipped cream","strawberry","kiwifruit","vanilla"]');

INSERT INTO clues (dish_id, order_index, text) VALUES
(1,1,'This dish comes from Europe, and its home country is shaped like a boot.'),
(1,2,'Roman legend ties it to charcoal workers — or to American rations after WWII.'),
(1,3,'Purists riot when you add cream; the internet riots when chefs add peas.'),
(1,4,'Cured pork cheek and pecorino cheese are tossed with hot pasta and raw egg.'),
(1,5,'A Roman pasta whose name loosely means "in the style of the charcoal burner".'),
(2,1,'A southern European classic, from a city in the shadow of a volcano.'),
(2,2,'Born in Naples, where street ovens fed the working class for centuries.'),
(2,3,'Named for a queen who visited in 1889 and picked the patriotic option.'),
(2,4,'Its three toppings — tomato, mozzarella, basil — mirror a national flag.'),
(2,5,'The world''s most famous flatbread, best from a wood-fired oven.'),
(3,1,'A layered comfort classic from southern Europe.'),
(3,2,'Emilia-Romagna claims the definitive version, rich with ragù and béchamel.'),
(3,3,'A certain orange cartoon cat would steal it right off your table.'),
(3,4,'Wide, flat pasta sheets are stacked with meat sauce and cheese.'),
(3,5,'The ultimate baked pasta, served by the square slice.'),
(4,1,'A golden rice dish from Europe''s fashion capital.'),
(4,2,'Legend says a glassmaker''s apprentice colored it with a stained-glass pigment in 1574.'),
(4,3,'Traditionally served alongside osso buco.'),
(4,4,'Saffron turns this slow-stirred, creamy rice dish a deep gold.'),
(4,5,'Milan''s glossy saffron rice, finished with butter and parmesan.'),
(5,1,'A no-bake dessert from southern Europe.'),
(5,2,'Born in the Veneto in the 1960s — remarkably young for a classic.'),
(5,3,'Its name is a promise: "pick me up".'),
(5,4,'Coffee-soaked ladyfingers layered with mascarpone cream and cocoa.'),
(5,5,'Italy''s most famous spoon dessert, heavy on the espresso.'),
(6,1,'A hot sandwich from Western Europe.'),
(6,2,'First appeared on a Paris café menu around 1910.'),
(6,3,'Proust name-checked it; add a fried egg on top and it becomes a "madame".'),
(6,4,'Ham and gruyère under a blanket of béchamel, grilled until bubbling.'),
(6,5,'France''s deluxe take on grilled ham and cheese.'),
(7,1,'A rustic vegetable dish from Europe''s Mediterranean coast.'),
(7,2,'A peasant stew from Provence, once dismissed by chefs as too humble.'),
(7,3,'A 2007 animated rat made it fine-dining famous.'),
(7,4,'Eggplant, zucchini, peppers and tomato, stewed or fanned in neat spirals.'),
(7,5,'Nice''s summer-vegetable stew — no meat, all garden.'),
(8,1,'A bistro staple from Western Europe.'),
(8,2,'Once sold at dawn in the Les Halles market to porters and night owls.'),
(8,3,'Julia Child taught America to make it on public television.'),
(8,4,'Slow-caramelized onions in beef broth, capped with bread and molten gruyère.'),
(8,5,'The soup you eat through a broiled cheese lid.'),
(9,1,'A custard dessert claimed by several European countries.'),
(9,2,'France, Spain''s crema catalana, and Cambridge''s Trinity College all claim it.'),
(9,3,'The 2001 film Amélie made cracking its top one of cinema''s small joys.'),
(9,4,'Vanilla custard hiding under a torched sugar shell.'),
(9,5,'Its name means "burnt cream" — tap the caramel glass and dig in.'),
(10,1,'A slow braise from Western Europe''s wine country.'),
(10,2,'Folk tales trace it to Julius Caesar and a defiant Gallic chieftain''s rooster.'),
(10,3,'Another dish Julia Child made famous in American kitchens.'),
(10,4,'Chicken braised in red wine with bacon, mushrooms and pearl onions.'),
(10,5,'Literally "rooster in wine" — Burgundy in a pot.'),
(11,1,'A festive rice dish from Mediterranean Europe.'),
(11,2,'Born in Valencia''s rice paddies, cooked by farmhands over orange-wood fires.'),
(11,3,'Named for the wide shallow pan it''s cooked in — and never over-stirred.'),
(11,4,'Saffron rice studded with shrimp and mussels, prized for its crusty bottom.'),
(11,5,'Spain''s big-pan party rice.'),
(12,1,'A summer dish from Europe''s hottest region — eaten with a spoon, never hot.'),
(12,2,'Andalusian field workers blended it long before refrigerators existed.'),
(12,3,'It pops up everywhere from Seinfeld jokes to Almodóvar films.'),
(12,4,'Raw tomato, cucumber, pepper and bread, blended with olive oil and vinegar.'),
(12,5,'Spain''s famous cold soup — basically a salad you drink.'),
(13,1,'A fried treat beloved across Spain and Latin America.'),
(13,2,'Possibly modeled on Chinese youtiao met at sea — Iberian shepherds claim it too.'),
(13,3,'A theme-park and street-fair icon from Madrid to Mexico City.'),
(13,4,'Ridged dough piped straight into hot oil, then rolled in cinnamon sugar.'),
(13,5,'Long fried dough sticks made for dunking in thick hot chocolate.'),
(14,1,'An island nation''s favorite takeaway, wrapped to go.'),
(14,2,'Jewish immigrants'' fried-fish shops met fried potatoes and built a 19th-century institution.'),
(14,3,'Considered so vital it stayed unrationed through both World Wars.'),
(14,4,'Battered white fish — usually cod or haddock — with thick-cut fried potatoes.'),
(14,5,'Britain''s chip-shop classic, best with malt vinegar and mushy peas.'),
(15,1,'A baked comfort dish from the British Isles.'),
(15,2,'Invented to stretch Sunday-roast leftovers in frugal farm kitchens.'),
(15,3,'Its beef cousin is properly called cottage pie — reliable pub-quiz gold.'),
(15,4,'Minced lamb and vegetables under a browned mashed-potato roof.'),
(15,5,'The casserole named after the flock its meat comes from.'),
(16,1,'Its spices say South Asia; its birth certificate likely says Britain.'),
(16,2,'Legend claims a Glasgow chef doused dry chicken in tomato soup for a grumbling customer.'),
(16,3,'A UK foreign secretary once declared it "a true British national dish".'),
(16,4,'Char-grilled marinated chicken in a creamy spiced tomato sauce.'),
(16,5,'The curry-house favorite that outsells fish and chips.'),
(17,1,'A layered bake from the eastern Mediterranean.'),
(17,2,'Its modern form was codified in the 1920s by chef Tselementes, who added béchamel.'),
(17,3,'The centerpiece of every taverna menu and long family Sunday.'),
(17,4,'Layers of eggplant and cinnamon-spiced lamb under a thick custardy top.'),
(17,5,'Greece''s answer to lasagna — aubergine instead of pasta.'),
(18,1,'A crispy classic from Central Europe.'),
(18,2,'Vienna perfected it, though Milan insists its cotoletta came first.'),
(18,3,'By Austrian law the real thing must be veal — pork versions need a different name.'),
(18,4,'A cutlet pounded paper-thin, breaded, and fried golden, served with lemon.'),
(18,5,'Vienna''s giant golden cutlet, wider than its plate.'),
(19,1,'A street-food icon from Central Europe.'),
(19,2,'Invented in 1949 Berlin after Herta Heuwer traded for ketchup and curry powder from British soldiers.'),
(19,3,'Germans eat some 800 million servings a year; it even had its own museum.'),
(19,4,'Sliced sausage drowned in curried tomato sauce, usually with fries.'),
(19,5,'Berlin''s chopped sausage with curry ketchup.'),
(20,1,'A paprika-red stew from Central Europe.'),
(20,2,'Cooked in kettles by Magyar herdsmen — its name literally means "herdsman".'),
(20,3,'So national that Hungary''s softer communism was nicknamed after it.'),
(20,4,'Beef simmered with onions and a very heavy hand of sweet paprika.'),
(20,5,'Hungary''s national stew — part soup, part main course.'),
(21,1,'Stuffed comfort food from Eastern Europe.'),
(21,2,'Peasant food turned national treasure; a 13th-century saint supposedly fed them to the poor.'),
(21,3,'Poland throws festivals for them; American church basements sell them by the dozen.'),
(21,4,'Half-moon dumplings stuffed with potato and cheese, finished in browned butter and onions.'),
(21,5,'Poland''s boiled-then-buttered dumplings, best with sour cream.'),
(22,1,'A vividly colored soup from Eastern Europe.'),
(22,2,'UNESCO listed it as Ukrainian heritage in 2022, settling a long argument.'),
(22,3,'An entire Catskills resort region — the Borscht Belt — was named after it.'),
(22,4,'Beets give it a shocking magenta color; sour cream swirls it pink.'),
(22,5,'The famous beet soup, served with dill.'),
(23,1,'A creamy dish named after an aristocratic European family.'),
(23,2,'Created for a 19th-century Russian count, possibly by his French chef.'),
(23,3,'It swept 1950s American dinner parties, ladled over egg noodles.'),
(23,4,'Sautéed strips of beef and mushrooms in a mustardy sour-cream sauce.'),
(23,5,'The Russian count''s beef in cream sauce.'),
(24,1,'A homey dish from Northern Europe.'),
(24,2,'Sweden''s official Twitter account admitted in 2018 that a king brought the recipe home from Türkiye.'),
(24,3,'A certain flat-pack furniture store serves about a billion of them a year.'),
(24,4,'Little beef-and-pork meatballs in cream sauce with lingonberry jam.'),
(24,5,'IKEA made them world-famous; Sweden made them first (sort of).'),
(25,1,'A sticky dessert claimed by an entire former empire.'),
(25,2,'Perfected in the Ottoman palace kitchens of Topkapı.'),
(25,3,'Sultans paraded trays of it to their elite troops every mid-Ramadan.'),
(25,4,'Dozens of buttered phyllo sheets, crushed nuts, and a soak of syrup or honey.'),
(25,5,'The diamond-cut pistachio pastry with paper-thin layers.'),
(26,1,'A dip eaten across an entire region — and claimed by most of it.'),
(26,2,'Recipes resembling it appear in 13th-century Cairo cookbooks.'),
(26,3,'Lebanon and Israel have traded world records for the largest plate of it.'),
(26,4,'Chickpeas blended smooth with tahini, lemon and garlic.'),
(26,5,'The beige dip you scoop with warm pita.'),
(27,1,'A fried street food from the Middle East and North Africa.'),
(27,2,'Likely invented by Egypt''s Copts as a meatless Lent food, originally with fava beans.'),
(27,3,'Now the default street lunch from Cairo to Berlin.'),
(27,4,'Ground chickpeas and herbs, rolled into balls and fried — green inside.'),
(27,5,'Crunchy chickpea fritters stuffed into pita with tahini.'),
(28,1,'A one-pan meal eaten across North Africa and the Middle East.'),
(28,2,'Its name means "all mixed up" in Maghrebi Arabic; Tunisia and Libya both claim it.'),
(28,3,'It conquered the world''s weekend brunch menus in the 2010s.'),
(28,4,'Eggs poached directly in a spiced tomato-pepper sauce.'),
(28,5,'The skillet of eggs in red sauce, mopped up with bread.'),
(29,1,'A spinning street-food icon with Ottoman roots.'),
(29,2,'The vertical rotisserie was popularized in 19th-century Bursa.'),
(29,3,'Turkish guest workers in Berlin turned it into Europe''s favorite late-night sandwich.'),
(29,4,'Seasoned meat shaved off a rotating spit into flatbread with salad and garlic sauce.'),
(29,5,'The kebab that spins all day — cousin to shawarma and al pastor.'),
(30,1,'A slow-cooked dish from North Africa.'),
(30,2,'Berber cooks have simmered it for centuries; medieval travelogues sing its praises.'),
(30,3,'Named for its cone-lidded clay pot, which rains the steam back into the stew.'),
(30,4,'Chicken braised with preserved lemon, olives, saffron and ginger.'),
(30,5,'Morocco''s cone-pot stew, served with couscous or bread.'),
(31,1,'A party rice dish from West Africa.'),
(31,2,'Traced to the Wolof empire of the Senegal river valley.'),
(31,3,'The "Jollof Wars" between Nigeria and Ghana are the internet''s tastiest rivalry.'),
(31,4,'Rice steamed in a smoky blended sauce of tomato, red pepper and scotch bonnet.'),
(31,5,'West Africa''s one-pot orange-red rice — no wedding is complete without it.'),
(32,1,'A baked dish from the southern tip of Africa.'),
(32,2,'Assembled by Cape Malay cooks from Dutch East India trade-route flavors.'),
(32,3,'Often called South Africa''s national dish.'),
(32,4,'Curried minced beef with raisins under a golden savory custard.'),
(32,5,'The Cape Town curry-meat bake with the egg-custard top.'),
(33,1,'A rich curry from South Asia.'),
(33,2,'Invented at Delhi''s Moti Mahal restaurant in the 1950s to revive leftover tandoori chicken.'),
(33,3,'Two Delhi restaurant families fought a 2024 court battle over who invented it.'),
(33,4,'Tandoori chicken simmered in a silky tomato-butter-cream sauce.'),
(33,5,'Murgh makhani — the creamiest gateway curry on any menu.'),
(34,1,'A celebration rice dish from South Asia.'),
(34,2,'Perfected in Mughal court kitchens; Hyderabad and Lucknow still duel over the crown.'),
(34,3,'India''s most-ordered delivery dish — one goes out every few seconds.'),
(34,4,'Marinated chicken and saffron rice steamed together in a sealed pot.'),
(34,5,'The layered, fragrant rice dish served at every South Asian wedding.'),
(35,1,'A triangular snack eaten from South Asia to East Africa.'),
(35,2,'It arrived in India with Central Asian traders by the 13th century.'),
(35,3,'No cricket match or train journey in India is complete without one.'),
(35,4,'A crisp fried pastry triangle stuffed with spiced potato and peas.'),
(35,5,'The fried triangle you dip in tamarind and mint chutney.'),
(36,1,'A breakfast staple from South Asia.'),
(36,2,'Born in the Udupi temple kitchens of India''s southwest coast.'),
(36,3,'Often served longer than your arm — the crepe that crunches.'),
(36,4,'A fermented rice-and-lentil crepe wrapped around turmeric-spiced potatoes.'),
(36,5,'South India''s giant golden crepe with coconut chutney and sambar.'),
(37,1,'An East Asian icon that began as a way to preserve fish.'),
(37,2,'Edo-period street stalls turned preserved fish and rice into fast food.'),
(37,3,'It conveyor-belted to world domination; one bluefin tuna sold for $3 million.'),
(37,4,'Vinegared rice pressed or rolled with raw fish and seaweed.'),
(37,5,'Japan''s raw-fish-and-rice art form, with wasabi and soy.'),
(38,1,'A noodle soup from East Asia with cult status.'),
(38,2,'Chinese wheat noodles adopted by Japan, then supercharged by postwar wheat imports.'),
(38,3,'The instant version, invented in 1958 by Momofuku Ando, has its own museum.'),
(38,4,'Springy noodles in rich pork broth with a jammy soft-boiled egg.'),
(38,5,'The slurpable Japanese noodle bowl — tonkotsu, shoyu, or miso.'),
(39,1,'An imperial dish from East Asia.'),
(39,2,'Roasted for Ming emperors; Beijing''s oldest duck house dates to 1416.'),
(39,3,'Nixon eating it at a 1972 banquet became a symbol of diplomatic thaw.'),
(39,4,'Lacquered crispy skin carved tableside, eaten in thin pancakes with hoisin.'),
(39,5,'Beijing''s glossy roast duck with scallion and cucumber.'),
(40,1,'A stir-fry from a chili-loving inland province of East Asia.'),
(40,2,'Named for a Qing-dynasty governor whose honorific title was "Gong Bao".'),
(40,3,'Its sweeter American cousin stars in every takeout box and countless sitcoms.'),
(40,4,'Diced chicken, dried chilies, and peanuts with numbing Sichuan peppercorns.'),
(40,5,'The Sichuan chicken-and-peanut stir-fry.'),
(41,1,'A numbing-hot dish from inland East Asia.'),
(41,2,'Named for a pockmarked grandmother who ran a Chengdu eatery in the 1860s.'),
(41,3,'Anime heroes and food-manga judges regularly weep over a bowl of it.'),
(41,4,'Silken tofu and minced pork in a fiery chili-bean sauce.'),
(41,5,'Sichuan''s "pockmarked granny" tofu.'),
(42,1,'A colorful bowl from East Asia.'),
(42,2,'Traced to royal table scraps or farmers'' field lunches; Jeonju claims the best.'),
(42,3,'Korean airlines made it the world''s favorite in-flight meal.'),
(42,4,'Rice topped with neatly arranged vegetables, beef and a fried egg — stir in the gochujang.'),
(42,5,'Korea''s "mixed rice", best served in a sizzling stone bowl.'),
(43,1,'A noodle dish from Southeast Asia.'),
(43,2,'Promoted by a 1930s prime minister to build national identity — and save rice.'),
(43,3,'Now the litmus test of every Thai restaurant on Earth.'),
(43,4,'Rice noodles with tamarind, fish sauce, egg and peanuts, plus a squeeze of lime.'),
(43,5,'Thailand''s sweet-sour-salty stir-fried noodles.'),
(44,1,'A breakfast soup from Southeast Asia.'),
(44,2,'Born in early-1900s Hanoi, with French beef bones and Chinese noodles in its family tree.'),
(44,3,'It traveled the world with refugees after 1975 and never looked back.'),
(44,4,'Beef and rice noodles in a broth perfumed with star anise, cinnamon and charred ginger.'),
(44,5,'Vietnam''s herb-piled noodle soup — add lime, basil and sprouts.'),
(45,1,'A sandwich from Southeast Asia with a colonial backstory.'),
(45,2,'French baguettes met Saigon street carts; independence made the filling Vietnamese.'),
(45,3,'Anthony Bourdain called it "a symphony in a sandwich".'),
(45,4,'A crackly baguette with pork, pâté, pickled carrot and daikon, cilantro and chili.'),
(45,5,'Vietnam''s baguette sandwich.'),
(46,1,'A fried-rice dish from an archipelago of 17,000 islands.'),
(46,2,'Born of thrift — yesterday''s rice became this morning''s breakfast.'),
(46,3,'Obama praised it on a state visit, recalling his Jakarta childhood.'),
(46,4,'Rice fried in sweet soy sauce and shrimp paste, crowned with a fried egg.'),
(46,5,'Indonesia''s smoky-sweet fried rice with crackers on the side.'),
(47,1,'A slow-cooked dish from a Southeast Asian archipelago.'),
(47,2,'A Minangkabau ceremonial dish from West Sumatra, made to survive long journeys.'),
(47,3,'CNN readers voted it the world''s most delicious food — twice.'),
(47,4,'Beef simmered in spiced coconut milk until the sauce nearly vanishes.'),
(47,5,'Indonesia''s dry, caramelized coconut beef curry.'),
(48,1,'A noodle soup from Southeast Asia''s spice-trade crossroads.'),
(48,2,'A Peranakan creation — Chinese noodles meeting Malay spice.'),
(48,3,'Singapore and Malaysia argue over it the way siblings argue over everything.'),
(48,4,'Rice noodles in a spicy coconut broth with shrimp, tofu puffs and a special herb leaf.'),
(48,5,'The curry-coconut noodle soup of Malaysia and Singapore.'),
(49,1,'A tangy braise from an island nation in Southeast Asia.'),
(49,2,'Pre-colonial cooks used vinegar to keep meat in the tropics; Spain later supplied the name.'),
(49,3,'Every Filipino family insists their version is the correct one.'),
(49,4,'Chicken simmered in soy sauce, vinegar, garlic and bay leaves.'),
(49,5,'The Philippines'' unofficial national dish, served over rice.'),
(50,1,'A deceptively simple dish from a Southeast Asian city-state.'),
(50,2,'Brought by Hainanese immigrants and perfected in hawker stalls.'),
(50,3,'When Malaysia limited chicken exports in 2022, Singapore treated it as a national crisis.'),
(50,4,'Poached chicken over rice cooked in the poaching fat, with ginger-scallion and chili sauces.'),
(50,5,'Singapore''s silky poached chicken and fragrant rice.'),
(51,1,'A sandwich named after a European port city but perfected elsewhere.'),
(51,2,'German immigrants'' minced steak met the American bun; several state fairs claim the wedding.'),
(51,3,'The 1904 St. Louis World''s Fair made it famous; golden arches made it global.'),
(51,4,'A grilled beef patty in a bun with lettuce, tomato, pickles and cheese.'),
(51,5,'America''s burger — this diner''s best seller.'),
(52,1,'A comfort classic with much older roots than you''d think.'),
(52,2,'Thomas Jefferson served a version at an 1802 state dinner.'),
(52,3,'The blue box arrived in 1937 and carried Depression-era families through the week.'),
(52,4,'Elbow pasta folded into cheddar sauce, baked under breadcrumbs.'),
(52,5,'Macaroni plus cheese sauce — the name hides nothing.'),
(53,1,'A crispy icon of the American South.'),
(53,2,'Scottish frying traditions and West African seasoning met in Southern kitchens — largely the work of enslaved cooks.'),
(53,3,'A Kentucky colonel franchised it worldwide with 11 secret herbs and spices.'),
(53,4,'Buttermilk-brined chicken shaken in seasoned flour and fried to a craggy crust.'),
(53,5,'The crunchy bird served with biscuits and gravy.'),
(54,1,'A creamy soup from a rocky Atlantic coastline.'),
(54,2,'Settlers'' fish stews thickened into a Yankee staple by the 1750s.'),
(54,3,'Adding tomatoes is such heresy that a 1939 Maine bill tried to outlaw it.'),
(54,4,'Clams, potatoes and salt pork in thick cream, with oyster crackers.'),
(54,5,'Boston''s white clam soup, served in a bread bowl.'),
(55,1,'A dessert so iconic a whole country claims to be "as American as" it.'),
(55,2,'English settlers brought the recipe; the apples themselves trace back to Kazakhstan.'),
(55,3,'GIs in WWII said they were fighting "for mom and" this.'),
(55,4,'Cinnamon-spiced fruit under a lattice crust, best served à la mode.'),
(55,5,'The all-American double-crust fruit pie.'),
(56,1,'An over-the-top dessert born in a drugstore.'),
(56,2,'Invented in 1904 by a 23-year-old apprentice pharmacist in Latrobe, Pennsylvania.'),
(56,3,'Soda fountains and diners made it the showpiece of the menu — this diner included.'),
(56,4,'Three scoops, three sauces, whipped cream and a cherry over a lengthwise-halved fruit.'),
(56,5,'The boat-shaped ice cream sundae on a split banana.'),
(57,1,'A thrifty family classic — and a diner blue-plate special.'),
(57,2,'Depression-era cooks stretched ground beef with breadcrumbs and called it dinner.'),
(57,3,'A leather-clad rock singer borrowed its name and sold 40 million albums.'),
(57,4,'Seasoned ground beef baked in a loaf pan under a ketchup glaze.'),
(57,5,'The sliced loaf of meat served with mashed potatoes.'),
(58,1,'A slow-simmered pot from America''s Gulf Coast.'),
(58,2,'West African okra, French roux and Choctaw filé — Louisiana stirred them into one pot.'),
(58,3,'The official cuisine of Louisiana; Mardi Gras runs on it.'),
(58,4,'A dark roux stew with shrimp, andouille sausage, okra and the "holy trinity" of vegetables.'),
(58,5,'New Orleans'' rice-topped stew — Creole or Cajun, them''s fighting words.'),
(59,1,'A late-night indulgence from north of the American border.'),
(59,2,'Born in 1950s rural Québec; a restaurateur allegedly warned it would make "a damn mess".'),
(59,3,'Canadian politicians are all but required to eat it on camera.'),
(59,4,'Fries and squeaky cheese curds drowned in hot gravy.'),
(59,5,'Québec''s gravy-and-curds fries.'),
(60,1,'A street taco with an immigrant backstory.'),
(60,2,'Lebanese immigrants brought the vertical spit to Puebla; Mexico swapped in chili-red pork.'),
(60,3,'Netflix''s Taco Chronicles crowned it the king of tacos.'),
(60,4,'Spit-roasted marinated pork shaved onto tortillas with pineapple, onion and cilantro.'),
(60,5,'The pineapple-topped "shepherd-style" taco.'),
(61,1,'A green dip with ancient roots.'),
(61,2,'The Aztecs called it āhuacamolli — "avocado sauce" — centuries before the conquistadors.'),
(61,3,'America eats over 100 million pounds of avocado every Super Bowl Sunday.'),
(61,4,'Mashed avocado with lime, onion, cilantro and chili.'),
(61,5,'The green dip served with tortilla chips.'),
(62,1,'A sauce with more ingredients than most entire menus.'),
(62,2,'Legend says convent nuns in Puebla improvised it for a surprise archbishop visit.'),
(62,3,'Often called Mexico''s national dish; families guard their recipe for generations.'),
(62,4,'Chilies, nuts and spices simmered for hours — with a famous touch of chocolate.'),
(62,5,'The dark, chocolate-tinged chili sauce of Puebla, served over chicken.'),
(63,1,'A dish "cooked" without any heat.'),
(63,2,'Peru''s coast has cured fish in citrus for two millennia; UNESCO honored it in 2023.'),
(63,3,'Peru gave it a national holiday — every June 28.'),
(63,4,'Raw white fish cured in lime with onion and chili, served with corn and sweet potato.'),
(63,5,'The citrus-cured raw fish dish of Lima.'),
(64,1,'A portable pastry beloved across an entire continent.'),
(64,2,'Descended from Galician pies that crossed the Atlantic with Spanish settlers.'),
(64,3,'In Argentina, each province crimps its edge a different way so you know what''s inside.'),
(64,4,'A folded pastry half-moon stuffed with spiced beef, olives and egg.'),
(64,5,'The baked or fried hand pie of Argentina.'),
(65,1,'A weekend feast from South America''s largest country.'),
(65,2,'Rooted in Portuguese bean stews and shaped over centuries in Brazil.'),
(65,3,'Rio restaurants serve it only on Wednesdays and Saturdays; schedule your nap accordingly.'),
(65,4,'Black beans slow-cooked with many cuts of pork, with rice, orange slices and farofa.'),
(65,5,'Brazil''s black bean and pork stew.'),
(66,1,'A griddled staple with a pre-Columbian pedigree.'),
(66,2,'Indigenous cooks ground maize for these centuries before Columbus; two countries claim them.'),
(66,3,'The famous "reina pepiada" filling honors a 1955 beauty queen.'),
(66,4,'A split griddled corn cake stuffed with cheese, avocado or shredded meat.'),
(66,5,'The corn pocket bread of Venezuela and Colombia.'),
(67,1,'A fiery grilled dish from a Caribbean island.'),
(67,2,'Maroon communities smoked meat over pimento wood in Jamaica''s Blue Mountains.'),
(67,3,'Its drum-barrel grills perfume every street festival from Kingston to Notting Hill.'),
(67,4,'Chicken in a scotch bonnet and allspice marinade, grilled over smoke.'),
(67,5,'Jamaica''s spicy smoke-grilled chicken.'),
(68,1,'An airy dessert two neighboring countries fight over.'),
(68,2,'Named for a touring Russian ballerina in the 1920s; New Zealand and Australia both claim the first recipe.'),
(68,3,'It anchors every Antipodean Christmas table — in midsummer.'),
(68,4,'A crisp meringue shell with a marshmallow heart, piled with cream and kiwifruit.'),
(68,5,'The ballerina-light meringue cake from Down Under.');

INSERT INTO schedule (date, dish_id) VALUES
('2026-07-17',51),
('2026-07-18',43),
('2026-07-19',9),
('2026-07-20',26),
('2026-07-21',38),
('2026-07-22',11),
('2026-07-23',55),
('2026-07-24',28),
('2026-07-25',44),
('2026-07-26',20),
('2026-07-27',61),
('2026-07-28',1),
('2026-07-29',67),
('2026-07-30',5),
('2026-07-31',33),
('2026-08-01',14),
('2026-08-02',63),
('2026-08-03',21),
('2026-08-04',39),
('2026-08-05',13),
('2026-08-06',30),
('2026-08-07',54),
('2026-08-08',47),
('2026-08-09',6),
('2026-08-10',68),
('2026-08-11',60),
('2026-08-12',36),
('2026-08-13',24),
('2026-08-14',48),
('2026-08-15',2);
